package WebGUI::i18n::English::Asset_InOutBoard;

our $I18N = {
	'In Out Template' => {
		message => q|In/Out Template|,
		lastUpdated =>1091624565
	},

	'22' => {
		message => q|In/Out Board, Report Template|,
		lastUpdated =>1091624565
	},

	'18' => {
		message => q|In/Out Board, Add/Edit|,
		lastUpdated =>1091624565
	},

	'select delegate' => {
		message => q|In/Out Board, Select Delegates|,
		lastUpdated =>1122010599
	},

	'in/out status delegates' => {
		message => q|In/Out Status Delegates|,
		lastUpdated =>1122010599
	},

	'23' => {
		message => q| The following variables are made available from In/Out Board Report: 
<P><B>showReport</B><BR>A boolean indicating whether or not the&nbsp;<I>rows_loop</I> variable will be set. <BR><BR><B>form</B><BR>A variable that contains the HTML for displaying the&nbsp;Date Range Selector Form for the report.&nbsp;<BR><BR><B>rows_loop</B><BR>A loop containing the rows of data for the In/Out Board Report&nbsp;<BR><BR>
<BLOCKQUOTE><B>deptHasChanged</B><BR>A boolean value indicating whether or not this row of data is for a department that is differnet than the previous rows<BR><BR><B>username</B><BR>A variable that returns the users name. If the first and last name fields are defined in the user profile, that is what is returned. Otherwise, the users WebGUI username is returned. i.e., "John Doe" vs "Jdoe" <BR><BR><B>status</B><BR>A variable that returns the users status. The status of a user is defined by the Status List in the Wobject Properties. If no status is set for the current user 'Never Checked In' is returned. <BR><BR><B>dateStamp</B><BR>A variable that returns the date the status of the user was last updated. <BR><BR><B>message</B><BR>A variable that returns what the user entered in the "What's going on?" field when updating their status. <BR><BR></BLOCKQUOTE><B>paginateBar</B><BR>A variable that returns the HTML necessary to create a Traditional Pagination Bar. i.e., &lt;&lt; First, 1, 2, Last &gt;&gt; <BR><BR>|,

		lastUpdated =>1091624565
	},

        '1 description' => {
                message => q|The status list allows you to customize what the 'states' of a user are. i.e., 'In' or 'Out'.|,
                lastUpdated => 1138988640,
        },

        '12 description' => {
                message => q|How many rows should be displayed before splitting the results into separate pages? In other words, how many rows should be displayed per page?|,
                lastUpdated => 1138988640,
        },

        'In Out Template description' => {
                message => q|Choose a template to style the display of the In/Out Board to users.|,
                lastUpdated => 1138988640,
        },

        '13 description' => {
                message => q|Choose a template to style the display of the In/Out Board Report.|,
                lastUpdated => 1138988640,
        },

        '3 description' => {
                message => q|Which groups are allowed to view reports generated by the In/Out Board Wobject?|,
                lastUpdated => 1138988640,
        },

        'inOutGroup description' => {
                message => q|Whichs groups are allowed to use this In/Out Board to change their status?|,
                lastUpdated => 1138988640,
        },

	'19' => {
		message => q|<p>
An In/Out board is used to keep track of whether people are currently
in/out of the office. It shows the current In/Out status of all WebGUI
users and also logs the reason the person has left, the time they
left and the time they return.  The log
</p>
|,
		lastUpdated =>1091624565
	},

	'20' => {
		message => q|In/Out Board, Template|,
		lastUpdated =>1091624565
	},

	'21' => {
		message => q|The following variables are made available from In/Out Board:
<p><b>canViewReport</b><br />
A boolean indicating whether or not the <i>viewReportURL</i> variable will be set.</p>

<p><b>viewReportURL</b><br />
URL that links to the view report page.</p>

<p><b>selectDelegatesURL</b><br />
URL that links to a form where users can select other users (delegates) who
can alter their status.</p>

<p><b>displayForm</b><br />
A boolean indicating whether or not the <i>form</i> variable will be set.</p>

<p><b>form</b><br />
A variable that contains the HTML for displaying the In/Out Entry Form.</p>

<p><b>rows_loop</b><br />
A loop containing the rows of data for the In/Out Board</p>

<blockquote>

<p><b>deptHasChanged</b><br />
A boolean value indicating whether or not this row of data is for a department that is differnet than the previous rows</p>

<p><b>username</b><br />
A variable that returns the users name.  If the first and last name fields are defined in the user profile, that is what is returned.  Otherwise, the users WebGUI username is returned.  i.e., "John Doe" vs "Jdoe"</p>

<p><b>status</b><br />
A variable that returns the users status.  The status of a user is defined by the Status List in the Wobject Properties.  If no status is set for the current user 'Never Checked In' is returned.</p>

<p><b>dateStamp</b><br />
A variable that returns the date the status of the user was last updated.</p>

<p><b>message</b><br />
A variable that returns what the user entered in the "What's going on?" field when updating their status.</p>
</blockquote>
<p><b>paginateBar</b><br />
A variable that returns the HTML necessary to create a Traditional Pagination Bar.  i.e., &gt;&gt; First, 1, 2, Last &lt;&lt;</p>

  |,
		lastUpdated =>1122523725
	},

	'2' => {
		message => q|Enter one per line.|,
		lastUpdated =>1091624565
	},

	'in/out status delegates subtext' => {
		message => q|Multiple users can be selected as delegates.  Delegates will be able to update your status.|,
		lastUpdated =>1122523790,
	},

	'17' => {
		message => q|End Date|,
		lastUpdated =>1091624565
	},

	'16' => {
		message => q|Start Date|,
		lastUpdated =>1091624565
	},

	'15' => {
		message => q|Never Checked In|,
		lastUpdated =>1091624565
	},

	'14' => {
		message => q|Paginate Report After|,
		lastUpdated =>1091624565
	},

	'13' => {
		message => q|Report Template|,
		lastUpdated =>1091624565
	},

	'12' => {
		message => q|Paginate After|,
		lastUpdated =>1091624565
	},

	'11' => {
		message => q|Out|,
		lastUpdated =>1091624565
	},

	'10' => {
		message => q|In|,
		lastUpdated =>1091624565
	},

	'assetName' => {
		message => q|In/Out Board|,
		lastUpdated =>1091624565
	},

	'8' => {
		message => q|Status Log Report|,
		lastUpdated =>1091624565
	},

	'7' => {
		message => q|No Department|,
		lastUpdated =>1091624565
	},

	'6' => {
		message => q|What's happening?|,
		lastUpdated =>1091624565
	},

	'delegate' => {
		message => q|Update status for: |,
		lastUpdated =>1122319088
	},

	'myself' => {
		message => q|Myself|,
		lastUpdated =>1122319088
	},

	'5' => {
		message => q|Status|,
		lastUpdated =>1091624565
	},

	'4' => {
		message => q|View Report|,
		lastUpdated =>1091624565
	},

	'3' => {
		message => q|Who can view reports?|,
		lastUpdated =>1091624565
	},

	'1' => {
		message => q|Status List|,
		lastUpdated =>1091624565
	},

	'inOutGroup' => {
		message => q|Who can log in/out?|,
		lastUpdated =>1091624565
	},

	'username label' => {
		message => q|Username|,
		lastUpdated =>1123199740
	},

	'date label' => {
		message => q|Date|,
		lastUpdated =>1123199740
	},

	'message label' => {
		message => q|Message|,
		lastUpdated =>1123199740
	},

	'updatedBy label' => {
		message => q|Updated By|,
		lastUpdated =>1123199740
	},

	'all departments' => {
		message => q|All Departments|,
		lastUpdated =>1123266324
	},

	'filter departments' => {
		message => q|Filter departments:|,
		lastUpdated =>1123266322
	},


};

1;
