CREATE TABLE `Survey` (
  `groupToTakeSurvey` varchar(22) character set utf8 collate utf8_bin NOT NULL default '2',
  `groupToViewReports` varchar(22) character set utf8 collate utf8_bin NOT NULL default '3',
  `responseTemplateId` varchar(22) character set utf8 collate utf8_bin NOT NULL default '',
  `overviewTemplateId` varchar(22) character set utf8 collate utf8_bin NOT NULL default '',
  `maxResponsesPerUser` int(11) NOT NULL default '1',
  `gradebookTemplateId` varchar(22) character set utf8 collate utf8_bin NOT NULL default '',
  `assetId` varchar(22) character set utf8 collate utf8_bin NOT NULL default '',
  `templateId` varchar(22) character set utf8 collate utf8_bin NOT NULL default '',
  `revisionDate` bigint(20) NOT NULL default '0',
  `surveyEditTemplateId` varchar(22) NOT NULL,
  `answerEditTemplateId` varchar(22) NOT NULL,
  `questionEditTemplateId` varchar(22) NOT NULL,
  `sectionEditTemplateId` varchar(22) NOT NULL,
  `surveyTakeTemplateId` varchar(22) NOT NULL,
  `surveyQuestionsId` varchar(22) NOT NULL,
  `exitURL` varchar(512) default NULL,
  `surveyJSON` longblob,
  PRIMARY KEY  (`assetId`,`revisionDate`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8
