insert into webguiVersion values ('4.2.0','upgrade',unix_timestamp());
insert into international values (6,'Item','English','Edit Item');
insert into settings values ('runOnRegistration','');
insert into international values (559,'WebGUI','English','Run On Registration');
alter table discussion add column locked int not null default 0;
alter table discussion add column status varchar(30) not null default 'Approved';
update international set internationalId=560, namespace='WebGUI' where internationalId=7 and namespace='UserSubmission';
update international set internationalId=561, namespace='WebGUI' where internationalId=8 and namespace='UserSubmission';
update international set internationalId=562, namespace='WebGUI' where internationalId=9 and namespace='UserSubmission';
update international set internationalId=563, namespace='WebGUI' where internationalId=10 and namespace='UserSubmission';
update international set internationalId=564, namespace='WebGUI' where internationalId=3 and namespace='MessageBoard';
update international set internationalId=565, namespace='WebGUI' where internationalId=21 and namespace='MessageBoard';
update international set internationalId=566, namespace='WebGUI' where internationalId=5 and namespace='MessageBoard';
delete from international where internationalId=19 and namespace='Article';
delete from international where internationalId=20 and namespace='Article';
delete from international where internationalId=21 and namespace='Article';
delete from international where namespace='UserSubmission' and internationalId=30;
delete from international where namespace='UserSubmission' and internationalId=49;
delete from international where namespace='UserSubmission' and internationalId=50;
delete from international where namespace='UserSubmission' and internationalId=44;
insert into international values (567,'WebGUI','English','Pre-emptive');
insert into international values (568,'WebGUI','English','After-the-fact');
insert into international values (569,'WebGUI','English','Moderation Type');
alter table wobject add column groupToPost int not null default 2;
alter table wobject add column editTimeout int not null default 1;
alter table wobject add column groupToModerate int not null default 4;
alter table wobject add column karmaPerPost int not null default 0;
alter table wobject add column moderationType varchar(30) not null default 'after';
alter table MessageBoard drop column editTimeout;
alter table MessageBoard drop column groupToModerate;
alter table MessageBoard drop column groupToPost;
alter table MessageBoard drop column karmaPerPost;
alter table UserSubmission drop column groupToPost;
alter table UserSubmission drop column groupToModerate;
alter table UserSubmission drop column editTimeout;
alter table UserSubmission drop column karmaPerPost;
alter table Article drop column karmaPerPost;
alter table Article drop column editTimeout;
alter table Article drop column groupToModerate;
alter table Article drop column groupToPost;
insert into international values (570,'WebGUI','English','Lock Thread');
insert into international values (571,'WebGUI','English','Unlock Thread');
update international set internationalId=572, namespace='WebGUI' where namespace='UserSubmission' and internationalId=24;
update international set internationalId=573, namespace='WebGUI' where namespace='UserSubmission' and internationalId=25;
update international set internationalId=574, namespace='WebGUI' where namespace='UserSubmission' and internationalId=26;
insert into international values (575,'WebGUI','English','Edit');
insert into international values (576,'WebGUI','English','Delete');
update international set internationalId=577, namespace='WebGUI' where namespace='MessageBoard' and internationalId=13;
delete from international where namespace='UserSubmission' and internationalId=42;
delete from international where namespace='UserSubmission' and internationalId=43;
delete from international where namespace='Article' and internationalId=25;
delete from international where namespace='Article' and internationalId=26;
insert into international values (578,'WebGUI','English','You have a pending message to approve.');
insert into international values (579,'WebGUI','English','Your message has been approved.');
insert into international values (580,'WebGUI','English','Your message has been denied.');
insert into international values (58,'UserSubmission','English','Previous Submission');
insert into international values (59,'UserSubmission','English','Next Submission');
insert into international values (1,'Product','English','Product');
create table Product_specification ( wobjectId int not null, productSpecificationId int not null primary key, name varchar(255), value varchar(255), units varchar(255), sequenceNumber int not null);
create table Product_feature ( wobjectId int not null, productFeatureId int not null primary key, feature varchar(255), sequenceNumber int not null);
create table Product (wobjectId int not null primary key, image1 varchar(255), image2 varchar(255), image3 varchar(255), brochure varchar(255), manual varchar(255), warranty varchar(255), price varchar(255), productNumber varchar(255));
insert into incrementer values ('productFeatureId',1000);
insert into incrementer values ('productSpecificationId',1000);
create table Product_accessory ( wobjectId int not null, AccessoryWobjectId int not null, sequenceNumber int not null, primary key (wobjectId, AccessoryWobjectId));
create table Product_related ( wobjectId int not null, RelatedWobjectId int not null, sequenceNumber int not null, primary key (wobjectId, RelatedWobjectId));
insert into international values (7,'Product','English','Product Image 1');
insert into international values (8,'Product','English','Product Image 2');
insert into international values (9,'Product','English','Product Image 3');
insert into international values (5,'Product','English','Are you certain you wish to delete this specification?');
insert into international values (4,'Product','English','Are you certain you wish to delete the relationship to this related product?');
insert into international values (3,'Product','English','Are you certain you wish to delete this feature?');
insert into international values (2,'Product','English','Are you certain you wish to delete the relationship to this accessory?');
insert into international values (6,'Product','English','Edit Product');
insert into international values (10,'Product','English','Price');
insert into international values (11,'Product','English','Product Number');
insert into international values (12,'Product','English','Are you certain you wish to delete this file?');
insert into international values (13,'Product','English','Brochure');
insert into international values (14,'Product','English','Manual');
insert into international values (15,'Product','English','Warranty');
insert into international values (16,'Product','English','Add Accessory');
insert into international values (17,'Product','English','Accessory');
insert into international values (18,'Product','English','Add another accessory?');
insert into international values (21,'Product','English','Add another related product?');
insert into international values (19,'Product','English','Add Related Product');
insert into international values (20,'Product','English','Related Product');
insert into international values (22,'Product','English','Edit Feature');
insert into international values (23,'Product','English','Feature');
insert into international values (24,'Product','English','Add another feature?');
insert into international values (25,'Product','English','Edit Specification');
insert into international values (26,'Product','English','Label');
insert into international values (27,'Product','English','Specification');
insert into international values (28,'Product','English','Add another specification?');
insert into international values (29,'Product','English','Units');
insert into international values (30,'Product','English','Features');
insert into international values (31,'Product','English','Specifications');
insert into international values (32,'Product','English','Accessories');
insert into international values (33,'Product','English','Related Products');
insert into international values (34,'Product','English','Add a feature.');
insert into international values (35,'Product','English','Add a specification.');
insert into international values (36,'Product','English','Add an accessory.');
insert into international values (37,'Product','English','Add a related product.');
insert into international values (581,'WebGUI','English','Add New Value');
insert into international values (582,'WebGUI','English','Leave Blank');
insert into international values (583,'WebGUI','English','Max Image Size');
insert into settings values ('maxImageSize','100000');
insert into international values (1,'WobjectProxy','English','Wobject To Proxy');
insert into international values (2,'WobjectProxy','English','Edit Wobject Proxy');
create table WobjectProxy (wobjectId int not null primary key, proxiedWobjectId int not null);
insert into international values (3,'WobjectProxy','English','Wobject Proxy');
insert into international values (4,'WobjectProxy','English','Wobject proxying failed. Perhaps the proxied wobject has been deleted.');
INSERT INTO international VALUES (5,'UserSubmission','简体中文','您的投稿被拒绝。');
INSERT INTO international VALUES (5,'SyndicatedContent','简体中文','最后提取于');
INSERT INTO international VALUES (5,'SQLReport','简体中文','DSN');
INSERT INTO international VALUES (5,'SiteMap','简体中文','编辑网站地图');
INSERT INTO international VALUES (5,'Poll','简体中文','图形宽度');
INSERT INTO international VALUES (5,'MessageBoard','简体中文','编辑超时');
INSERT INTO international VALUES (5,'LinkList','简体中文','是否执行添加链接？');
INSERT INTO international VALUES (5,'Item','简体中文','下载附件');
INSERT INTO international VALUES (5,'FAQ','简体中文','问题');
INSERT INTO international VALUES (5,'ExtraColumn','简体中文','风格单 Class');
INSERT INTO international VALUES (5,'EventsCalendar','简体中文','天');
INSERT INTO international VALUES (20,'EventsCalendar','简体中文','添加事务。');
INSERT INTO international VALUES (38,'UserSubmission','简体中文','(如果您使用了超文本语言，请选择“否”。)');
INSERT INTO international VALUES (4,'WebGUI','简体中文','管理设置。');
INSERT INTO international VALUES (4,'UserSubmission','简体中文','您的投稿已通过审核。');
INSERT INTO international VALUES (4,'SyndicatedContent','简体中文','编辑同步内容');
INSERT INTO international VALUES (4,'SQLReport','简体中文','查询');
INSERT INTO international VALUES (4,'SiteMap','简体中文','展开深度');
INSERT INTO international VALUES (4,'Poll','简体中文','投票权限？');
INSERT INTO international VALUES (4,'MessageBoard','简体中文','每页显示');
INSERT INTO international VALUES (4,'LinkList','简体中文','前缀字符');
INSERT INTO international VALUES (4,'Item','简体中文','项目');
INSERT INTO international VALUES (4,'ExtraColumn','简体中文','宽度');
INSERT INTO international VALUES (4,'EventsCalendar','简体中文','只发生一次。');
INSERT INTO international VALUES (4,'Article','简体中文','结束日期');
INSERT INTO international VALUES (3,'WebGUI','简体中文','从剪贴板中粘贴...');
INSERT INTO international VALUES (3,'UserSubmission','简体中文','您有一篇新的用户投稿等待审核。');
INSERT INTO international VALUES (3,'SQLReport','简体中文','报告模板');
INSERT INTO international VALUES (3,'SiteMap','简体中文','是否从此级别开始？');
INSERT INTO international VALUES (3,'Poll','简体中文','激活');
INSERT INTO international VALUES (3,'MessageBoard','简体中文','发表权限？');
INSERT INTO international VALUES (3,'LinkList','简体中文','是否在新窗口中打开？');
INSERT INTO international VALUES (3,'Item','简体中文','删除附件');
INSERT INTO international VALUES (3,'ExtraColumn','简体中文','空白');
INSERT INTO international VALUES (3,'Article','简体中文','开始日期');
INSERT INTO international VALUES (2,'WebGUI','简体中文','页');
INSERT INTO international VALUES (2,'UserSubmission','简体中文','投稿权限？');
INSERT INTO international VALUES (2,'SyndicatedContent','简体中文','同步内容');
INSERT INTO international VALUES (2,'SiteMap','简体中文','网站地图');
INSERT INTO international VALUES (2,'MessageBoard','简体中文','公告栏');
INSERT INTO international VALUES (2,'LinkList','简体中文','行间距');
INSERT INTO international VALUES (2,'Item','简体中文','附件');
INSERT INTO international VALUES (2,'FAQ','简体中文','F.A.Q.');
INSERT INTO international VALUES (2,'EventsCalendar','简体中文','行事历');
INSERT INTO international VALUES (507,'WebGUI','简体中文','编辑模板');
INSERT INTO international VALUES (1,'WebGUI','简体中文','添加内容...');
INSERT INTO international VALUES (1,'UserSubmission','简体中文','审核权限？');
INSERT INTO international VALUES (1,'SyndicatedContent','简体中文','RSS 文件链接');
INSERT INTO international VALUES (1,'SQLReport','简体中文','SQL 报告');
INSERT INTO international VALUES (1,'Poll','简体中文','调查');
INSERT INTO international VALUES (1,'LinkList','简体中文','缩进');
INSERT INTO international VALUES (1,'Item','简体中文','链接 URL');
INSERT INTO international VALUES (1,'FAQ','简体中文','是否执行添加问题？');
INSERT INTO international VALUES (1,'ExtraColumn','简体中文','扩展列');
INSERT INTO international VALUES (1,'EventsCalendar','简体中文','是否执行添加事务？');
INSERT INTO international VALUES (1,'Article','简体中文','文章');
INSERT INTO international VALUES (367,'WebGUI','简体中文','过期时间');
INSERT INTO international VALUES (5,'WebGUI','简体中文','管理用户组。');
INSERT INTO international VALUES (6,'Article','简体中文','图片');
INSERT INTO international VALUES (6,'EventsCalendar','简体中文','星期');
INSERT INTO international VALUES (6,'ExtraColumn','简体中文','编辑扩展列');
INSERT INTO international VALUES (6,'FAQ','简体中文','回答');
INSERT INTO international VALUES (6,'LinkList','简体中文','链接列表');
INSERT INTO international VALUES (6,'MessageBoard','简体中文','编辑公告栏');
INSERT INTO international VALUES (6,'Poll','简体中文','问题');
INSERT INTO international VALUES (6,'SiteMap','简体中文','缩进');
INSERT INTO international VALUES (6,'SQLReport','简体中文','数据库用户');
INSERT INTO international VALUES (6,'SyndicatedContent','简体中文','当前内容');
INSERT INTO international VALUES (6,'UserSubmission','简体中文','每页投稿数');
INSERT INTO international VALUES (6,'WebGUI','简体中文','管理风格');
INSERT INTO international VALUES (7,'Article','简体中文','连接标题');
INSERT INTO international VALUES (7,'FAQ','简体中文','您是否确信您要删除这个问题？');
INSERT INTO international VALUES (7,'MessageBoard','简体中文','作者：');
INSERT INTO international VALUES (7,'Poll','简体中文','回答');
INSERT INTO international VALUES (7,'SiteMap','简体中文','前缀字符');
INSERT INTO international VALUES (7,'SQLReport','简体中文','数据库密码');
INSERT INTO international VALUES (7,'UserSubmission','简体中文','通过');
INSERT INTO international VALUES (7,'WebGUI','简体中文','管理用户。');
INSERT INTO international VALUES (8,'Article','简体中文','链接 URL');
INSERT INTO international VALUES (8,'EventsCalendar','简体中文','重复周期');
INSERT INTO international VALUES (8,'FAQ','简体中文','编辑 F.A.Q.');
INSERT INTO international VALUES (8,'LinkList','简体中文','URL');
INSERT INTO international VALUES (8,'MessageBoard','简体中文','日期：');
INSERT INTO international VALUES (8,'Poll','简体中文','（每行输入一条答案。最多不超过20条。）');
INSERT INTO international VALUES (9,'MessageBoard','简体中文','文章 ID:');
INSERT INTO international VALUES (11,'MessageBoard','简体中文','返回文章列表');
INSERT INTO international VALUES (12,'MessageBoard','简体中文','编辑文章');
INSERT INTO international VALUES (13,'MessageBoard','简体中文','发表回复');
INSERT INTO international VALUES (15,'MessageBoard','简体中文','作者');
INSERT INTO international VALUES (16,'MessageBoard','简体中文','日期');
INSERT INTO international VALUES (17,'MessageBoard','简体中文','发表新文章');
INSERT INTO international VALUES (18,'MessageBoard','简体中文','线索开始');
INSERT INTO international VALUES (19,'MessageBoard','简体中文','回复');
INSERT INTO international VALUES (20,'MessageBoard','简体中文','最后回复');
INSERT INTO international VALUES (21,'MessageBoard','简体中文','管理权限？');
INSERT INTO international VALUES (22,'MessageBoard','简体中文','删除文章');
INSERT INTO international VALUES (9,'Poll','简体中文','编辑调查');
INSERT INTO international VALUES (10,'Poll','简体中文','初始化投票。');
INSERT INTO international VALUES (11,'Poll','简体中文','投票！');
INSERT INTO international VALUES (8,'SiteMap','简体中文','行距');
INSERT INTO international VALUES (8,'SQLReport','简体中文','Edit SQL Report');
INSERT INTO international VALUES (8,'UserSubmission','简体中文','被拒绝');
INSERT INTO international VALUES (8,'WebGUI','简体中文','您查看的页面不存在。');
INSERT INTO international VALUES (9,'Article','简体中文','附件');
INSERT INTO international VALUES (9,'EventsCalendar','简体中文','直到');
INSERT INTO international VALUES (9,'FAQ','简体中文','添加新问题。');
INSERT INTO international VALUES (9,'LinkList','简体中文','您是否确定要删除此链接？');
INSERT INTO international VALUES (9,'SQLReport','简体中文','<b>Debug:</b> Error: The DSN specified is of an improper format.');
INSERT INTO international VALUES (9,'UserSubmission','简体中文','审核中');
INSERT INTO international VALUES (9,'WebGUI','简体中文','查看剪贴板');
INSERT INTO international VALUES (10,'Article','简体中文','是否转换回车符？');
INSERT INTO international VALUES (10,'EventsCalendar','简体中文','您是否确定要删除此项事务');
INSERT INTO international VALUES (10,'FAQ','简体中文','编辑问题');
INSERT INTO international VALUES (10,'LinkList','简体中文','编辑链接列表');
INSERT INTO international VALUES (10,'SQLReport','简体中文','<b>Debug:</b> Error: The SQL specified is of an improper format.');
INSERT INTO international VALUES (10,'UserSubmission','简体中文','默认状态');
INSERT INTO international VALUES (10,'WebGUI','简体中文','管理垃圾箱');
INSERT INTO international VALUES (11,'Article','简体中文','(如果您没有手动输入&lt;br&gt;，请选择“是”)');
INSERT INTO international VALUES (11,'EventsCalendar','简体中文','<b>和</b>所有相关事务？');
INSERT INTO international VALUES (11,'SQLReport','简体中文','<b>Debug:</b> Error: There was a problem with the query.');
INSERT INTO international VALUES (11,'WebGUI','简体中文','清空垃圾箱');
INSERT INTO international VALUES (12,'Article','简体中文','编辑文章');
INSERT INTO international VALUES (12,'EventsCalendar','简体中文','编辑行事历');
INSERT INTO international VALUES (12,'LinkList','简体中文','编辑链接');
INSERT INTO international VALUES (12,'SQLReport','简体中文','<b>Debug:</b> Error: Could not connect to the database.');
INSERT INTO international VALUES (12,'UserSubmission','简体中文','(如果您使用了超文本语言，请不要选择此项)');
INSERT INTO international VALUES (12,'WebGUI','简体中文','退出管理');
INSERT INTO international VALUES (13,'Article','简体中文','删除');
INSERT INTO international VALUES (13,'EventsCalendar','简体中文','编辑事务');
INSERT INTO international VALUES (13,'LinkList','简体中文','添加新链接。');
INSERT INTO international VALUES (13,'UserSubmission','简体中文','投稿时间');
INSERT INTO international VALUES (13,'WebGUI','简体中文','查看帮助索引');
INSERT INTO international VALUES (14,'Article','简体中文','图片位置');
INSERT INTO international VALUES (516,'WebGUI','简体中文','进入管理');
INSERT INTO international VALUES (517,'WebGUI','简体中文','退出管理');
INSERT INTO international VALUES (515,'WebGUI','简体中文','是否添加编辑戳？');
INSERT INTO international VALUES (14,'UserSubmission','简体中文','状态');
INSERT INTO international VALUES (14,'WebGUI','简体中文','查看等待审核的投稿');
INSERT INTO international VALUES (15,'UserSubmission','简体中文','编辑/删除');
INSERT INTO international VALUES (15,'WebGUI','简体中文','一月');
INSERT INTO international VALUES (16,'UserSubmission','简体中文','无标题');
INSERT INTO international VALUES (16,'WebGUI','简体中文','二月');
INSERT INTO international VALUES (17,'UserSubmission','简体中文','您确定要删除此稿件吗？');
INSERT INTO international VALUES (17,'WebGUI','简体中文','三月');
INSERT INTO international VALUES (18,'UserSubmission','简体中文','编辑用户投稿系统');
INSERT INTO international VALUES (18,'WebGUI','简体中文','四月');
INSERT INTO international VALUES (19,'UserSubmission','简体中文','编辑投稿');
INSERT INTO international VALUES (19,'WebGUI','简体中文','五月');
INSERT INTO international VALUES (20,'UserSubmission','简体中文','我要投稿');
INSERT INTO international VALUES (20,'WebGUI','简体中文','六月');
INSERT INTO international VALUES (21,'UserSubmission','简体中文','发表人');
INSERT INTO international VALUES (21,'WebGUI','简体中文','七月');
INSERT INTO international VALUES (22,'UserSubmission','简体中文','发表人：');
INSERT INTO international VALUES (22,'WebGUI','简体中文','八月');
INSERT INTO international VALUES (23,'UserSubmission','简体中文','投稿时间');
INSERT INTO international VALUES (23,'WebGUI','简体中文','九月');
INSERT INTO international VALUES (24,'UserSubmission','简体中文','通过');
INSERT INTO international VALUES (24,'WebGUI','简体中文','十月');
INSERT INTO international VALUES (25,'UserSubmission','简体中文','继续审核');
INSERT INTO international VALUES (25,'WebGUI','简体中文','十一月');
INSERT INTO international VALUES (26,'UserSubmission','简体中文','拒绝');
INSERT INTO international VALUES (26,'WebGUI','简体中文','十二月');
INSERT INTO international VALUES (27,'UserSubmission','简体中文','编辑');
INSERT INTO international VALUES (27,'WebGUI','简体中文','星期日');
INSERT INTO international VALUES (28,'UserSubmission','简体中文','返回稿件列表');
INSERT INTO international VALUES (28,'WebGUI','简体中文','星期一');
INSERT INTO international VALUES (29,'UserSubmission','简体中文','用户投稿系统');
INSERT INTO international VALUES (29,'WebGUI','简体中文','星期二');
INSERT INTO international VALUES (30,'WebGUI','简体中文','星期三');
INSERT INTO international VALUES (31,'WebGUI','简体中文','星期四');
INSERT INTO international VALUES (32,'WebGUI','简体中文','星期五');
INSERT INTO international VALUES (33,'WebGUI','简体中文','星期六');
INSERT INTO international VALUES (34,'WebGUI','简体中文','设置日期');
INSERT INTO international VALUES (35,'WebGUI','简体中文','管理功能');
INSERT INTO international VALUES (36,'WebGUI','简体中文','您必须是系统管理员才能使用此功能。请联系您的系统管理员。以下是本系统的系统管理员清单：');
INSERT INTO international VALUES (37,'WebGUI','简体中文','权限被拒绝！');
INSERT INTO international VALUES (404,'WebGUI','简体中文','第一页');
INSERT INTO international VALUES (38,'WebGUI','简体中文','您没有足够的权限执行此项操作。请^a(登录);然后再试一次。');
INSERT INTO international VALUES (39,'WebGUI','简体中文','对不起，您没有足够的权限访问一页。');
INSERT INTO international VALUES (40,'WebGUI','简体中文','系统组件');
INSERT INTO international VALUES (41,'WebGUI','简体中文','您将要删除一个系统组件。如果您继续，系统功能可能会受到影响。');
INSERT INTO international VALUES (42,'WebGUI','简体中文','请确认');
INSERT INTO international VALUES (43,'WebGUI','简体中文','您是否确定要删除此内容吗？');
INSERT INTO international VALUES (44,'WebGUI','简体中文','是的，我确定。');
INSERT INTO international VALUES (45,'WebGUI','简体中文','不，我按错了。');
INSERT INTO international VALUES (46,'WebGUI','简体中文','我的帐户');
INSERT INTO international VALUES (47,'WebGUI','简体中文','首页');
INSERT INTO international VALUES (48,'WebGUI','简体中文','欢迎！');
INSERT INTO international VALUES (49,'WebGUI','简体中文','点击 <a href=\"^;?op=logout\">此处</a> 退出登录。');
INSERT INTO international VALUES (50,'WebGUI','简体中文','帐户');
INSERT INTO international VALUES (51,'WebGUI','简体中文','密码');
INSERT INTO international VALUES (52,'WebGUI','简体中文','登录');
INSERT INTO international VALUES (53,'WebGUI','简体中文','打印本页');
INSERT INTO international VALUES (54,'WebGUI','简体中文','创建帐户');
INSERT INTO international VALUES (55,'WebGUI','简体中文','密码（确认）');
INSERT INTO international VALUES (56,'WebGUI','简体中文','电子邮件');
INSERT INTO international VALUES (57,'WebGUI','简体中文','此项只在您希望使用到需要电子邮件的功能的时候有用。');
INSERT INTO international VALUES (58,'WebGUI','简体中文','我已经有了一个帐户。');
INSERT INTO international VALUES (59,'WebGUI','简体中文','我忘记了密码。');
INSERT INTO international VALUES (60,'WebGUI','简体中文','您是否真的希望注销您的帐户？如果您继续，您的帐户信息将被永久删除。');
INSERT INTO international VALUES (61,'WebGUI','简体中文','更新帐户信息');
INSERT INTO international VALUES (62,'WebGUI','简体中文','保存');
INSERT INTO international VALUES (63,'WebGUI','简体中文','进入管理。');
INSERT INTO international VALUES (64,'WebGUI','简体中文','退出登录。');
INSERT INTO international VALUES (65,'WebGUI','简体中文','请删除我的帐户。');
INSERT INTO international VALUES (66,'WebGUI','简体中文','用户登录');
INSERT INTO international VALUES (67,'WebGUI','简体中文','创建新帐户。');
INSERT INTO international VALUES (68,'WebGUI','简体中文','您输入的帐户信息无效。可能是您输入的帐户不存在，或输入了错误的密码。');
INSERT INTO international VALUES (69,'WebGUI','简体中文','如果您需要协助，请联系系统管理员。');
INSERT INTO international VALUES (70,'WebGUI','简体中文','错误');
INSERT INTO international VALUES (71,'WebGUI','简体中文','恢复密码');
INSERT INTO international VALUES (72,'WebGUI','简体中文','恢复');
INSERT INTO international VALUES (73,'WebGUI','简体中文','用户登录');
INSERT INTO international VALUES (74,'WebGUI','简体中文','帐户信息');
INSERT INTO international VALUES (75,'WebGUI','简体中文','您的帐户信息已经发送到您的电子邮件中。');
INSERT INTO international VALUES (76,'WebGUI','简体中文','对不起，此电子邮件地址不在系统数据库中。');
INSERT INTO international VALUES (77,'WebGUI','简体中文','对不起，此帐户名已被其他用户使用。请另外选择一个用户名。我们建议您使用以下名字作为登录名：');
INSERT INTO international VALUES (78,'WebGUI','简体中文','您输入的密码不一致，请重新输入。');
INSERT INTO international VALUES (79,'WebGUI','简体中文','不能连接到目录服务器。');
INSERT INTO international VALUES (80,'WebGUI','简体中文','创建帐户成功！');
INSERT INTO international VALUES (81,'WebGUI','简体中文','更新帐户成功！');
INSERT INTO international VALUES (82,'WebGUI','简体中文','管理功能...');
INSERT INTO international VALUES (536,'WebGUI','简体中文','新用户 ^@; 刚加入本站。');
INSERT INTO international VALUES (84,'WebGUI','简体中文','用户组');
INSERT INTO international VALUES (85,'WebGUI','简体中文','描述');
INSERT INTO international VALUES (86,'WebGUI','简体中文','您确信要删除此用户组吗？此项操作将永久删除此用户组，并取消此用户组所有相关权限。');
INSERT INTO international VALUES (87,'WebGUI','简体中文','编辑用户组');
INSERT INTO international VALUES (88,'WebGUI','简体中文','用户组成员');
INSERT INTO international VALUES (89,'WebGUI','简体中文','用户组');
INSERT INTO international VALUES (90,'WebGUI','简体中文','添加新组。');
INSERT INTO international VALUES (91,'WebGUI','简体中文','上一页');
INSERT INTO international VALUES (92,'WebGUI','简体中文','下一页');
INSERT INTO international VALUES (93,'WebGUI','简体中文','帮助');
INSERT INTO international VALUES (94,'WebGUI','简体中文','参考');
INSERT INTO international VALUES (95,'WebGUI','简体中文','帮助索引');
INSERT INTO international VALUES (96,'WebGUI','简体中文','按动作排序');
INSERT INTO international VALUES (97,'WebGUI','简体中文','按组件排序');
INSERT INTO international VALUES (99,'WebGUI','简体中文','标题');
INSERT INTO international VALUES (100,'WebGUI','简体中文','Meta 标识');
INSERT INTO international VALUES (101,'WebGUI','简体中文','您确信要删除此页面以及页面内的所有内容和组件吗？');
INSERT INTO international VALUES (102,'WebGUI','简体中文','编辑页面');
INSERT INTO international VALUES (103,'WebGUI','简体中文','页面描述');
INSERT INTO international VALUES (104,'WebGUI','简体中文','页面 URL');
INSERT INTO international VALUES (105,'WebGUI','简体中文','风格');
INSERT INTO international VALUES (106,'WebGUI','简体中文','选择“是”将本页面下级所有页面风格改为此风格。');
INSERT INTO international VALUES (107,'WebGUI','简体中文','权限设置');
INSERT INTO international VALUES (108,'WebGUI','简体中文','拥有者');
INSERT INTO international VALUES (109,'WebGUI','简体中文','拥有者访问权限？');
INSERT INTO international VALUES (110,'WebGUI','简体中文','拥有者编辑权限？');
INSERT INTO international VALUES (111,'WebGUI','简体中文','用户组');
INSERT INTO international VALUES (112,'WebGUI','简体中文','用户组访问权限？');
INSERT INTO international VALUES (113,'WebGUI','简体中文','用户组编辑权限？');
INSERT INTO international VALUES (114,'WebGUI','简体中文','任何人可访问？');
INSERT INTO international VALUES (115,'WebGUI','简体中文','任何人可编辑？');
INSERT INTO international VALUES (116,'WebGUI','简体中文','选择“是”将本页面下级所有页面权限改为此权限设置。');
INSERT INTO international VALUES (117,'WebGUI','简体中文','编辑用户设置');
INSERT INTO international VALUES (118,'WebGUI','简体中文','匿名用户注册');
INSERT INTO international VALUES (119,'WebGUI','简体中文','默认用户认证方式');
INSERT INTO international VALUES (120,'WebGUI','简体中文','默认 LDAP URL');
INSERT INTO international VALUES (121,'WebGUI','简体中文','默认 LDAP Identity');
INSERT INTO international VALUES (122,'WebGUI','简体中文','LDAP Identity 名');
INSERT INTO international VALUES (123,'WebGUI','简体中文','LDAP Password 名');
INSERT INTO international VALUES (124,'WebGUI','简体中文','编辑公司信息');
INSERT INTO international VALUES (125,'WebGUI','简体中文','公司名');
INSERT INTO international VALUES (126,'WebGUI','简体中文','公司电子邮件地址');
INSERT INTO international VALUES (127,'WebGUI','简体中文','公司链接');
INSERT INTO international VALUES (128,'WebGUI','简体中文','编辑文件设置');
INSERT INTO international VALUES (129,'WebGUI','简体中文','网站扩展目录');
INSERT INTO international VALUES (130,'WebGUI','简体中文','最大附件大小');
INSERT INTO international VALUES (131,'WebGUI','简体中文','附件访问路径');
INSERT INTO international VALUES (132,'WebGUI','简体中文','附件保存路径');
INSERT INTO international VALUES (133,'WebGUI','简体中文','编辑邮件设置');
INSERT INTO international VALUES (134,'WebGUI','简体中文','恢复密码邮件内容');
INSERT INTO international VALUES (135,'WebGUI','简体中文','邮件服务器');
INSERT INTO international VALUES (138,'WebGUI','简体中文','是');
INSERT INTO international VALUES (139,'WebGUI','简体中文','否');
INSERT INTO international VALUES (140,'WebGUI','简体中文','编辑一般设置');
INSERT INTO international VALUES (141,'WebGUI','简体中文','默认未找到页面');
INSERT INTO international VALUES (142,'WebGUI','简体中文','对话超时');
INSERT INTO international VALUES (143,'WebGUI','简体中文','管理设置');
INSERT INTO international VALUES (144,'WebGUI','简体中文','查看统计信息。');
INSERT INTO international VALUES (145,'WebGUI','简体中文','系统版本');
INSERT INTO international VALUES (146,'WebGUI','简体中文','活动对话');
INSERT INTO international VALUES (147,'WebGUI','简体中文','页面数');
INSERT INTO international VALUES (148,'WebGUI','简体中文','组件数');
INSERT INTO international VALUES (149,'WebGUI','简体中文','用户数');
INSERT INTO international VALUES (533,'WebGUI','简体中文','<b>不包括</b>搜索字');
INSERT INTO international VALUES (532,'WebGUI','简体中文','包括<b>至少一个</b>搜索字');
INSERT INTO international VALUES (151,'WebGUI','简体中文','风格名');
INSERT INTO international VALUES (505,'WebGUI','简体中文','添加一个新模板');
INSERT INTO international VALUES (504,'WebGUI','简体中文','模板');
INSERT INTO international VALUES (502,'WebGUI','简体中文','您确信要删除此模板，并将所有使用此模板的页面设为默认模板？');
INSERT INTO international VALUES (154,'WebGUI','简体中文','风格单');
INSERT INTO international VALUES (155,'WebGUI','简体中文','您确定要删除此页面风格，并将所有使用此风格的页面风格设为“安全模式”风格？');
INSERT INTO international VALUES (156,'WebGUI','简体中文','编辑风格');
INSERT INTO international VALUES (157,'WebGUI','简体中文','风格');
INSERT INTO international VALUES (158,'WebGUI','简体中文','添加新风格。');
INSERT INTO international VALUES (160,'WebGUI','简体中文','提交日期');
INSERT INTO international VALUES (161,'WebGUI','简体中文','提交人');
INSERT INTO international VALUES (162,'WebGUI','简体中文','您是否确定要清空垃圾箱中所有页面和组件吗？');
INSERT INTO international VALUES (163,'WebGUI','简体中文','添加用户');
INSERT INTO international VALUES (164,'WebGUI','简体中文','用户认证方式');
INSERT INTO international VALUES (165,'WebGUI','简体中文','LDAP URL');
INSERT INTO international VALUES (166,'WebGUI','简体中文','连接 DN');
INSERT INTO international VALUES (167,'WebGUI','简体中文','您是否确定要删除此用户吗？注意删除用户将永久删除该用户的所有信息。');
INSERT INTO international VALUES (168,'WebGUI','简体中文','编辑用户');
INSERT INTO international VALUES (169,'WebGUI','简体中文','添加新用户。');
INSERT INTO international VALUES (170,'WebGUI','简体中文','搜索');
INSERT INTO international VALUES (171,'WebGUI','简体中文','可视化编辑');
INSERT INTO international VALUES (174,'WebGUI','简体中文','是否显示标题？');
INSERT INTO international VALUES (175,'WebGUI','简体中文','是否执行宏命令？');
INSERT INTO international VALUES (228,'WebGUI','简体中文','编辑消息...');
INSERT INTO international VALUES (229,'WebGUI','简体中文','标题');
INSERT INTO international VALUES (230,'WebGUI','简体中文','消息');
INSERT INTO international VALUES (231,'WebGUI','简体中文','发布新消息...');
INSERT INTO international VALUES (232,'WebGUI','简体中文','无标题');
INSERT INTO international VALUES (233,'WebGUI','简体中文','(eom)');
INSERT INTO international VALUES (234,'WebGUI','简体中文','发表回应...');
INSERT INTO international VALUES (237,'WebGUI','简体中文','标题：');
INSERT INTO international VALUES (238,'WebGUI','简体中文','作者：');
INSERT INTO international VALUES (239,'WebGUI','简体中文','日期：');
INSERT INTO international VALUES (240,'WebGUI','简体中文','消息 ID:');
INSERT INTO international VALUES (244,'WebGUI','简体中文','作者');
INSERT INTO international VALUES (245,'WebGUI','简体中文','日期');
INSERT INTO international VALUES (304,'WebGUI','简体中文','语言');
INSERT INTO international VALUES (306,'WebGUI','简体中文','用户名绑定');
INSERT INTO international VALUES (307,'WebGUI','简体中文','是否使用默认 meta 标识符？');
INSERT INTO international VALUES (308,'WebGUI','简体中文','编辑用户属性设置');
INSERT INTO international VALUES (309,'WebGUI','简体中文','是否允许使用真实姓名？');
INSERT INTO international VALUES (310,'WebGUI','简体中文','是否允许使用扩展联系信息？');
INSERT INTO international VALUES (311,'WebGUI','简体中文','是否允许使用家庭信息？');
INSERT INTO international VALUES (312,'WebGUI','简体中文','是否允许使用商业信息？');
INSERT INTO international VALUES (313,'WebGUI','简体中文','是否允许使用其他信息？');
INSERT INTO international VALUES (314,'WebGUI','简体中文','姓');
INSERT INTO international VALUES (315,'WebGUI','简体中文','中间名');
INSERT INTO international VALUES (316,'WebGUI','简体中文','名');
INSERT INTO international VALUES (317,'WebGUI','简体中文','<a href=\"http://www.icq.com\">ICQ</a> UIN');
INSERT INTO international VALUES (318,'WebGUI','简体中文','<a href=\"http://www.aol.com/aim/homenew.adp\">AIM</a> ID');
INSERT INTO international VALUES (319,'WebGUI','简体中文','<a href=\"http://messenger.msn.com/\">MSN Messenger</a> ID');
INSERT INTO international VALUES (320,'WebGUI','简体中文','<a href=\"http://messenger.yahoo.com/\">Yahoo! Messenger</a> ID');
INSERT INTO international VALUES (321,'WebGUI','简体中文','移动电话');
INSERT INTO international VALUES (322,'WebGUI','简体中文','传呼');
INSERT INTO international VALUES (323,'WebGUI','简体中文','家庭住址');
INSERT INTO international VALUES (324,'WebGUI','简体中文','城市');
INSERT INTO international VALUES (325,'WebGUI','简体中文','省份');
INSERT INTO international VALUES (326,'WebGUI','简体中文','邮政编码');
INSERT INTO international VALUES (327,'WebGUI','简体中文','国家');
INSERT INTO international VALUES (328,'WebGUI','简体中文','住宅电话');
INSERT INTO international VALUES (329,'WebGUI','简体中文','单位地址');
INSERT INTO international VALUES (330,'WebGUI','简体中文','城市');
INSERT INTO international VALUES (331,'WebGUI','简体中文','省份');
INSERT INTO international VALUES (332,'WebGUI','简体中文','邮政编码');
INSERT INTO international VALUES (333,'WebGUI','简体中文','国家');
INSERT INTO international VALUES (334,'WebGUI','简体中文','单位电话');
INSERT INTO international VALUES (335,'WebGUI','简体中文','性别');
INSERT INTO international VALUES (336,'WebGUI','简体中文','生日');
INSERT INTO international VALUES (337,'WebGUI','简体中文','个人网页');
INSERT INTO international VALUES (338,'WebGUI','简体中文','编辑用户属性');
INSERT INTO international VALUES (339,'WebGUI','简体中文','男');
INSERT INTO international VALUES (340,'WebGUI','简体中文','女');
INSERT INTO international VALUES (341,'WebGUI','简体中文','编辑用户属性。');
INSERT INTO international VALUES (342,'WebGUI','简体中文','编辑帐户信息');
INSERT INTO international VALUES (343,'WebGUI','简体中文','查看用户属性。');
INSERT INTO international VALUES (351,'WebGUI','简体中文','消息');
INSERT INTO international VALUES (345,'WebGUI','简体中文','不是本站用户');
INSERT INTO international VALUES (346,'WebGUI','简体中文','此用户不再是本站用户。无法提供此用户的更多信息。');
INSERT INTO international VALUES (347,'WebGUI','简体中文','查看用户属性：');
INSERT INTO international VALUES (348,'WebGUI','简体中文','姓名');
INSERT INTO international VALUES (349,'WebGUI','简体中文','最新版本');
INSERT INTO international VALUES (350,'WebGUI','简体中文','结束');
INSERT INTO international VALUES (352,'WebGUI','简体中文','发出日期');
INSERT INTO international VALUES (471,'WebGUI','简体中文','编辑用户属性项');
INSERT INTO international VALUES (355,'WebGUI','简体中文','默认');
INSERT INTO international VALUES (356,'WebGUI','简体中文','模板');
INSERT INTO international VALUES (357,'WebGUI','简体中文','新闻');
INSERT INTO international VALUES (358,'WebGUI','简体中文','左导航');
INSERT INTO international VALUES (359,'WebGUI','简体中文','右导航');
INSERT INTO international VALUES (360,'WebGUI','简体中文','一加三');
INSERT INTO international VALUES (361,'WebGUI','简体中文','三加一');
INSERT INTO international VALUES (362,'WebGUI','简体中文','平分');
INSERT INTO international VALUES (363,'WebGUI','简体中文','模板定位');
INSERT INTO international VALUES (364,'WebGUI','简体中文','搜索');
INSERT INTO international VALUES (365,'WebGUI','简体中文','搜索结果...');
INSERT INTO international VALUES (366,'WebGUI','简体中文','没有找到符合搜索条件的页面。');
INSERT INTO international VALUES (368,'WebGUI','简体中文','将此用户加入新用户组。');
INSERT INTO international VALUES (369,'WebGUI','简体中文','过期日期');
INSERT INTO international VALUES (370,'WebGUI','简体中文','编辑用户分组');
INSERT INTO international VALUES (371,'WebGUI','简体中文','添加用户分组');
INSERT INTO international VALUES (372,'WebGUI','简体中文','编辑用户所属组群');
INSERT INTO international VALUES (373,'WebGUI','简体中文','<b>警告：</b>编辑上面的组群列表，将重置所有组群的过期信息为新的初始值。');
INSERT INTO international VALUES (374,'WebGUI','简体中文','管理包裹。');
INSERT INTO international VALUES (375,'WebGUI','简体中文','选择要展开的包裹。');
INSERT INTO international VALUES (376,'WebGUI','简体中文','包裹');
INSERT INTO international VALUES (377,'WebGUI','简体中文','包裹管理员或系统管理员没有定义包裹。');
INSERT INTO international VALUES (31,'UserSubmission','简体中文','内容');
INSERT INTO international VALUES (32,'UserSubmission','简体中文','图片');
INSERT INTO international VALUES (33,'UserSubmission','简体中文','附件');
INSERT INTO international VALUES (34,'UserSubmission','简体中文','转换回车');
INSERT INTO international VALUES (35,'UserSubmission','简体中文','标题');
INSERT INTO international VALUES (21,'EventsCalendar','简体中文','是否执行添加事务？');
INSERT INTO international VALUES (378,'WebGUI','简体中文','用户 ID');
INSERT INTO international VALUES (379,'WebGUI','简体中文','用户组 ID');
INSERT INTO international VALUES (380,'WebGUI','简体中文','风格 ID');
INSERT INTO international VALUES (381,'WebGUI','简体中文','系统收到一个无效的表单请求，无法继续。当通过表单输入了一些非法字符，通常会导致这个结果。请按浏览器的返回按纽返回上页重新输入。');
INSERT INTO international VALUES (1,'DownloadManager','简体中文','下载管理');
INSERT INTO international VALUES (3,'DownloadManager','简体中文','是否执行添加文件？');
INSERT INTO international VALUES (5,'DownloadManager','简体中文','文件标题');
INSERT INTO international VALUES (6,'DownloadManager','简体中文','下载文件');
INSERT INTO international VALUES (7,'DownloadManager','简体中文','下载用户组');
INSERT INTO international VALUES (8,'DownloadManager','简体中文','简介');
INSERT INTO international VALUES (9,'DownloadManager','简体中文','编辑下载管理员');
INSERT INTO international VALUES (10,'DownloadManager','简体中文','编辑下载');
INSERT INTO international VALUES (11,'DownloadManager','简体中文','添加新下载');
INSERT INTO international VALUES (12,'DownloadManager','简体中文','您是否确定要删除此下载项吗？');
INSERT INTO international VALUES (22,'DownloadManager','简体中文','是否执行添加下载？');
INSERT INTO international VALUES (14,'DownloadManager','简体中文','文件');
INSERT INTO international VALUES (15,'DownloadManager','简体中文','描述');
INSERT INTO international VALUES (16,'DownloadManager','简体中文','上载日期');
INSERT INTO international VALUES (15,'Article','简体中文','靠右');
INSERT INTO international VALUES (16,'Article','简体中文','靠左');
INSERT INTO international VALUES (17,'Article','简体中文','居中');
INSERT INTO international VALUES (37,'UserSubmission','简体中文','删除');
INSERT INTO international VALUES (13,'SQLReport','简体中文','Convert carriage returns?');
INSERT INTO international VALUES (17,'DownloadManager','简体中文','其他版本 #1');
INSERT INTO international VALUES (18,'DownloadManager','简体中文','其他版本 #2');
INSERT INTO international VALUES (19,'DownloadManager','简体中文','没有您可以下载的文件。');
INSERT INTO international VALUES (14,'EventsCalendar','简体中文','开始日期');
INSERT INTO international VALUES (15,'EventsCalendar','简体中文','结束日期');
INSERT INTO international VALUES (20,'DownloadManager','简体中文','在后面标注页码');
INSERT INTO international VALUES (14,'SQLReport','简体中文','Paginate After');
INSERT INTO international VALUES (16,'EventsCalendar','简体中文','行事历布局');
INSERT INTO international VALUES (17,'EventsCalendar','简体中文','列表方式');
INSERT INTO international VALUES (18,'EventsCalendar','简体中文','日历方式');
INSERT INTO international VALUES (19,'EventsCalendar','简体中文','在后面标注页码');
INSERT INTO international VALUES (529,'WebGUI','简体中文','结果');
INSERT INTO international VALUES (383,'WebGUI','简体中文','名字');
INSERT INTO international VALUES (384,'WebGUI','简体中文','文件');
INSERT INTO international VALUES (385,'WebGUI','简体中文','参数');
INSERT INTO international VALUES (386,'WebGUI','简体中文','编辑图象');
INSERT INTO international VALUES (387,'WebGUI','简体中文','上载人');
INSERT INTO international VALUES (388,'WebGUI','简体中文','上载日期');
INSERT INTO international VALUES (389,'WebGUI','简体中文','图象 ID');
INSERT INTO international VALUES (390,'WebGUI','简体中文','显示图象...');
INSERT INTO international VALUES (391,'WebGUI','简体中文','删除附加文件。');
INSERT INTO international VALUES (392,'WebGUI','简体中文','您确定要删除此图象吗？');
INSERT INTO international VALUES (393,'WebGUI','简体中文','管理图象');
INSERT INTO international VALUES (394,'WebGUI','简体中文','管理图象。');
INSERT INTO international VALUES (395,'WebGUI','简体中文','添加新图象。');
INSERT INTO international VALUES (396,'WebGUI','简体中文','查看图象');
INSERT INTO international VALUES (397,'WebGUI','简体中文','返回图象列表。');
INSERT INTO international VALUES (398,'WebGUI','简体中文','文档类型定义');
INSERT INTO international VALUES (399,'WebGUI','简体中文','分析本页面。');
INSERT INTO international VALUES (400,'WebGUI','简体中文','是否阻止代理缓存？');
INSERT INTO international VALUES (401,'WebGUI','简体中文','您是否确定要删除此条消息以及此条消息的所有线索？');
INSERT INTO international VALUES (402,'WebGUI','简体中文','您要阅读的消息不存在。');
INSERT INTO international VALUES (403,'WebGUI','简体中文','不告诉你');
INSERT INTO international VALUES (405,'WebGUI','简体中文','最后一页');
INSERT INTO international VALUES (406,'WebGUI','简体中文','快照大小');
INSERT INTO international VALUES (21,'DownloadManager','简体中文','显示快照');
INSERT INTO international VALUES (407,'WebGUI','简体中文','点击此处注册。');
INSERT INTO international VALUES (15,'SQLReport','简体中文','Preprocess macros on query?');
INSERT INTO international VALUES (16,'SQLReport','简体中文','Debug?');
INSERT INTO international VALUES (17,'SQLReport','简体中文','<b>Debug:</b> Query:');
INSERT INTO international VALUES (18,'SQLReport','简体中文','There were no results for this query.');
INSERT INTO international VALUES (506,'WebGUI','简体中文','管理模板');
INSERT INTO international VALUES (535,'WebGUI','简体中文','当新用户注册时通知用户组');
INSERT INTO international VALUES (353,'WebGUI','简体中文','现在您的收件箱中没有消息。');
INSERT INTO international VALUES (530,'WebGUI','简体中文','搜索<b>所有</b>关键字');
INSERT INTO international VALUES (408,'WebGUI','简体中文','管理根页面');
INSERT INTO international VALUES (409,'WebGUI','简体中文','添加新根页面。');
INSERT INTO international VALUES (410,'WebGUI','简体中文','管理根页面。');
INSERT INTO international VALUES (411,'WebGUI','简体中文','目录标题');
INSERT INTO international VALUES (412,'WebGUI','简体中文','页面描述');
INSERT INTO international VALUES (9,'SiteMap','简体中文','显示简介？');
INSERT INTO international VALUES (18,'Article','简体中文','是否允许讨论？');
INSERT INTO international VALUES (19,'Article','简体中文','谁可以发表？');
INSERT INTO international VALUES (20,'Article','简体中文','谁可以管理？');
INSERT INTO international VALUES (21,'Article','简体中文','编辑超时');
INSERT INTO international VALUES (22,'Article','简体中文','作者');
INSERT INTO international VALUES (23,'Article','简体中文','日期');
INSERT INTO international VALUES (24,'Article','简体中文','发表回应');
INSERT INTO international VALUES (25,'Article','简体中文','编辑回应');
INSERT INTO international VALUES (26,'Article','简体中文','删除回应');
INSERT INTO international VALUES (27,'Article','简体中文','返回文章');
INSERT INTO international VALUES (413,'WebGUI','简体中文','遇到严重错误时');
INSERT INTO international VALUES (28,'Article','简体中文','查看回应');
INSERT INTO international VALUES (414,'WebGUI','简体中文','显示除错信息。');
INSERT INTO international VALUES (415,'WebGUI','简体中文','显示友好信息。');
INSERT INTO international VALUES (416,'WebGUI','简体中文','<h1>您的请求出现问题</h1> \r\n您的请求出现一个错误。请按浏览器的返回按钮返回上一页重试一次。如果此项错误继续存在，请联系我们，同时告诉我们您在什么时间使用什么功能的时候出现的这个错误。谢谢！');
INSERT INTO international VALUES (417,'WebGUI','简体中文','<h1>安全警报</h1>\r\n 您访问的组件不在这一页上。此信息已经发送给系统管理员。');
INSERT INTO international VALUES (418,'WebGUI','简体中文','HTML 过滤');
INSERT INTO international VALUES (419,'WebGUI','简体中文','清除所有的标识符。');
INSERT INTO international VALUES (420,'WebGUI','简体中文','保留所有的标识符。');
INSERT INTO international VALUES (421,'WebGUI','简体中文','保留基本的标识符。');
INSERT INTO international VALUES (422,'WebGUI','简体中文','<h1>登录失败</h1>\r\n您输入的帐户信息有误。');
INSERT INTO international VALUES (423,'WebGUI','简体中文','查看活动对话。');
INSERT INTO international VALUES (424,'WebGUI','简体中文','查看登录历史记录。');
INSERT INTO international VALUES (425,'WebGUI','简体中文','活动对话');
INSERT INTO international VALUES (426,'WebGUI','简体中文','登录历史记录');
INSERT INTO international VALUES (427,'WebGUI','简体中文','风格');
INSERT INTO international VALUES (428,'WebGUI','简体中文','用户 (ID)');
INSERT INTO international VALUES (429,'WebGUI','简体中文','登录时间');
INSERT INTO international VALUES (430,'WebGUI','简体中文','最后访问页面');
INSERT INTO international VALUES (431,'WebGUI','简体中文','IP 地址');
INSERT INTO international VALUES (432,'WebGUI','简体中文','过期');
INSERT INTO international VALUES (433,'WebGUI','简体中文','用户端');
INSERT INTO international VALUES (434,'WebGUI','简体中文','状态');
INSERT INTO international VALUES (435,'WebGUI','简体中文','对话信号');
INSERT INTO international VALUES (436,'WebGUI','简体中文','杀掉此对话');
INSERT INTO international VALUES (437,'WebGUI','简体中文','统计信息');
INSERT INTO international VALUES (438,'WebGUI','简体中文','您的名字');
INSERT INTO international VALUES (439,'WebGUI','简体中文','个人信息');
INSERT INTO international VALUES (440,'WebGUI','简体中文','联系信息');
INSERT INTO international VALUES (441,'WebGUI','简体中文','电子邮件到传呼网关');
INSERT INTO international VALUES (442,'WebGUI','简体中文','工作信息');
INSERT INTO international VALUES (443,'WebGUI','简体中文','家庭信息');
INSERT INTO international VALUES (444,'WebGUI','简体中文','个人隐私');
INSERT INTO international VALUES (445,'WebGUI','简体中文','喜好设置');
INSERT INTO international VALUES (446,'WebGUI','简体中文','单位网站');
INSERT INTO international VALUES (447,'WebGUI','简体中文','管理页面树');
INSERT INTO international VALUES (448,'WebGUI','简体中文','页面树');
INSERT INTO international VALUES (449,'WebGUI','简体中文','一般信息');
INSERT INTO international VALUES (450,'WebGUI','简体中文','单位名称');
INSERT INTO international VALUES (451,'WebGUI','简体中文','必需');
INSERT INTO international VALUES (452,'WebGUI','简体中文','进入中...');
INSERT INTO international VALUES (453,'WebGUI','简体中文','创建日期');
INSERT INTO international VALUES (454,'WebGUI','简体中文','最后更新');
INSERT INTO international VALUES (455,'WebGUI','简体中文','编辑用户信息。');
INSERT INTO international VALUES (456,'WebGUI','简体中文','返回用户列表。');
INSERT INTO international VALUES (457,'WebGUI','简体中文','编辑此用户帐户。');
INSERT INTO international VALUES (458,'WebGUI','简体中文','编辑此用户组群。');
INSERT INTO international VALUES (459,'WebGUI','简体中文','编辑此用户属性。');
INSERT INTO international VALUES (460,'WebGUI','简体中文','时区');
INSERT INTO international VALUES (461,'WebGUI','简体中文','日期格式');
INSERT INTO international VALUES (462,'WebGUI','简体中文','时间格式');
INSERT INTO international VALUES (463,'WebGUI','简体中文','文本输入区行数');
INSERT INTO international VALUES (464,'WebGUI','简体中文','文本输入区列数');
INSERT INTO international VALUES (465,'WebGUI','简体中文','文本框大小');
INSERT INTO international VALUES (466,'WebGUI','简体中文','您确定要删除此类别并且将此类别下所有栏目移动到一般类别吗？');
INSERT INTO international VALUES (467,'WebGUI','简体中文','您确定要删除此栏目，并且所有关于此栏目的用户信息吗？');
INSERT INTO international VALUES (469,'WebGUI','简体中文','ID');
INSERT INTO international VALUES (470,'WebGUI','简体中文','名字');
INSERT INTO international VALUES (472,'WebGUI','简体中文','标题');
INSERT INTO international VALUES (473,'WebGUI','简体中文','可见？');
INSERT INTO international VALUES (474,'WebGUI','简体中文','必须？');
INSERT INTO international VALUES (475,'WebGUI','简体中文','文字');
INSERT INTO international VALUES (476,'WebGUI','简体中文','文字区');
INSERT INTO international VALUES (477,'WebGUI','简体中文','HTML 区');
INSERT INTO international VALUES (478,'WebGUI','简体中文','URL');
INSERT INTO international VALUES (479,'WebGUI','简体中文','日期');
INSERT INTO international VALUES (480,'WebGUI','简体中文','电子邮件地址');
INSERT INTO international VALUES (481,'WebGUI','简体中文','电话号码');
INSERT INTO international VALUES (482,'WebGUI','简体中文','数字 (整数)');
INSERT INTO international VALUES (483,'WebGUI','简体中文','是或否');
INSERT INTO international VALUES (484,'WebGUI','简体中文','选择列表');
INSERT INTO international VALUES (485,'WebGUI','简体中文','布尔值 (选择框)');
INSERT INTO international VALUES (486,'WebGUI','简体中文','数据类型');
INSERT INTO international VALUES (487,'WebGUI','简体中文','可选值');
INSERT INTO international VALUES (488,'WebGUI','简体中文','默认值');
INSERT INTO international VALUES (489,'WebGUI','简体中文','属性类');
INSERT INTO international VALUES (490,'WebGUI','简体中文','添加一个属性类。');
INSERT INTO international VALUES (491,'WebGUI','简体中文','添加一个属性栏。');
INSERT INTO international VALUES (492,'WebGUI','简体中文','属性栏列表。');
INSERT INTO international VALUES (493,'WebGUI','简体中文','返回网站。');
INSERT INTO international VALUES (495,'WebGUI','简体中文','内置编辑器');
INSERT INTO international VALUES (496,'WebGUI','简体中文','使用');
INSERT INTO international VALUES (494,'WebGUI','简体中文','Real Objects Edit-On Pro');
INSERT INTO international VALUES (497,'WebGUI','简体中文','开始日期');
INSERT INTO international VALUES (498,'WebGUI','简体中文','结束日期');
INSERT INTO international VALUES (499,'WebGUI','简体中文','组件 ID');
INSERT INTO international VALUES (500,'WebGUI','简体中文','页面 ID');
INSERT INTO international VALUES (514,'WebGUI','简体中文','访问');
INSERT INTO international VALUES (527,'WebGUI','简体中文','默认首页');
INSERT INTO international VALUES (503,'WebGUI','简体中文','模板 ID');
INSERT INTO international VALUES (501,'WebGUI','简体中文','主体');
INSERT INTO international VALUES (528,'WebGUI','简体中文','模板名称');
INSERT INTO international VALUES (468,'WebGUI','简体中文','编辑用户属性类');
INSERT INTO international VALUES (159,'WebGUI','简体中文','收件箱');
INSERT INTO international VALUES (508,'WebGUI','简体中文','管理模板。');
INSERT INTO international VALUES (39,'UserSubmission','简体中文','发表回复');
INSERT INTO international VALUES (40,'UserSubmission','简体中文','作者');
INSERT INTO international VALUES (41,'UserSubmission','简体中文','日期');
INSERT INTO international VALUES (42,'UserSubmission','简体中文','编辑回应');
INSERT INTO international VALUES (43,'UserSubmission','简体中文','删除回应');
INSERT INTO international VALUES (45,'UserSubmission','简体中文','返回投稿系统');
INSERT INTO international VALUES (46,'UserSubmission','简体中文','更多...');
INSERT INTO international VALUES (47,'UserSubmission','简体中文','回复');
INSERT INTO international VALUES (48,'UserSubmission','简体中文','是否允许讨论？');
INSERT INTO international VALUES (49,'UserSubmission','简体中文','编辑超时');
INSERT INTO international VALUES (50,'UserSubmission','简体中文','允许发表的用户组');
INSERT INTO international VALUES (44,'UserSubmission','简体中文','允许管理的用户组');
INSERT INTO international VALUES (51,'UserSubmission','简体中文','显示快照？');
INSERT INTO international VALUES (52,'UserSubmission','简体中文','快照');
INSERT INTO international VALUES (53,'UserSubmission','简体中文','布局');
INSERT INTO international VALUES (54,'UserSubmission','简体中文','留言模式');
INSERT INTO international VALUES (55,'UserSubmission','简体中文','列表模式');
INSERT INTO international VALUES (56,'UserSubmission','简体中文','相册');
INSERT INTO international VALUES (57,'UserSubmission','简体中文','回应');
INSERT INTO international VALUES (11,'FAQ','简体中文','是否打开 TOC ？');
INSERT INTO international VALUES (12,'FAQ','简体中文','是否打开 Q/A ？');
INSERT INTO international VALUES (13,'FAQ','简体中文','是否打开 [top] 连接？');
INSERT INTO international VALUES (14,'FAQ','简体中文','Q');
INSERT INTO international VALUES (15,'FAQ','简体中文','A');
INSERT INTO international VALUES (16,'FAQ','简体中文','[返回顶端]');
INSERT INTO international VALUES (509,'WebGUI','简体中文','讨论布局');
INSERT INTO international VALUES (510,'WebGUI','简体中文','平铺');
INSERT INTO international VALUES (511,'WebGUI','简体中文','线索');
INSERT INTO international VALUES (512,'WebGUI','简体中文','下一条线索');
INSERT INTO international VALUES (513,'WebGUI','简体中文','上一条线索');
INSERT INTO international VALUES (534,'WebGUI','简体中文','新用户提示？');
INSERT INTO international VALUES (354,'WebGUI','简体中文','查看收件箱。');
INSERT INTO international VALUES (531,'WebGUI','简体中文','包括<b>完整的拼写</b>');
INSERT INTO international VALUES (518,'WebGUI','简体中文','收件箱提示');
INSERT INTO international VALUES (519,'WebGUI','简体中文','我希望被提醒。');
INSERT INTO international VALUES (520,'WebGUI','简体中文','我希望通过电子邮件的方式提醒。');
INSERT INTO international VALUES (521,'WebGUI','简体中文','我希望通过电子邮件到传呼的方式提醒。');
INSERT INTO international VALUES (522,'WebGUI','简体中文','我希望通过 ICQ 的方式提醒。');
INSERT INTO international VALUES (523,'WebGUI','简体中文','提醒');
INSERT INTO international VALUES (524,'WebGUI','简体中文','是否添加编辑戳？');
INSERT INTO international VALUES (525,'WebGUI','简体中文','编辑内容设置');
INSERT INTO international VALUES (526,'WebGUI','简体中文','只清除 JavaScript 。');
insert into incrementer values ('languageId',1000);
create table language (languageId int not null primary key, language varchar(255), characterSet varchar(255));
insert into language values (1,'English','ISO-8859-1');
insert into language values (2,'Deutsch','ISO-8859-1');
insert into language values (3,'Dutch','ISO-8859-1');
insert into language values (4,'Espa駉l','ISO-8859-1');
insert into language values (5,'Portugu阺','ISO-8859-1');
insert into language values (6,'Svenska','ISO-8859-1');
insert into language values (7,'简体中文 (Chinese Simple)','gb2312');
update international set language=1 where language='English';
update international set language=2 where language='Deutsch';
update international set language=3 where language='Dutch';
update international set language=4 where language='Espa駉l';
update international set language=5 where language='Portugu阺';
update international set language=6 where language='Svenska';
update international set language=7 where language='简体中文';
alter table international change language languageId int not null default 1;
update userProfileData set fieldData=1 where fieldname='language' and fieldData='English';
update userProfileData set fieldData=2 where fieldname='language' and fieldData='Deutsch';
update userProfileData set fieldData=3 where fieldname='language' and fieldData='Dutch';
update userProfileData set fieldData=4 where fieldname='language' and fieldData='Espa駉l';
update userProfileData set fieldData=5 where fieldname='language' and fieldData='Portugu阺';
update userProfileData set fieldData=6 where fieldname='language' and fieldData='Svenska';
update userProfileData set fieldData=7 where fieldname='language' and fieldData='简体中文';
update userProfileField set dataDefault='[1]' where fieldName='language';
update help set language=1 where language='English';
update help set language=2 where language='Deutsch';
update help set language=3 where language='Dutch';
update help set language=4 where language='Espa駉l';
update help set language=5 where language='Portugu阺';
update help set language=6 where language='Svenska';
update help set language=7 where language='简体中文';
alter table help change language languageId int not null default 1;




















