insert into webguiVersion values ('5.0.1','upgrade',unix_timestamp());
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=89;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (89,2,'EventsCalendar','3 Monate vom Beginn an anzeigen', 1040662577);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=88;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (88,2,'EventsCalendar','6 Monate vom Beginn an anzeigen', 1040662541);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=87;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (87,2,'EventsCalendar','9 Monate vom Beginn an anzeigen', 1040662529);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=86;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (86,2,'EventsCalendar','12 Monate vom Beginn an anzeigen', 1040662515);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=83;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (83,2,'EventsCalendar','Erster im Kalender', 1040662448);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=85;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (85,2,'EventsCalendar','Letzter im Kalender', 1040662419);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=82;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (82,2,'EventsCalendar','Aktuell', 1040662319);
delete from international where languageId=2 and namespace='USS' and internationalId=30;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (30,2,'USS','Karma pro Benutzer Beitrag', 1040656066);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=627;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (627,2,'WebGUI','Profile werden genutzt, um sich weitergehende Informationen über einen bestimmten Benuter anzuschauen. Für mache Seiten sind Profile wichtig, für andere wiederum nicht. Das Profilsystem ist komplett anpassbar. Sie können so viel Informationen anzeigen oder anfordern, wie Sie möchten.', 1040655917);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=638;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (638,2,'WebGUI','Templates werden eingesetzt um das Layout in WebGUI festzulegen. Mit WebGUI werden viele Templates ausgeliefert. Und mit der Templateverwaltung können Sie Ihrer eigenen Templates erstellen, damit Ihre Seite genau so aussieht, wie Sie sie sich vorstellen. ', 1040655721);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=639;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (639,2,'WebGUI','<b>Template Name</b><br>\r\nVergeben Sie einen aussagekräftigen Namen, damit Sie später wissen, wofür dieses Template ist.\r\n<br><br>\r\n<b>Namensbereich</b><br>\r\nWelcher Template Typ ist es? z.B. Template für das Textelement\r\n<br><br>\r\n<b>Template</b><br>\r\nBenutzen Sie zur Erstellung des Templates die vorhandenen Template-Befehle und Variablen, Macros und auch HTML-Code.\r\n<br><br>\r\n<b>Beachten Sie:</b><br>\r\nSie sollten niemals die Standardtemplates, die mit WebGUI ausgeliefert werden, bearbeiten, da diese oft mit jeder neuen Version von WebGUI geändert werden. Verfahren Sie stattdessen so, dass Sie ein Template Ihrer Wahl zuerst kopieren und dann mit dieser Kopie weiterarbeiten und z. B. einen neuen Namen vergeben etc.', 1040655572);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=838;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (838,2,'WebGUI','Verzeichnisse (Ordner) werden zum Organisieren von Uploads genutzt, ähnlich wie Sie Dateien auf Ihrer Festplatte in Verzeichnisses sortiert haben.\r\n<br><br>\r\n<b>In Verzeichnisses organisieren</b><br>\r\nVerzeichnisse können sich innerhalb anderer Verzeichnisse befinden. In welchen Ordner möchten Sie diesen Ordner verschieben?\r\n<br><br>\r\n<b>Name</b><br>\r\nBenennen Sie den Ordner so, dass Sie auch erkennen, was sich darin befindet (z. B. Grafiken, Private Bilder, Musikfiles, ...)\r\n<br><br>\r\n<b>Beschreibung</b><br>\r\nGeben Sie eine kurze Beschreibung des Ordners an, so dass Sie sich z. b. warum Sie diesen Ordner erstellt haben, was sich darin befindet, etc.', 1040655148);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=830;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (830,2,'WebGUI','Seiten Templates werden genutzt um Wobjects auf Ihrer Seite zu organisieren. Um dies zu ermöglichen, müssen Sie Template Positionen erstellen. Sie können eine unbegrenzte Anzahl von Postionsnummern in Ihren Seiten-Templates benutzen, aber sie müssen dafür immer eine Position schaffen. Die Template Positions Variablen können ungefähr so aussehen:<br><br>\r\n\r\n<pre>\r\n&lt;tmpl_var page.position1&gt;\r\n&lt;tmpl_var page.position2&gt;\r\n&lt;tmpl_var page.position3&gt;\r\n&lt;tmpl_var page.position4&gt;\r\n&lt;tmpl_var page.position5&gt;\r\n&lt;tmpl_var page.position6&gt;\r\n&lt;tmpl_var page.position7&gt;\r\n&lt;tmpl_var ...&gt;\r\n\r\n</pre>\r\n\r\n\r\nSie können mehr als 1 Million dieser Positionen einsetzen... Das sollte mehr als genug auch für die komplexeste Seite sein.', 1040654716);
delete from international where languageId=2 and namespace='Item' and internationalId=74;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (74,2,'Item','Nachfolgend eine Liste von Template Variablen für Textelement Templates.\r\n<br><br>\r\n<b>attachment.name</b><br>\r\nDer Dateiname für den Anhang\r\n<br><br>\r\n<b>attachment.url</b><br>\r\nDie URL zum Downloaden des Anhangs\r\n<br><br>\r\n<b>attachment.icon</b><br>\r\nDie URL zum Icon für den Anhang (z.B. Symbol für PDF-Dateien)<br>', 1040654374);
delete from international where languageId=2 and namespace='FAQ' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,2,'FAQ','<b>Frage</b><br>\r\nFügen Sie die Frage hinzu, die in der FAQ erscheinen soll.\r\n<br><br>\r\n<b>Antwort</b><br>\r\nFügen Sie die Antwort hinzu, die für die Frage, die Sie eben eingegeben haben, erscheinen soll.\r\n<br><br>\r\n<b>Als nächstes?</b><br>\r\nMöchten Sie eine neue Frage hinzufügen, so wählen Sie es hier aus.<br>', 1040654126);
delete from international where languageId=2 and namespace='FAQ' and internationalId=71;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (71,2,'FAQ','Es scheint, dass es auf fast auf jeder Website, privaten Homepage, in Intranets oder auch in Extranets einen F.A.Q-Bereich (Frequently Asked Questions) gibt. Dieses Wobject hilft Ihnen, solch eine FAQ aufzubauen.\r\n<br><br>\r\n<b>Template</b><br>\r\nWählen Sie ein Layout für diese FAQ aus.\r\n<br><br>\r\n<b>Als nächstes?</b><br>\r\nWählen Sie \"Eine Frage hinzufügen\", wenn Sie eine neue Frage hinzufügen möchten.<br><br>\r\n<hr>\r\n<b>Beachten Sie bitte:</b> Die nachfolgende Stylesheet Class ist speziell für die FAQ.\r\n<br><br>\r\n<b>faqQuestion</b><br>\r\nEine FAQ Frage. zum Abgrenzen von der Antwort<br>', 1040653967);
delete from international where languageId=2 and namespace='ExtraColumn' and internationalId=71;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (71,2,'ExtraColumn','Extra Spalten erlauben Ihnen, unbhängig vom Gesamtlayout(Style) Ihrer Seite für die momentan ausgewählte Seite eine Zusatzspalte einzufügen.\r\n<br><br>\r\nMöchten Sie mehrere Spalten auf all Ihren Seiten haben, müssen Sie den Style entsprechend bearbeiten oder stattdessen ein Template benutzen.\r\n<br><br>\r\nSpalten werden immer von links nach rechts hinzugefügt. Deswegen erscheint bereits vorhandener Content links von der neuen Spalte.\r\n<br><br>\r\n<b>Platzhalter</b><br>\r\nDer Platzhalter ist die Grösse der Abstände zwischen dem bereits vorhandenen Content und Ihrer neuen Spalte. Angaben in Pixel.\r\n<br><br>\r\n<b>Breite</b><br>\r\nGeben Sie hier bitte die Breite in Pixel für die neue Spalte an.\r\n<br><br>\r\n<b>StyleSheet Class</b><br>\r\nWenn Sie eine spezielle StyleSheet Class für Spalten benutzen, können Sie diese hier angeben.', 1040653582);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,2,'EventsCalendar','<b>Titel</b><br>\r\nBezeichnung dieses Ereignisses\r\n<br><br>\r\n<b>Description</b><br>\r\nBeschreibung dieses Ereignisses\r\n<br><br>\r\n<b>Start Datum</b><br>\r\nWann beginnt das Ereignis?\r\n<br><br>\r\n<b>Ende Datum</b><br>\r\nWann endet das Ereignis?\r\n<br><br>\r\n<b>Wiederholt sich</b><br>\r\nWählen Sie einen Wiederholungszeitraum für dieses Ereignis aus\r\n<br><br>\r\n<b>Als nächstes?</b><br>\r\nWählen Sie \"Neues Ereignis hinzufügen\", wenn Sie ein neues Ereignis hinzufügen möchten, andernfalls wählen Sie \"Zurück zur Seite\".\r\n<br>', 1040652689);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=770;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (770,2,'WebGUI','Schnipsel bearbeiten', 1040652306);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=733;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (733,2,'WebGUI','4 geübt', 1040652286);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=731;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (731,2,'WebGUI','2 Anfänger', 1040652248);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=730;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (730,2,'WebGUI','1 Absoluter Anfänger', 1040652226);
delete from international where languageId=2 and namespace='FAQ' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,2,'FAQ','Frage bearbeiten', 1040652178);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=117;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (117,2,'WebGUI','Authentifizierungseinstellungen bearbeiten', 1040652080);
delete from international where languageId=2 and namespace='Auth/SMB' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'Auth/SMB','SMB Anmeldefehler (3)<br>\r\nSie haben einen falschen Benutzernamen oder ein falsches Kennwort eingegeben. Bitte versuchen Sie es noch einmal.', 1040651997);
delete from international where languageId=2 and namespace='Auth/SMB' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'Auth/SMB','SMB Protokol Fehler (2)<br>\r\nBitte nehmen Sie Kontakt mit Ihrem Systemadministrator auf.', 1040651984);
delete from international where languageId=2 and namespace='Auth/SMB' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'Auth/SMB','SMB Server Fehler(1)<br>\r\nProbleme beim Zugriff auf den Domain-Controller. Wahrscheinlich gibt es einen Verbindungs-Timeout. Bitte versuchen Sie es nochmal oder nehmen Sie Kontakt mit Ihrem Systemadministrator auf.', 1040651968);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=422;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (422,2,'WebGUI','<h1>Anmeldung ist fehlgeschlagen!</h1> Die eingegebenen Zugangsdaten stimmen mit keinen Benutzerdaten überein.', 1040651916);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=416;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (416,2,'WebGUI','<h1>Abfrageproblem</h1> Ihre Anfrage macht dem\r\nSystem Probleme. Bitte betätigen Sie den Zurückbutton im Browser und\r\nversuchen Sie es nochmal. Sollte dieses Problem weiterbestehen, teilen Sie uns bitte mit, was Sie wo im System wann gemacht haben.', 1040651888);
delete from international where languageId=2 and namespace='Article' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,2,'Article','Die nachfolgenden Template Variablen sind für Artikel Templates verfügbar.<br><br>\r\n\r\n<b>attachment.box</b><br>\r\nGibt eine Standard WebGUI Anlagen-Box aus mit Icon, Dateiname und Anlageindikator. \r\n<br><br>\r\n<b>attachment.icon</b><br>\r\nDie URL zum Icon-Symbol für diesen Anlagentyp.\r\n<br><br>\r\n<b>attachment.name</b><br>\r\nDer Dateiname für diese Anlage.\r\n<br><br>\r\n<b>attachment.url</b><br>\r\nDie URL zum Downloaden dieser Anlage. \r\n<br><br>\r\n<b>image.thumbnail</b><br>\r\nDie URL zum Thumbnail für die angefügte Grafik.\r\n<br><br>\r\n<b>image.url</b><br>\r\nDie URL zur angefügten Grafik. \r\n<br><br>\r\n<b>post.label</b><br>\r\nDas übersetzte Label um Kommentare zu diesem Artikel hinzuzufügen. \r\n<br><br>\r\n<b>post.URL</b><br>\r\nDie URL um einen Kommentar zu diesem Artikel hinzuzufügen. \r\n<br><br>\r\n<b>replies.count</b><br>\r\nDie Anzahl d!
 er Kommentare zu diesem Artikel. \r\n<br><br>\r\n<b>replies.label</b><br>\r\nDer übersetzte Text, der anzeigt, dass Sie die Kommentare anschauen können..\r\n<br><br> \r\n\r\n<b>replies.url</b><br>\r\nDie URL, um die Kommentare zu diesem Artikel anzuschauen.', 1040651575);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=681;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (681,2,'WebGUI','Pakete erstellen', 1040651285);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=535;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (535,2,'WebGUI','Gruppe, die bei einem neuen Benutzer benachrichtigt werden soll', 1040651243);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=68;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (68,2,'WebGUI','Die Benutzerkontoinformationen, die Sie eingegeben haben, sind ungültig. Entweder existiert das Konto nicht, oder die Kombination aus Benutzername und Passwort ist falsch.', 1040651193);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=53;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (53,2,'WebGUI','Druckbares Format', 1040651152);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=472;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (472,2,'WebGUI','Label', 1040651094);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=412;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (412,2,'WebGUI','Zusammenfassung', 1040651014);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=402;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (402,2,'WebGUI','Die Nachricht, die Sie abfragen möchten, existiert leider nicht.', 1040650980);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=406;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (406,2,'WebGUI','Thumbnail Größe', 1040650952);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=398;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (398,2,'WebGUI','Dokumententyp Beschreibung', 1040650908);
delete from international where languageId=2 and namespace='Survey' and internationalId=48;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (48,2,'Survey','Sie sind momentan nicht berechtigt, an dieser Umfrage teilzunehmen.', 1040650776);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=38;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (38,2,'WebGUI','Sie sind nicht berechtigt, diese Aktion auszuführen. ^a(\"Melden Sie sich bitte mit einem Benutzernamen an\");, der über ausreichende Rechte verfügt.', 1040650735);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=360;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (360,2,'WebGUI','Einer über drei', 1040650631);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=233;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (233,2,'WebGUI','(eom)', 1040650575);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=148;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (148,2,'WebGUI','Wobjects', 1040650550);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=134;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (134,2,'WebGUI','Passwortmeldung wiederherstellen', 1040650516);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=116;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (116,2,'WebGUI','Rechte an alle nachfolgenden Seiten weitergeben.', 1040650415);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=115;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (115,2,'WebGUI','Kann jeder bearbeiten?', 1040650403);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=114;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (114,2,'WebGUI','Kann jeder anschauen?', 1040650391);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=113;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (113,2,'WebGUI','Gruppe kann bearbeiten?', 1040650380);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=112;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (112,2,'WebGUI','Gruppe kann anschauen?', 1040650369);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=111;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (111,2,'WebGUI','Gruppe', 1040650358);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=110;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (110,2,'WebGUI','Besitzer kann bearbeiten?', 1040650348);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=11;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (11,2,'WebGUI','Mülleimer leeren', 1040650325);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=109;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (109,2,'WebGUI','Besitzer kann anschauen?', 1040650313);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=108;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (108,2,'WebGUI','Besitzer', 1040650300);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=107;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (107,2,'WebGUI','Rechte', 1040650272);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=104;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (104,2,'WebGUI','URL der Seite', 1040650221);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=102;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (102,2,'WebGUI','Seite bearbeiten', 1040650212);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=100;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (100,2,'WebGUI','Meta Tags', 1040650200);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'WebGUI','Inhalt hinzufügen...', 1040650189);
delete from international where languageId=2 and namespace='USS' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,2,'USS','Benutzerbeitragssystem hinzufügen oder bearbeiten', 1040650173);
delete from international where languageId=2 and namespace='USS' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'USS','Beiträge pro Seite', 1040650162);
delete from international where languageId=2 and namespace='USS' and internationalId=59;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (59,2,'USS','nächster Beitrag', 1040650142);
delete from international where languageId=2 and namespace='USS' and internationalId=58;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (58,2,'USS','vorheriger Beitrag', 1040650131);
delete from international where languageId=2 and namespace='USS' and internationalId=57;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (57,2,'USS','Antworten', 1040650122);
delete from international where languageId=2 and namespace='USS' and internationalId=53;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (53,2,'USS','Layout', 1040650113);
delete from international where languageId=2 and namespace='USS' and internationalId=51;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (51,2,'USS','Vorschaubild anzeigen?', 1040650103);
delete from international where languageId=2 and namespace='USS' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'USS','Ihr Beitrag wurde abgelehnt.', 1040650082);
delete from international where languageId=2 and namespace='USS' and internationalId=48;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (48,2,'USS','Diskussion erlauben?', 1040650070);
delete from international where languageId=2 and namespace='USS' and internationalId=47;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (47,2,'USS','eine Antwort schreiben', 1040650057);
delete from international where languageId=2 and namespace='USS' and internationalId=46;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (46,2,'USS','Lesen Sie mehr...', 1040650048);
delete from international where languageId=2 and namespace='USS' and internationalId=45;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (45,2,'USS','zurück zu den Beiträgen', 1040650038);
delete from international where languageId=2 and namespace='USS' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'USS','Ihr Betrag wurde angenommen.', 1040650019);
delete from international where languageId=2 and namespace='USS' and internationalId=39;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (39,2,'USS','Antwort schreiben', 1040650007);
delete from international where languageId=2 and namespace='USS' and internationalId=37;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (37,2,'USS','Löschen', 1040649997);
delete from international where languageId=2 and namespace='USS' and internationalId=34;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (34,2,'USS','Carriage Return beachten?', 1040649988);
delete from international where languageId=2 and namespace='USS' and internationalId=31;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (31,2,'USS','Inhalt', 1040649976);
delete from international where languageId=2 and namespace='USS' and internationalId=29;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (29,2,'USS','Benutzer Beitragssystem', 1040649967);
delete from international where languageId=2 and namespace='USS' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'USS','Sie haben einen neuen Beitrag zu genehmigen.', 1040649956);
delete from international where languageId=2 and namespace='USS' and internationalId=28;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (28,2,'USS','Zurück zur Beitragsliste', 1040649930);
delete from international where languageId=2 and namespace='USS' and internationalId=27;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (27,2,'USS','Bearbeiten', 1040649918);
delete from international where languageId=2 and namespace='USS' and internationalId=21;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (21,2,'USS','Erstellt von', 1040649909);
delete from international where languageId=2 and namespace='USS' and internationalId=20;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (20,2,'USS','Neuen Beitrag schreiben', 1040649897);
delete from international where languageId=2 and namespace='USS' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'USS','Wer kann Beiträge schreiben?', 1040649886);
delete from international where languageId=2 and namespace='USS' and internationalId=19;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (19,2,'USS','Beitrag bearbeiten', 1040649874);
delete from international where languageId=2 and namespace='USS' and internationalId=18;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (18,2,'USS','Benutzer Beitragssystem bearbeiten', 1040649861);
delete from international where languageId=2 and namespace='USS' and internationalId=16;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (16,2,'USS','Ohne Titel', 1040649848);
delete from international where languageId=2 and namespace='USS' and internationalId=15;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (15,2,'USS','Bearbeiten/Löschen', 1040649837);
delete from international where languageId=2 and namespace='USS' and internationalId=14;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (14,2,'USS','Status', 1040649826);
delete from international where languageId=2 and namespace='USS' and internationalId=13;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (13,2,'USS','Erstellungsdatum', 1040649817);
delete from international where languageId=2 and namespace='USS' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,2,'USS','(Bitte deaktivieren, wenn Ihr Beitrag in HTML geschrieben ist)', 1040649805);
delete from international where languageId=2 and namespace='USS' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'USS','Wer kann genehmigen?', 1040649787);
delete from international where languageId=2 and namespace='SyndicatedContent' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'SyndicatedContent','Aktueller Inhalt', 1040649770);
delete from international where languageId=2 and namespace='SyndicatedContent' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'SyndicatedContent','zuletzt aktualisiert', 1040649759);
delete from international where languageId=2 and namespace='SyndicatedContent' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'SyndicatedContent','Clipping-Dienst bearbeiten', 1040649742);
delete from international where languageId=2 and namespace='SyndicatedContent' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'SyndicatedContent','Clipping-Dienst', 1040649731);
delete from international where languageId=2 and namespace='SyndicatedContent' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'SyndicatedContent','URL zur RSS-Datei', 1040649721);
delete from international where languageId=2 and namespace='SiteMap' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,2,'SiteMap','SiteMap hinzufügen oder bearbeiten', 1040649701);
delete from international where languageId=2 and namespace='SiteMap' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'SiteMap','Einrückung', 1040649644);
delete from international where languageId=2 and namespace='SiteMap' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'SiteMap','SiteMap bearbeiten', 1040649591);
delete from international where languageId=2 and namespace='SiteMap' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'SiteMap','Tiefe', 1040649577);
delete from international where languageId=2 and namespace='SiteMap' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'SiteMap','Beginnen mit?', 1040649534);
delete from international where languageId=2 and namespace='SiteMap' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'SiteMap','SiteMap', 1040649477);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'SQLReport','<b>Fehler:</b> Die DSN besitzt das falsche Format.', 1040649453);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,2,'SQLReport','SQL Report bearbeiten', 1040649433);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,2,'SQLReport','Datenbankpasswort', 1040649412);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,2,'SQLReport','SQL Bericht hinzufügen oder bearbeiten', 1040649401);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'SQLReport','Datenbankbenutzer', 1040649393);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'SQLReport','DSN (Data Source Name)', 1040649383);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'SQLReport','Abfrage', 1040649369);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'SQLReport','Report Template', 1040649352);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=18;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (18,2,'SQLReport','Diese Abfrage liefert keine Ergebnisse.', 1040649334);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=16;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (16,2,'SQLReport','Debuggen?', 1040649322);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=15;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (15,2,'SQLReport','Sollen die Makros in der Abfrage vorverarbeitet werden?', 1040649287);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=14;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (14,2,'SQLReport','Später mit Seitenzahlen versehen', 1040649247);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=13;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (13,2,'SQLReport','Carriage Return beachten?', 1040649235);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,2,'SQLReport','<b>Fehler:</b> Datenbankverbindung konnte nicht aufgebaut werden.', 1040649187);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=17;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (17,2,'SQLReport','<b>Debug:</b> Abfrage:', 1040649160);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=11;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (11,2,'SQLReport','Fehler: Es gab ein Problem mit der Abfrage.', 1040649134);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,2,'SQLReport','Fehler: Das SQL-Statement ist im falschen Format.', 1040649121);
delete from international where languageId=2 and namespace='SQLReport' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'SQLReport','SQL Bericht', 1040649107);
delete from international where languageId=2 and namespace='Product' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'Product','Produktgrafik 3', 1040649097);
delete from international where languageId=2 and namespace='Product' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,2,'Product','Produktgrafik 1', 1040649077);
delete from international where languageId=2 and namespace='Product' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,2,'Product','Produktgrafik 2', 1040648973);
delete from international where languageId=2 and namespace='Product' and internationalId=62;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (62,2,'Product','Produkt Template hinzufügen oder bearbeiten', 1040648945);
delete from international where languageId=2 and namespace='Product' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'Product','Produkt bearbeiten', 1040648932);
delete from international where languageId=2 and namespace='Product' and internationalId=59;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (59,2,'Product','Name', 1040648917);
delete from international where languageId=2 and namespace='Product' and internationalId=58;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (58,2,'Product','Produkt Template bearbeiten', 1040648907);
delete from international where languageId=2 and namespace='Product' and internationalId=56;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (56,2,'Product','Ein Produkt Template hinzufügen.', 1040648893);
delete from international where languageId=2 and namespace='Product' and internationalId=55;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (55,2,'Product','Gewinn (benefit) hinzufügen', 1040648870);
delete from international where languageId=2 and namespace='Product' and internationalId=54;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (54,2,'Product','Gewinne', 1040648851);
delete from international where languageId=2 and namespace='Product' and internationalId=53;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (53,2,'Product','Gewinn (benefit) bearbeiten', 1040648839);
delete from international where languageId=2 and namespace='Product' and internationalId=52;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (52,2,'Product','Einen weiteren Gewinn hinzufügen?', 1040648808);
delete from international where languageId=2 and namespace='Product' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'Product','Sind Sie sicher, dass Sie die Beziehung zu diesem verwandten Produkt löschen möchten?', 1040648767);
delete from international where languageId=2 and namespace='Product' and internationalId=37;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (37,2,'Product','Verwandtes Produkt hinzufügen', 1040648744);
delete from international where languageId=2 and namespace='Product' and internationalId=20;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (20,2,'Product','verwandtes Produkt', 1040648728);
delete from international where languageId=2 and namespace='Product' and internationalId=21;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (21,2,'Product','weiteres verwandtes Produkt hinzufügen?', 1040648710);
delete from international where languageId=2 and namespace='Product' and internationalId=19;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (19,2,'Product','verwandtes Produkt hinzufügen', 1040648686);
delete from international where languageId=2 and namespace='Product' and internationalId=51;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (51,2,'Product','Gewinn', 1040648651);
delete from international where languageId=2 and namespace='Product' and internationalId=49;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (49,2,'Product','Produktgewinn (benefit) hinzufügen oder bearbeiten', 1040648586);
delete from international where languageId=2 and namespace='Product' and internationalId=46;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (46,2,'Product','Produkt (verwandt) hinzufügen oder bearbeiten', 1040648575);
delete from international where languageId=2 and namespace='Product' and internationalId=40;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (40,2,'Product','Produkteigenschaft hinzufügen oder bearbeiten', 1040648558);
delete from international where languageId=2 and namespace='Product' and internationalId=38;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (38,2,'Product','Produkt hinzufügen oder bearbeiten', 1040648539);
delete from international where languageId=2 and namespace='Product' and internationalId=36;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (36,2,'Product','Zubehör hinzufügen', 1040648529);
delete from international where languageId=2 and namespace='Product' and internationalId=34;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (34,2,'Product','Eine Eigenschaft hinzufügen.', 1040648518);
delete from international where languageId=2 and namespace='Product' and internationalId=33;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (33,2,'Product','Verwandte Produkte', 1040648504);
delete from international where languageId=2 and namespace='Product' and internationalId=32;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (32,2,'Product','Zubehör', 1040648494);
delete from international where languageId=2 and namespace='Product' and internationalId=30;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (30,2,'Product','Eigenschaften', 1040648485);
delete from international where languageId=2 and namespace='FAQ' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,2,'FAQ','Sind Sie sicher, dass Sie diese Frage löschen möchten?', 1040648475);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=466;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (466,2,'WebGUI','Sind Sie sicher, dass Sie diese Kategorie löschen und alle ihre Felder in die Kategorie \'Sonstiges\' verschieben möchten?', 1040648419);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=167;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (167,2,'WebGUI','Sind Sie sicher, dass Sie diesen Benutzer löschen möchten? Die Benutzerinformation geht damit endgültig verloren!', 1040648387);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=101;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (101,2,'WebGUI','Sind Sie sicher, dass Sie diese Seite und ihren kompletten Inhalt darunter löschen möchten?', 1040648355);
delete from international where languageId=2 and namespace='Product' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'Product','Sind Sie sicher, dass Sie diese Anforderung löschen möchten?', 1040648319);
delete from international where languageId=2 and namespace='Product' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'Product','Sind Sie sicher, dass Sie diese Eigenschaft löschen möchten?', 1040648288);
delete from international where languageId=2 and namespace='Product' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'Product','Sind Sie sicher, dass Sie die Verknüpfung zu diesem Zubehör löschen möchten?', 1040648263);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=86;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (86,2,'WebGUI','Sind Sie sicher, dass Sie diese Gruppe löschen möchten? Denken Sie daran, dass diese Gruppe und die zugehörige Rechtesstruktur endgültig gelöscht wird.', 1040648228);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=728;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (728,2,'WebGUI','Sind Sie sicher, daß Sie diese Datei löschen möchten?', 1040648207);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=60;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (60,2,'WebGUI','Sind Sie sicher, dass Sie dieses Benutzerkonto deaktivieren möchten? Wenn Sie fortfahren, sind Ihre Konteninformationen endgültig verloren.', 1040648187);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=588;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (588,2,'WebGUI','Sind Sie sicher, dass Sie diese Übersetzung an Plain Black zur Einbeziehung in die Standardverteilung übermitteln möchten?\r\nWenn Sie den \'Ja\'-Link anklicken, erklären Sie sich damit einverstanden, dass Sie Plain Black eine unbeschränkte Lizenz zur Verwendung der Übersetzung in seiner Softwareverteilung geben.', 1040648165);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=587;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (587,2,'WebGUI','Sind Sie sicher, dass Sie diese Sprache und somit auch alle damit verbundenen sprachspezifischen Nachrichten und damit auch die Hilfenachrichten löschen möchten?', 1040648130);
delete from international where languageId=2 and namespace='USS' and internationalId=17;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (17,2,'USS','Sind Sie sicher, dass Sie diesen Beitrag löschen möchten?', 1040648045);
delete from international where languageId=2 and namespace='Product' and internationalId=57;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (57,2,'Product','Sind Sie sicher, dass Sie dieses Template löschen und alle Produkte, die dieses benutzen, auf die Standardvorlage setzen möchten?', 1040648024);
delete from international where languageId=2 and namespace='MailForm' and internationalId=19;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (19,2,'MailForm','Sind Sie sicher, dass Sie dieses Feld löschen möchten?', 1040647952);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=43;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (43,2,'WebGUI','Sind Sie sicher, dass Sie diesen Inhalt löschen möchten?', 1040647922);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=401;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (401,2,'WebGUI','Sind Sie sicher, dass Sie diese Nachrichten und alle darunterliegenden löschen möchten?', 1040647903);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=162;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (162,2,'WebGUI','Sind Sie sicher, dass Sie alle Seiten und Wobjects im Mülleimer löschen möchten?', 1040647879);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=467;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (467,2,'WebGUI','Sind Sie sicher, dass Sie dieses Feld und alle darauf bezogenen Benutzerdaten löschen möchten?', 1040647852);
delete from international where languageId=2 and namespace='Product' and internationalId=48;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (48,2,'Product','Sind Sie sicher, dass Sie diesen Gewinn (benefit) löschen möchten? Er kann, wenn er einmal gelöscht wurde, nicht mehr wiederhergestellt werden.', 1040647723);
delete from international where languageId=2 and namespace='Product' and internationalId=29;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (29,2,'Product','Einheiten', 1040647667);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=103;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (103,2,'WebGUI','Seitendetails', 1040647645);
delete from international where languageId=2 and namespace='Product' and internationalId=25;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (25,2,'Product','Anforderung bearbeiten', 1040647545);
delete from international where languageId=2 and namespace='Product' and internationalId=35;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (35,2,'Product','Anforderung hinzufügen', 1040647495);
delete from international where languageId=2 and namespace='Product' and internationalId=31;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (31,2,'Product','Anforderungen', 1040647478);
delete from international where languageId=2 and namespace='Product' and internationalId=27;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (27,2,'Product','Anforderung', 1040647436);
delete from international where languageId=2 and namespace='Product' and internationalId=28;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (28,2,'Product','Eine weitere Anforderung hinzufügen?', 1040647402);
delete from international where languageId=2 and namespace='Product' and internationalId=26;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (26,2,'Product','Produktname', 1040647368);
delete from international where languageId=2 and namespace='Product' and internationalId=24;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (24,2,'Product','Eine weitere Eigenschaft hinzufügen?', 1040647336);
delete from international where languageId=2 and namespace='Product' and internationalId=23;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (23,2,'Product','Eigenschaft', 1040647315);
delete from international where languageId=2 and namespace='Product' and internationalId=22;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (22,2,'Product','Eigenschaft bearbeiten', 1040647306);
delete from international where languageId=2 and namespace='Product' and internationalId=15;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (15,2,'Product','Garantie', 1040647244);
delete from international where languageId=2 and namespace='Product' and internationalId=14;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (14,2,'Product','Handbuch', 1040647234);
delete from international where languageId=2 and namespace='Product' and internationalId=13;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (13,2,'Product','Prospekt', 1040647224);
delete from international where languageId=2 and namespace='Product' and internationalId=11;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (11,2,'Product','Produktnummer', 1040647181);
delete from international where languageId=2 and namespace='Product' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,2,'Product','Preis', 1040647172);
delete from international where languageId=2 and namespace='Product' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'Product','Produkt', 1040647163);
delete from international where languageId=2 and namespace='WobjectProxy' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'WobjectProxy','Wobject Proxy hinzufügen oder bearbeiten', 1040647154);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=837;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (837,2,'WebGUI','Verzeichnis hinzufügen oder bearbeiten', 1040647122);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=835;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (835,2,'WebGUI','Schnipsel hinzufügen oder bearbeiten', 1040647101);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=833;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (833,2,'WebGUI','Datei hinzufügen oder bearbeiten', 1040647079);
delete from international where languageId=2 and namespace='Survey' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'Survey','Umfrage hinzufügen oder bearbeiten', 1040647060);
delete from international where languageId=2 and namespace='Product' and internationalId=44;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (44,2,'Product','Produkt Zubehör hinzufügen oder bearbeiten', 1040647041);
delete from international where languageId=2 and namespace='Product' and internationalId=42;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (42,2,'Product','Produkt Beschreibung hinzufügen oder bearbeiten', 1040647019);
delete from international where languageId=2 and namespace='FileManager' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,2,'FileManager','Download Manager hinzufügen oder bearbeiten', 1040646987);
delete from international where languageId=2 and namespace='Poll' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'Poll','Abstimmung bearbeiten', 1040646954);
delete from international where languageId=2 and namespace='Poll' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,2,'Poll','(Eine Antwort pro Zeile. Bitte nicht mehr als 20 verschiedene Antworten)', 1040646943);
delete from international where languageId=2 and namespace='Poll' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,2,'Poll','Antworten zufällig anordnen?', 1040646923);
delete from international where languageId=2 and namespace='Poll' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,2,'Poll','Antworten', 1040646913);
delete from international where languageId=2 and namespace='Poll' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,2,'Poll','Abstimmung hinzufügen oder bearbeiten', 1040646904);
delete from international where languageId=2 and namespace='Poll' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'Poll','Frage', 1040646895);
delete from international where languageId=2 and namespace='Poll' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'Poll','Breite der Grafik', 1040646885);
delete from international where languageId=2 and namespace='Poll' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'Poll','Wer kann abstimmen?', 1040646876);
delete from international where languageId=2 and namespace='Poll' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'Poll','Aktiv', 1040646865);
delete from international where languageId=2 and namespace='Poll' and internationalId=11;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (11,2,'Poll','Abstimmen!', 1040646855);
delete from international where languageId=2 and namespace='Poll' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,2,'Poll','Abstimmung zurücksetzen', 1040646831);
delete from international where languageId=2 and namespace='Poll' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'Poll','Abstimmung', 1040646819);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'MessageBoard','Beitrags ID:', 1040646809);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,2,'MessageBoard','Datum:', 1040646798);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=244;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (244,2,'WebGUI','Autor', 1040646786);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=15;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (15,2,'MessageBoard','Autor', 1040646766);
delete from international where languageId=2 and namespace='Article' and internationalId=22;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (22,2,'Article','Autor', 1040646744);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,2,'MessageBoard','Autor:', 1040646729);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'MessageBoard','Diskussionsforum bearbeiten', 1040646718);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'MessageBoard','Beiträge pro Seite', 1040646708);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=22;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (22,2,'MessageBoard','Beitrag löschen', 1040646696);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=20;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (20,2,'MessageBoard','Letzte Antwort', 1040646685);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'MessageBoard','Diskussionsforum', 1040646673);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=19;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (19,2,'MessageBoard','Antworten', 1040646664);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=18;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (18,2,'MessageBoard','Diskussion begonnen', 1040646655);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=17;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (17,2,'MessageBoard','Neuen Beitrag schreiben', 1040646643);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=16;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (16,2,'MessageBoard','Datum', 1040646632);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,2,'MessageBoard','Beitrag bearbeiten', 1040646622);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=11;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (11,2,'MessageBoard','Zurück zur Beitragsliste', 1040646605);
delete from international where languageId=2 and namespace='MailForm' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'MailForm','Feld hinzufügen', 1040645502);
delete from international where languageId=2 and namespace='MailForm' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,2,'MailForm','Breite', 1040645492);
delete from international where languageId=2 and namespace='MailForm' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,2,'MailForm','Emailformular bearbeiten', 1040645483);
delete from international where languageId=2 and namespace='MailForm' and internationalId=62;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (62,2,'MailForm','Formularfelder hinzufügen oder bearbeiten', 1040645473);
delete from international where languageId=2 and namespace='MailForm' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,2,'MailForm','Emailformular hinzufügen oder bearbeiten', 1040645457);
delete from international where languageId=2 and namespace='MailForm' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'MailForm','veränderbar', 1040645444);
delete from international where languageId=2 and namespace='MailForm' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'MailForm','Angezeigt', 1040645433);
delete from international where languageId=2 and namespace='MailForm' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'MailForm','unsichtbar', 1040645418);
delete from international where languageId=2 and namespace='MailForm' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'MailForm','Vielen Dank für Ihren Beitrag!', 1040645407);
delete from international where languageId=2 and namespace='MailForm' and internationalId=26;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (26,2,'MailForm','Eintragungen speichern?', 1040645391);
delete from international where languageId=2 and namespace='MailForm' and internationalId=25;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (25,2,'MailForm','Standartwert (optional)', 1040645382);
delete from international where languageId=2 and namespace='MailForm' and internationalId=24;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (24,2,'MailForm','Mögliche Werte der Drop-Down Box', 1040645370);
delete from international where languageId=2 and namespace='MailForm' and internationalId=23;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (23,2,'MailForm','Art', 1040645355);
delete from international where languageId=2 and namespace='MailForm' and internationalId=22;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (22,2,'MailForm','Status', 1040645344);
delete from international where languageId=2 and namespace='MailForm' and internationalId=21;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (21,2,'MailForm','Feldname', 1040645334);
delete from international where languageId=2 and namespace='MailForm' and internationalId=20;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (20,2,'MailForm','Feld bearbeiten', 1040645325);
delete from international where languageId=2 and namespace='MailForm' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'MailForm','Hier Betreff ihrer Email eingeben', 1040645315);
delete from international where languageId=2 and namespace='MailForm' and internationalId=18;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (18,2,'MailForm','Zurück!', 1040645179);
delete from international where languageId=2 and namespace='MailForm' and internationalId=17;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (17,2,'MailForm','E-mail wurde gesendet', 1040645170);
delete from international where languageId=2 and namespace='MailForm' and internationalId=16;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (16,2,'MailForm','Eingangsbestätigung', 1040645157);
delete from international where languageId=2 and namespace='MailForm' and internationalId=15;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (15,2,'MailForm','Weitere Felder hinzufügen?', 1040645122);
delete from international where languageId=2 and namespace='MailForm' and internationalId=14;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (14,2,'MailForm','Betreff', 1040645108);
delete from international where languageId=2 and namespace='MailForm' and internationalId=13;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (13,2,'MailForm','Blindkopie', 1040645098);
delete from international where languageId=2 and namespace='MailForm' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,2,'MailForm','Kopie', 1040645088);
delete from international where languageId=2 and namespace='MailForm' and internationalId=11;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (11,2,'MailForm','senden an (Email, Benutzername oder Gruppenname)', 1040645079);
delete from international where languageId=2 and namespace='LinkList' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'LinkList','Sind Sie sicher, dass Sie diesen Link löschen möchten?', 1040645063);
delete from international where languageId=2 and namespace='LinkList' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,2,'LinkList','URL', 1040645046);
delete from international where languageId=2 and namespace='LinkList' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,2,'LinkList','Link hinzufügen oder bearbeiten', 1040645036);
delete from international where languageId=2 and namespace='LinkList' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,2,'LinkList','Linkliste hinzufügen oder bearbeiten', 1040645027);
delete from international where languageId=2 and namespace='LinkList' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'LinkList','Link Liste', 1040645017);
delete from international where languageId=2 and namespace='LinkList' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'LinkList','In neuem Fenster öffnen?', 1040645008);
delete from international where languageId=2 and namespace='LinkList' and internationalId=13;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (13,2,'LinkList','Neuen Link hinzufügen', 1040644996);
delete from international where languageId=2 and namespace='LinkList' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,2,'LinkList','Link bearbeiten', 1040644982);
delete from international where languageId=2 and namespace='LinkList' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,2,'LinkList','Link Liste bearbeiten', 1040644971);
delete from international where languageId=2 and namespace='Item' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,2,'Item','Textelement hinzufügen oder bearbeiten', 1040644958);
delete from international where languageId=2 and namespace='Item' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'Item','Textelement bearbeiten', 1040644948);
delete from international where languageId=2 and namespace='Item' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'Item','Anhang herunterladen', 1040644938);
delete from international where languageId=2 and namespace='Item' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'Item','Textelement', 1040644925);
delete from international where languageId=2 and namespace='Item' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'Item','Anhang löschen', 1040644914);
delete from international where languageId=2 and namespace='Item' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'Item','Anhang', 1040644904);
delete from international where languageId=2 and namespace='Item' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'Item','Link URL', 1040644895);
delete from international where languageId=2 and namespace='FileManager' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'FileManager','Download Manager bearbeiten', 1040644884);
delete from international where languageId=2 and namespace='FileManager' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,2,'FileManager','Kurze Beschreibung', 1040644869);
delete from international where languageId=2 and namespace='FileManager' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,2,'FileManager','Download hinzufügen oder bearbeiten', 1040644857);
delete from international where languageId=2 and namespace='FileManager' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,2,'FileManager','Gruppe, die Download benutzen kann', 1040644847);
delete from international where languageId=2 and namespace='FileManager' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'FileManager','Dateiname', 1040644818);
delete from international where languageId=2 and namespace='FileManager' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'FileManager','Dateititel', 1040644808);
delete from international where languageId=2 and namespace='FileManager' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'FileManager','Fortfahren, die Datei hinzuzufügen?', 1040644798);
delete from international where languageId=2 and namespace='FileManager' and internationalId=20;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (20,2,'FileManager','Später mit Seitenzahlen versehen', 1040644783);
delete from international where languageId=2 and namespace='FileManager' and internationalId=19;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (19,2,'FileManager','Sie besitzen keine Dateien, die zum Download bereitstehen.', 1040644770);
delete from international where languageId=2 and namespace='FileManager' and internationalId=18;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (18,2,'FileManager','Alternative #2', 1040644753);
delete from international where languageId=2 and namespace='FileManager' and internationalId=17;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (17,2,'FileManager','Alternative #1', 1040644743);
delete from international where languageId=2 and namespace='FileManager' and internationalId=16;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (16,2,'FileManager','Upload Datum', 1040644733);
delete from international where languageId=2 and namespace='FileManager' and internationalId=15;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (15,2,'FileManager','Beschreibung', 1040644722);
delete from international where languageId=2 and namespace='FileManager' and internationalId=14;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (14,2,'FileManager','Datei', 1040644713);
delete from international where languageId=2 and namespace='FileManager' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,2,'FileManager','Sind Sie sicher, dass Sie diesen Download löschen möchten?', 1040644704);
delete from international where languageId=2 and namespace='FileManager' and internationalId=11;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (11,2,'FileManager','Neuen Download hinzufügen.', 1040644692);
delete from international where languageId=2 and namespace='FileManager' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,2,'FileManager','Download bearbeiten', 1040644674);
delete from international where languageId=2 and namespace='FileManager' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'FileManager','Download Manager', 1040644661);
delete from international where languageId=2 and namespace='FAQ' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'FAQ','Neue Frage hinzufügen.', 1040644646);
delete from international where languageId=2 and namespace='FAQ' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,2,'FAQ','F.A.Q. bearbeiten', 1040644631);
delete from international where languageId=2 and namespace='FAQ' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,2,'FAQ','Frage hinzufügen oder bearbeiten', 1040644620);
delete from international where languageId=2 and namespace='FAQ' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,2,'FAQ','FAQ hinzufügen oder bearbeiten', 1040644590);
delete from international where languageId=2 and namespace='FAQ' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'FAQ','Antwort', 1040644580);
delete from international where languageId=2 and namespace='FAQ' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'FAQ','Frage', 1040644571);
delete from international where languageId=2 and namespace='FAQ' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'FAQ','F.A.Q.', 1040644562);
delete from international where languageId=2 and namespace='FAQ' and internationalId=13;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (13,2,'FAQ','[top] Link einschalten?', 1040644552);
delete from international where languageId=2 and namespace='FAQ' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,2,'FAQ','Frage/Antwort einschalten?', 1040644541);
delete from international where languageId=2 and namespace='FAQ' and internationalId=11;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (11,2,'FAQ','Inhaltsverzeichnis aktivieren?', 1040644529);
delete from international where languageId=2 and namespace='ExtraColumn' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,2,'ExtraColumn','zusätzliche Spalte hinzufügen oder bearbeiten', 1040644500);
delete from international where languageId=2 and namespace='ExtraColumn' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'ExtraColumn','Extra Spalte bearbeiten', 1040644489);
delete from international where languageId=2 and namespace='ExtraColumn' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'ExtraColumn','StyleSheet Class', 1040644477);
delete from international where languageId=2 and namespace='ExtraColumn' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'ExtraColumn','Breite', 1040644466);
delete from international where languageId=2 and namespace='ExtraColumn' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'ExtraColumn','Platzhalter', 1040644456);
delete from international where languageId=2 and namespace='ExtraColumn' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'ExtraColumn','Extra Spalte', 1040644447);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'EventsCalendar','bis', 1040644433);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,2,'EventsCalendar','Wiederholt sich', 1040644422);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=78;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (78,2,'EventsCalendar','Löschen Sie nichts, ich habe einen Fehler verursacht.', 1040644404);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=77;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (77,2,'EventsCalendar','Dieses Ereignis und alle Wiederholungen löschen.', 1040644391);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=76;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (76,2,'EventsCalendar','Nur dieses Ereignis löschen', 1040644379);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,2,'EventsCalendar','Ereignis hinzufügen oder bearbeiten', 1040644368);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,2,'EventsCalendar','Ereigniskalender hinzufügen oder bearbeiten', 1040644357);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'EventsCalendar','Einmaliges Ereignis', 1040644337);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=20;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (20,2,'EventsCalendar','ein Ereignis hinzufügen', 1040644323);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'EventsCalendar','Veranstaltungskalender', 1040644311);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=19;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (19,2,'EventsCalendar','Später mit Seitenzahlen versehen', 1040644301);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=15;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (15,2,'EventsCalendar','Ende Datum', 1040644283);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=14;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (14,2,'EventsCalendar','Start Datum', 1040644271);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=13;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (13,2,'EventsCalendar','Veranstaltung bearbeiten', 1040644259);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,2,'EventsCalendar','Veranstaltungskalender bearbeiten', 1040644246);
delete from international where languageId=2 and namespace='Auth/WebGUI' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'Auth/WebGUI','Passwort (bestätigen)', 1040644235);
delete from international where languageId=2 and namespace='Auth/LDAP' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,2,'Auth/LDAP','LDAP Passwort/Name', 1040644223);
delete from international where languageId=2 and namespace='Auth/LDAP' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,2,'Auth/LDAP','LDAP Identitäts-Name', 1040644209);
delete from international where languageId=2 and namespace='Auth/LDAP' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'Auth/LDAP','LDAP Identität (Standard)', 1040644196);
delete from international where languageId=2 and namespace='Auth/LDAP' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'Auth/LDAP','LDAP URL (Standard)', 1040644184);
delete from international where languageId=2 and namespace='Auth/LDAP' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'Auth/LDAP','Connect DN', 1040644169);
delete from international where languageId=2 and namespace='Auth/LDAP' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'Auth/LDAP','LDAP URL', 1040644157);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=536;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (536,2,'WebGUI','Ein neuer Benutzer mit dem Namen ^@; hat die Seite betreten.', 1040643993);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=329;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (329,2,'WebGUI','Strasse', 1040641648);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=446;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (446,2,'WebGUI','Homepage URL (geschäftlich)', 1040641618);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=334;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (334,2,'WebGUI','Telefon (geschäftlich)', 1040641557);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=333;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (333,2,'WebGUI','Land (geschäftlich)', 1040641541);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=332;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (332,2,'WebGUI','Postleitzahl (geschäftlich)', 1040641490);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=331;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (331,2,'WebGUI','Bundesland (geschäftlich)', 1040641451);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=330;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (330,2,'WebGUI','Ort (geschäftlich)', 1040641430);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'WebGUI','&nbsp;Seite', 1040641098);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,2,'WebGUI','Administrationsmodus abschalten', 1040640906);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=13;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (13,2,'WebGUI','Anschauen: Hilfe', 1040640807);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=410;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (410,2,'WebGUI','&nbsp;Verwalten: Startseiten', 1040640721);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=508;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (508,2,'WebGUI','&nbsp;Verwalten: Templates', 1040640696);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=585;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (585,2,'WebGUI','&nbsp;Verwalten: Übersetzungen', 1040640671);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'WebGUI','&nbsp;Verwalten: Styles', 1040640645);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,2,'WebGUI','&nbsp;Verwalten: Benutzer', 1040640629);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=447;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (447,2,'WebGUI','&nbsp;Verwalten: Baumstruktur', 1040640595);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'WebGUI','&nbsp;Verwalten: Einstellungen', 1040640578);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=394;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (394,2,'WebGUI','&nbsp;Verwalten: Uploads', 1040640559);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=374;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (374,2,'WebGUI','&nbsp;Verwalten: Pakete', 1040640537);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,2,'WebGUI','&nbsp;Verwalten: Mülleimer', 1040640519);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'WebGUI','&nbsp;Verwalten: Gruppen', 1040640476);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=408;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (408,2,'WebGUI','Startseiten bearbeiten', 1040640244);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=377;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (377,2,'WebGUI','Von Ihren (Paket)-Administratoren wurden keine Pakete bereitgestellt.', 1040640135);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=506;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (506,2,'WebGUI','Templates verwalten', 1040639849);
delete from international where languageId=2 and namespace='USS' and internationalId=41;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (41,2,'USS','Datum', 1040639647);
delete from international where languageId=2 and namespace='USS' and internationalId=33;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (33,2,'USS','Anhang', 1040639638);
delete from international where languageId=2 and namespace='USS' and internationalId=35;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (35,2,'USS','Titel', 1040639629);
delete from international where languageId=2 and namespace='USS' and internationalId=32;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (32,2,'USS','Grafik', 1040639621);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=168;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (168,2,'WebGUI','Benutzer bearbeiten', 1040639529);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=658;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (658,2,'WebGUI','Benutzer verwalten', 1040639097);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=757;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (757,2,'WebGUI','Uploads verwalten', 1040638501);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=144;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (144,2,'WebGUI','Anschauen: Statistik', 1040638400);


