insert into webguiVersion values ('5.3.2','upgrade',unix_timestamp());


delete from international where languageId=2 and namespace='WebGUI' and internationalId=945;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (945,2,'WebGUI','Scratch Filter', 1054050912);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=946;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (946,2,'WebGUI','Gemeinsamen Mülleimer benutzen?', 1054048298);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=947;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (947,2,'WebGUI','Gemeinsame Zwischenablage benutzen?', 1054048284);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=948;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (948,2,'WebGUI','Zwischenablage verwalten', 1054048257);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=949;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (949,2,'WebGUI','Verwalten: Zwischenablage', 1054048234);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=950;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (950,2,'WebGUI','Zwischenablage leeren.', 1054048162);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=951;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (951,2,'WebGUI','Sind Sie sicher, dass Sie den Inhalt der Zwischenablage in den Mülleimer verschieben möchten?', 1054048139);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=952;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (952,2,'WebGUI','Datum Zwischenablage', 1054048102);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=953;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (953,2,'WebGUI','Vorherige Location', 1054048086);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=954;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (954,2,'WebGUI','System-Zwischenablage verwalten.', 1054048052);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=955;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (955,2,'WebGUI','System-Zwischenablage verwalten', 1054048035);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=957;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (957,2,'WebGUI','Zwischenablage, Verwalten', 1054048016);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=959;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (959,2,'WebGUI','System-Zwischenablage leeren.', 1054047995);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=960;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (960,2,'WebGUI','Mülleimer, Verwalten', 1054047974);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=962;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (962,2,'WebGUI','Mülleimer verwalten', 1054047952);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=963;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (963,2,'WebGUI','Lösch Datum', 1054047937);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=964;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (964,2,'WebGUI','System-Mülleimer verwalten.', 1054047881);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=965;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (965,2,'WebGUI','System-Mülleimer verwalten', 1054047852);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=967;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (967,2,'WebGUI','System-Mülleimer löschen', 1054047831);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=970;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (970,2,'WebGUI','Uhrzeit setzen', 1054047795);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=971;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (971,2,'WebGUI','Uhrzeit', 1054047781);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=972;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (972,2,'WebGUI','Datum und Zeit', 1054047767);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=973;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (973,2,'WebGUI','Falls Proxy benutzt wird: echte Client IP-Adressen benutzen?', 1054047756);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=974;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (974,2,'WebGUI','Benutzer können sich selbst hinzufügen?', 1054047723);
delete from international where languageId=2 and namespace='WobjectProxy' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,2,'WobjectProxy','Template überschreiben?', 1054047705);
delete from international where languageId=2 and namespace='WobjectProxy' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,2,'WobjectProxy','Titel überschreiben?', 1054047691);
delete from international where languageId=2 and namespace='WobjectProxy' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,2,'WobjectProxy','Angezeigten Titel überschreiben?', 1054047678);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=975;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (975,2,'WebGUI','Benutzer können sich selbst von dieser Gruppe entfernen?', 1054047654);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=976;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (976,2,'WebGUI','Benutzer hinzufügen', 1054046453);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=977;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (977,2,'WebGUI','Zusätzlicher Administrator?', 1054046425);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=978;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (978,2,'WebGUI','Benutzer erfolgreich hinzugefügt.', 1054046403);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=938;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (938,2,'WebGUI','Thema, löschen', 1054046371);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=940;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (940,2,'WebGUI','In neuem Fenster öffnen?', 1054046355);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=936;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (936,2,'WebGUI','Thema, importieren', 1054046328);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=933;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (933,2,'WebGUI','Thema, bearbeiten', 1054046301);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=931;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (931,2,'WebGUI','Themen, Verwalten', 1054046281);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=930;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (930,2,'WebGUI','Thema anschauen.', 1054046267);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=929;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (929,2,'WebGUI','Importieren!', 1054046249);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=928;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (928,2,'WebGUI','Möchten Sie dieses Thema importieren?', 1054046238);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=927;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (927,2,'WebGUI','Thema importieren', 1054046215);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=926;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (926,2,'WebGUI','Dieses Thema wurde mit einer neueren WebGUI Version erstellt. Sie müssen WebGUI zuerst updaten, bevor Sie dieses Thema installieren.', 1054046200);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=925;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (925,2,'WebGUI','Sie haben bereits eine Version dieses Themas installiert. Sie müssen sie vor dem Neuinstallieren löschen.', 1054046137);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=924;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (924,2,'WebGUI','Thema importieren.', 1054045996);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=923;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (923,2,'WebGUI','Thema Version', 1054045979);
delete from international where languageId=2 and namespace='DataForm' and internationalId=85;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (85,2,'DataForm','Einer pro Zeile.', 1054045953);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=921;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (921,2,'WebGUI','Themen Paket Datei', 1054045920);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=922;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (922,2,'WebGUI','Erstellt mit', 1054045908);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=920;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (920,2,'WebGUI','Dieses Thema exportieren.', 1054045888);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=919;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (919,2,'WebGUI','Dieses Thema bearbeiten.', 1054045866);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=918;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (918,2,'WebGUI','Diese Thema löschen.', 1054045852);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=917;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (917,2,'WebGUI','Themen-Komponente hinzufügen.', 1054045837);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=916;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (916,2,'WebGUI','Schnippsel', 1054045820);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=915;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (915,2,'WebGUI','Datei', 1054045810);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=914;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (914,2,'WebGUI','Grafik', 1054045801);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=913;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (913,2,'WebGUI','Template', 1054045792);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=912;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (912,2,'WebGUI','Style', 1054045784);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=911;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (911,2,'WebGUI','Komponente', 1054045774);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=910;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (910,2,'WebGUI','Komponenten Typ', 1054045760);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=909;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (909,2,'WebGUI','Themen Komponente hinzufügen', 1054045743);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=908;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (908,2,'WebGUI','Sind Sie sicher, dass Sie diese Komponente von diesem Thema entfernen möchten?', 1054045727);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=907;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (907,2,'WebGUI','Sind Sie sicher, dass Sie dieses Thema löschen möchten?', 1054045699);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=906;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (906,2,'WebGUI','Designer URL', 1054045674);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=905;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (905,2,'WebGUI','Thema Designer', 1054045664);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=904;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (904,2,'WebGUI','Themen Name', 1054045647);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=903;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (903,2,'WebGUI','Themen ID', 1054045634);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=902;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (902,2,'WebGUI','Thema bearbeiten', 1054045624);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=901;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (901,2,'WebGUI','Neues Thema hinzufügen.', 1054045611);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=900;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (900,2,'WebGUI','Verwalten: Themen', 1054045592);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=899;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (899,2,'WebGUI','Themen Verwalten', 1054045577);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=898;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (898,2,'WebGUI','Site Icon', 1054045556);
delete from international where languageId=2 and namespace='DataForm' and internationalId=28;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (28,2,'DataForm','Optional für Text- und HTML Bereich', 1054045535);
delete from international where languageId=2 and namespace='DataForm' and internationalId=25;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (25,2,'DataForm','Standardwert(e)', 1054045511);
delete from international where languageId=2 and namespace='DataForm' and internationalId=11;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (11,2,'DataForm','An', 1054045486);
delete from international where languageId=2 and namespace='DataForm' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'DataForm','DataForm', 1054045463);
delete from international where languageId=2 and namespace='WebGUI/Profile' and internationalId=897;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (897,2,'WebGUI/Profile','Veränderbar?', 1054045436);
delete from international where languageId=2 and namespace='WobjectProxy' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'WobjectProxy','Beschreibung überschreiben?', 1054045415);
delete from international where languageId=2 and namespace='DataForm' and internationalId=87;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (87,2,'DataForm','Listen Template', 1054045385);
delete from international where languageId=2 and namespace='DataForm' and internationalId=86;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (86,2,'DataForm','Alle Einträge anzeigen.', 1054045370);
delete from international where languageId=2 and namespace='DataForm' and internationalId=88;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (88,2,'DataForm','DataForm Listen Template', 1054045351);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=897;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (897,2,'WebGUI','Favicon', 1054045326);
delete from international where languageId=2 and namespace='SI_scaledImage' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'SI_scaledImage','Skalierte Grafik Makro', 1054045293);
delete from international where languageId=2 and namespace='Poll' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,2,'Poll','Abstimmungs Template', 1054045268);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=98;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (98,2,'EventsCalendar','Jetzt!', 1054045254);
delete from international where languageId=2 and namespace='DataForm' and internationalId=84;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (84,2,'DataForm','Exportieren (durch Tabulator getrennt)', 1054045239);
delete from international where languageId=2 and namespace='DataForm' and internationalId=82;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (82,2,'DataForm','DataForm Template', 1054045206);
delete from international where languageId=2 and namespace='DataForm' and internationalId=81;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (81,2,'DataForm','Bestätigungs Template', 1054045190);
delete from international where languageId=2 and namespace='DataForm' and internationalId=80;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (80,2,'DataForm','Email Template', 1054045154);
delete from international where languageId=2 and namespace='DataForm' and internationalId=79;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (79,2,'DataForm','Zusatztext', 1054045142);
delete from international where languageId=2 and namespace='DataForm' and internationalId=77;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (77,2,'DataForm','Label', 1054045130);
delete from international where languageId=2 and namespace='DataForm' and internationalId=76;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (76,2,'DataForm','Feld hinzufügen.', 1054045117);
delete from international where languageId=2 and namespace='DataForm' and internationalId=75;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (75,2,'DataForm','Erforderlich', 1054045105);
delete from international where languageId=2 and namespace='DataForm' and internationalId=74;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (74,2,'DataForm','Daten per Email versenden?', 1054045087);
delete from international where languageId=2 and namespace='Auth/LDAP' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'Auth/LDAP','Benutzer RDN', 1054045062);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,2,'WebGUI','Editieren abschalten.', 1050568811);

alter table DataForm_entryData add primary key (DataForm_entryId,name);


