insert into webguiVersion values ('5.0.3','upgrade',unix_timestamp());
delete from international where languageId=2 and namespace='WebGUI' and internationalId=625;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (625,2,'WebGUI','Laden Sie einige Bilder hoch, die Sie in mehreren Bereichen der Seite benutzen \r\nmöchten. \r\n<P><b>Name</b><BR>Die Bezeichnung, mit der Sie dieses Bild referenzieren, um \r\nes in anderen Seiten einzufügen. \r\n<P><b>In welches Verzeichnis?</b><BR>In welches Verzeichnis möchten Sie diese \r\nGrafik platzieren?<P><b>Datei</b><BR>Wählen Sie eine Grafik aus Ihrem lokalen \r\nVerzeichnis, die Sie zum Server hochladen möchten. \r\n<P><b>Parameter</b><BR>Geben Sie hier einige  HTML &lt;img Tag Parameter an, \r\ndie Sie standardmässig für diese Grafik benutzen möchten. \r\n<P><I>Beispiel:</I><BR>align=&quot;right&quot;<BR>alt=&quot;Dies ist ein Bild&quot;<BR>\r\n<P><b>Thumbnail Size</b><BR>Wie gross  (in Pixels) soll das Vorschaubild (Thumbnail) \r\nsein?</P>', 1042585804);
delete from international where languageId=2 and namespace='MailForm' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,2,'MailForm','Senden', 1042383682);
delete from international where languageId=2 and namespace='Product' and internationalId=47;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (47,2,'Product','Verwandte Produkte sind Produkte, die vergleichbar zu anderen Produkten sind.<br><br>\r\n<b>Verwandte Produkte</b><br>\r\nWählen Sie aus der Liste ein Produkt aus, das Sie bereits eingegeben haben.<br><br>\r\n<b>Weiteres verwandtes Produkt hinzufügen?</b><br><br>\r\nMöchten Sie ein weiteres Produkt hinzufügen?\r\n', 1042383649);
delete from template where templateId=1 and namespace='USS/Submission';
INSERT INTO template VALUES (1,'Default Submission','<h1><tmpl_var title></h1>\r\n<table width=\"100%\" cellpadding=2 cellspacing=1 border=0>\r\n<tr><td valign=\"top\" class=\"tableHeader\" width=\"100%\">\r\n<b><tmpl_var user.label>:</b> <a href=\"<tmpl_var user.Profile>\"><tmpl_var user.username></a><br />\r\n<b><tmpl_var date.label>:</b> <tmpl_var date.human><br />\r\n<b><tmpl_var status.label>:</b> <tmpl_var status.status><br />\r\n<b><tmpl_var views.label>:</b> <tmpl_var views.count><br />\r\n</td>\r\n<td rowspan=\"2\" class=\"tableMenu\" nowrap=\"1\" valign=\"top\">\r\n\r\n<tmpl_if previous.more>\r\n   <a href=\"<tmpl_var previous.url>\">&laquo;<tmpl_var previous.label></a><br />\r\n</tmpl_if>\r\n<tmpl_if next.more>\r\n   <a href=\"<tmpl_var next.url>\"><tmpl_var next.label>&raquo;</a><br />\r\n</tmpl_if>\r\n<tmpl_if canEdit>\r\n   <a href=\"<tmpl_var edit.url>\"><tmpl_var edit.label></a><br />\r\n   <a href=\"<tmpl_var delete.url>\"><tmpl_var delete.label></a><br />\r\n</tmpl_if>\r\n<tmpl_if canChangeStatus>\r\n   <a href=\"<tmpl_var approve.url>\"><tmpl_var approve.label></a><br />\r\n   <a href=\"<tmpl_var leave.url>\"><tmpl_var leave.label></a><br />\r\n   <a href=\"<tmpl_var deny.url>\"><tmpl_var deny.label></a><br />\r\n</tmpl_if>\r\n<tmpl_if canReply>\r\n   <a href=\"<tmpl_var reply.url>\"><tmpl_var reply.label></a><br />\r\n</tmpl_if>\r\n<tmpl_if canPost>\r\n   <a href=\"<tmpl_var post.url>\"><tmpl_var post.label></a><br />\r\n</tmpl_if>\r\n<a href=\"<tmpl_var search.url>\"><tmpl_var search.label></a><br />\r\n<a href=\"<tmpl_var back.url>\"><tmpl_var back.label></a><br />\r\n\r\n</td</tr><tr><td class=\"tableData\">\r\n<tmpl_if image.url>\r\n  <img src=\"<tmpl_var image.url>\" border=\"0\"><p />\r\n</tmpl_if>\r\n<tmpl_var content><p />\r\n<tmpl_var attachment.box><br />\r\n\r\n</td></tr></table>\r\n\r\n<tmpl_var replies>','USS/Submission');
delete from international where languageId=1 and namespace='WebGUI' and internationalId=624;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (624,1,'WebGUI','WebGUI macros are used to create dynamic content within otherwise static content. For instance, you may wish to show which user is logged in on every page, or you may wish to have a dynamically built menu or crumb trail. \r\n<p>\r\n\r\nMacros always begin with a carat (^) and follow with at least one other character and ended with a semicolon (;). Some macros can be extended/configured by taking the format of ^<i>x</i>("<b>config text</b>");. \r\n<p>\r\n\r\nNOTE: The following macros are reserved for system/wobject-specific functions as in the SQL Report wobject and the Body in the Style Manager: \r\n<b>^-;,^0;,^1;,^2;,^3;, etc.</b><br>\r\n<p>\r\n', 1043289717);
delete from international where languageId=1 and namespace='WebGUI' and internationalId=832;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (832,1,'WebGUI','The collateral management system has several macros for its specific purpose.\r\n<p/>\r\n\r\n<b>^File();</b><br/>\r\nThis macro builds a quick file link. It creates an icon for the file and outputs the files name. Then it links them both to the file for downloading.\r\n<p/>\r\n\r\n<b>^I();</b><br/>\r\nThis macro retrieves an image from the collateral management system along with an HTML image tag so that you can quickly display an image from the repository in your content.\r\n<p/>\r\n<i>Example:</i> ^I("logo");\r\n<p/>\r\n\r\n<b>^i();</b><br/>\r\nThis macro retrieves the URL for any file in the collateral management system.\r\n<p/>\r\n<i>Example:</i> ^i("status report");\r\n<p/>\r\n\r\n<b>^Snippet();</b><br/>\r\nThis macro retrieves the contents of a snippet in the collateral management system and inserts it into the page.\r\n<p />\r\n<i>Example:</i> ^Snippet("flash code");\r\n<p />\r\n\r\n<b>^Thumbnail();</b><br/>\r\nThis macro retrieves the URL for the thumbnail of any image in the collateral management system.\r\n<p/>\r\n<i>Example:</i> ^Thumbnail("logo");\r\n<p/>\r\n\r\n<b>^ThumbnailLinker();</b><br/>\r\nThis macro builds a quick image viewer using nothing more than the collateral management system. It creates a thumbnail image with the name of the image under it and then links them both to the full sized image.\r\n<p/>\r\n<i>Example:</i> ^ThumbnailLinker("logo");\r\n<p/>\r\n\r\n', 1043289595);
delete from language where languageId=4;
insert into language (languageId,language,characterSet,toolbar) values (4, 'Espa�ol (Spanish)', 'ISO-8859-1', 'spanish');



