insert into webguiVersion values ('4.0.0','upgrade',unix_timestamp());

INSERT INTO international VALUES (14,'Article','Dutch','Plaatje uitlijnen');
INSERT INTO international VALUES (15,'Article','Dutch','Rechts');
INSERT INTO international VALUES (16,'Article','Dutch','links');
INSERT INTO international VALUES (17,'Article','Dutch','Centreren');
INSERT INTO international VALUES (18,'Article','Dutch','Discussie toelaten?');
INSERT INTO international VALUES (19,'Article','Dutch','Wie kan reageren?');
INSERT INTO international VALUES (20,'Article','Dutch','Wie kan aanpassen?');
INSERT INTO international VALUES (21,'Article','Dutch','bewerk timeout');
INSERT INTO international VALUES (22,'Article','Dutch','Auteur');
INSERT INTO international VALUES (23,'Article','Dutch','Datum');
INSERT INTO international VALUES (24,'Article','Dutch','Post reactie');
INSERT INTO international VALUES (25,'Article','Dutch','bewerk reactie');
INSERT INTO international VALUES (26,'Article','Dutch','Verwijder reactie');
INSERT INTO international VALUES (27,'Article','Dutch','Terug naar artikel');
INSERT INTO international VALUES (28,'Article','Dutch','Bekijk reacties');
INSERT INTO international VALUES (1,'DownloadManager','Dutch','Download Manager');
INSERT INTO international VALUES (3,'DownloadManager','Dutch','Verder gaan met bestand toevoegen?');
INSERT INTO international VALUES (5,'DownloadManager','Dutch','Bestand Titel');
INSERT INTO international VALUES (6,'DownloadManager','Dutch','Download bestand');
INSERT INTO international VALUES (7,'DownloadManager','Dutch','Groep om te downloaden');
INSERT INTO international VALUES (8,'DownloadManager','Dutch','Korte Omschrijving');
INSERT INTO international VALUES (9,'DownloadManager','Dutch','Bewerk download Manager');
INSERT INTO international VALUES (10,'DownloadManager','Dutch','Bewerk Download');
INSERT INTO international VALUES (11,'DownloadManager','Dutch','Nieuwe download toevoegen');
INSERT INTO international VALUES (12,'DownloadManager','Dutch','Weet u zeker dat u deze download wilt verwijderen?');
INSERT INTO international VALUES (14,'DownloadManager','Dutch','Bestand');
INSERT INTO international VALUES (15,'DownloadManager','Dutch','Beschrijving');
INSERT INTO international VALUES (16,'DownloadManager','Dutch','Upload datum');
INSERT INTO international VALUES (17,'DownloadManager','Dutch','Alternatieve Versie #1');
INSERT INTO international VALUES (18,'DownloadManager','Dutch','Alternatieve Versie #2');
INSERT INTO international VALUES (19,'DownloadManager','Dutch','U heeft geen bestanden te downloaden');
INSERT INTO international VALUES (20,'DownloadManager','Dutch','Kap pagina af na');
INSERT INTO international VALUES (21,'DownloadManager','Dutch','Miniaturen weergeven?');
INSERT INTO international VALUES (22,'DownloadManager','Dutch','Doorgaan met download toevoegen');
INSERT INTO international VALUES (20,'EventsCalendar','Dutch','Evenement toevoegen');
INSERT INTO international VALUES (21,'EventsCalendar','Dutch','Doorgaan met evenement toevoegen?');
INSERT INTO international VALUES (14,'EventsCalendar','Dutch','Start datum');
INSERT INTO international VALUES (15,'EventsCalendar','Dutch','Eind datum');
INSERT INTO international VALUES (16,'EventsCalendar','Dutch','Kalender layout');
INSERT INTO international VALUES (17,'EventsCalendar','Dutch','Lijst');
INSERT INTO international VALUES (18,'EventsCalendar','Dutch','Kalender');
INSERT INTO international VALUES (19,'EventsCalendar','Dutch','Breek pagina af na');
INSERT INTO international VALUES (11,'FAQ','Dutch','Zet inhoud aan?');
INSERT INTO international VALUES (12,'FAQ','Dutch','Zet V/A aan?');
INSERT INTO international VALUES (13,'FAQ','Dutch','Zet [top] link aan?');
INSERT INTO international VALUES (14,'FAQ','Dutch','V');
INSERT INTO international VALUES (15,'FAQ','Dutch','A');
INSERT INTO international VALUES (16,'FAQ','Dutch','[top]');
INSERT INTO international VALUES (1,'Item','Dutch','Link URL');
INSERT INTO international VALUES (2,'Item','Dutch','Bijlage');
INSERT INTO international VALUES (3,'Item','Dutch','Verwijder bijlage');
INSERT INTO international VALUES (4,'Item','Dutch','Item');
INSERT INTO international VALUES (5,'Item','Dutch','Download bijlage');
INSERT INTO international VALUES (21,'MessageBoard','Dutch','Wie kan bewerken?');
INSERT INTO international VALUES (22,'MessageBoard','Dutch','Verwijder bericht');
INSERT INTO international VALUES (11,'Poll','Dutch','Stem!');
INSERT INTO international VALUES (9,'SiteMap','Dutch','Omschrijving laten zien?');
INSERT INTO international VALUES (13,'SQLReport','Dutch','Converteer Return?');
INSERT INTO international VALUES (14,'SQLReport','Dutch','Breek pagina af na');
INSERT INTO international VALUES (15,'SQLReport','Dutch','Verwerk macros voor query?');
INSERT INTO international VALUES (16,'SQLReport','Dutch','Debug?');
INSERT INTO international VALUES (17,'SQLReport','Dutch','Debug: Query:');
INSERT INTO international VALUES (18,'SQLReport','Dutch','Er waren geen resultaten voor deze query');
INSERT INTO international VALUES (31,'UserSubmission','Dutch','Inhoud');
INSERT INTO international VALUES (32,'UserSubmission','Dutch','Plaatje');
INSERT INTO international VALUES (33,'UserSubmission','Dutch','Bijlage');
INSERT INTO international VALUES (34,'UserSubmission','Dutch','Return converteren');
INSERT INTO international VALUES (35,'UserSubmission','Dutch','Titel');
INSERT INTO international VALUES (37,'UserSubmission','Dutch','Verwijder');
INSERT INTO international VALUES (39,'UserSubmission','Dutch','Post een reactie');
INSERT INTO international VALUES (40,'UserSubmission','Dutch','Gepost door');
INSERT INTO international VALUES (41,'UserSubmission','Dutch','Datum');
INSERT INTO international VALUES (42,'UserSubmission','Dutch','Bewerk reactie');
INSERT INTO international VALUES (43,'UserSubmission','Dutch','Verwijder reactie');
INSERT INTO international VALUES (45,'UserSubmission','Dutch','Ga terug naar bijdrages');
INSERT INTO international VALUES (46,'UserSubmission','Dutch','Lees meer...');
INSERT INTO international VALUES (47,'UserSubmission','Dutch','Post een reactie');
INSERT INTO international VALUES (48,'UserSubmission','Dutch','Discussie toestaan?');
INSERT INTO international VALUES (49,'UserSubmission','Dutch','Bewerk timeout');
INSERT INTO international VALUES (50,'UserSubmission','Dutch','Groep om te poesten');
INSERT INTO international VALUES (44,'UserSubmission','Dutch','Groep om te veranderen');
INSERT INTO international VALUES (51,'UserSubmission','Dutch','Miniaturen weergeven');
INSERT INTO international VALUES (52,'UserSubmission','Dutch','Miniatuur');
INSERT INTO international VALUES (53,'UserSubmission','Dutch','Layout');
INSERT INTO international VALUES (54,'UserSubmission','Dutch','Web Log');
INSERT INTO international VALUES (55,'UserSubmission','Dutch','Traditioneel');
INSERT INTO international VALUES (56,'UserSubmission','Dutch','Foto gallerij');
INSERT INTO international VALUES (57,'UserSubmission','Dutch','Reacties');
INSERT INTO international VALUES (516,'WebGUI','Dutch','Zet beheermode aan!');
INSERT INTO international VALUES (517,'WebGUI','Dutch','Zet beheermode uit!');
INSERT INTO international VALUES (515,'WebGUI','Dutch','Bewerkings stempel toevoegen?');
INSERT INTO international VALUES (532,'WebGUI','Dutch','Met minstens 1 van de worden');
INSERT INTO international VALUES (531,'WebGUI','Dutch','met de exacte zin');
INSERT INTO international VALUES (505,'WebGUI','Dutch','Een niewe template toevoegen');
INSERT INTO international VALUES (504,'WebGUI','Dutch','Sjabloon');
INSERT INTO international VALUES (503,'WebGUI','Dutch','Sjabloon ID');
INSERT INTO international VALUES (502,'WebGUI','Dutch','Weet u zeker dat u deze sjabloon wilt verwijderen? Elke pagina die de template gebruikt zal de standaard template krijgen!');
INSERT INTO international VALUES (536,'WebGUI','Dutch','Een nieuwe gebruiker genaamd ^@; is bij de site aangemeld');
DELETE FROM international WHERE internationalId='351' and namespace='WebGUI' and language='Dutch';
INSERT INTO international VALUES (351,'WebGUI','Dutch','Bericht');
DELETE FROM international WHERE internationalId='355' and namespace='WebGUI' and language='Dutch';
INSERT INTO international VALUES (355,'WebGUI','Dutch','Standaard');
INSERT INTO international VALUES (356,'WebGUI','Dutch','Sjabloon');
INSERT INTO international VALUES (357,'WebGUI','Dutch','Nieuws');
INSERT INTO international VALUES (358,'WebGUI','Dutch','Linker kolom');
INSERT INTO international VALUES (359,'WebGUI','Dutch','Rechter kolom');
INSERT INTO international VALUES (360,'WebGUI','Dutch','Een boven drie');
INSERT INTO international VALUES (361,'WebGUI','Dutch','Drie boven een');
INSERT INTO international VALUES (362,'WebGUI','Dutch','Zij aan zij');
INSERT INTO international VALUES (363,'WebGUI','Dutch','Sjabloon positie');
INSERT INTO international VALUES (364,'WebGUI','Dutch','Zoeken');
INSERT INTO international VALUES (365,'WebGUI','Dutch','Zoek resultaten');
INSERT INTO international VALUES (366,'WebGUI','Dutch','Er is geen pagina die aan uw vraag voldoet');
INSERT INTO international VALUES (368,'WebGUI','Dutch','Voeg een nieuwe groep aan deze gebruiker toe');
INSERT INTO international VALUES (369,'WebGUI','Dutch','Verloop datum');
INSERT INTO international VALUES (370,'WebGUI','Dutch','Bewerk groeperen');
INSERT INTO international VALUES (371,'WebGUI','Dutch','Groeperen toevoegen');
INSERT INTO international VALUES (372,'WebGUI','Dutch','Bewerk gebruiker groep');
INSERT INTO international VALUES (373,'WebGUI','Dutch','Waarschuwing: Door de groepen lijst aan te passen ');
INSERT INTO international VALUES (374,'WebGUI','Dutch','Beheer pakketten');
INSERT INTO international VALUES (375,'WebGUI','Dutch','Selecteer pakket');
INSERT INTO international VALUES (376,'WebGUI','Dutch','Pakket');
INSERT INTO international VALUES (377,'WebGUI','Dutch','Er zijn geen pakketten gedefinieerd door uw pakket manager of beheerder.');
INSERT INTO international VALUES (378,'WebGUI','Dutch','Gebruikers ID');
INSERT INTO international VALUES (379,'WebGUI','Dutch','Groep ID');
INSERT INTO international VALUES (380,'WebGUI','Dutch','Stijl ID');
INSERT INTO international VALUES (381,'WebGUI','Dutch','WebGUI heeft een verkeerde vraag gekregen en kan niet verder gaan. Bepaalde karakters op de pagina kunnen de oorzaak zijn. Probeer terug te gaan naar de vorige pagina en probeer het opnieuw.');
INSERT INTO international VALUES (528,'WebGUI','Dutch','Sjabloon naam');
INSERT INTO international VALUES (383,'WebGUI','Dutch','Naam');
INSERT INTO international VALUES (384,'WebGUI','Dutch','Bestand');
INSERT INTO international VALUES (385,'WebGUI','Dutch','Parameters');
INSERT INTO international VALUES (386,'WebGUI','Dutch','Bewerk plaatje');
INSERT INTO international VALUES (387,'WebGUI','Dutch','Geleverd door');
INSERT INTO international VALUES (388,'WebGUI','Dutch','Upload datum');
INSERT INTO international VALUES (389,'WebGUI','Dutch','Plaatje ID');
INSERT INTO international VALUES (390,'WebGUI','Dutch','Plaatje laten zien......');
INSERT INTO international VALUES (391,'WebGUI','Dutch','Verwijder bijgevoegd bestand');
INSERT INTO international VALUES (392,'WebGUI','Dutch','Weet u zeker dat u dit plaatje wilt verwijderen?');
INSERT INTO international VALUES (393,'WebGUI','Dutch','Beheer plaatjes');
INSERT INTO international VALUES (394,'WebGUI','Dutch','Beheer plaatjes.');
INSERT INTO international VALUES (395,'WebGUI','Dutch','Een nieuw plaatje toevoegen');
INSERT INTO international VALUES (396,'WebGUI','Dutch','Plaatje laten zien');
INSERT INTO international VALUES (397,'WebGUI','Dutch','Terug naar plaatjes lijst');
INSERT INTO international VALUES (398,'WebGUI','Dutch','Document type declaratie');
INSERT INTO international VALUES (399,'WebGUI','Dutch','Valideer deze pagina');
INSERT INTO international VALUES (400,'WebGUI','Dutch','Voorkom Proxy Caching');
INSERT INTO international VALUES (401,'WebGUI','Dutch','Weet u zeker dat u dit bericht wilt verwijderen en alle berichten onder deze thread?');
INSERT INTO international VALUES (402,'WebGUI','Dutch','Het bericht wat u vroeg bestaat niet.');
INSERT INTO international VALUES (403,'WebGUI','Dutch','Geen mening');
INSERT INTO international VALUES (405,'WebGUI','Dutch','Laatste pagina');
INSERT INTO international VALUES (406,'WebGUI','Dutch','Miniatuur grootte');
INSERT INTO international VALUES (407,'WebGUI','Dutch','Klik hier om te registreren');
INSERT INTO international VALUES (506,'WebGUI','Dutch','Beheer Sjablonen');
INSERT INTO international VALUES (408,'WebGUI','Dutch','Beheer roots');
INSERT INTO international VALUES (409,'WebGUI','Dutch','Een nieuwe root toevoegen');
INSERT INTO international VALUES (410,'WebGUI','Dutch','Beheer roots.');
INSERT INTO international VALUES (411,'WebGUI','Dutch','Menu Titel');
INSERT INTO international VALUES (412,'WebGUI','Dutch','Omschrijving');
INSERT INTO international VALUES (413,'WebGUI','Dutch','Bij kritische fout');
INSERT INTO international VALUES (414,'WebGUI','Dutch','Geef debug informatie weer');
INSERT INTO international VALUES (415,'WebGUI','Dutch','Geef vriendelijk bericht weer');
INSERT INTO international VALUES (416,'WebGUI','Dutch','<h1>Probleem met aanvraag</h1><br> We hebben een probleemm gevonden met de aanvraag van deze pagina. Ga terug naar de vorige pagina en probeer het opnieuw. Mocht het probleem zich blijven voordoen wendt u dan tot de beheerder.');
INSERT INTO international VALUES (417,'WebGUI','Dutch','<h1>Beveiligings probleem</h1><br> U probeerde een widget op te vragen die niet bij deze pagina hoort. Het incident is gerapporteerd.');
INSERT INTO international VALUES (418,'WebGUI','Dutch','Filter Contributed HTML');
INSERT INTO international VALUES (419,'WebGUI','Dutch','Verwijder alle tags');
INSERT INTO international VALUES (420,'WebGUI','Dutch','Laat het zoals het is');
INSERT INTO international VALUES (421,'WebGUI','Dutch','Verwijder alles behalve de basis formaten');
INSERT INTO international VALUES (422,'WebGUI','Dutch','<h1>Login Fout</h1><br>De informatie komt niet overeen met het account');
INSERT INTO international VALUES (423,'WebGUI','Dutch','Laat aktieve sessies zien');
INSERT INTO international VALUES (424,'WebGUI','Dutch','Laat login historie zien');
INSERT INTO international VALUES (425,'WebGUI','Dutch','Aktieve sessies');
INSERT INTO international VALUES (426,'WebGUI','Dutch','Login historie');
INSERT INTO international VALUES (427,'WebGUI','Dutch','Stijlen');
INSERT INTO international VALUES (428,'WebGUI','Dutch','Gebruiker (ID)');
INSERT INTO international VALUES (429,'WebGUI','Dutch','Login tijd');
INSERT INTO international VALUES (430,'WebGUI','Dutch','Laatst bekeken pagina');
INSERT INTO international VALUES (431,'WebGUI','Dutch','IP Adres');
INSERT INTO international VALUES (432,'WebGUI','Dutch','Verloopt');
INSERT INTO international VALUES (433,'WebGUI','Dutch','Gebruikers applicatie');
INSERT INTO international VALUES (434,'WebGUI','Dutch','Status');
INSERT INTO international VALUES (435,'WebGUI','Dutch','Sessie handtekening');
INSERT INTO international VALUES (436,'WebGUI','Dutch','Vermoord sessie');
INSERT INTO international VALUES (437,'WebGUI','Dutch','Statistieken');
INSERT INTO international VALUES (438,'WebGUI','Dutch','Uw naam');
INSERT INTO international VALUES (441,'WebGUI','Dutch','Email naar pager gateway');
INSERT INTO international VALUES (442,'WebGUI','Dutch','Bedrijfs informatie');
INSERT INTO international VALUES (443,'WebGUI','Dutch','Thuis informatie');
INSERT INTO international VALUES (439,'WebGUI','Dutch','Persoonlijke informatie');
INSERT INTO international VALUES (440,'WebGUI','Dutch','Contact informatie');
INSERT INTO international VALUES (444,'WebGUI','Dutch','Demografische informatie');
INSERT INTO international VALUES (445,'WebGUI','Dutch','Voorkeuren');
INSERT INTO international VALUES (446,'WebGUI','Dutch','Bedrijfs website');
INSERT INTO international VALUES (447,'WebGUI','Dutch','Beheer pagina boom');
INSERT INTO international VALUES (448,'WebGUI','Dutch','Pagina boom');
INSERT INTO international VALUES (449,'WebGUI','Dutch','Overige informatie');
INSERT INTO international VALUES (450,'WebGUI','Dutch','Werk naam (Bedrijfsnaam)');
INSERT INTO international VALUES (451,'WebGUI','Dutch','is vereist');
INSERT INTO international VALUES (452,'WebGUI','Dutch','Even wachten alstublieft....');
INSERT INTO international VALUES (453,'WebGUI','Dutch','Creatie datum');
INSERT INTO international VALUES (454,'WebGUI','Dutch','Laatst veranderd');
INSERT INTO international VALUES (455,'WebGUI','Dutch','Bewerk gebruikersprofiel');
INSERT INTO international VALUES (456,'WebGUI','Dutch','Terug naar gebruikers lijst');
INSERT INTO international VALUES (457,'WebGUI','Dutch','Bewerk het account van deze gebruiker');
INSERT INTO international VALUES (458,'WebGUI','Dutch','Bewerk de groepen van deze gebruiker');
INSERT INTO international VALUES (459,'WebGUI','Dutch','Bewerk het profiel van deze gebruiker');
INSERT INTO international VALUES (460,'WebGUI','Dutch','Tijd offset');
INSERT INTO international VALUES (461,'WebGUI','Dutch','Datum formaat');
INSERT INTO international VALUES (462,'WebGUI','Dutch','Tijd formaat');
INSERT INTO international VALUES (463,'WebGUI','Dutch','Tekst vlak rijen');
INSERT INTO international VALUES (464,'WebGUI','Dutch','Tekst vlak kolommen');
INSERT INTO international VALUES (465,'WebGUI','Dutch','Tekst blok grootte');
INSERT INTO international VALUES (466,'WebGUI','Dutch','Weet u zeker dat u deze categorie wilt verwijderen en alle velden naar de overige categorie wilt verplaatsen?');
INSERT INTO international VALUES (467,'WebGUI','Dutch','Weet u zeker dat u dit veld wilt verwijderen en daarmee ook alle data die er aan vast zit?');
INSERT INTO international VALUES (469,'WebGUI','Dutch','Id');
INSERT INTO international VALUES (470,'WebGUI','Dutch','Naam');
INSERT INTO international VALUES (472,'WebGUI','Dutch','Label');
INSERT INTO international VALUES (473,'WebGUI','Dutch','Zichtbaar?');
INSERT INTO international VALUES (474,'WebGUI','Dutch','Verplicht?');
INSERT INTO international VALUES (475,'WebGUI','Dutch','Tekst');
INSERT INTO international VALUES (476,'WebGUI','Dutch','Tekst vlak');
INSERT INTO international VALUES (477,'WebGUI','Dutch','HTML vlak');
INSERT INTO international VALUES (478,'WebGUI','Dutch','URL');
INSERT INTO international VALUES (479,'WebGUI','Dutch','Datum');
INSERT INTO international VALUES (480,'WebGUI','Dutch','Email adres');
INSERT INTO international VALUES (481,'WebGUI','Dutch','Telefoon nummer');
INSERT INTO international VALUES (482,'WebGUI','Dutch','Nummer (Geheel getal)');
INSERT INTO international VALUES (483,'WebGUI','Dutch','Ja of nee');
INSERT INTO international VALUES (484,'WebGUI','Dutch','Selecteer lijst');
INSERT INTO international VALUES (485,'WebGUI','Dutch','Booleaanse waarde (Checkbox)');
INSERT INTO international VALUES (486,'WebGUI','Dutch','Data type');
INSERT INTO international VALUES (487,'WebGUI','Dutch','Mogelijke waardes');
INSERT INTO international VALUES (488,'WebGUI','Dutch','Standaard waarde(s)');
INSERT INTO international VALUES (489,'WebGUI','Dutch','Profiel categorie');
INSERT INTO international VALUES (490,'WebGUI','Dutch','Profiel categorie toevoegen');
INSERT INTO international VALUES (491,'WebGUI','Dutch','Profiel veld toevoegen');
INSERT INTO international VALUES (492,'WebGUI','Dutch','Profiel veld lijst');
INSERT INTO international VALUES (493,'WebGUI','Dutch','terug naar de site');
INSERT INTO international VALUES (496,'WebGUI','Dutch','Ingebouwde editor');
INSERT INTO international VALUES (494,'WebGUI','Dutch','Te gebruiken Editor');
INSERT INTO international VALUES (497,'WebGUI','Dutch','Start datum');
INSERT INTO international VALUES (498,'WebGUI','Dutch','Eind Datum');
INSERT INTO international VALUES (499,'WebGUI','Dutch','Wobject ID');
INSERT INTO international VALUES (500,'WebGUI','Dutch','Pagina ID');
INSERT INTO international VALUES (514,'WebGUI','Dutch','Bekeken');
INSERT INTO international VALUES (527,'WebGUI','Dutch','Standaard home pagina');
INSERT INTO international VALUES (530,'WebGUI','Dutch','Met alle woorden');
INSERT INTO international VALUES (501,'WebGUI','Dutch','Body');
INSERT INTO international VALUES (468,'WebGUI','Dutch','Bewerk gebruikers profiel categorie');
INSERT INTO international VALUES (507,'WebGUI','Dutch','Bewerk sjabloon');
INSERT INTO international VALUES (508,'WebGUI','Dutch','Beheer sjablonen');
INSERT INTO international VALUES (509,'WebGUI','Dutch','Discussie layout');
INSERT INTO international VALUES (510,'WebGUI','Dutch','Plat');
INSERT INTO international VALUES (511,'WebGUI','Dutch','threaded');
INSERT INTO international VALUES (512,'WebGUI','Dutch','Volgende thread');
INSERT INTO international VALUES (513,'WebGUI','Dutch','Vorige thread');
INSERT INTO international VALUES (533,'WebGUI','Dutch','Zonder de woorden');
INSERT INTO international VALUES (529,'WebGUI','Dutch','Resultaten');
INSERT INTO international VALUES (518,'WebGUI','Dutch','Inbox notificaties');
INSERT INTO international VALUES (519,'WebGUI','Dutch','Ik wil geen notificatie krijgen');
INSERT INTO international VALUES (520,'WebGUI','Dutch','Ik wil notificatie via email');
INSERT INTO international VALUES (521,'WebGUI','Dutch','Ik wil notificatie via email naar pager');
INSERT INTO international VALUES (522,'WebGUI','Dutch','Ik wil notificatie via ICQ');
INSERT INTO international VALUES (523,'WebGUI','Dutch','Notificatie');
INSERT INTO international VALUES (524,'WebGUI','Dutch','Voeg bewerk stempel toe aan post');
INSERT INTO international VALUES (525,'WebGUI','Dutch','Bewerk inhoud Settings');
INSERT INTO international VALUES (526,'WebGUI','Dutch','Verwijder alleen javascript');

