insert into webguiVersion values ('5.0.0','upgrade',unix_timestamp());
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (856,3,'WebGUI','Er zijn op dit moment geen account eigenschappen die u mag aanpassen.', 1040350000);


delete from international where languageId=2 and namespace='Survey' and internationalId=36;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (36,2,'Survey','nicht ganz ablehnen', 1040600035);
delete from international where languageId=2 and namespace='Survey' and internationalId=41;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (41,2,'Survey','Häufig', 1040599965);
delete from international where languageId=2 and namespace='Survey' and internationalId=42;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (42,2,'Survey','Gelegentlich', 1040599945);
delete from international where languageId=2 and namespace='Survey' and internationalId=43;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (43,2,'Survey','Nie', 1040599922);
delete from international where languageId=2 and namespace='Survey' and internationalId=46;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (46,2,'Survey','Danke, dass Sie sich die Zeit genommen haben, an der Umfrage teilzunehmen.', 1040599910);
delete from international where languageId=2 and namespace='Survey' and internationalId=47;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (47,2,'Survey','Sie haben dieses Quiz abgeschlossen.', 1040599877);
delete from international where languageId=2 and namespace='Survey' and internationalId=49;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (49,2,'Survey','Sie können im Moment nicht an diesem Quiz teilnehmen.', 1040599818);
delete from international where languageId=2 and namespace='Survey' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'Survey','der Reihe nach', 1040599792);
delete from international where languageId=2 and namespace='Survey' and internationalId=50;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (50,2,'Survey','Weiter', 1040599769);
delete from international where languageId=2 and namespace='Survey' and internationalId=51;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (51,2,'Survey','Kommentare?', 1040599752);
delete from international where languageId=2 and namespace='Survey' and internationalId=54;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (54,2,'Survey','Prozentzahl', 1040599736);
delete from international where languageId=2 and namespace='Survey' and internationalId=56;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (56,2,'Survey','Kommentare anschauen.', 1040599702);
delete from international where languageId=2 and namespace='Survey' and internationalId=57;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (57,2,'Survey','Kommentare', 1040599684);
delete from international where languageId=2 and namespace='Survey' and internationalId=58;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (58,2,'Survey','Statistische Übersicht', 1040599672);
delete from international where languageId=2 and namespace='Survey' and internationalId=59;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (59,2,'Survey','Statistische Übersicht anschauen.', 1040599655);
delete from international where languageId=2 and namespace='Survey' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'Survey','Zufällig', 1040599636);
delete from international where languageId=2 and namespace='Survey' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,2,'Survey','Rangstufen anschauen.', 1040599619);
delete from international where languageId=2 and namespace='Survey' and internationalId=55;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (55,2,'Survey','Kommentare anschauen.', 1040599304);
delete from international where languageId=2 and namespace='Survey' and internationalId=64;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (64,2,'Survey','Kommentare exportieren.', 1040599109);
delete from international where languageId=2 and namespace='Survey' and internationalId=62;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (62,2,'Survey','Antworten exportieren.', 1040599029);
delete from international where languageId=2 and namespace='Survey' and internationalId=63;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (63,2,'Survey','Fragen exportieren.', 1040599013);
delete from international where languageId=2 and namespace='Survey' and internationalId=65;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (65,2,'Survey','Gemischte Auswertung exportieren.', 1040598966);
delete from international where languageId=2 and namespace='Survey' and internationalId=66;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (66,2,'Survey','Kommentare', 1040598828);
delete from international where languageId=2 and namespace='Survey' and internationalId=67;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (67,2,'Survey','Benutzer', 1040598808);
delete from international where languageId=2 and namespace='Survey' and internationalId=68;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (68,2,'Survey','Reports anschauen, Exportieren, ...', 1040598788);
delete from international where languageId=2 and namespace='Survey' and internationalId=71;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (71,2,'Survey','Rangstufen', 1040598736);
delete from international where languageId=2 and namespace='Survey' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,2,'Survey','Alle Kommentare löschen.', 1040598401);
delete from international where languageId=2 and namespace='Survey' and internationalId=75;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (75,2,'Survey','Diese Frage bearbeiten.', 1040598384);
delete from international where languageId=2 and namespace='Survey' and internationalId=76;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (76,2,'Survey','Start Zeit', 1040598367);
delete from international where languageId=2 and namespace='Survey' and internationalId=77;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (77,2,'Survey','Ende Zeit', 1040598353);
delete from international where languageId=2 and namespace='Survey' and internationalId=78;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (78,2,'Survey','Gesamtzeit', 1040598333);
delete from international where languageId=2 and namespace='Survey' and internationalId=79;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (79,2,'Survey','Minuten', 1040598320);
delete from international where languageId=2 and namespace='Survey' and internationalId=69;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (69,2,'Survey','Kommentare dieses Benutzers löschen.', 1040598306);
delete from international where languageId=2 and namespace='Survey' and internationalId=70;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (70,2,'Survey','Individuelle Kommentare', 1040598278);
delete from international where languageId=2 and namespace='Survey' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,2,'Survey','Sind Sie sicher, dass Sie die Kommentare dieses Benutzers löschen möchten?', 1040598254);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=651;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (651,2,'WebGUI','Falls Sie Ihren Mülleimer leeren, werden alle Posten darin unwiderruflich gelöscht. Wenn Sie sich über einige Posten nicht sicher sind, wäre es am besten, sie mittels \'ausschneiden\' in die Zwischenablage zu legen, bevor Sie den Mülleimer leeren.', 1040598182);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,2,'WebGUI','Anmelden', 1040598159);
delete from international where languageId=2 and namespace='MailForm' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,2,'MailForm','Von', 1040598111);
delete from international where languageId=2 and namespace='LinkList' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,2,'LinkList','', 1040598095);
delete from international where languageId=2 and namespace='Auth/WebGUI' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'Auth/WebGUI','Die Passwörter unterscheiden sich. Bitte versuchen Sie es noch einmal.', 1040598052);
delete from international where languageId=2 and namespace='Auth/LDAP' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'Auth/LDAP','Verbindung zum LDAP-Server konnte nicht hergestellt werden.', 1040598025);
delete from international where languageId=2 and namespace='Article' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'Article','Dateianhang', 1040598013);
delete from international where languageId=2 and namespace='Article' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,2,'Article','Link URL', 1040598002);
delete from international where languageId=2 and namespace='Article' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,2,'Article','Link Titel', 1040597992);
delete from international where languageId=2 and namespace='Article' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,2,'Article','Artikel hinzufügen oder bearbeiten', 1040597983);
delete from international where languageId=2 and namespace='Article' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'Article','Grafik', 1040597952);
delete from international where languageId=2 and namespace='Article' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'Article','Ende Datum', 1040597938);
delete from international where languageId=2 and namespace='Article' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'Article','Start Datum', 1040597929);
delete from international where languageId=2 and namespace='Article' and internationalId=28;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (28,2,'Article','Kommentare anschauen', 1040597920);
delete from international where languageId=2 and namespace='Article' and internationalId=27;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (27,2,'Article','Zurück zum Artikel', 1040597909);
delete from international where languageId=2 and namespace='Article' and internationalId=24;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (24,2,'Article','Kommentar schreiben', 1040597898);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=75;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (75,2,'EventsCalendar','Was möchten Sie gerne tun?', 1040597885);
delete from international where languageId=2 and namespace='Article' and internationalId=23;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (23,2,'Article','Datum', 1040597864);
delete from international where languageId=2 and namespace='Article' and internationalId=22;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (22,2,'Article','Author', 1040597852);
delete from international where languageId=2 and namespace='Article' and internationalId=18;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (18,2,'Article','Diskussion erlauben?', 1040597839);
delete from international where languageId=2 and namespace='Article' and internationalId=13;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (13,2,'Article','Löschen', 1040597823);
delete from international where languageId=2 and namespace='Article' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,2,'Article','Artikel bearbeiten', 1040597813);
delete from international where languageId=2 and namespace='Article' and internationalId=11;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (11,2,'Article','(Bitte anklicken, falls Sie nicht &lt;br&gt; in Ihrem Text hinzufügen.)', 1040597800);
delete from international where languageId=2 and namespace='Article' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,2,'Article','Carriage Return beachten?', 1040597777);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=804;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (804,2,'WebGUI','Diesen Style kopieren.', 1040597735);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=803;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (803,2,'WebGUI','Diesen Style bearbeiten.', 1040597719);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=801;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (801,2,'WebGUI','Wobject Interaktionen', 1040597703);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=800;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (800,2,'WebGUI','Eindeutige Besucher', 1040597685);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=799;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (799,2,'WebGUI','Seiten angeschaut', 1040597666);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=797;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (797,2,'WebGUI','Traffic Statistiken anschauen.', 1040597629);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=795;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (795,2,'WebGUI','Wurzeln (Roots)', 1040597527);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=794;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (794,2,'WebGUI','Pakete', 1040597469);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=793;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (793,2,'WebGUI','Uploadbereiche', 1040597455);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=792;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (792,2,'WebGUI','Templates', 1040597433);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=790;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (790,2,'WebGUI','Diese Profil Kategorie löschen.', 1040597419);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=789;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (789,2,'WebGUI','Diese Profil Kategorie bearbeiten.', 1040597406);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=788;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (788,2,'WebGUI','Dieses Profilfeld löschen.', 1040597377);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=787;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (787,2,'WebGUI','Dieses Profilfeld bearbeiten.', 1040597360);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=786;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (786,2,'WebGUI','WebGUI\'s Upload Verwaltungssystem erlaubt Ihnen, Dateien und Texte zu einem zentralen Speicher hochzuladen, um Sie dann irgendwo in Ihrem Content einzusetzen.', 1040597320);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=785;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (785,2,'WebGUI','Uploads, verwalten', 1040597235);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=784;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (784,2,'WebGUI','Vorschaubild', 1040597218);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=782;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (782,2,'WebGUI','Beliebig', 1040597198);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=781;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (781,2,'WebGUI','Schnipsel', 1040597177);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=780;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (780,2,'WebGUI','Datei', 1040597163);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=779;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (779,2,'WebGUI','Grafik', 1040597152);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=777;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (777,2,'WebGUI','Verzeichnis ID', 1040597140);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=776;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (776,2,'WebGUI','Verzeichnis bearbeiten', 1040597128);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=773;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (773,2,'WebGUI','Datei', 1040597112);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=772;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (772,2,'WebGUI','Datei bearbeiten', 1040597100);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=771;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (771,2,'WebGUI','Schnipsel', 1040597084);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=769;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (769,2,'WebGUI','In Verzeichnissen organisieren', 1040597070);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=768;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (768,2,'WebGUI','Name', 1040597050);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=767;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (767,2,'WebGUI','Upload ID', 1040597039);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=757;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (757,2,'WebGUI','Uploads verwalten', 1040597024);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=754;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (754,2,'WebGUI','Benutzer dieser Gruppe verwalten.', 1040597007);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=753;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (753,2,'WebGUI','Diese Gruppe bearbeiten.', 1040596983);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=752;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (752,2,'WebGUI','Profil dieses Benutzers anschauen.', 1040596967);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=751;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (751,2,'WebGUI','Diesen Benutzer übernehmen.', 1040596935);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=750;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (750,2,'WebGUI','Diesen Benutzer löschen.', 1040596917);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=746;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (746,2,'WebGUI','Bearbeitungsleiste Icon Set', 1040596900);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=744;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (744,2,'WebGUI','Als nächstes?', 1040596874);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=743;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (743,2,'WebGUI','Sie müssen eine korrekte Emailadresse angeben, um Ihr Passwort zu erhalten.', 1040596854);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=742;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (742,2,'WebGUI','Templates verwalten.', 1040596824);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=739;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (739,2,'WebGUI','UI Level', 1040596808);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=738;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (738,2,'WebGUI','9 Guru', 1040596787);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=737;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (737,2,'WebGUI','8 Master', 1040596775);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=736;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (736,2,'WebGUI','7 Experte', 1040596762);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=735;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (735,2,'WebGUI','6 Professional', 1040596749);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=734;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (734,2,'WebGUI','5 erfahren', 1040596731);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=733;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (733,2,'WebGUI','4 gelernt', 1040596702);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=732;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (732,2,'WebGUI','3 erweiterter Anfänger', 1040596670);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=731;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (731,2,'WebGUI','2 Geübt', 1040596626);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=730;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (730,2,'WebGUI','1 Neuling', 1040596580);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=729;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (729,2,'WebGUI','0 Anfänger', 1040596557);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=725;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (725,2,'WebGUI','Der Benutzername darf nicht leer sein.', 1040596542);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=724;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (724,2,'WebGUI','Der Benutzername kann nicht mit einem Leerzeichen anfangen oder enden.', 1040596522);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=722;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (722,2,'WebGUI','ID', 1040596484);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=721;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (721,2,'WebGUI','Namensbereich', 1040596472);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=720;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (720,2,'WebGUI','OK', 1040596445);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=719;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (719,2,'WebGUI','Veraltet', 1040596428);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=714;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (714,2,'WebGUI','Template Verwalter Gruppe', 1040596402);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=713;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (713,2,'WebGUI','Styles Verwalter Gruppe', 1040596382);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=711;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (711,2,'WebGUI','Grafiken Verwalter Gruppe', 1040596363);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=709;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (709,2,'WebGUI','Style Verwalter Gruppe\r\nDiese Gruppe sollte die Berechtigung haben, Styles hinzuzufügen, zu bearbeiten und zu löschen.\r\n\r\nTemplate Verwalter Gruppe\r\nDiese Gruppe sollte die Berechtigung haben, Templates hinzuzufügen, zu bearbeiten und zu löschen.', 1040596290);
delete from international where languageId=2 and namespace='Survey' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,2,'Survey','Antwort gesteuert', 1040596122);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'WebGUI','Styles verwalten.', 1040596089);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=427;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (427,2,'WebGUI','Styles', 1040596068);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=380;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (380,2,'WebGUI','Style ID', 1040596050);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=158;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (158,2,'WebGUI','Neuen Style hinzufügen.', 1040596030);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=157;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (157,2,'WebGUI','Styles', 1040596005);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=156;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (156,2,'WebGUI','Style bearbeiten', 1040595987);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=155;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (155,2,'WebGUI','Sind Sie sicher, dass Sie diesen Style löschen möchten? Beachten Sie, dass alle Seiten, die diesen Style benutzen, auf den Style \"Fail Safe\" umgestellt werden.', 1040595965);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=151;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (151,2,'WebGUI','Style Name', 1040595820);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=106;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (106,2,'WebGUI','Style für alle nachfolgenden Seiten übernehmen.', 1040595792);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=105;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (105,2,'WebGUI','Style', 1040595751);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=805;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (805,2,'WebGUI','Diesen Style löschen.', 1040595710);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=806;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (806,2,'WebGUI','Diese Gruppe löschen.', 1040595693);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=807;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (807,2,'WebGUI','Verwalten Sie die Gruppen in dieser Gruppe.', 1040595655);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=808;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (808,2,'WebGUI','Senden Sie dieser Gruppe eine Email.', 1040595633);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=809;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (809,2,'WebGUI','Email Gruppe', 1040595612);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=810;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (810,2,'WebGUI','Senden', 1040595597);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=811;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (811,2,'WebGUI','Von', 1040595584);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=812;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (812,2,'WebGUI','Ihre Nachricht wurde gesendet.', 1040595571);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=813;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (813,2,'WebGUI','Gruppen in dieser Gruppe', 1040595549);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=815;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (815,2,'WebGUI','Die Datei, die Sie hochladen möchten, ist zu gross.', 1040595529);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=816;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (816,2,'WebGUI','Status', 1040595505);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=817;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (817,2,'WebGUI','Aktiviert', 1040595489);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=818;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (818,2,'WebGUI','Deaktiviert', 1040595477);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=819;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (819,2,'WebGUI','Selbst-Deaktivierend', 1040595462);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=820;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (820,2,'WebGUI','Ihr Zugang ist nicht aktiviert. Daher können Sie sich solange nicht einloggen, bis er aktiviert wurde. Die Aktivierung kann nur durch den Administrator erfolgen.', 1040595434);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=821;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (821,2,'WebGUI','beliebig', 1040595358);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=823;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (823,2,'WebGUI','Zur neuen Seite gehen.', 1040595331);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=824;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (824,2,'WebGUI','Email Fussbereich', 1040595314);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=825;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (825,2,'WebGUI','Template, Sprache', 1040595289);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=827;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (827,2,'WebGUI','Wobject Template', 1040595269);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=831;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (831,2,'WebGUI','Upload Macros', 1040595240);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=834;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (834,2,'WebGUI','Sie können jede Art von Datei hochladen, um sie später zu benutzen.\r\n\r\nName\r\nVergeben Sie einen eindeutigen Namen, den Sie später benutzen können.\r\n\r\nIn Verzeichnisnissen organisieren\r\nIn welches Verzeichnis soll diese Datei gespeichert werden?\r\n\r\nDatei\r\nWählen Sie eine Datei von Ihrer Festplatte aus, die sich hochladen möchten.', 1040595218);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=833;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (833,2,'WebGUI','Datei, hinzufügen/bearbeiten', 1040595050);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=835;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (835,2,'WebGUI','Schnipsel, hinzufügen/bearbeiten', 1040594993);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=837;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (837,2,'WebGUI','Verzeichnis, hinzufügen/bearbeiten', 1040594954);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=839;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (839,2,'WebGUI','Entwickler Macros', 1040594928);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=841;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (841,2,'WebGUI','Navigations Macros', 1040594909);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=843;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (843,2,'WebGUI','Benutzer Macros', 1040594886);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=845;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (845,2,'WebGUI','Style Macros', 1040594867);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=848;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (848,2,'WebGUI','Ein Syntaxfehler ist in diesem Template enhalten. Bitte korrigieren Sie den Fehler.', 1040594846);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=856;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (856,2,'WebGUI','Sie haben im Moment keine Account Eigenschaften zu bearbeiten.', 1040594811);
delete from international where languageId=2 and namespace='WobjectProxy' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'WobjectProxy','Mit dem Wobject Proxy können Sie ein Wobject von einer Seite zu einer anderen Seite spiegeln. Dies ist hilfreich, wenn Sie das selbe Inhaltselement in mehreren Bereichen auf Ihrer Seite einsetzen möchten.\r\n\r\nWobject To Proxy\r\nWählen Sie ein Wobject aus Ihrem System aus, dass Sie als Proxy Element nutzen möchten. Die Auswahlbox hat das Format \"Seiten Titel/Wobject Name (Wobject ID), sodass Sie schnell und direkt das Wobject finden können, dass Sie suchen.', 1040594768);
delete from international where languageId=2 and namespace='WobjectProxy' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'WobjectProxy','Wobject Proxy fehlgeschlagen. Vieleicht wurde das Object gelöscht?', 1040594574);
delete from international where languageId=2 and namespace='WobjectProxy' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'WobjectProxy','Wobject Proxy', 1040594541);
delete from international where languageId=2 and namespace='WobjectProxy' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'WobjectProxy','Wobject zu Proxy', 1040594526);
delete from international where languageId=2 and namespace='WobjectProxy' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'WobjectProxy','Wobject Proxy, hinzufügen/bearbeiten', 1040594506);
delete from international where languageId=2 and namespace='Article' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,2,'Article','Die nachfolgenden Template Variablen sind für Artikel Templates verfügbar.\r\n\r\nattachment.box\r\nGibt eine Standard WebGUI Anlagen-Box aus mit Icon, Dateiname und Anlageindikator. \r\n\r\nattachment.icon\r\nDie URL zum Icon-Symbol für diesen Anlagentyp.\r\n\r\nattachment.name\r\nDer Dateiname für diese Anlage.\r\n\r\nattachment.url\r\nDie URL zum Downloaden dieser Anlage. \r\n\r\nimage.thumbnail\r\nDie URL zum Thumbnail für die angefügte Grafik.\r\n\r\nimage.url\r\nDie URL zur angefügten Grafik. \r\n\r\npost.label\r\nDas übersetzte Label um Kommentare zu diesem Artikel hinzuzufügen. \r\n\r\npost.URL\r\nDie URL um einen Kommentar zu diesem Artikel hinzuzufügen. \r\n\r\nreplies.count\r\nDie Anzahl der Kommentare zu diesem Artikel. \r\n\r\nreplies.label\r\nDer übersetzte Text, der anzeigt, dass Sie die Kommentare anschauen können.. \r\n\r\nreplies.url\r\nDie URL, um d!
 ie Kommentare zu diesem Artikel anzuschauen.\r\n', 1040594389);
delete from international where languageId=2 and namespace='Survey' and internationalId=38;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (38,2,'Survey','Stimme auf keinen Fall zu', 1040593717);
delete from international where languageId=2 and namespace='Survey' and internationalId=37;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (37,2,'Survey','Stimme nicht zu', 1040593668);
delete from international where languageId=2 and namespace='Survey' and internationalId=39;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (39,2,'Survey','Nicht massgeblich', 1040593621);
delete from international where languageId=2 and namespace='Survey' and internationalId=74;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (74,2,'Survey','Sind Sie sicher, dass Sie alle Kommentare löschen möchten?', 1040593584);
delete from international where languageId=2 and namespace='Survey' and internationalId=44;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (44,2,'Survey','Sind Sie sicher, dass Sie diese Frage, ihre Antworten und die Kommentare löschen möchten?', 1040593415);
delete from international where languageId=2 and namespace='Survey' and internationalId=45;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (45,2,'Survey','Sind Sie sicher, dass Sie diese Antwort und Ihre Kommentare löschen möchten?', 1040593366);
delete from international where languageId=2 and namespace='Survey' and internationalId=52;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (52,2,'Survey','Auswertung', 1040593309);
delete from international where languageId=2 and namespace='Survey' and internationalId=53;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (53,2,'Survey','Kommentare', 1040593288);
delete from international where languageId=2 and namespace='Survey' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,2,'Survey','Reihenfolge der Fragen', 1040593268);
delete from international where languageId=2 and namespace='Survey' and internationalId=80;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (80,2,'Survey','Sekunden', 1040593240);
delete from international where languageId=2 and namespace='Survey' and internationalId=40;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (40,2,'Survey','Immer', 1040593211);
delete from international where languageId=2 and namespace='Survey' and internationalId=35;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (35,2,'Survey','Ein wenig einverstanden', 1040593179);
delete from international where languageId=2 and namespace='Survey' and internationalId=34;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (34,2,'Survey','Einverstanden', 1040593148);
delete from international where languageId=2 and namespace='Survey' and internationalId=33;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (33,2,'Survey','Komplett einverstanden', 1040593131);
delete from international where languageId=2 and namespace='Survey' and internationalId=32;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (32,2,'Survey','Falsch', 1040593062);
delete from international where languageId=2 and namespace='Survey' and internationalId=31;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (31,2,'Survey','Wahr', 1040593051);
delete from international where languageId=2 and namespace='Survey' and internationalId=28;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (28,2,'Survey','Eine Frage hinzufügen.', 1040593038);
delete from international where languageId=2 and namespace='Survey' and internationalId=26;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (26,2,'Survey','Frequenz (immer/nie) Antwortbereich hinzufügen.', 1040593016);
delete from international where languageId=2 and namespace='Survey' and internationalId=25;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (25,2,'Survey','Falsch/wahr Antwort hinzufügen.', 1040592716);
delete from international where languageId=2 and namespace='Survey' and internationalId=24;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (24,2,'Survey','Mehrfachauswahl-Antwort hinzufügen.', 1040592694);
delete from international where languageId=2 and namespace='Survey' and internationalId=23;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (23,2,'Survey','Neue Antwort hinzufügen.', 1040592638);
delete from international where languageId=2 and namespace='Survey' and internationalId=22;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (22,2,'Survey','Antwort Typ', 1040592620);
delete from international where languageId=2 and namespace='Product' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'Product','Sind Sie sicher, dass Sie die Beziehung zu diesem ähnlichen Produkt löschen möchten?', 1040592527);
delete from international where languageId=2 and namespace='Product' and internationalId=37;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (37,2,'Product','Ähnliches Produkt hinzufügen', 1040592400);
delete from international where languageId=2 and namespace='Survey' and internationalId=21;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (21,2,'Survey','Gehe zu', 1040592351);
delete from international where languageId=2 and namespace='Survey' and internationalId=20;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (20,2,'Survey','Ist diese Antwort korrekt?', 1040592337);
delete from international where languageId=2 and namespace='Survey' and internationalId=18;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (18,2,'Survey','Antwort bearbeiten', 1040592317);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=770;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (770,2,'WebGUI','Schnippsel bearbeiten', 1040471469);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=764;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (764,2,'WebGUI','Upload bearbeiten.', 1040471399);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=759;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (759,2,'WebGUI','Dieses Verzeichnis bearbeiten', 1040471347);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=774;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (774,2,'WebGUI','Möchten Sie diesen Upload wirklich löschen? Nach dem Löschen kann das File nicht wiederhergestellt werden...', 1040471298);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=765;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (765,2,'WebGUI','Diesen Upload löschen.', 1040471238);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=63;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (63,2,'WebGUI','Editieren einschalten', 1040464598);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=517;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (517,2,'WebGUI','Editieren ausschalten!', 1040464575);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=516;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (516,2,'WebGUI','Editieren einschalten!', 1040464558);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,2,'WebGUI','Editieren abschalten', 1040464536);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=502;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (502,2,'WebGUI','Sind Sie sich sicher, dass Sie dieses Template löschen möchten und alle Seiten, die dieses Template benutzen, somit auf das Standardtemplate setzen?', 1040406207);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=640;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (640,2,'WebGUI','Es ist nicht sinnvoll Templates zu löschen, da man nie weiß, welche ungünstige Auswirkung es auf die Seite haben kann (manche Seiten nutzen dieses Template eventuell noch). Wenn Sie ein Template löschen, werden alle Seiten, die dieses Template noch benutzen, auf das Standardtemplate gesetzt.', 1040406160);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=506;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (506,2,'WebGUI','Templates verwalten', 1040406102);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=683;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (683,2,'WebGUI','Template verwalten', 1040406082);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=507;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (507,2,'WebGUI','Templates bearbeiten', 1040406060);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=528;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (528,2,'WebGUI','Name des Templates', 1040406037);
delete from international where languageId=2 and namespace='SiteMap' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,2,'SiteMap','Site Map Template', 1040406015);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=503;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (503,2,'WebGUI','Template ID', 1040405992);
delete from international where languageId=2 and namespace='Product' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,2,'Product','Produkt Template', 1040405973);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=508;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (508,2,'WebGUI','Templates verwalten', 1040405956);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=356;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (356,2,'WebGUI','Template', 1040405929);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=505;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (505,2,'WebGUI','neues Template', 1040405911);
delete from international where languageId=2 and namespace='USS' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,2,'USS','Haupt Template', 1040405887);
delete from international where languageId=2 and namespace='Product' and internationalId=60;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (60,2,'Product','Template', 1040405867);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=504;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (504,2,'WebGUI','Template', 1040405842);
delete from international where languageId=2 and namespace='USS' and internationalId=76;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (76,2,'USS','Template', 1040405824);
delete from international where languageId=2 and namespace='MailForm' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'MailForm','Mail Formular', 1040405801);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,2,'MessageBoard','Message Board Template', 1040405772);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,2,'MessageBoard','Haupt Template', 1040405753);
delete from international where languageId=2 and namespace='LinkList' and internationalId=75;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (75,2,'LinkList','Link Liste Template', 1040405733);
delete from international where languageId=2 and namespace='Survey' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'Survey','Umfrage, hinzufügen/bearbeiten', 1040405696);
delete from international where languageId=2 and namespace='Survey' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'Survey','Umfrage bearbeiten', 1040405651);
delete from international where languageId=2 and namespace='Survey' and internationalId=48;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (48,2,'Survey','Sie sind momentan nicht berechtigt an dieser Umfrage teilzunehmen', 1040405625);
delete from international where languageId=2 and namespace='Item' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,2,'Item','Textelement Template', 1040404643);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=829;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (829,2,'WebGUI','Seiten Template', 1040404503);
delete from international where languageId=2 and namespace='Item' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,2,'Item','Template', 1040404478);
delete from international where languageId=2 and namespace='FileManager' and internationalId=75;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (75,2,'FileManager','Dateimanager Template', 1040404451);
delete from international where languageId=2 and namespace='FAQ' and internationalId=76;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (76,2,'FAQ','FAQ Template', 1040404432);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=96;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (96,2,'EventsCalendar','Ereignis Template', 1040404414);
delete from international where languageId=2 and namespace='FAQ' and internationalId=74;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (74,2,'FAQ','Template', 1040404399);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=94;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (94,2,'EventsCalendar','Ereignis Kalender Template', 1040404377);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=80;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (80,2,'EventsCalendar','Ereignis Template', 1040404360);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=79;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (79,2,'EventsCalendar','Haupt Template', 1040404342);
delete from international where languageId=2 and namespace='Article' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,2,'Article','Artikel Template', 1040404102);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=723;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (723,2,'WebGUI','Abgelehnt', 1040403998);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=668;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (668,2,'WebGUI','Style Sheets verwenden', 1040403977);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=680;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (680,2,'WebGUI','Package hinzufügen', 1040403940);
delete from international where languageId=2 and namespace='MessageBoard' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,2,'MessageBoard','Diskussionsforum hinzufügen oder bearbeiten', 1040403918);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=697;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (697,2,'WebGUI','Karma verwenden', 1040403885);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=539;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (539,2,'WebGUI','Karma aktivieren?', 1040403865);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=855;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (855,2,'WebGUI','Alle Templates anzeigen', 1040402476);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=854;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (854,2,'WebGUI','Alle Vorlagen wie diese anzeigen', 1040402446);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=853;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (853,2,'WebGUI','Vorlage löschen', 1040402383);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=852;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (852,2,'WebGUI','Vorlage kopieren', 1040402305);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=851;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (851,2,'WebGUI','Vorlage bearbeiten', 1040402275);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=741;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (741,2,'WebGUI','Vorlage bearbeiten', 1040402257);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=783;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (783,2,'WebGUI','Typ', 1040399695);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=387;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (387,2,'WebGUI','Upload von', 1040399607);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=766;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (766,2,'WebGUI','Zurück zu den Uploads', 1040399523);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=756;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (756,2,'WebGUI','Zurück zur Gruppenliste.', 1040399470);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=814;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (814,2,'WebGUI','Zurück zu den Styles.', 1040399446);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=745;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (745,2,'WebGUI','Zurück zur Seite.', 1040399379);
delete from international where languageId=2 and namespace='Survey' and internationalId=60;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (60,2,'Survey','Zurück zur Umfrage.', 1040399321);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=775;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (775,2,'WebGUI','Sind Sie sicher, dass Sie dieses Verzeichnis löschen und den Inhalt in den darüberliegenden Ordner verschieben möchten?', 1040399275);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=760;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (760,2,'WebGUI','Dieses Verzeichnis löschen', 1040399202);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=763;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (763,2,'WebGUI','Schnipsel hinzufügen', 1040399163);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=762;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (762,2,'WebGUI','Datei hinzufügen', 1040399069);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=761;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (761,2,'WebGUI','Grafik hinzufügen', 1040399045);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=758;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (758,2,'WebGUI','Verzeichnis hinzufügen', 1040399023);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=749;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (749,2,'WebGUI','Seitenstatistik aktivieren?', 1040398977);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=796;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (796,2,'WebGUI','Seitenstatistik', 1040398941);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=144;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (144,2,'WebGUI','Auswertungen', 1040398912);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=423;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (423,2,'WebGUI','Aktive Sitzungen', 1040398889);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=424;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (424,2,'WebGUI','Anmeldungshistorie', 1040398863);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=798;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (798,2,'WebGUI','Seitentitel', 1040398799);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=802;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (802,2,'WebGUI','WebGUI speichert momentan keine Seitenstatistiken. Sie können dieses Feature in den Einstellungen aktivieren.', 1040398735);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=584;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (584,2,'WebGUI','Neue Sprache hinzufügen.', 1040398571);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'WebGUI','Neue Seite', 1040398436);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=593;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (593,2,'WebGUI','Übersetzung übermitteln.', 1040398176);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=791;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (791,2,'WebGUI','Diese Übersetzung löschen', 1040398136);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=847;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (847,2,'WebGUI','Zurück zur vorhergehenden Seite gehen.', 1040398065);
delete from international where languageId=2 and namespace='Article' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'Article','Artikel', 1040398023);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=778;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (778,2,'WebGUI','Verzeichnisbeschreibung', 1040398001);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=747;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (747,2,'WebGUI','Benutzernamen müssen alpha-numerische Zeichen enthalten', 1040397962);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=567;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (567,2,'WebGUI','Präventiv', 1040397902);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=601;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (601,2,'WebGUI','International ID', 1040397860);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=570;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (570,2,'WebGUI','Thema sperren', 1040397845);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=559;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (559,2,'WebGUI','Beim Registieren ausführen', 1040397832);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=568;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (568,2,'WebGUI','After-the-fact', 1040397800);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=558;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (558,2,'WebGUI','Benutzer Karma bearbeiten', 1040397662);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=554;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (554,2,'WebGUI','Aktion ausführen', 1040397646);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=538;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (538,2,'WebGUI','Karma Grenzwert', 1040397605);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=521;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (521,2,'WebGUI','Ich möchte via Email to Pager informiert werden.', 1040397574);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=518;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (518,2,'WebGUI','Benachrichtigungen', 1040397531);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=515;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (515,2,'WebGUI','Zeitpunkt der Bearbeitung einfügen/anzeigen?', 1040397458);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=513;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (513,2,'WebGUI','Vorheriges Thema', 1040397425);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=512;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (512,2,'WebGUI','Nächstes Thema', 1040397414);
delete from international where languageId=2 and namespace='USS' and internationalId=74;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (74,2,'USS','Benutzer-Beitragssystem Systemvorlage', 1040397377);
delete from international where languageId=2 and namespace='USS' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,2,'USS','Beitragssystem Vorlage', 1040397353);
delete from international where languageId=2 and namespace='USS' and internationalId=52;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (52,2,'USS','Vorschaubild', 1040397318);
delete from international where languageId=2 and namespace='USS' and internationalId=38;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (38,2,'USS','(Wählen Sie \"Nein\", wenn Sie ein HTML/Richedit Beitragssystem hinzufügen)', 1040397301);
delete from international where languageId=2 and namespace='Survey' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'Survey','Umfrage', 1040397175);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=511;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (511,2,'WebGUI','durchgehend', 1040397160);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=509;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (509,2,'WebGUI','Diskussions Layout', 1040397118);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=496;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (496,2,'WebGUI','Editor auswählen', 1040397079);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=495;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (495,2,'WebGUI','htmlArea (Standard)', 1040397060);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=494;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (494,2,'WebGUI','Real Objects Edit-on Pro', 1040397039);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=501;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (501,2,'WebGUI','Body', 1040397021);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=510;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (510,2,'WebGUI','Flach', 1040397009);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=748;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (748,2,'WebGUI','Benutzer Zähler', 1040396997);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=492;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (492,2,'WebGUI','Liste der Profil-Felder', 1040396980);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=491;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (491,2,'WebGUI','Profil Feld hinzufügen.', 1040396957);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=490;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (490,2,'WebGUI','Profil Kategorie hinzufügen.', 1040396942);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=489;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (489,2,'WebGUI','Profil Kategorie', 1040396924);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=485;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (485,2,'WebGUI','Boolean (Checkbox)', 1040396911);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=484;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (484,2,'WebGUI','Liste auswählen', 1040396891);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=468;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (468,2,'WebGUI','User-Profil Kategorie bearbeiten', 1040396875);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=446;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (446,2,'WebGUI','Webseite (geschäftlich)', 1040396777);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=443;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (443,2,'WebGUI','Privat', 1040396759);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=442;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (442,2,'WebGUI','Geschäftlich', 1040396750);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=441;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (441,2,'WebGUI','Email zu Pager Gateway', 1040396717);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=440;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (440,2,'WebGUI','Kontakt Informationen', 1040396599);
delete from international where languageId=2 and namespace='Product' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'Product','Produkt-Abbildung 3', 1040396553);
delete from international where languageId=2 and namespace='Product' and internationalId=42;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (42,2,'Product','Produkt Beschreibung, hinzufügen/bearbeiten', 1040396511);
delete from international where languageId=2 and namespace='Survey' and internationalId=15;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (15,2,'Survey','Kommentare erlauben?', 1040396480);
delete from international where languageId=2 and namespace='Survey' and internationalId=17;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (17,2,'Survey','Frage bearbeiten', 1040396466);
delete from international where languageId=2 and namespace='Product' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'Product','Sind Sie sicher, dass die Verknüpfung zu diesem Zubehör löschen möchten?', 1040396438);
delete from international where languageId=2 and namespace='Product' and internationalId=17;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (17,2,'Product','Zubehör', 1040396372);
delete from international where languageId=2 and namespace='Product' and internationalId=18;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (18,2,'Product','Anderes Zubehör hinzufügen?', 1040396355);
delete from international where languageId=2 and namespace='Product' and internationalId=16;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (16,2,'Product','Zubehör hinzufügen', 1040396333);
delete from international where languageId=2 and namespace='Product' and internationalId=44;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (44,2,'Product','Produkt Zubehör, Hinzufügen/Bearbeiten', 1040396310);
delete from international where languageId=2 and namespace='Survey' and internationalId=19;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (19,2,'Survey','Antwort', 1040396283);
delete from international where languageId=2 and namespace='Survey' and internationalId=30;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (30,2,'Survey','Neue Frage hinzufügen.', 1040396272);
delete from international where languageId=2 and namespace='Survey' and internationalId=29;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (29,2,'Survey','Antwort-Textfeld hinzufügen.', 1040396252);
delete from international where languageId=2 and namespace='Survey' and internationalId=27;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (27,2,'Survey','Meinungsbereich hinzufügen (einverstanden/nicht einverstanden).', 1040396228);
delete from international where languageId=2 and namespace='Survey' and internationalId=16;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (16,2,'Survey','Antworten zufällig anordnen?', 1040396058);
delete from international where languageId=2 and namespace='Survey' and internationalId=14;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (14,2,'Survey','Frage', 1040396029);
delete from international where languageId=2 and namespace='Survey' and internationalId=13;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (13,2,'Survey','Wer kann die Ergebnisliste anschauen?', 1040395954);
delete from international where languageId=2 and namespace='Survey' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,2,'Survey','Wer kann an der Umfrage teilnehmen?', 1040395930);
delete from international where languageId=2 and namespace='Survey' and internationalId=11;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (11,2,'Survey','Modus', 1040395911);
delete from international where languageId=2 and namespace='Survey' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,2,'Survey','Quiz', 1040395898);
delete from international where languageId=2 and namespace='Survey' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'Survey','Umfrage', 1040395887);
delete from international where languageId=2 and namespace='SiteMap' and internationalId=75;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (75,2,'SiteMap','Alle Hauptpfade', 1040395875);
delete from international where languageId=2 and namespace='SiteMap' and internationalId=74;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (74,2,'SiteMap','Diese Seite', 1040395856);
delete from international where languageId=2 and namespace='Poll' and internationalId=20;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (20,2,'Poll','Karma pro Abstimmung', 1040395813);
delete from international where languageId=2 and namespace='Poll' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,2,'Poll','Gesamtzahl der Votes:', 1040395798);
delete from international where languageId=2 and namespace='HttpProxy' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'HttpProxy','Verzeichnis zum Speichern der Cookies', 1040395667);
delete from international where languageId=2 and namespace='HttpProxy' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,2,'HttpProxy','Redirects folgen', 1040395646);
delete from international where languageId=2 and namespace='HttpProxy' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,2,'HttpProxy','Inhalt filtern', 1040395634);
delete from international where languageId=2 and namespace='HttpProxy' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'HttpProxy','Style vom Inhalt entfernen', 1040395623);
delete from international where languageId=2 and namespace='HttpProxy' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'HttpProxy','Externen Links folgen', 1040395599);
delete from international where languageId=2 and namespace='HttpProxy' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'HttpProxy','Timeout (Sekunden)', 1040395576);
delete from international where languageId=2 and namespace='HttpProxy' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'HttpProxy','HTTP Proxy', 1040395372);
delete from international where languageId=2 and namespace='HttpProxy' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'HttpProxy','HTTP Proxy ändern', 1040395360);
delete from international where languageId=2 and namespace='HttpProxy' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'HttpProxy','URL', 1040395344);
delete from international where languageId=2 and namespace='FileManager' and internationalId=74;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (74,2,'FileManager','Neue Datei hinzufügen.', 1040395313);
delete from international where languageId=2 and namespace='FAQ' and internationalId=75;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (75,2,'FAQ','Frage hinzufügen.', 1040395090);
delete from international where languageId=2 and namespace='Auth/SMB' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,2,'Auth/SMB','SMB Protokol Fehler (2)\r\nBitte nehmen Sie Kontakt mit Ihrem Systemadministrator auf.', 1040395045);
delete from international where languageId=2 and namespace='Auth/SMB' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'Auth/SMB','SMB Anmeldefehler (3)\r\nSie haben einen falschen Benutzernamen oder ein falsches Kennwort eingegeben. Bitte versuchen Sie es noch einmal.', 1040395014);
delete from international where languageId=2 and namespace='Auth/SMB' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'Auth/SMB','PDC', 1040394965);
delete from international where languageId=2 and namespace='Auth/SMB' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,2,'Auth/SMB','BDC', 1040394956);
delete from international where languageId=2 and namespace='Auth/SMB' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,2,'Auth/SMB','NT Domain', 1040394946);
delete from international where languageId=2 and namespace='Auth/SMB' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,2,'Auth/SMB','NT Login', 1040394932);
delete from international where languageId=2 and namespace='Auth/SMB' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,2,'Auth/SMB','NT Passwort', 1040394921);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=93;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (93,2,'EventsCalendar','Nächster Termin', 1040394862);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=718;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (718,2,'WebGUI','Übersetzung exportieren.', 1040394793);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=92;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (92,2,'EventsCalendar','Vorheriger Termin.', 1040394762);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=91;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (91,2,'EventsCalendar','Neues Ereignis hinzufügen.', 1040394748);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=90;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (90,2,'EventsCalendar','Standard Monat', 1040394734);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=89;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (89,2,'EventsCalendar','3 Monate vom Beginn an anzeigen.', 1040394722);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=88;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (88,2,'EventsCalendar','6 Monate vom Beginn an anzeigen.', 1040394712);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=87;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (87,2,'EventsCalendar','9 Monate vom Beginn an anzeigen.', 1040394701);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=86;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (86,2,'EventsCalendar','12 Monate vom Beginn an anzeigen.', 1040394683);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=85;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (85,2,'EventsCalendar','Letzter im Kalender.', 1040394664);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=84;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (84,2,'EventsCalendar','Ende Monat', 1040394649);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=83;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (83,2,'EventsCalendar','Erster Tag im Kalender.', 1040394632);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=82;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (82,2,'EventsCalendar','Aktuell.', 1040394612);
delete from international where languageId=2 and namespace='EventsCalendar' and internationalId=81;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (81,2,'EventsCalendar','Anfangsmonat', 1040394600);
delete from international where languageId=2 and namespace='Auth/WebGUI' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,2,'Auth/WebGUI','Ihr Passwort darf nicht \"Passwort\" lauten.', 1040394515);
delete from international where languageId=2 and namespace='Auth/WebGUI' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,2,'Auth/WebGUI','Ihr Passwort darf nicht leer sein.', 1040394494);
delete from international where languageId=2 and namespace='Auth/WebGUI' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'Auth/WebGUI','WebGUI Authentifizierungs-Optionen', 1040394478);
delete from international where languageId=2 and namespace='Auth/SMB' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,2,'Auth/SMB','SMB Server Fehler(1)\r\nProbleme beim Zugriff auf den Domain-Controller. Wahrscheinlich gibt es einen Verbindungs-Timeout. Bitte versuchen Sie es nochmal oder nehmen Sie Kontakt mit Ihrem Systemadministrator auf.', 1040394452);
delete from international where languageId=2 and namespace='Auth/SMB' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'Auth/SMB','SMB Authentifizierungs-Optionen', 1040394357);
delete from international where languageId=2 and namespace='Auth/LDAP' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,2,'Auth/LDAP','LDAP Authentifizierungs Optionen', 1040384677);
delete from international where languageId=2 and namespace='WebGUI' and internationalId=394;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (394,2,'WebGUI','Uploads\r\nverwalten', 1039441090);
