delete from help where helpId=1 and language='English' and (namespace='LinkList' or namespace='EventsCalendar' or namespace='FAQ');
INSERT INTO help VALUES (1,'LinkList','English','Add/Edit','Link List','Link lists are just what they sound like, a list of links. Many sites have a links section, and this just automates the process.\r\n\r\n<b>Title</b>\r\nWhat is the title of this link list?\r\n\r\n<b>Display the title?</b>\r\nDo you wish to disply the title?\r\n\r\n<b>Process macros?</b>\r\nDo you wish to process WebGUI macros? Unchecking this box will not process macros and will speed up page execution.\r\n\r\n<b>Description</b>\r\nDescribe the purpose of the links in this list.\r\n\r\n<b>Proceed to add link?</b>\r\nLeave this checked if you want to add links to the link list directly after creating it.\r\n\r\n<b>Adding / Editing Links</b>\r\nYou\'ll notice at the bottom of the Edit screen that there are some options to add, edit, delete and reorder the links in your link lists. This process works exactly as the process for doing the same with widgets and pages. The three properties of links are <i>name</i>, <i>url</i>, and <i>description</i>.\r\n','1,2,3,4,5');
INSERT INTO help VALUES (1,'EventsCalendar','English','Add/Edit','Events Calendar','Events calendars are used on many intranets to keep track of internal dates that affect a whole organization. Also events calendars on consumer sites are a great way to let your customers know what events you\'ll be attending and what promotions you\'ll be having.\r\n\r\n<b>Title</b>\r\nWhat is the title of this events calendar?\r\n\r\n<b>Display the title?</b>\r\nDo you wish to disply the title?\r\n\r\n<b>Process macros?</b>\r\nDo you wish to process WebGUI macros? Unchecking this box will not process macros and will speed up page execution.\r\n\r\n<b>Description</b>\r\nBriefly describe what this events calendar details.\r\n\r\n<b>Proceed to add event?</b>\r\nLeave this checked if you want to add events to the events calendar directly after creating it.\r\n\r\n<b>Add / Edit Events</b>\r\nOn the edit screen you\'ll notice that there are options to add, edit, and delete the events in your events calendar. The properties for events are <i>name</i>, <i>description</i>, <i>start date</i>,  and <i>end date</i>.\r\n\r\n<i>Note:</i> Events that have already happened will not be displayed on the events calendar.','1,2,3,4,5');
INSERT INTO help VALUES (1,'FAQ','English','Add/Edit','F.A.Q.','It seems that almost every web site, intranet, and extranet in the world has a frequently asked questions area. This widget helps you build one too.\r\n\r\n<b>Title</b>\r\nWhat is the title for this FAQ section?\r\n\r\n<b>Display the title?</b>\r\nDo you wish to disply the title?\r\n\r\n<b>Process macros?</b>\r\nDo you wish to process WebGUI macros? Unchecking this box will not process macros and will speed up page execution.\r\n\r\n<b>Description</b>\r\nBriefly describe what this FAQ covers.\r\n\r\n<b>Proceed to add question?</b>\r\nLeave this checked if you want to add questions to the FAQ directly after creating it.\r\n\r\n<b>Add / Edit Questions</b>\r\nOn the edit screen you\'ll notice options for adding, editing, deleting, and reordering the questions in your FAQ. The two properties of FAQ questions are <i>question</i> and <i>answer</i>.\r\n','1,2,3,4,5');

INSERT INTO international VALUES (259,'WebGUI','Español','Reporte SQL');
INSERT INTO international VALUES (258,'WebGUI','Español','Editar Encuesta');
INSERT INTO international VALUES (257,'WebGUI','Español','(Ingrese una por línea. No más de 20)');
INSERT INTO international VALUES (255,'WebGUI','Español','Pregunta');
INSERT INTO international VALUES (256,'WebGUI','Español','Respuestas');
INSERT INTO international VALUES (254,'WebGUI','Español','Ancho del gráfico');
INSERT INTO international VALUES (253,'WebGUI','Español','Quiénes pueden votar?');
INSERT INTO international VALUES (251,'WebGUI','Español','Agregar Encuesta');
INSERT INTO international VALUES (252,'WebGUI','Español','Activar');
INSERT INTO international VALUES (250,'WebGUI','Español','Encuesta');
INSERT INTO international VALUES (249,'WebGUI','Español','Última respuesta');
INSERT INTO international VALUES (247,'WebGUI','Español','Inicio');
INSERT INTO international VALUES (248,'WebGUI','Español','Respuestas');
INSERT INTO international VALUES (246,'WebGUI','Español','Mandar Nuevo Mensage');
INSERT INTO international VALUES (244,'WebGUI','Español','Autor');
INSERT INTO international VALUES (245,'WebGUI','Español','Fecha');
INSERT INTO international VALUES (243,'WebGUI','Español','Siguiente');
INSERT INTO international VALUES (241,'WebGUI','Español','Anterior');
INSERT INTO international VALUES (242,'WebGUI','Español','Volver a la Lista de Mensages');
INSERT INTO international VALUES (239,'WebGUI','Español','Fecha:');
INSERT INTO international VALUES (240,'WebGUI','Español','ID del mensage:');
INSERT INTO international VALUES (237,'WebGUI','Español','Asunto:');
INSERT INTO international VALUES (238,'WebGUI','Español','Autor:');
INSERT INTO international VALUES (235,'WebGUI','Español','Editar mensage');
INSERT INTO international VALUES (236,'WebGUI','Español','Responder');
INSERT INTO international VALUES (234,'WebGUI','Español','Respondiendo...');
INSERT INTO international VALUES (232,'WebGUI','Español','sin título');
INSERT INTO international VALUES (233,'WebGUI','Español','(eom)');
INSERT INTO international VALUES (231,'WebGUI','Español','Mandando Nuevo Mensage ...');
INSERT INTO international VALUES (229,'WebGUI','Español','Asunto');
INSERT INTO international VALUES (230,'WebGUI','Español','Mensage');
INSERT INTO international VALUES (228,'WebGUI','Español','Editar Mensage...');
INSERT INTO international VALUES (227,'WebGUI','Español','Editar Tabla de Mensages');
INSERT INTO international VALUES (226,'WebGUI','Español','Timeout de edición');
INSERT INTO international VALUES (225,'WebGUI','Español','Mensages por página');
INSERT INTO international VALUES (224,'WebGUI','Español','Quienes pueden mandar?');
INSERT INTO international VALUES (223,'WebGUI','Español','Table de Mensages');
INSERT INTO international VALUES (222,'WebGUI','Español','Agregar Tabla de Mensages');
INSERT INTO international VALUES (221,'WebGUI','Español','Agregar nuevo Enlace');
INSERT INTO international VALUES (220,'WebGUI','Español','Editar Enlace');
INSERT INTO international VALUES (218,'WebGUI','Español','Editar Lista de Enlaces');
INSERT INTO international VALUES (219,'WebGUI','Español','Agregar Lista de Enlaces');
INSERT INTO international VALUES (217,'WebGUI','Español','Está seguro de querer eliminar éste enlace?');
INSERT INTO international VALUES (216,'WebGUI','Español','URL');
INSERT INTO international VALUES (215,'WebGUI','Español','Agregar Enlace');
INSERT INTO international VALUES (214,'WebGUI','Español','Lista de Enlaces');
INSERT INTO international VALUES (213,'WebGUI','Español','Editar Pregunta');
INSERT INTO international VALUES (212,'WebGUI','Español','Agregar nueva pregunta.');
INSERT INTO international VALUES (211,'WebGUI','Español','Editar F.A.Q.');
INSERT INTO international VALUES (209,'WebGUI','Español','Respuesta');
INSERT INTO international VALUES (210,'WebGUI','Español','Está seguro de querer eliminar ésta pregunta?');
INSERT INTO international VALUES (208,'WebGUI','Español','Pregunta');
INSERT INTO international VALUES (207,'WebGUI','Español','Agregar Pregunta');
INSERT INTO international VALUES (206,'WebGUI','Español','Agregar F.A.Q.');
INSERT INTO international VALUES (205,'WebGUI','Español','F.A.Q.');
INSERT INTO international VALUES (204,'WebGUI','Español','Editar Columna Extra');
INSERT INTO international VALUES (203,'WebGUI','Español','Clase StyleSheet');
INSERT INTO international VALUES (202,'WebGUI','Español','Ancho');
INSERT INTO international VALUES (201,'WebGUI','Español','Espaciador');
INSERT INTO international VALUES (200,'WebGUI','Español','Agregar Columna Extra');
INSERT INTO international VALUES (199,'WebGUI','Español','Columna Extra');
INSERT INTO international VALUES (198,'WebGUI','Español','Editar Evento');
INSERT INTO international VALUES (197,'WebGUI','Español','Editar Calendario de Eventos');
INSERT INTO international VALUES (196,'WebGUI','Español','<b>y</b> todos las recurrencias del mismo');
INSERT INTO international VALUES (195,'WebGUI','Español','Está segugo de querer eliminar éste evento');
INSERT INTO international VALUES (194,'WebGUI','Español','hasta');
INSERT INTO international VALUES (193,'WebGUI','Español','Se repite cada');
INSERT INTO international VALUES (192,'WebGUI','Español','Agregar Evento');
INSERT INTO international VALUES (191,'WebGUI','Español','Semana');
INSERT INTO international VALUES (187,'WebGUI','Español','Calendario de Eventos');
INSERT INTO international VALUES (188,'WebGUI','Español','Agregar Calendario de Eventos');
INSERT INTO international VALUES (189,'WebGUI','Español','Sucede solo una vez.');
INSERT INTO international VALUES (190,'WebGUI','Español','Día');
INSERT INTO international VALUES (186,'WebGUI','Español','Eliminar');
INSERT INTO international VALUES (185,'WebGUI','Español','Editar Artículo');
INSERT INTO international VALUES (184,'WebGUI','Español','(marque si no está agregando &lt;br&gt; manualmente.)');
INSERT INTO international VALUES (183,'WebGUI','Español','Convertir saltos de carro?');
INSERT INTO international VALUES (181,'WebGUI','Español','Link URL');
INSERT INTO international VALUES (182,'WebGUI','Español','Adjuntar');
INSERT INTO international VALUES (179,'WebGUI','Español','Imagen');
INSERT INTO international VALUES (180,'WebGUI','Español','Link Título');
INSERT INTO international VALUES (178,'WebGUI','Español','Cuerpo');
INSERT INTO international VALUES (173,'WebGUI','Español','Agregar Artículo');
INSERT INTO international VALUES (174,'WebGUI','Español','Mostrar el título?');
INSERT INTO international VALUES (175,'WebGUI','Español','Procesar macros?');
INSERT INTO international VALUES (176,'WebGUI','Español','Fecha Inicio');
INSERT INTO international VALUES (177,'WebGUI','Español','Fecha finalización');
INSERT INTO international VALUES (171,'WebGUI','Español','rich edit');
INSERT INTO international VALUES (172,'WebGUI','Español','Artículo');
INSERT INTO international VALUES (170,'WebGUI','Español','buscar');
INSERT INTO international VALUES (169,'WebGUI','Español','Agregar nuevo usuario');
INSERT INTO international VALUES (168,'WebGUI','Español','Editar Usuario');
INSERT INTO international VALUES (166,'WebGUI','Español','Connect DN');
INSERT INTO international VALUES (167,'WebGUI','Español','Está seguro de querer eliminar éste usuario? Tenga en cuenta que toda la información del usuario será eliminada permanentemente si procede.');
INSERT INTO international VALUES (164,'WebGUI','Español','Método de Auntentificación');
INSERT INTO international VALUES (165,'WebGUI','Español','LDAP URL');
INSERT INTO international VALUES (163,'WebGUI','Español','Agregar usuario');
INSERT INTO international VALUES (162,'WebGUI','Español','Está seguro de querer eliminar todos los elementos de la papelera?');
INSERT INTO international VALUES (161,'WebGUI','Español','Contribuido por');
INSERT INTO international VALUES (160,'WebGUI','Español','Fecha Contribución');
INSERT INTO international VALUES (159,'WebGUI','Español','Contribuciones Pendientes');
INSERT INTO international VALUES (156,'WebGUI','Español','Editar Estilo');
INSERT INTO international VALUES (157,'WebGUI','Español','Estilos');
INSERT INTO international VALUES (158,'WebGUI','Español','Agregar nuevo Estilo');
INSERT INTO international VALUES (155,'WebGUI','Español','\"Está seguro de querer eliminar éste estilo y migrar todas la páginas que lo usen al estilo \"\"Fail Safe\"\"?\"');
INSERT INTO international VALUES (152,'WebGUI','Español','Encabezado');
INSERT INTO international VALUES (153,'WebGUI','Español','Pie');
INSERT INTO international VALUES (154,'WebGUI','Español','Hoja de Estilo');
INSERT INTO international VALUES (151,'WebGUI','Español','Nombre del Estilo');
INSERT INTO international VALUES (150,'WebGUI','Español','Agregar Estilo');
INSERT INTO international VALUES (149,'WebGUI','Español','Usuarios');
INSERT INTO international VALUES (148,'WebGUI','Español','Widgets Visibles');
INSERT INTO international VALUES (147,'WebGUI','Español','Páginas Visibles');
INSERT INTO international VALUES (146,'WebGUI','Español','Sesiones activas');
INSERT INTO international VALUES (145,'WebGUI','Español','Versión de WebGUI');
INSERT INTO international VALUES (144,'WebGUI','Español','Ver estadísticas');
INSERT INTO international VALUES (143,'WebGUI','Español','Configurar Opciones');
INSERT INTO international VALUES (142,'WebGUI','Español','Timeout de sesión');
INSERT INTO international VALUES (141,'WebGUI','Español','Página no encontrada');
INSERT INTO international VALUES (139,'WebGUI','Español','No');
INSERT INTO international VALUES (140,'WebGUI','Español','Editar configuraciones misceláneas');
INSERT INTO international VALUES (138,'WebGUI','Español','Si');
INSERT INTO international VALUES (135,'WebGUI','Español','Servidor SMTP');
INSERT INTO international VALUES (136,'WebGUI','Español','Página de Inicio');
INSERT INTO international VALUES (137,'WebGUI','Español','Página: Página No Encontrada');
INSERT INTO international VALUES (133,'WebGUI','Español','Editar configuración de e-mail');
INSERT INTO international VALUES (134,'WebGUI','Español','Mensage de Recuperar Password');
INSERT INTO international VALUES (129,'WebGUI','Español','Camino a Extras de WebGUI');
INSERT INTO international VALUES (130,'WebGUI','Español','Tamaño máximo de adjuntos');
INSERT INTO international VALUES (131,'WebGUI','Español','Camino Web de los archivos adjuntos');
INSERT INTO international VALUES (132,'WebGUI','Español','Camino en server de los archivos adjuntos');
INSERT INTO international VALUES (128,'WebGUI','Español','Editar Opciones de Archivos');
INSERT INTO international VALUES (124,'WebGUI','Español','Editar Información de la Companía');
INSERT INTO international VALUES (125,'WebGUI','Español','Nombre de la Companía');
INSERT INTO international VALUES (126,'WebGUI','Español','E-mail de la Companía');
INSERT INTO international VALUES (127,'WebGUI','Español','URL de la Companía');
INSERT INTO international VALUES (123,'WebGUI','Español','Password LDAP');
INSERT INTO international VALUES (122,'WebGUI','Español','Nombre Identidad LDAP');
INSERT INTO international VALUES (121,'WebGUI','Español','Identidad LDAP (por defecto)');
INSERT INTO international VALUES (120,'WebGUI','Español','URL LDAP (por defecto)');
INSERT INTO international VALUES (119,'WebGUI','Español','Método de Autentificación (por defecto)');
INSERT INTO international VALUES (118,'WebGUI','Español','Registración Anónima');
INSERT INTO international VALUES (117,'WebGUI','Español','Editar Opciones de Auntentificación');
INSERT INTO international VALUES (116,'WebGUI','Español','Marque para dar éstos privilegios a todas las sub-páginas.');
INSERT INTO international VALUES (115,'WebGUI','Español','Cualquiera puede editar?');
INSERT INTO international VALUES (114,'WebGUI','Español','Cualquiera puede ver?');
INSERT INTO international VALUES (113,'WebGUI','Español','Grupo puede editar?');
INSERT INTO international VALUES (112,'WebGUI','Español','Grupo puede ver?');
INSERT INTO international VALUES (111,'WebGUI','Español','Grupo');
INSERT INTO international VALUES (110,'WebGUI','Español','Dueño puede editar?');
INSERT INTO international VALUES (109,'WebGUI','Español','Dueño puede ver?');
INSERT INTO international VALUES (108,'WebGUI','Español','Dueño');
INSERT INTO international VALUES (107,'WebGUI','Español','Privilegios');
INSERT INTO international VALUES (106,'WebGUI','Español','Marque para dar éste estilo a todas las sub-páginas.');
INSERT INTO international VALUES (105,'WebGUI','Español','Estilo');
INSERT INTO international VALUES (104,'WebGUI','Español','URL de la página');
INSERT INTO international VALUES (103,'WebGUI','Español','Propio de la página');
INSERT INTO international VALUES (102,'WebGUI','Español','Editar Página');
INSERT INTO international VALUES (101,'WebGUI','Español','Está seguro de querer eliminar ésta página');
INSERT INTO international VALUES (100,'WebGUI','Español','Meta Tags');
INSERT INTO international VALUES (98,'WebGUI','Español','Agregar Página');
INSERT INTO international VALUES (99,'WebGUI','Español','Título');
INSERT INTO international VALUES (97,'WebGUI','Español','Ordenar por Objeto');
INSERT INTO international VALUES (96,'WebGUI','Español','Ordenar por Acción');
INSERT INTO international VALUES (94,'WebGUI','Español','Vea también');
INSERT INTO international VALUES (95,'WebGUI','Español','Índice de Ayuda');
INSERT INTO international VALUES (93,'WebGUI','Español','Ayuda');
INSERT INTO international VALUES (92,'WebGUI','Español','Siguiente página');
INSERT INTO international VALUES (91,'WebGUI','Español','Página previa');
INSERT INTO international VALUES (90,'WebGUI','Español','Agregar nuevo grupo');
INSERT INTO international VALUES (89,'WebGUI','Español','Grupos');
INSERT INTO international VALUES (88,'WebGUI','Español','Usuarios en Grupo');
INSERT INTO international VALUES (87,'WebGUI','Español','Editar Grupo');
INSERT INTO international VALUES (86,'WebGUI','Español','Está segugo de querer eliminar éste grupo? Tenga en cuenta que la eliminación es permanente y removerá todos los privilegios asociados con el grupo.');
INSERT INTO international VALUES (85,'WebGUI','Español','Descripción');
INSERT INTO international VALUES (84,'WebGUI','Español','Nombre del Grupo');
INSERT INTO international VALUES (83,'WebGUI','Español','Agregar Grupo');
INSERT INTO international VALUES (82,'WebGUI','Español','Funciones Administrativas...');
INSERT INTO international VALUES (81,'WebGUI','Español','La cuenta se actualizó con éxito!');
INSERT INTO international VALUES (80,'WebGUI','Español','La cuenta se ha creado con éxito!');
INSERT INTO international VALUES (78,'WebGUI','Español','Su password no concuerda. Trate de nuevo.');
INSERT INTO international VALUES (79,'WebGUI','Español','No se puede conectar con el servidor LDAP');
INSERT INTO international VALUES (77,'WebGUI','Español','El nombre de cuenta ya está en uso por otro miembro. Por favor trate con otro nombre de usuario.  Los siguiente son algunas sugerencias:');
INSERT INTO international VALUES (76,'WebGUI','Español','El e-mail no está en nuestra base de datos');
INSERT INTO international VALUES (75,'WebGUI','Español','La información de su cuenta ha sido enviada a su e-mail-');
INSERT INTO international VALUES (74,'WebGUI','Español','Información de la Cuenta');
INSERT INTO international VALUES (73,'WebGUI','Español','Ingresar.');
INSERT INTO international VALUES (72,'WebGUI','Español','recuperar');
INSERT INTO international VALUES (71,'WebGUI','Español','Recuperar password');
INSERT INTO international VALUES (70,'WebGUI','Español','Error');
INSERT INTO international VALUES (69,'WebGUI','Español','Por favor contacte a su administrador por asistencia.');
INSERT INTO international VALUES (68,'WebGUI','Español','La información de su cuenta no es válida. O la cuenta no existe');
INSERT INTO international VALUES (67,'WebGUI','Español','Crear nueva Cuenta');
INSERT INTO international VALUES (66,'WebGUI','Español','Ingresar');
INSERT INTO international VALUES (65,'WebGUI','Español','Por favor desactive mi cuenta permanentemente');
INSERT INTO international VALUES (64,'WebGUI','Español','Salir');
INSERT INTO international VALUES (63,'WebGUI','Español','Encender Admin');
INSERT INTO international VALUES (62,'WebGUI','Español','guardar');
INSERT INTO international VALUES (61,'WebGUI','Español','Actualizar información de la Cuenta');
INSERT INTO international VALUES (60,'WebGUI','Español','Está seguro que quiere desactivar su cuenta. Si continúa su información se perderá permanentemente.');
INSERT INTO international VALUES (59,'WebGUI','Español','Perdí mi password');
INSERT INTO international VALUES (58,'WebGUI','Español','Ya tengo una cuenta!');
INSERT INTO international VALUES (57,'WebGUI','Español','Solo es necesaria si desea usar opciones que requieren e-mail.');
INSERT INTO international VALUES (56,'WebGUI','Español','Dirección de e-mail');
INSERT INTO international VALUES (55,'WebGUI','Español','Password (confirmar)');
INSERT INTO international VALUES (54,'WebGUI','Español','Crear Cuenta');
INSERT INTO international VALUES (53,'WebGUI','Español','Hacer página imprimible');
INSERT INTO international VALUES (52,'WebGUI','Español','ingresar');
INSERT INTO international VALUES (51,'WebGUI','Español','Password');
INSERT INTO international VALUES (50,'WebGUI','Español','Nombre usuario');
INSERT INTO international VALUES (49,'WebGUI','Español','\"Click <a href=\"\"^\\?op=logout\"\">aquí</a> para salir.\"');
INSERT INTO international VALUES (48,'WebGUI','Español','Hola');
INSERT INTO international VALUES (47,'WebGUI','Español','Home');
INSERT INTO international VALUES (46,'WebGUI','Español','Mi Cuenta');
INSERT INTO international VALUES (45,'WebGUI','Español','No');
INSERT INTO international VALUES (44,'WebGUI','Español','Si');
INSERT INTO international VALUES (43,'WebGUI','Español','Está seguro de querer eliminar éste contenido?');
INSERT INTO international VALUES (42,'WebGUI','Español','Por favor confirme');
INSERT INTO international VALUES (41,'WebGUI','Español','Esta intentando eliminar un componente vital del sistema WebGUI. Si continúa puede causar un mal funcionamiento de WebGUI.');
INSERT INTO international VALUES (40,'WebGUI','Español','Componente Vital');
INSERT INTO international VALUES (39,'WebGUI','Español','No tiene suficientes privilegios para ingresar a ésta página.');
INSERT INTO international VALUES (38,'WebGUI','Español','\"No tiene privilegios suficientes para realizar ésta operación. Por favor <a href=\"\"^\\?op=displayLogin\"\">ingrese con una cuenta</a> que posea los privilegios suficientes antes de intentar ésta operación.\"');
INSERT INTO international VALUES (37,'WebGUI','Español','Permiso Denegado!');
INSERT INTO international VALUES (36,'WebGUI','Español','Debe ser administrador para realizar esta tarea. Por favor contacte a uno de los administradores. La siguiente es una lista de los administradores de éste sistema:');
INSERT INTO international VALUES (35,'WebGUI','Español','Funciones Administrativas');
INSERT INTO international VALUES (34,'WebGUI','Español','fijar fecha');
INSERT INTO international VALUES (33,'WebGUI','Español','Sabado');
INSERT INTO international VALUES (32,'WebGUI','Español','Viernes');
INSERT INTO international VALUES (31,'WebGUI','Español','Jueves');
INSERT INTO international VALUES (30,'WebGUI','Español','Miércoles');
INSERT INTO international VALUES (29,'WebGUI','Español','Martes');
INSERT INTO international VALUES (28,'WebGUI','Español','Lunes');
INSERT INTO international VALUES (26,'WebGUI','Español','Diciembre');
INSERT INTO international VALUES (27,'WebGUI','Español','Domingo');
INSERT INTO international VALUES (24,'WebGUI','Español','Octubre');
INSERT INTO international VALUES (25,'WebGUI','Español','Noviembre');
INSERT INTO international VALUES (23,'WebGUI','Español','Septiembre');
INSERT INTO international VALUES (22,'WebGUI','Español','Agosto');
INSERT INTO international VALUES (21,'WebGUI','Español','Julio');
INSERT INTO international VALUES (20,'WebGUI','Español','Junio');
INSERT INTO international VALUES (19,'WebGUI','Español','Mayo');
INSERT INTO international VALUES (18,'WebGUI','Español','Abril');
INSERT INTO international VALUES (17,'WebGUI','Español','Marzo');
INSERT INTO international VALUES (16,'WebGUI','Español','Febrero');
INSERT INTO international VALUES (15,'WebGUI','Español','Enero');
INSERT INTO international VALUES (14,'WebGUI','Español','Ver contribuciones pendientes.');
INSERT INTO international VALUES (13,'WebGUI','Español','Ver índice de Ayuda');
INSERT INTO international VALUES (12,'WebGUI','Español','Apagar Admin');
INSERT INTO international VALUES (11,'WebGUI','Español','Vaciar Papelera');
INSERT INTO international VALUES (10,'WebGUI','Español','Ver Papelera');
INSERT INTO international VALUES (9,'WebGUI','Español','Ver Portapapeles');
INSERT INTO international VALUES (8,'WebGUI','Español','Ver Página No Encontrada');
INSERT INTO international VALUES (7,'WebGUI','Español','Configurar Usuarios');
INSERT INTO international VALUES (6,'WebGUI','Español','Configurar Estilos');
INSERT INTO international VALUES (5,'WebGUI','Español','Configurar Grupos.');
INSERT INTO international VALUES (4,'WebGUI','Español','Configurar Opciones.');
INSERT INTO international VALUES (3,'WebGUI','Español','Pegar desde el Portapapeles...');
INSERT INTO international VALUES (2,'WebGUI','Español','Página');
INSERT INTO international VALUES (1,'WebGUI','Español','Agregar Contenido ...');
INSERT INTO international VALUES (260,'WebGUI','Español','Agregar Reporte SQL');
INSERT INTO international VALUES (261,'WebGUI','Español','Modelo');
INSERT INTO international VALUES (262,'WebGUI','Español','Consulta');
INSERT INTO international VALUES (263,'WebGUI','Español','DSN');
INSERT INTO international VALUES (264,'WebGUI','Español','Usuario de la Base de Datos');
INSERT INTO international VALUES (265,'WebGUI','Español','Password de la Base de Datos');
INSERT INTO international VALUES (266,'WebGUI','Español','Editar Reporte SQL');
INSERT INTO international VALUES (267,'WebGUI','Español','Error: El DSN especificado está en un formato incorrecto.');
INSERT INTO international VALUES (268,'WebGUI','Español','Error: El SQL especificado está en un formato incorrecto.');
INSERT INTO international VALUES (269,'WebGUI','Español','Error: Hay un problema con la consulta.');
INSERT INTO international VALUES (270,'WebGUI','Español','Error: No se puede conectar a la base de datos.');
INSERT INTO international VALUES (277,'WebGUI','Español','Sistema de Contribución de Usuarios');
INSERT INTO international VALUES (278,'WebGUI','Español','Agregar Sistema de Contribución de Usuarios');
INSERT INTO international VALUES (279,'WebGUI','Español','Quiénes pueden contribuir?');
INSERT INTO international VALUES (280,'WebGUI','Español','Contribuciones por página');
INSERT INTO international VALUES (281,'WebGUI','Español','Aprobado');
INSERT INTO international VALUES (282,'WebGUI','Español','Denegado');
INSERT INTO international VALUES (283,'WebGUI','Español','Pendiente');
INSERT INTO international VALUES (284,'WebGUI','Español','Estado por defecto');
INSERT INTO international VALUES (285,'WebGUI','Español','Contribuir');
INSERT INTO international VALUES (286,'WebGUI','Español','(desmarque si está escribiendo la contribución en HTML.)');
INSERT INTO international VALUES (287,'WebGUI','Español','Fecha Contribución');
INSERT INTO international VALUES (288,'WebGUI','Español','Estado');
INSERT INTO international VALUES (289,'WebGUI','Español','Editar/Eliminar');
INSERT INTO international VALUES (290,'WebGUI','Español','Sin título');
INSERT INTO international VALUES (291,'WebGUI','Español','Está seguro de querer eliminar ésta contribución?');
INSERT INTO international VALUES (292,'WebGUI','Español','Editar Sistema de Contribución de Usuarios');
INSERT INTO international VALUES (293,'WebGUI','Español','Editar Contribución');
INSERT INTO international VALUES (294,'WebGUI','Español','Nueva Contribución');
INSERT INTO international VALUES (295,'WebGUI','Español','Fecha Contribución');
INSERT INTO international VALUES (296,'WebGUI','Español','Contribuida por');
INSERT INTO international VALUES (297,'WebGUI','Español','Contribuida por:');
INSERT INTO international VALUES (298,'WebGUI','Español','Fecha Contribución:');
INSERT INTO international VALUES (299,'WebGUI','Español','Aprobar');
INSERT INTO international VALUES (300,'WebGUI','Español','Dejan pendiente');
INSERT INTO international VALUES (301,'WebGUI','Español','Denegar');
INSERT INTO international VALUES (302,'WebGUI','Español','Editar');
INSERT INTO international VALUES (303,'WebGUI','Español','Regresar a lista de contribuciones');
INSERT INTO international VALUES (304,'WebGUI','Español','Idioma');
INSERT INTO international VALUES (1,'FAQ','English','Proceed to add question?');
INSERT INTO international VALUES (5,'LinkList','English','Proceed to add link?');
INSERT INTO international VALUES (1,'EventsCalendar','English','Proceed to add event?');

update settings set value='2.3.4' where name='VERSION';

