insert into webguiVersion values ('4.6.6','upgrade',unix_timestamp());
insert into language values (10,'Dansk','ISO-8859-1');
update international set languageId=10 where languageId=0;
delete from international where languageId=2;
INSERT INTO international VALUES (13,'SQLReport',2,'Carriage Return\nbeachten?');
INSERT INTO international VALUES (13,'UserSubmission',2,'Erstellungsdatum');
INSERT INTO international VALUES (13,'WebGUI',2,'Hilfe anschauen');
INSERT INTO international VALUES (14,'Article',2,'Anhang\nherunterladen');
INSERT INTO international VALUES (14,'DownloadManager',2,'Datei');
INSERT INTO international VALUES (14,'EventsCalendar',2,'Start\nDatum');
INSERT INTO international VALUES (14,'SQLReport',2,'Später mit\nSeitenzahlen versehen');
INSERT INTO international VALUES (14,'UserSubmission',2,'Status');
INSERT INTO international VALUES (15,'Article',2,'Rechts');
INSERT INTO international VALUES (14,'WebGUI',2,'Ausstehende\nBeiträge anschauen');
INSERT INTO international VALUES (15,'DownloadManager',2,'Beschreibung');
INSERT INTO international VALUES (15,'EventsCalendar',2,'Ende\nDatum');
INSERT INTO international VALUES (15,'MessageBoard',2,'Autor');
INSERT INTO international VALUES (15,'SQLReport',2,'Sollen die\nMakros in der Abfrage vorverarbeitet werden?');
INSERT INTO international VALUES (15,'UserSubmission',2,'Bearbeiten/Löschen');
INSERT INTO international VALUES (15,'WebGUI',2,'Januar');
INSERT INTO international VALUES (16,'Article',2,'Links');
INSERT INTO international VALUES (16,'DownloadManager',2,'Upload\nDatum');
INSERT INTO international VALUES (16,'EventsCalendar',2,'Kalender\nLayout');
INSERT INTO international VALUES (16,'SQLReport',2,'debuggen?');
INSERT INTO international VALUES (16,'MessageBoard',2,'Datum');
INSERT INTO international VALUES (17,'Article',2,'Zentrum');
INSERT INTO international VALUES (16,'UserSubmission',2,'Ohne\nTitel');
INSERT INTO international VALUES (16,'WebGUI',2,'Februar');
INSERT INTO international VALUES (17,'DownloadManager',2,'Alternative #1');
INSERT INTO international VALUES (17,'EventsCalendar',2,'Liste');
INSERT INTO international VALUES (17,'MessageBoard',2,'Neuen\nBeitrag schreiben');
INSERT INTO international VALUES (17,'SQLReport',2,'<b>Debug:</b>\nAbfrage:');
INSERT INTO international VALUES (17,'UserSubmission',2,'Sind Sie\nsicher, dass Sie diesen Beitrag löschen wollen?');
INSERT INTO international VALUES (18,'Article',2,'Diskussion\nerlauben?');
INSERT INTO international VALUES (17,'WebGUI',2,'März');
INSERT INTO international VALUES (18,'EventsCalendar',2,'Kalendermonat');
INSERT INTO international VALUES (18,'DownloadManager',2,'Alternative #2');
INSERT INTO international VALUES (18,'MessageBoard',2,'Diskussion\nbegonnen');
INSERT INTO international VALUES (18,'SQLReport',2,'Diese Abfrage\nliefert keine Ergebnisse.');
INSERT INTO international VALUES (18,'UserSubmission',2,'Benutzer\nBeitragssystem bearbeiten');
INSERT INTO international VALUES (18,'WebGUI',2,'April');
INSERT INTO international VALUES (19,'DownloadManager',2,'Sie\nbesitzen keine Dateien, die zum Download bereitstehen.');
INSERT INTO international VALUES (19,'EventsCalendar',2,'Später mit\nSeitenzahlen versehen');
INSERT INTO international VALUES (19,'MessageBoard',2,'Antworten');
INSERT INTO international VALUES (19,'UserSubmission',2,'Beitrag\nbearbeiten');
INSERT INTO international VALUES (19,'WebGUI',2,'Mai');
INSERT INTO international VALUES (20,'DownloadManager',2,'Später\nmit Seitenzahlen versehen');
INSERT INTO international VALUES (20,'MessageBoard',2,'Letzte\nAntwort');
INSERT INTO international VALUES (20,'UserSubmission',2,'Neuen\nBeitrag schreiben');
INSERT INTO international VALUES (20,'WebGUI',2,'Juni');
INSERT INTO international VALUES (21,'DownloadManager',2,'Vorschaubilder anzeigen?');
INSERT INTO international VALUES (565,'WebGUI',2,'Wer kann\nmoderieren?');
INSERT INTO international VALUES (21,'UserSubmission',2,'Erstellt\nvon');
INSERT INTO international VALUES (21,'WebGUI',2,'Juli');
INSERT INTO international VALUES (22,'MessageBoard',2,'Beitrag\nlöschen');
INSERT INTO international VALUES (22,'Article',2,'Autor');
INSERT INTO international VALUES (22,'UserSubmission',2,'Erstellt\nvon:');
INSERT INTO international VALUES (22,'WebGUI',2,'August');
INSERT INTO international VALUES (23,'Article',2,'Datum');
INSERT INTO international VALUES (23,'UserSubmission',2,'Erstellungsdatum:');
INSERT INTO international VALUES (23,'WebGUI',2,'September');
INSERT INTO international VALUES (572,'WebGUI',2,'Erlauben');
INSERT INTO international VALUES (24,'Article',2,'Kommentar\nschreiben');
INSERT INTO international VALUES (24,'WebGUI',2,'Oktober');
INSERT INTO international VALUES (573,'WebGUI',2,'Ausstehend\nverlassen');
INSERT INTO international VALUES (25,'WebGUI',2,'November');
INSERT INTO international VALUES (574,'WebGUI',2,'Verbieten');
INSERT INTO international VALUES (26,'WebGUI',2,'Dezember');
INSERT INTO international VALUES (27,'Article',2,'Zurück zum\nArtikel');
INSERT INTO international VALUES (27,'UserSubmission',2,'Bearbeiten');
INSERT INTO international VALUES (27,'WebGUI',2,'Sonntag');
INSERT INTO international VALUES (28,'Article',2,'Kommentare\nanschauen');
INSERT INTO international VALUES (28,'UserSubmission',2,'Zurück zur\nBeitragsliste');
INSERT INTO international VALUES (29,'UserSubmission',2,'Benutzer\nBeitragssystem');
INSERT INTO international VALUES (28,'WebGUI',2,'Montag');
INSERT INTO international VALUES (29,'WebGUI',2,'Dienstag');
INSERT INTO international VALUES (31,'UserSubmission',2,'Inhalt');
INSERT INTO international VALUES (30,'WebGUI',2,'Mittwoch');
INSERT INTO international VALUES (31,'WebGUI',2,'Donnerstag');
INSERT INTO international VALUES (32,'UserSubmission',2,'Grafik');
INSERT INTO international VALUES (33,'UserSubmission',2,'Anhang');
INSERT INTO international VALUES (32,'WebGUI',2,'Freitag');
INSERT INTO international VALUES (33,'WebGUI',2,'Samstag');
INSERT INTO international VALUES (34,'UserSubmission',2,'Carriage\nReturn beachten?');
INSERT INTO international VALUES (34,'WebGUI',2,'Datum setzen');
INSERT INTO international VALUES (35,'UserSubmission',2,'Titel');
INSERT INTO international VALUES (35,'WebGUI',2,'Administrative\nFunktion');
INSERT INTO international VALUES (36,'WebGUI',2,'Um diese Funktion\nausführen zu können, müssen Sie Administrator sein. Eine der folgenden\nPersonen kann Sie zum Administrator machen:');
INSERT INTO international VALUES (37,'UserSubmission',2,'Löschen');
INSERT INTO international VALUES (37,'WebGUI',2,'Zugriff\nverweigert!');
INSERT INTO international VALUES (38,'WebGUI',2,'Sie sind nicht\nberechtigt, diese Aktion auszuführen. ^a(Melden Sie sich bitte mit einem\nBenutzernamen an);, der über ausreichende Rechte verfügt.');
INSERT INTO international VALUES (40,'WebGUI',2,'Notwendiger\nBestandteil');
INSERT INTO international VALUES (39,'WebGUI',2,'Sie sind nicht\nberechtigt, diese Seite anzuschauen.');
INSERT INTO international VALUES (42,'WebGUI',2,'Bitte bestätigen\nSie');
INSERT INTO international VALUES (41,'WebGUI',2,'Sie versuchen\neinen notwendigen Bestandteil des Systems zu löschen. WebGUI wird nach\ndieser Aktion möglicherweise nicht mehr richtig funktionieren.');
INSERT INTO international VALUES (43,'WebGUI',2,'Sind Sie sicher,\ndass Sie diesen Inhalt löschen möchten?');
INSERT INTO international VALUES (44,'WebGUI',2,'Ja, ich bin mir\nsicher.');
INSERT INTO international VALUES (45,'WebGUI',2,'Nein, ich habe\neinen Fehler gemacht.');
INSERT INTO international VALUES (46,'WebGUI',2,'Mein\nBenutzerkonto');
INSERT INTO international VALUES (47,'WebGUI',2,'Startseite');
INSERT INTO international VALUES (48,'WebGUI',2,'Hallo');
INSERT INTO international VALUES (50,'WebGUI',2,'Benutzername');
INSERT INTO international VALUES (52,'WebGUI',2,'Anmelden');
INSERT INTO international VALUES (49,'WebGUI',2,'Hier können Sie\nsich <a href=\"^;?op=logout\">abmelden</a>.');
INSERT INTO international VALUES (51,'WebGUI',2,'Passwort');
INSERT INTO international VALUES (53,'WebGUI',2,'Druckerbares\nFormat');
INSERT INTO international VALUES (54,'WebGUI',2,'Benutzerkonto\nanlegen');
INSERT INTO international VALUES (55,'WebGUI',2,'Passwort\n(bestätigen)');
INSERT INTO international VALUES (57,'WebGUI',2,'(Dies ist nur\nnotwendig, wenn Sie Eigenschaften benutzen möchten die eine Emailadresse\nvoraussetzen)');
INSERT INTO international VALUES (56,'WebGUI',2,'Email Adresse');
INSERT INTO international VALUES (58,'WebGUI',2,'Ich besitze\nbereits ein Benutzerkonto.');
INSERT INTO international VALUES (59,'WebGUI',2,'Ich habe mein\nPasswort vergessen');
INSERT INTO international VALUES (60,'WebGUI',2,'Sind Sie sicher,\ndass Sie dieses Benutzerkonto deaktivieren möchten? Wenn Sie fortfahren\nsind Ihre Konteninformationen endgültig verloren.');
INSERT INTO international VALUES (61,'WebGUI',2,'Benutzerkontendetails aktualisieren');
INSERT INTO international VALUES (64,'WebGUI',2,'Abmelden');
INSERT INTO international VALUES (63,'WebGUI',2,'Administrationsmodus einschalten');
INSERT INTO international VALUES (62,'WebGUI',2,'sichern');
INSERT INTO international VALUES (65,'WebGUI',2,'Benutzerkonto\nendgültig deaktivieren');
INSERT INTO international VALUES (68,'WebGUI',2,'Die\nBenutzerkontoinformationen die Sie eingegeben haben, sind ungültig.\nEntweder existiert das Konto nicht, oder die Kombination aus Benutzername\nund Passwort ist falsch.');
INSERT INTO international VALUES (67,'WebGUI',2,'Neues\nBenutzerkonto einrichten');
INSERT INTO international VALUES (66,'WebGUI',2,'Anmelden');
INSERT INTO international VALUES (69,'WebGUI',2,'Bitten Sie Ihren\nSystemadministrator um Hilfe.');
INSERT INTO international VALUES (70,'WebGUI',2,'Fehler');
INSERT INTO international VALUES (71,'WebGUI',2,'Passwort\nwiederherstellen');
INSERT INTO international VALUES (72,'WebGUI',2,'wiederherstellen');
INSERT INTO international VALUES (75,'WebGUI',2,'Ihre\nBenutzerkonteninformation wurde an Ihre Emailadresse geschickt');
INSERT INTO international VALUES (74,'WebGUI',2,'Benutzerkonteninformation');
INSERT INTO international VALUES (73,'WebGUI',2,'Anmelden');
INSERT INTO international VALUES (76,'WebGUI',2,'Ihre Emailadresse\nist nicht in unserer Datenbank.');
INSERT INTO international VALUES (77,'WebGUI',2,'Ein anderes\nMitglied dieser Seiten benutzt bereits diesen Namen. Bitte wählen Sie einen\nanderen Benutzernamen. Hier sind einige Vorschläge:');
INSERT INTO international VALUES (79,'WebGUI',2,'Verbindung zum\nLDAP-Server konnte nicht hergestellt werden.');
INSERT INTO international VALUES (78,'WebGUI',2,'Die Passworte\nunterscheiden sich. Bitte versuchen Sie es noch einmal.');
INSERT INTO international VALUES (80,'WebGUI',2,'Benutzerkonto\nwurde angelegt');
INSERT INTO international VALUES (81,'WebGUI',2,'Benutzerkonto\nwurde aktualisiert');
INSERT INTO international VALUES (82,'WebGUI',2,'Administrative\nFunktionen ...');
INSERT INTO international VALUES (84,'WebGUI',2,'Gruppenname');
INSERT INTO international VALUES (85,'WebGUI',2,'Beschreibung');
INSERT INTO international VALUES (86,'WebGUI',2,'Sind Sie sicher,\ndass Sie diese Gruppe löschen möchten? Denken Sie daran, dass diese Gruppe\nund die zugehörige Rechtesstruktur endgültig gelöscht wird.');
INSERT INTO international VALUES (87,'WebGUI',2,'Gruppe\nbearbeiten');
INSERT INTO international VALUES (88,'WebGUI',2,'Benutzer in dieser\nGruppe');
INSERT INTO international VALUES (90,'WebGUI',2,'Neue Gruppe\nhinzufügen');
INSERT INTO international VALUES (89,'WebGUI',2,'Gruppen');
INSERT INTO international VALUES (91,'WebGUI',2,'Vorherige Seite');
INSERT INTO international VALUES (92,'WebGUI',2,'Nächste Seite');
INSERT INTO international VALUES (95,'WebGUI',2,'Hilfe');
INSERT INTO international VALUES (94,'WebGUI',2,'Siehe auch');
INSERT INTO international VALUES (93,'WebGUI',2,'Hilfe');
INSERT INTO international VALUES (99,'WebGUI',2,'Titel');
INSERT INTO international VALUES (101,'WebGUI',2,'Sind Sie sicher,\ndass Sie diese Seite und ihren kompletten Inhalt darunter löschen\nmöchten?');
INSERT INTO international VALUES (100,'WebGUI',2,'Meta Tags');
INSERT INTO international VALUES (102,'WebGUI',2,'Seite\nbearbeiten');
INSERT INTO international VALUES (103,'WebGUI',2,'Seitenspezifikation');
INSERT INTO international VALUES (104,'WebGUI',2,'URL der Seite');
INSERT INTO international VALUES (106,'WebGUI',2,'Stil an alle\nnachfolgenden Seiten weitergeben.');
INSERT INTO international VALUES (105,'WebGUI',2,'Stil');
INSERT INTO international VALUES (107,'WebGUI',2,'Rechte');
INSERT INTO international VALUES (109,'WebGUI',2,'Besitzer kann\nanschauen?');
INSERT INTO international VALUES (108,'WebGUI',2,'Besitzer');
INSERT INTO international VALUES (112,'WebGUI',2,'Gruppe kann\nanschauen?');
INSERT INTO international VALUES (110,'WebGUI',2,'Besitzer kann\nbearbeiten?');
INSERT INTO international VALUES (111,'WebGUI',2,'Gruppe');
INSERT INTO international VALUES (113,'WebGUI',2,'Gruppe kann\nbearbeiten?');
INSERT INTO international VALUES (114,'WebGUI',2,'Kann jeder\nanschauen?');
INSERT INTO international VALUES (116,'WebGUI',2,'Rechte an alle\nnachfolgenden Seiten weitergeben.');
INSERT INTO international VALUES (115,'WebGUI',2,'Kann jeder\nbearbeiten?');
INSERT INTO international VALUES (118,'WebGUI',2,'anonyme\nRegistrierung');
INSERT INTO international VALUES (117,'WebGUI',2,'Authentifizierungseinstellungen bearbeiten');
INSERT INTO international VALUES (120,'WebGUI',2,'LDAP URL\n(Standard)');
INSERT INTO international VALUES (119,'WebGUI',2,'Authentifizierungsmethode (Standard)');
INSERT INTO international VALUES (121,'WebGUI',2,'LDAP Identität\n(Standard)');
INSERT INTO international VALUES (123,'WebGUI',2,'LDAP Passwort\nName');
INSERT INTO international VALUES (122,'WebGUI',2,'LDAP\nIdentitäts-Name');
INSERT INTO international VALUES (124,'WebGUI',2,'Firmeninformationen bearbeiten');
INSERT INTO international VALUES (127,'WebGUI',2,'Webseite der\nFirma');
INSERT INTO international VALUES (126,'WebGUI',2,'Emailadresse der\nFirma');
INSERT INTO international VALUES (125,'WebGUI',2,'Firmenname');
INSERT INTO international VALUES (130,'WebGUI',2,'Maximale\nDateigröße für Anhänge');
INSERT INTO international VALUES (133,'WebGUI',2,'Maileinstellungen\nbearbeiten');
INSERT INTO international VALUES (134,'WebGUI',2,'Passwortmeldung\nwiederherstellen');
INSERT INTO international VALUES (135,'WebGUI',2,'SMTP Server');
INSERT INTO international VALUES (138,'WebGUI',2,'Ja');
INSERT INTO international VALUES (139,'WebGUI',2,'Nein');
INSERT INTO international VALUES (143,'WebGUI',2,'Einstellungen\nverwalten');
INSERT INTO international VALUES (142,'WebGUI',2,'Sitzungs\nZeitüberschreitung');
INSERT INTO international VALUES (141,'WebGUI',2,'\"Nicht gefunden\nSeite\"');
INSERT INTO international VALUES (140,'WebGUI',2,'Sonstige\nEinstellungen bearbeiten');
INSERT INTO international VALUES (144,'WebGUI',2,'Auswertungen\nanschauen');
INSERT INTO international VALUES (145,'WebGUI',2,'WebGUI Build\nVersion');
INSERT INTO international VALUES (147,'WebGUI',2,'sichtbare\nSeiten');
INSERT INTO international VALUES (146,'WebGUI',2,'Aktive\nSitzungen');
INSERT INTO international VALUES (148,'WebGUI',2,'Widgets');
INSERT INTO international VALUES (149,'WebGUI',2,'Benutzer');
INSERT INTO international VALUES (151,'WebGUI',2,'Stil Name');
INSERT INTO international VALUES (154,'WebGUI',2,'Style Sheet');
INSERT INTO international VALUES (155,'WebGUI',2,'Sind Sie sicher,\ndass Sie diesen Stil löschen und alle Seiten die diesen Stil benutzen in\nden Stil \"Fail Safe\" überführen wollen?');
INSERT INTO international VALUES (156,'WebGUI',2,'Stil\nbearbeiten');
INSERT INTO international VALUES (157,'WebGUI',2,'Stile');
INSERT INTO international VALUES (159,'WebGUI',2,'Ausstehende\nBeiträge');
INSERT INTO international VALUES (158,'WebGUI',2,'Neuen Stil\nhinzufügen');
INSERT INTO international VALUES (161,'WebGUI',2,'Erstellt von');
INSERT INTO international VALUES (160,'WebGUI',2,'Erstellungsdatum');
INSERT INTO international VALUES (162,'WebGUI',2,'Sind Sie sicher,\ndass Sie alle Seiten und Widgets im Mülleimer löschen möchten?');
INSERT INTO international VALUES (163,'WebGUI',2,'Benutzer\nhinzufügen');
INSERT INTO international VALUES (164,'WebGUI',2,'Authentifizierungsmethode');
INSERT INTO international VALUES (165,'WebGUI',2,'LDAP URL');
INSERT INTO international VALUES (166,'WebGUI',2,'Connect DN');
INSERT INTO international VALUES (167,'WebGUI',2,'Sind Sie sicher,\ndass sie diesen Benutzer löschen möchten? Die Benutzerinformation geht\ndamit endgültig verloren!');
INSERT INTO international VALUES (168,'WebGUI',2,'Benutzer\nbearbeiten');
INSERT INTO international VALUES (174,'WebGUI',2,'Titel\nanzeigen?');
INSERT INTO international VALUES (170,'WebGUI',2,'suchen');
INSERT INTO international VALUES (171,'WebGUI',2,'Bearbeiten mit\nAttributen');
INSERT INTO international VALUES (169,'WebGUI',2,'Neuen Benutzer\nhinzufügen');
INSERT INTO international VALUES (228,'WebGUI',2,'Beiträge\nbearbeiten ...');
INSERT INTO international VALUES (175,'WebGUI',2,'Makros\nausführen?');
INSERT INTO international VALUES (232,'WebGUI',2,'kein Betreff');
INSERT INTO international VALUES (229,'WebGUI',2,'Betreff');
INSERT INTO international VALUES (230,'WebGUI',2,'Beitrag');
INSERT INTO international VALUES (238,'WebGUI',2,'Autor:');
INSERT INTO international VALUES (231,'WebGUI',2,'Neuen Beitrag\nschreiben...');
INSERT INTO international VALUES (237,'WebGUI',2,'Betreff:');
INSERT INTO international VALUES (234,'WebGUI',2,'Antworten...');
INSERT INTO international VALUES (233,'WebGUI',2,'(eom)');
INSERT INTO international VALUES (304,'WebGUI',2,'Sprache');
INSERT INTO international VALUES (245,'WebGUI',2,'Datum');
INSERT INTO international VALUES (240,'WebGUI',2,'Beitrags ID:');
INSERT INTO international VALUES (244,'WebGUI',2,'Autor');
INSERT INTO international VALUES (239,'WebGUI',2,'Datum:');
INSERT INTO international VALUES (306,'WebGUI',2,'Benutze LDAP\nBenutzername');
INSERT INTO international VALUES (308,'WebGUI',2,'Profil\nbearbeiten');
INSERT INTO international VALUES (307,'WebGUI',2,'Standard Meta\nTags benutzen?');
INSERT INTO international VALUES (310,'WebGUI',2,'Kontaktinformationen anzeigen?');
INSERT INTO international VALUES (309,'WebGUI',2,'Name anzeigen?');
INSERT INTO international VALUES (311,'WebGUI',2,'Privatadresse\nanzeigen?');
INSERT INTO international VALUES (312,'WebGUI',2,'Geschäftsadresse\nanzeigen?');
INSERT INTO international VALUES (313,'WebGUI',2,'Zusätzliche\nInformationen anzeigen?');
INSERT INTO international VALUES (315,'WebGUI',2,'Zweiter\nVorname');
INSERT INTO international VALUES (314,'WebGUI',2,'Vorname');
INSERT INTO international VALUES (316,'WebGUI',2,'Nachname');
INSERT INTO international VALUES (318,'WebGUI',2,'<a href=\"\"\nhttp://www.aol.com/aim/homenew.adp\"\">AIM</a> Id');
INSERT INTO international VALUES (317,'WebGUI',2,'<a href=\"\"\nhttp://www.icq.com\"\">ICQ</a> UIN');
INSERT INTO international VALUES (319,'WebGUI',2,'<a href=\"\"\nhttp://messenger.msn.com/\"\">MSN Messenger</a> Id');
INSERT INTO international VALUES (320,'WebGUI',2,'<a href=\"\"\nhttp://messenger.yahoo.com/\"\">Yahoo! Messenger</a> Id');
INSERT INTO international VALUES (322,'WebGUI',2,'Pager');
INSERT INTO international VALUES (321,'WebGUI',2,'Mobiltelefon');
INSERT INTO international VALUES (324,'WebGUI',2,'Ort (privat)');
INSERT INTO international VALUES (323,'WebGUI',2,'Strasse\n(privat)');
INSERT INTO international VALUES (325,'WebGUI',2,'Bundesland\n(privat)');
INSERT INTO international VALUES (329,'WebGUI',2,'Strasse (Büro)');
INSERT INTO international VALUES (328,'WebGUI',2,'Telefon\n(privat)');
INSERT INTO international VALUES (327,'WebGUI',2,'Land (privat)');
INSERT INTO international VALUES (326,'WebGUI',2,'Postleitzahl\n(privat)');
INSERT INTO international VALUES (332,'WebGUI',2,'Postleitzahl\n(Büro)');
INSERT INTO international VALUES (330,'WebGUI',2,'Ort (Büro)');
INSERT INTO international VALUES (331,'WebGUI',2,'Bundesland\n(Büro)');
INSERT INTO international VALUES (333,'WebGUI',2,'Land (Büro)');
INSERT INTO international VALUES (335,'WebGUI',2,'Geschlecht');
INSERT INTO international VALUES (334,'WebGUI',2,'Telefon (Büro)');
INSERT INTO international VALUES (336,'WebGUI',2,'Geburtstag');
INSERT INTO international VALUES (337,'WebGUI',2,'Homepage URL');
INSERT INTO international VALUES (339,'WebGUI',2,'männlich');
INSERT INTO international VALUES (338,'WebGUI',2,'Profil\nbearbeiten');
INSERT INTO international VALUES (343,'WebGUI',2,'Profil\nanschauen.');
INSERT INTO international VALUES (342,'WebGUI',2,'Benutzerkonto\nbearbeiten.');
INSERT INTO international VALUES (341,'WebGUI',2,'Profil\nbearbeiten.');
INSERT INTO international VALUES (340,'WebGUI',2,'weiblich');
INSERT INTO international VALUES (345,'WebGUI',2,'Kein Mitglied');
INSERT INTO international VALUES (346,'WebGUI',2,'Dieser Benutzer\nist kein Mitglied. Wir haben keine weiteren Informationen über ihn.');
INSERT INTO international VALUES (347,'WebGUI',2,'Profil anschauen\nvon');
INSERT INTO international VALUES (349,'WebGUI',2,'Aktuelle\nVersion');
INSERT INTO international VALUES (348,'WebGUI',2,'Name');
INSERT INTO international VALUES (352,'WebGUI',2,'Beitragsdatum');
INSERT INTO international VALUES (351,'WebGUI',2,'Beitragseingang');
INSERT INTO international VALUES (350,'WebGUI',2,'Abgeschlossen');
INSERT INTO international VALUES (353,'WebGUI',2,'Zur Zeit sind\nkeine ausstehenden Beiträge vorhanden.');
INSERT INTO international VALUES (355,'WebGUI',2,'Standard');
INSERT INTO international VALUES (356,'WebGUI',2,'Vorlage');
INSERT INTO international VALUES (354,'WebGUI',2,'Beitrags Log\nanschauen.');
INSERT INTO international VALUES (359,'WebGUI',2,'Rechte Spalte');
INSERT INTO international VALUES (360,'WebGUI',2,'Einer über\ndrei');
INSERT INTO international VALUES (357,'WebGUI',2,'Nachrichten');
INSERT INTO international VALUES (358,'WebGUI',2,'Linke Spalte');
INSERT INTO international VALUES (361,'WebGUI',2,'Drei über\neinem');
INSERT INTO international VALUES (362,'WebGUI',2,'Nebeneinander');
INSERT INTO international VALUES (364,'WebGUI',2,'Suchen');
INSERT INTO international VALUES (363,'WebGUI',2,'Position des\nTemplates');
INSERT INTO international VALUES (365,'WebGUI',2,'Ergebnisse der\nAbfrage');
INSERT INTO international VALUES (366,'WebGUI',2,'Es wurden keine\nSeiten gefunden, die zu Ihrer Abfrage passen.');
INSERT INTO international VALUES (367,'WebGUI',2,'verfällt nach');
INSERT INTO international VALUES (370,'WebGUI',2,'Gruppierung\nbearbeiten');
INSERT INTO international VALUES (369,'WebGUI',2,'Verfallsdatum');
INSERT INTO international VALUES (368,'WebGUI',2,'Diesem Benutzer\neine neue Gruppe hinzufügen.');
INSERT INTO international VALUES (371,'WebGUI',2,'Gruppierung\nhinzufügen');
INSERT INTO international VALUES (372,'WebGUI',2,'Gruppen eines\nBenutzers bearbeiten');
INSERT INTO international VALUES (374,'WebGUI',2,'Pakete\nanschauen');
INSERT INTO international VALUES (375,'WebGUI',2,'Paket auswählen,\ndas verteilt werden soll');
INSERT INTO international VALUES (377,'WebGUI',2,'Von Ihren (Paket)\n-Administratoren wurden keine Pakete bereitgestellt.');
INSERT INTO international VALUES (376,'WebGUI',2,'Paket');
INSERT INTO international VALUES (378,'WebGUI',2,'Benutzer ID');
INSERT INTO international VALUES (381,'WebGUI',2,'WebGUI hat eine\nverstümmelte Anfrage erhalten und kann nicht weitermachen. Üblicherweise\nwird das durch Sonderzeichen verursacht. Nutzen Sie bitte den \"Zurück\"\nButton Ihres Browsers und versuchen Sie es noch einmal.');
INSERT INTO international VALUES (380,'WebGUI',2,'Stil ID');
INSERT INTO international VALUES (379,'WebGUI',2,'Gruppen ID');
INSERT INTO international VALUES (383,'WebGUI',2,'Name');
INSERT INTO international VALUES (384,'WebGUI',2,'Datei');
INSERT INTO international VALUES (386,'WebGUI',2,'Bild\nbearbeiten');
INSERT INTO international VALUES (385,'WebGUI',2,'Parameter');
INSERT INTO international VALUES (387,'WebGUI',2,'Zur Verfügung\ngestellt von');
INSERT INTO international VALUES (388,'WebGUI',2,'Upload Datum');
INSERT INTO international VALUES (389,'WebGUI',2,'Grafik Id');
INSERT INTO international VALUES (390,'WebGUI',2,'Grafik anzeigen\n...');
INSERT INTO international VALUES (391,'WebGUI',2,'Anhang löschen');
INSERT INTO international VALUES (393,'WebGUI',2,'Grafiken\nverwalten');
INSERT INTO international VALUES (392,'WebGUI',2,'Sind Sie sicher,\ndass Sie diese Grafik löschen wollen?');
INSERT INTO international VALUES (394,'WebGUI',2,'Grafiken\nverwalten');
INSERT INTO international VALUES (577,'WebGUI',2,'Antwort\nschicken');
INSERT INTO international VALUES (13,'LinkList',2,'Neuen Link\nhinzufügen');
INSERT INTO international VALUES (13,'EventsCalendar',2,'Veranstaltung bearbeiten');
INSERT INTO international VALUES (13,'Article',2,'Löschen');
INSERT INTO international VALUES (12,'WebGUI',2,'Administrationsmodus abschalten');
INSERT INTO international VALUES (12,'UserSubmission',2,'(Bitte\nausklicken, wenn Ihr Beitrag in HTML geschrieben ist)');
INSERT INTO international VALUES (12,'SQLReport',2,'Fehler:\nDatenbankverbindung konnte nicht aufgebaut werden.');
INSERT INTO international VALUES (12,'MessageBoard',2,'Beitrag\nbearbeiten');
INSERT INTO international VALUES (12,'LinkList',2,'Link\nbearbeiten');
INSERT INTO international VALUES (12,'EventsCalendar',2,'Veranstaltungskalender bearbeiten');
INSERT INTO international VALUES (12,'DownloadManager',2,'Sind Sie\nsicher, dass Sie diesen Download löschen möchten?');
INSERT INTO international VALUES (12,'Article',2,'Artikel\nbearbeiten');
INSERT INTO international VALUES (11,'WebGUI',2,'Mülleimer\nleeren');
INSERT INTO international VALUES (11,'SQLReport',2,'Fehler: Es gab\nein Problem mit der Abfrage.');
INSERT INTO international VALUES (11,'Poll',2,'Abstimmen');
INSERT INTO international VALUES (11,'MessageBoard',2,'Zurück zur\nBeitragsliste');
INSERT INTO international VALUES (11,'DownloadManager',2,'Neuen\nDownload hinzufügen.');
INSERT INTO international VALUES (11,'Article',2,'(Bitte anklicken,\nfalls Sie nicht &lt;br&gt; in Ihrem Text hinzufügen.)');
INSERT INTO international VALUES (10,'WebGUI',2,'Mülleimer\nanschauen');
INSERT INTO international VALUES (10,'SQLReport',2,'Fehler: Das\nSQL-Statement ist im falschen Format.');
INSERT INTO international VALUES (563,'WebGUI',2,'Standard\nstatus');
INSERT INTO international VALUES (10,'Poll',2,'Abstimmung\nzurücksetzen');
INSERT INTO international VALUES (10,'LinkList',2,'Link Liste\nbearbeiten');
INSERT INTO international VALUES (10,'FAQ',2,'Frage bearbeiten');
INSERT INTO international VALUES (10,'DownloadManager',2,'Download\nbearbeiten');
INSERT INTO international VALUES (10,'Article',2,'Carriage Return\nbeachten?');
INSERT INTO international VALUES (562,'WebGUI',2,'Ausstehend');
INSERT INTO international VALUES (9,'WebGUI',2,'Zwischenablage\nanschauen');
INSERT INTO international VALUES (9,'SQLReport',2,'Fehler: Die DSN\nbesitzt das falsche Format.');
INSERT INTO international VALUES (9,'SiteMap',2,'Übersicht\nanzeigen?');
INSERT INTO international VALUES (9,'Poll',2,'Abstimmung\nbearbeiten');
INSERT INTO international VALUES (9,'MessageBoard',2,'Beitrags\nID:');
INSERT INTO international VALUES (9,'LinkList',2,'Sind Sie sicher,\ndass Sie diesen Link löschen wollen?');
INSERT INTO international VALUES (9,'FAQ',2,'Neue Frage\nhinzufügen');
INSERT INTO international VALUES (9,'EventsCalendar',2,'bis');
INSERT INTO international VALUES (9,'DownloadManager',2,'Download\nManager bearbeiten');
INSERT INTO international VALUES (9,'Article',2,'Dateianhang');
INSERT INTO international VALUES (8,'WebGUI',2,'\"Seite nicht\ngefunden\" anschauen');
INSERT INTO international VALUES (561,'WebGUI',2,'Verboten');
INSERT INTO international VALUES (8,'SQLReport',2,'SQL Bericht\nbearbeiten');
INSERT INTO international VALUES (8,'SiteMap',2,'Zeilenabstand');
INSERT INTO international VALUES (8,'Poll',2,'(Eine Antwort pro\nZeile. Bitte nicht mehr als 20 verschiedene Antworten)');
INSERT INTO international VALUES (8,'MessageBoard',2,'Datum:');
INSERT INTO international VALUES (8,'LinkList',2,'URL');
INSERT INTO international VALUES (8,'FAQ',2,'F.A.Q. bearbeiten');
INSERT INTO international VALUES (8,'EventsCalendar',2,'Wiederholt\nsich');
INSERT INTO international VALUES (8,'DownloadManager',2,'Kurze\nBeschreibung');
INSERT INTO international VALUES (7,'WebGUI',2,'Benutzer\nverwalten');
INSERT INTO international VALUES (8,'Article',2,'Link URL');
INSERT INTO international VALUES (560,'WebGUI',2,'Erlaubt');
INSERT INTO international VALUES (7,'SQLReport',2,'Datenbankpasswort');
INSERT INTO international VALUES (7,'SiteMap',2,'Kugel');
INSERT INTO international VALUES (7,'Poll',2,'Antworten');
INSERT INTO international VALUES (7,'MessageBoard',2,'Autor:');
INSERT INTO international VALUES (7,'FAQ',2,'Sind Sie sicher, dass\nSie diese Frage löschen wollen?');
INSERT INTO international VALUES (7,'DownloadManager',2,'Gruppe,\ndie Download benutzen kann');
INSERT INTO international VALUES (7,'Article',2,'Link Titel');
INSERT INTO international VALUES (6,'WebGUI',2,'Stile verwalten');
INSERT INTO international VALUES (6,'UserSubmission',2,'Beiträge\npro Seite');
INSERT INTO international VALUES (6,'SyndicatedContent',2,'Aktueller Inhalt');
INSERT INTO international VALUES (6,'SQLReport',2,'Datenbankbenutzer');
INSERT INTO international VALUES (6,'SiteMap',2,'Zweck');
INSERT INTO international VALUES (6,'MessageBoard',2,'Diskussionsforum bearbeiten');
INSERT INTO international VALUES (6,'Poll',2,'Frage');
INSERT INTO international VALUES (6,'LinkList',2,'Link Liste');
INSERT INTO international VALUES (6,'FAQ',2,'Antwort');
INSERT INTO international VALUES (6,'ExtraColumn',2,'Extra Spalte\nbearbeiten');
INSERT INTO international VALUES (701,'WebGUI',2,'Woche');
INSERT INTO international VALUES (6,'DownloadManager',2,'Dateiname');
INSERT INTO international VALUES (6,'Article',2,'Bild');
INSERT INTO international VALUES (5,'WebGUI',2,'Gruppen\nverwalten');
INSERT INTO international VALUES (5,'UserSubmission',2,'Ihr Beitrag\nwurde abgelehnt.');
INSERT INTO international VALUES (5,'SyndicatedContent',2,'zuletzt\ngeholt');
INSERT INTO international VALUES (5,'SQLReport',2,'DSN (Data Source\nName)');
INSERT INTO international VALUES (5,'SiteMap',2,'Site Map\nbearbeiten');
INSERT INTO international VALUES (5,'Poll',2,'Breite der Grafik');
INSERT INTO international VALUES (566,'WebGUI',2,'Timeout zum\nbearbeiten');
INSERT INTO international VALUES (5,'LinkList',2,'Wollen Sie einen\nLink hinzufügen?');
INSERT INTO international VALUES (5,'Item',2,'Anhang\nherunterladen');
INSERT INTO international VALUES (5,'FAQ',2,'Frage');
INSERT INTO international VALUES (5,'ExtraColumn',2,'StyleSheet\nClass');
INSERT INTO international VALUES (700,'WebGUI',2,'Tag');
INSERT INTO international VALUES (5,'DownloadManager',2,'Dateititel');
INSERT INTO international VALUES (4,'WebGUI',2,'Einstellungen\nverwalten');
INSERT INTO international VALUES (4,'UserSubmission',2,'Ihr Betrag\nwurde angenommen.');
INSERT INTO international VALUES (4,'SQLReport',2,'Abfrage');
INSERT INTO international VALUES (4,'SyndicatedContent',2,'Clipping-Dienst bearbeiten');
INSERT INTO international VALUES (4,'SiteMap',2,'Tiefe');
INSERT INTO international VALUES (4,'Poll',2,'Wer kann\nabstimmen?');
INSERT INTO international VALUES (4,'Item',2,'Kleiner Artikel');
INSERT INTO international VALUES (4,'LinkList',2,'Kugel');
INSERT INTO international VALUES (4,'MessageBoard',2,'Beiträge pro\nSeite');
INSERT INTO international VALUES (4,'ExtraColumn',2,'Breite');
INSERT INTO international VALUES (4,'EventsCalendar',2,'Einmaliges\nEreignis');
INSERT INTO international VALUES (4,'Article',2,'Ende Datum');
INSERT INTO international VALUES (3,'WebGUI',2,'Aus Zwischenablage\neinfügen...');
INSERT INTO international VALUES (3,'UserSubmission',2,'Sie sollten\neinen neuen Beitrag genehmigen.');
INSERT INTO international VALUES (3,'SQLReport',2,'Schablone');
INSERT INTO international VALUES (3,'SiteMap',2,'Auf dieser Ebene\nStarten?');
INSERT INTO international VALUES (3,'Poll',2,'Aktiv');
INSERT INTO international VALUES (564,'WebGUI',2,'Wer kann\nBeiträge schreiben?');
INSERT INTO international VALUES (3,'LinkList',2,'In neuem Fenster\nöffnen?');
INSERT INTO international VALUES (3,'Item',2,'Anhang löschen');
INSERT INTO international VALUES (3,'ExtraColumn',2,'Platzhalter');
INSERT INTO international VALUES (3,'DownloadManager',2,'Fortfahren\ndie Datei hinzuzufügen?');
INSERT INTO international VALUES (3,'Article',2,'Start Datum');
INSERT INTO international VALUES (2,'WebGUI',2,'Seite');
INSERT INTO international VALUES (2,'UserSubmission',2,'Wer kann\nBeiträge schreiben?');
INSERT INTO international VALUES (2,'SyndicatedContent',2,'Clipping-Dienst');
INSERT INTO international VALUES (2,'SiteMap',2,'Site\nMap/Übersicht');
INSERT INTO international VALUES (2,'FAQ',2,'F.A.Q.');
INSERT INTO international VALUES (2,'Item',2,'Anhang');
INSERT INTO international VALUES (2,'LinkList',2,'Zeilenabstand');
INSERT INTO international VALUES (2,'MessageBoard',2,'Diskussionsforum');
INSERT INTO international VALUES (2,'EventsCalendar',2,'Veranstaltungskalender');
INSERT INTO international VALUES (1,'WebGUI',2,'Inhalt\nhinzufügen...');
INSERT INTO international VALUES (1,'SyndicatedContent',2,'URL zur\nRSS-Datei');
INSERT INTO international VALUES (1,'UserSubmission',2,'Wer kann\ngenehmigen?');
INSERT INTO international VALUES (1,'SQLReport',2,'SQL Bericht');
INSERT INTO international VALUES (1,'Poll',2,'Abstimmung');
INSERT INTO international VALUES (1,'LinkList',2,'Tabulator');
INSERT INTO international VALUES (1,'Item',2,'Link URL');
INSERT INTO international VALUES (1,'FAQ',2,'Frage hinzufügen?');
INSERT INTO international VALUES (1,'ExtraColumn',2,'Extra\nSpalte');
INSERT INTO international VALUES (1,'EventsCalendar',2,'Termin\nhinzufügen?');
INSERT INTO international VALUES (1,'DownloadManager',2,'Download\nManager');
INSERT INTO international VALUES (1,'Article',2,'Artikel');
INSERT INTO international VALUES (395,'WebGUI',2,'Neue Grafik\nhinzufügen.');
INSERT INTO international VALUES (396,'WebGUI',2,'Grafik\nanschauen');
INSERT INTO international VALUES (397,'WebGUI',2,'Zurück zur\nGrafikübersicht.');
INSERT INTO international VALUES (398,'WebGUI',2,'Dokumententyp\nBeschreibung');
INSERT INTO international VALUES (399,'WebGUI',2,'Diese Seite\nüberprüfen.');
INSERT INTO international VALUES (400,'WebGUI',2,'Caching\nverhindern');
INSERT INTO international VALUES (401,'WebGUI',2,'Sind Sie sicher,\ndass Sie diese Nachrichten und alle darunterliegenden löschen wollen?');
INSERT INTO international VALUES (402,'WebGUI',2,'Die Nachricht die\nsie abfragen wollten existiert leider nicht.');
INSERT INTO international VALUES (403,'WebGUI',2,'Ich teile es\nlieber nicht mit.');
INSERT INTO international VALUES (404,'WebGUI',2,'Erste Seite');
INSERT INTO international VALUES (405,'WebGUI',2,'Letzte Seite');
INSERT INTO international VALUES (406,'WebGUI',2,'Größe der kleinen\nBilder');
INSERT INTO international VALUES (407,'WebGUI',2,'Klicken Sie hier,\num sich zu registrieren');
INSERT INTO international VALUES (408,'WebGUI',2,'Startseiten\nbearbeiten');
INSERT INTO international VALUES (409,'WebGUI',2,'Neue Startseite\nanlegen');
INSERT INTO international VALUES (410,'WebGUI',2,'Startseiten\nbearbeiten');
INSERT INTO international VALUES (411,'WebGUI',2,'Menü Titel');
INSERT INTO international VALUES (412,'WebGUI',2,'Synopse');
INSERT INTO international VALUES (416,'WebGUI',2,'<h1>Abfrageproblem</h1> Ihre Anfrage macht dem\nSystem Probleme. Bitte betätigen Sie den Zurückbutton im Browser und\nversuchen Sie es nochmal. Sollte dieses Problem weiterbestehen, teilen Sie\nuns bitte mit, was Sie wo im System wann gemacht haben.');
INSERT INTO international VALUES (417,'WebGUI',2,'<h1>Sicherheitsverstoß</h1> Sie haben versucht\nauf einen Systemteil zuzugreifen, der Ihnen nicht erlaubt ist. Der Verstoß\nwurde gemeldet.');
INSERT INTO international VALUES (418,'WebGUI',2,'HTML filtern');
INSERT INTO international VALUES (419,'WebGUI',2,'Alle\nBeschreibungselemente entfernen');
INSERT INTO international VALUES (420,'WebGUI',2,'Nicht\nverändern');
INSERT INTO international VALUES (421,'WebGUI',2,'Nur einfache\nFormatierungen beibehalten');
INSERT INTO international VALUES (422,'WebGUI',2,'<h1>Anmeldung ist\nfehlgeschlagen!</h1> Die eingegebenen Zugansdaten stimmen mit keinen\nBenutzerdaten überein.');
INSERT INTO international VALUES (423,'WebGUI',2,'Aktive Sitzungen\nanschauen');
INSERT INTO international VALUES (424,'WebGUI',2,'Anmeldungshistorie anschauen');
INSERT INTO international VALUES (425,'WebGUI',2,'Aktive\nSitzungen');
INSERT INTO international VALUES (426,'WebGUI',2,'Anmeldungshistorie');
INSERT INTO international VALUES (427,'WebGUI',2,'Stile');
INSERT INTO international VALUES (428,'WebGUI',2,'Benutzername');
INSERT INTO international VALUES (429,'WebGUI',2,'Anmeldungszeit');
INSERT INTO international VALUES (430,'WebGUI',2,'Seite wurde das\nletzte mal angeschaut');
INSERT INTO international VALUES (431,'WebGUI',2,'IP Adresse');
INSERT INTO international VALUES (432,'WebGUI',2,'läuft ab');
INSERT INTO international VALUES (434,'WebGUI',2,'Status');
INSERT INTO international VALUES (435,'WebGUI',2,'Sitzungssignatur');
INSERT INTO international VALUES (436,'WebGUI',2,'Sitzung\nbeenden');
INSERT INTO international VALUES (437,'WebGUI',2,'Statistiken');
INSERT INTO international VALUES (438,'WebGUI',2,'Ihr Name');
INSERT INTO international VALUES (51,'UserSubmission',2,'Bildvorschau anzeigen?');
INSERT INTO international VALUES (1,'Product',2,'Produkt');
INSERT INTO international VALUES (10,'MailForm',2,'Von');
INSERT INTO international VALUES (10,'Product',2,'Preis');
INSERT INTO international VALUES (11,'FAQ',2,'Inhaltsverzeichnis einschalten?');
INSERT INTO international VALUES (11,'MailForm',2,'senden an (Email, Benutzername oder Gruppenname)');
INSERT INTO international VALUES (11,'Product',2,'Produktnummer');
INSERT INTO international VALUES (12,'FAQ',2,'Frage/Antwort einschalten?');
INSERT INTO international VALUES (12,'MailForm',2,'Kopie');
INSERT INTO international VALUES (12,'Product',2,'Sind Sie sicher, daß Sie diese Datei löschen wollen?');
INSERT INTO international VALUES (13,'FAQ',2,'[top] Link einschalten?');
INSERT INTO international VALUES (13,'MailForm',2,'Blindkopie');
INSERT INTO international VALUES (13,'Product',2,'Broschüre');
INSERT INTO international VALUES (14,'FAQ',2,'Frage');
INSERT INTO international VALUES (14,'MailForm',2,'Betreff');
INSERT INTO international VALUES (15,'FAQ',2,'Antwort');
INSERT INTO international VALUES (15,'MailForm',2,'Mehr Felder hinzufügen?');
INSERT INTO international VALUES (15,'Product',2,'Garantie');
INSERT INTO international VALUES (16,'FAQ',2,'zum Seitenanfang');
INSERT INTO international VALUES (9,'MailForm',2,'Feld hinzufügen');
INSERT INTO international VALUES (8,'MailForm',2,'Breite');
INSERT INTO international VALUES (1,'MailForm',2,'Mail Vorlage');
INSERT INTO international VALUES (16,'MailForm',2,'Wissen');
INSERT INTO international VALUES (17,'MailForm',2,'E-mail wurde gesendet');
INSERT INTO international VALUES (463,'WebGUI',2,'Zeilen des Textfeldes');
INSERT INTO international VALUES (462,'WebGUI',2,'Zeitformat');
INSERT INTO international VALUES (461,'WebGUI',2,'Format des Datums');
INSERT INTO international VALUES (460,'WebGUI',2,'Zeitabweichung');
INSERT INTO international VALUES (46,'UserSubmission',2,'Lesen Sie mehr...');
INSERT INTO international VALUES (46,'Product',2,'Produkt (verwandt), hinzufügen oder bearbeiten');
INSERT INTO international VALUES (459,'WebGUI',2,'Das Profil dieses Benutzers bearbeiten.');
INSERT INTO international VALUES (458,'WebGUI',2,'Gruppen dieses Benuzters bearbeiten');
INSERT INTO international VALUES (457,'WebGUI',2,'Konto des Benutzers bearbeiten');
INSERT INTO international VALUES (456,'WebGUI',2,'zurück zur Benutzerübersicht');
INSERT INTO international VALUES (455,'WebGUI',2,'Profil des Benutzers bearbeiten');
INSERT INTO international VALUES (454,'WebGUI',2,'letztes Update');
INSERT INTO international VALUES (453,'WebGUI',2,'Erstelldatum');
INSERT INTO international VALUES (452,'WebGUI',2,'Bitte warten...');
INSERT INTO international VALUES (451,'WebGUI',2,'ist erforderlich.');
INSERT INTO international VALUES (450,'WebGUI',2,'Firmenname');
INSERT INTO international VALUES (45,'UserSubmission',2,'zurück zur Submission');
INSERT INTO international VALUES (449,'WebGUI',2,'sonstige Informationen');
INSERT INTO international VALUES (448,'WebGUI',2,'Baumstruktur der Seite');
INSERT INTO international VALUES (447,'WebGUI',2,'Baumstruktur der Seite verwalten');
INSERT INTO international VALUES (445,'WebGUI',2,'Präferenzen');
INSERT INTO international VALUES (444,'WebGUI',2,'demografische Informationen');
INSERT INTO international VALUES (439,'WebGUI',2,'persönliche Informationen');
INSERT INTO international VALUES (39,'UserSubmission',2,'Antwort schreiben');
INSERT INTO international VALUES (4,'MailForm',2,'unsichtbar');
INSERT INTO international VALUES (40,'Product',2,'Produkteigenschaft hinzuügen/bearbeiten');
INSERT INTO international VALUES (40,'UserSubmission',2,'aufgegeben von');
INSERT INTO international VALUES (41,'UserSubmission',2,'Datum');
INSERT INTO international VALUES (18,'MailForm',2,'Zurück!');
INSERT INTO international VALUES (21,'Product',2,'Add another related product?');
INSERT INTO international VALUES (8,'Product',2,'Produktgrafik 3');
INSERT INTO international VALUES (78,'EventsCalendar',2,'Löschen Sie nichts, ich habe einen Fehler verursacht.');
INSERT INTO international VALUES (73,'LinkList',2,'Title\r\nThe text that will be linked. \r\nURL\r\nThe web site to link to. \r\n\r\nOpen in new window?\r\nSelect yes if you\'d like this link to pop-up into a new window. \r\n\r\nDescription\r\nDescribe the site you\'re linking to. You can omit this if you\'d like. \r\n\r\nProceed to add link? If you have another link to add, select \"Yes\". \r\n');
INSERT INTO international VALUES (76,'EventsCalendar',2,'Nur dieses Ereignis löschen');
INSERT INTO international VALUES (77,'EventsCalendar',2,'Dieses Ereignis und alle Wiederholungen löschen.');
INSERT INTO international VALUES (75,'EventsCalendar',2,'Was möchten Sie gerne tun?');
INSERT INTO international VALUES (74,'EventsCalendar',2,'Kalendermonat (klein)');
INSERT INTO international VALUES (72,'Poll',2,'Antworten zufällig anordnen?');
INSERT INTO international VALUES (72,'LinkList',2,'Link hinzufügen oder bearbeiten');
INSERT INTO international VALUES (72,'FAQ',2,'Frage hinzufügen oder bearbeiten');
INSERT INTO international VALUES (72,'EventsCalendar',2,'Ereignis hinzufügen oder bearbeiten');
INSERT INTO international VALUES (72,'DownloadManager',2,'Download hinzufügen oder bearbeiten');
INSERT INTO international VALUES (717,'WebGUI',2,'Abmelden');
INSERT INTO international VALUES (716,'WebGUI',2,'Anmelden');
INSERT INTO international VALUES (715,'WebGUI',2,'Redirect URL');
INSERT INTO international VALUES (710,'WebGUI',2,'privilegierte Einstellungen bearbeiten');
INSERT INTO international VALUES (27,'Product',2,'Spezifikation');
INSERT INTO international VALUES (26,'Product',2,'Label');
INSERT INTO international VALUES (25,'Product',2,'Spezifikation bearbeiten');
INSERT INTO international VALUES (25,'MailForm',2,'Standartwert (optional)');
INSERT INTO international VALUES (24,'Product',2,'Ein weitere Eigenschaft hinzufügen?');
INSERT INTO international VALUES (2,'WobjectProxy',2,'Wobject Proxy bearbeiten');
INSERT INTO international VALUES (26,'MailForm',2,'Eintragungen speichern?');
INSERT INTO international VALUES (24,'MailForm',2,'Mögliche Werte der Drop-Down Box');
INSERT INTO international VALUES (23,'Product',2,'Eigenschaft');
INSERT INTO international VALUES (23,'MailForm',2,'Art');
INSERT INTO international VALUES (22,'Product',2,'Eigenschaft bearbeiten');
INSERT INTO international VALUES (22,'MailForm',2,'Status');
INSERT INTO international VALUES (22,'DownloadManager',2,'Einen weiteren Download hinzufügen?');
INSERT INTO international VALUES (21,'MailForm',2,'Feldname');
INSERT INTO international VALUES (21,'EventsCalendar',2,'Ein weiteres Ereignis hinzufügen?');
INSERT INTO international VALUES (20,'Product',2,'ähnliches Produkt');
INSERT INTO international VALUES (20,'MailForm',2,'Feld bearbeiten');
INSERT INTO international VALUES (2,'MailForm',2,'Hier Betreff ihrer Email eingeben');
INSERT INTO international VALUES (14,'Product',2,'Handbuch');
INSERT INTO international VALUES (20,'EventsCalendar',2,'ein Ereignis hinzufügen');
INSERT INTO international VALUES (19,'Product',2,'ähnliches produkt hinzufügen');
INSERT INTO international VALUES (19,'MailForm',2,'Sind Sie sich sicher, dass Sie dieses Feld löschen möchten?');
INSERT INTO international VALUES (520,'WebGUI',2,'Ich möchte gern per Email benachrichtigt werden.');
INSERT INTO international VALUES (52,'Product',2,'Einen weiteren Gewinn (benefit) hinzufügen?');
INSERT INTO international VALUES (519,'WebGUI',2,'Ich möchte nicht benachrichtigt werden.');
INSERT INTO international VALUES (517,'WebGUI',2,'Administrationsmodus ausschalten!');
INSERT INTO international VALUES (516,'WebGUI',2,'Administrationsmodus einschalten!');
INSERT INTO international VALUES (514,'WebGUI',2,'Ansichten (views)');
INSERT INTO international VALUES (51,'Product',2,'Gewinn (benefit)');
INSERT INTO international VALUES (508,'WebGUI',2,'Vorlagen verwalten');
INSERT INTO international VALUES (507,'WebGUI',2,'Vorlage bearbeiten');
INSERT INTO international VALUES (506,'WebGUI',2,'Vorlagen verwalten');
INSERT INTO international VALUES (505,'WebGUI',2,'neue Vorlage hinzufügen');
INSERT INTO international VALUES (504,'WebGUI',2,'Vorlage');
INSERT INTO international VALUES (503,'WebGUI',2,'ID der Vorlage');
INSERT INTO international VALUES (502,'WebGUI',2,'Sind Sie sich sicher, dass Sie diese Vorlage löschen möchten und alle Seiten, die diese Vorlage benutzen somit auf die Standartvorlage setzen?');
INSERT INTO international VALUES (500,'WebGUI',2,'ID der Seite');
INSERT INTO international VALUES (5,'Product',2,'Sind Sie sich sicher, dass Sie diese Spezifikation löschen möchten?');
INSERT INTO international VALUES (5,'MailForm',2,'Displayed');
INSERT INTO international VALUES (499,'WebGUI',2,'Wobject ID');
INSERT INTO international VALUES (498,'WebGUI',2,'Enddatum');
INSERT INTO international VALUES (497,'WebGUI',2,'Anfangsdatum');
INSERT INTO international VALUES (493,'WebGUI',2,'Zurück zur Seite.');
INSERT INTO international VALUES (49,'Product',2,'Produktgewinn (benefit) hinzufügen oder bearbeiten');
INSERT INTO international VALUES (488,'WebGUI',2,'Standartwert(e)');
INSERT INTO international VALUES (487,'WebGUI',2,'mögliche Werte');
INSERT INTO international VALUES (486,'WebGUI',2,'Datentyp');
INSERT INTO international VALUES (483,'WebGUI',2,'Ja oder Nein');
INSERT INTO international VALUES (482,'WebGUI',2,'Zahl (Integer)');
INSERT INTO international VALUES (481,'WebGUI',2,'Telefonnummer');
INSERT INTO international VALUES (480,'WebGUI',2,'Emailadresse');
INSERT INTO international VALUES (48,'UserSubmission',2,'Diskussion zulassen?');
INSERT INTO international VALUES (48,'Product',2,'Sind Sie sich sicher, dass Sie diesen Gewinn (benefit) löschen möchten? Er kann, wenn er einmal gelöscht wurde, nicht mehr wiederhergestellt werden.');
INSERT INTO international VALUES (479,'WebGUI',2,'Datum');
INSERT INTO international VALUES (478,'WebGUI',2,'URL');
INSERT INTO international VALUES (477,'WebGUI',2,'HTML Bereich');
INSERT INTO international VALUES (476,'WebGUI',2,'Textfeld');
INSERT INTO international VALUES (475,'WebGUI',2,'Text');
INSERT INTO international VALUES (474,'WebGUI',2,'Erforderlich?');
INSERT INTO international VALUES (473,'WebGUI',2,'sichtbar?');
INSERT INTO international VALUES (472,'WebGUI',2,'Label');
INSERT INTO international VALUES (471,'WebGUI',2,'Benutzerprofilfeld bearbeiten');
INSERT INTO international VALUES (470,'WebGUI',2,'Name');
INSERT INTO international VALUES (47,'UserSubmission',2,'eine Antwort schreiben');
INSERT INTO international VALUES (469,'WebGUI',2,'Id');
INSERT INTO international VALUES (467,'WebGUI',2,'Sind Sie sich sicher, dass Sie dieses Feld und alle daraufbezogenen Benutzerdaten löschen möchten?');
INSERT INTO international VALUES (466,'WebGUI',2,'Sind sie sich sicher, dass Sie diese Kategorie löschen möchten und alle ihre Felder in die Kategorie \'sonstiges\' verschieben möchten?');
INSERT INTO international VALUES (465,'WebGUI',2,'Größe der Textbox');
INSERT INTO international VALUES (464,'WebGUI',2,'Spalten des Textfeldes');
INSERT INTO international VALUES (628,'WebGUI',2,'Wenn Sie ein Bild löschen, wird es endgültig gelöscht und kann nicht mehr wiederhergestellt werden. Sie sollten sich ganz sicher sein bevor Sie bestätigen, daß ein Bild gelöscht werden kann.');
INSERT INTO international VALUES (696,'WebGUI',2,'Mülleimer leeren');
INSERT INTO international VALUES (684,'WebGUI',2,'Vorlagen hinzufügen oder bearbeiten');
INSERT INTO international VALUES (683,'WebGUI',2,'Vorlagen verwalten');
INSERT INTO international VALUES (682,'WebGUI',2,'Benutzerpofil bearbeiten');
INSERT INTO international VALUES (681,'WebGUI',2,'Packages, Creating');
INSERT INTO international VALUES (680,'WebGUI',2,'\'Package\' hinzufügen');
INSERT INTO international VALUES (686,'WebGUI',2,'Gruppe von Grafiken hinzufügen');
INSERT INTO international VALUES (679,'WebGUI',2,'inhaltliche Einstellungen bearbeiten');
INSERT INTO international VALUES (677,'WebGUI',2,'Wobject hinzufügen oder bearbeiten');
INSERT INTO international VALUES (708,'WebGUI',2,'Sondereinstellungen verwalten');
INSERT INTO international VALUES (706,'WebGUI',2,'Stunde(n)');
INSERT INTO international VALUES (707,'WebGUI',2,'Fehlersuche anzeigen?');
INSERT INTO international VALUES (699,'WebGUI',2,'Erster Tag der Woche');
INSERT INTO international VALUES (702,'WebGUI',2,'Monat(e)');
INSERT INTO international VALUES (703,'WebGUI',2,'Jahr(e)');
INSERT INTO international VALUES (704,'WebGUI',2,'Sekunde(n)');
INSERT INTO international VALUES (7,'MailForm',2,'Emailformular bearbeiten');
INSERT INTO international VALUES (685,'WebGUI',2,'Vorlage löschen');
INSERT INTO international VALUES (678,'WebGUI',2,'Hauptverzeichns verwalten');
INSERT INTO international VALUES (676,'WebGUI',2,'Grafiken verwalten');
INSERT INTO international VALUES (673,'WebGUI',2,'Grafik löschen');
INSERT INTO international VALUES (675,'WebGUI',2,'Suchmaschine benutzen');
INSERT INTO international VALUES (674,'WebGUI',2,'sonstige Einstellungen bearbeiten');
INSERT INTO international VALUES (672,'WebGUI',2,'Profileinstellungen bearbeiten');
INSERT INTO international VALUES (669,'WebGUI',2,'Makros verwenden');
INSERT INTO international VALUES (668,'WebGUI',2,'\'Style Sheets\' verwenden');
INSERT INTO international VALUES (697,'WebGUI',2,'\'Karma\' verwenden');
INSERT INTO international VALUES (670,'WebGUI',2,'Grafik hinzufügen oder bearbeiten');
INSERT INTO international VALUES (666,'WebGUI',2,'Gestaltung hinzufügen oder bearbeiten');
INSERT INTO international VALUES (665,'WebGUI',2,'Gruppe löschen');
INSERT INTO international VALUES (662,'WebGUI',2,'Einstellungen verwalten');
INSERT INTO international VALUES (663,'WebGUI',2,'Email-Einstellungen bearbeiten');
INSERT INTO international VALUES (705,'WebGUI',2,'Minute(n)');
INSERT INTO international VALUES (661,'WebGUI',2,'DateiEinstellungen bearbeiten');
INSERT INTO international VALUES (659,'WebGUI',2,'Gestaltungen verwalten');
INSERT INTO international VALUES (658,'WebGUI',2,'Benutzer verwalten');
INSERT INTO international VALUES (660,'WebGUI',2,'Gruppen verwalten');
INSERT INTO international VALUES (655,'WebGUI',2,'Benutzer hinzufügen oder bearbeiten');
INSERT INTO international VALUES (652,'WebGUI',2,'Benutzereinstelungen bearbeiten');
INSERT INTO international VALUES (671,'WebGUI',2,'Wobjects benutzen');
INSERT INTO international VALUES (657,'WebGUI',2,'Benutzer löschen');
INSERT INTO international VALUES (667,'WebGUI',2,'Gruppe hinzufügen oder bearbeiten');
INSERT INTO international VALUES (653,'WebGUI',2,'Seite löschen');
INSERT INTO international VALUES (656,'WebGUI',2,'Informationen über das Unternehemen bearbeiten');
INSERT INTO international VALUES (651,'WebGUI',2,'Falls Sie Ihren Mülleimer leeren, werden alle Posten darin unwiderruflich gelöscht. Wenn Sie sich über einige Posten nicht sicher sind, wäre es am besten, sie mittels \'ausschneiden\' in die Zwischenablage zu legen bevor Sie den Mülleimer leeren.');
INSERT INTO international VALUES (664,'WebGUI',2,'Wobject löschen');
INSERT INTO international VALUES (640,'WebGUI',2,'Es ist nicht sinnvoll Vorlagen zu löschen, da man nie weiß, welche ungünstige Auswirkung es auf die Seite haben kann (manche Seiten nutzen diese Vorlage eventuell noch). Wenn Sie eine Vorlage löschen, werden alle Seiten, die diese Vorlage noch benutzen, auf die Standardcorlage gesetzt.');
INSERT INTO international VALUES (7,'Product',2,'Produktgrafik 3');
INSERT INTO international VALUES (526,'WebGUI',2,'nur JavaScript entfernen');
INSERT INTO international VALUES (547,'WebGUI',2,'Hauptgruppe');
INSERT INTO international VALUES (552,'WebGUI',2,'Ausstehend');
INSERT INTO international VALUES (551,'WebGUI',2,'Notiz/Bemerkung');
INSERT INTO international VALUES (550,'WebGUI',2,'Gruppe von Grafiken ansehen');
INSERT INTO international VALUES (542,'WebGUI',2,'Vorhergerige(r)');
INSERT INTO international VALUES (55,'Product',2,'Gewinn (benefit) hinzufügen');
INSERT INTO international VALUES (55,'UserSubmission',2,'traditionell');
INSERT INTO international VALUES (549,'WebGUI',2,'Beschreibung der Gruppe');
INSERT INTO international VALUES (548,'WebGUI',2,'Gruppenname');
INSERT INTO international VALUES (539,'WebGUI',2,'\'Karma\' aktivieren?');
INSERT INTO international VALUES (546,'WebGUI',2,'Id der Gruppe');
INSERT INTO international VALUES (545,'WebGUI',2,'Gruppe von Grafiken bearbeiten');
INSERT INTO international VALUES (535,'WebGUI',2,'Group To Alert On New User');
INSERT INTO international VALUES (534,'WebGUI',2,'Bei neuem Benutzer benachrichtigen?');
INSERT INTO international VALUES (536,'WebGUI',2,'Ein neuer Nebutzer mit dem Namen ^@, hat die Seite betreten');
INSERT INTO international VALUES (544,'WebGUI',2,'Sind Sie sich sicher, dass Sie diese Gruppe löschen möchten?');
INSERT INTO international VALUES (543,'WebGUI',2,'neue Gruppe von Bildern hinzufügen');
INSERT INTO international VALUES (541,'WebGUI',2,'Karma Per Post');
INSERT INTO international VALUES (537,'WebGUI',2,'Karma');
INSERT INTO international VALUES (540,'WebGUI',2,'Karma Per Login');
INSERT INTO international VALUES (54,'UserSubmission',2,'Web Log');
INSERT INTO international VALUES (54,'Product',2,'Gewinne (benefits)');
INSERT INTO international VALUES (533,'WebGUI',2,'ohne die Wörter');
INSERT INTO international VALUES (525,'WebGUI',2,'inhaltliche Einstellungen bearbeiten');
INSERT INTO international VALUES (522,'WebGUI',2,'Ich möchte über ICQ benachrichtigt werden.');
INSERT INTO international VALUES (527,'WebGUI',2,'Standard Startseite');
INSERT INTO international VALUES (528,'WebGUI',2,'Name der Vorlage');
INSERT INTO international VALUES (523,'WebGUI',2,'Benachrichtigung');
INSERT INTO international VALUES (38,'Product',2,'Produkt hinzufügen oder bearbeiten');
INSERT INTO international VALUES (532,'WebGUI',2,'mit mindestens einem der Wörter');
INSERT INTO international VALUES (36,'Product',2,'Zubehör hinzufügen');
INSERT INTO international VALUES (531,'WebGUI',2,'mit genau dem Satz');
INSERT INTO international VALUES (530,'WebGUI',2,'mit all diesen Wörtern');
INSERT INTO international VALUES (433,'WebGUI',2,'Benutzeragent');
INSERT INTO international VALUES (53,'UserSubmission',2,'Layout');
INSERT INTO international VALUES (31,'Product',2,'Spezifikationen');
INSERT INTO international VALUES (53,'Product',2,'Gewinn (benefit) bearbeiten');
INSERT INTO international VALUES (30,'Product',2,'Eigenschaften');
INSERT INTO international VALUES (3,'MailForm',2,'Vielen Dank für Ihren Beitrag!');
INSERT INTO international VALUES (29,'Product',2,'Einheiten');
INSERT INTO international VALUES (28,'Product',2,'Eine weitere Spezifikation hinzufügen?');
INSERT INTO international VALUES (3,'Product',2,'Sind Sie sich sicher, dass Sie diese Eigenschaft löschen möchten?');
INSERT INTO international VALUES (382,'WebGUI',2,'Grafik bearbeiten');
INSERT INTO international VALUES (32,'Product',2,'Zubehör');
INSERT INTO international VALUES (33,'Product',2,'Verwandte Produkte');
INSERT INTO international VALUES (34,'Product',2,'Eine Eigenschaft hinzufügen');
INSERT INTO international VALUES (61,'UserSubmission',2,'Benutzerbeitragssystem hinzufügen oder bearbeiten');
INSERT INTO international VALUES (61,'SiteMap',2,'Site Map/Übersicht hinzufügen oder bearbeiten');
INSERT INTO international VALUES (61,'SQLReport',2,'SQL Bericht hinzufügen oder bearbeiten');
INSERT INTO international VALUES (61,'Product',2,'Produktvorlage');
INSERT INTO international VALUES (61,'Poll',2,'Abstimmung hinzufügen oder bearbeiten');
INSERT INTO international VALUES (61,'MessageBoard',2,'\'Diskussionsforum\' hinzufügen oder bearbeiten');
INSERT INTO international VALUES (61,'LinkList',2,'Linkliste hinzufügen oder bearbeiten');
INSERT INTO international VALUES (61,'Item',2,'Posten hinzufügen oder bearbeiten');
INSERT INTO international VALUES (61,'FAQ',2,'FAQ hinzufügen oder bearbeiten');
INSERT INTO international VALUES (61,'ExtraColumn',2,'zusätzliche Spalte hinzufügen oder bearbeiten');
INSERT INTO international VALUES (61,'EventsCalendar',2,'Ereigniskalender hinzufügen oder bearbeiten');
INSERT INTO international VALUES (61,'DownloadManager',2,'Download Manager hinzufügen/bearebiten');
INSERT INTO international VALUES (61,'Article',2,'Artikel hinzufügen oder bearbeiten');
INSERT INTO international VALUES (61,'MailForm',2,'Emailformular hinzufügen oder bearbeiten');
INSERT INTO international VALUES (60,'Product',2,'Vorlage');
INSERT INTO international VALUES (6,'Product',2,'Produkt bearbeiten');
INSERT INTO international VALUES (6,'MailForm',2,'veränderbar');
INSERT INTO international VALUES (6,'Item',2,'Posten bearbeiten');
INSERT INTO international VALUES (597,'WebGUI',2,'Übersetzung bearbeiten');
INSERT INTO international VALUES (596,'WebGUI',2,'fehlende Übersetzung');
INSERT INTO international VALUES (598,'WebGUI',2,'Sprache bearbeiten');
INSERT INTO international VALUES (594,'WebGUI',2,'Übersetzen');
INSERT INTO international VALUES (593,'WebGUI',2,'Übersetzung zu Plain Black übermitteln');
INSERT INTO international VALUES (592,'WebGUI',2,'Zeichensatz');
INSERT INTO international VALUES (591,'WebGUI',2,'Sprache');
INSERT INTO international VALUES (590,'WebGUI',2,'ID der Sprache');
INSERT INTO international VALUES (595,'WebGUI',2,'Übersetzungen');
INSERT INTO international VALUES (59,'Product',2,'Name');
INSERT INTO international VALUES (589,'WebGUI',2,'Sprache bearbeiten');
INSERT INTO international VALUES (588,'WebGUI',2,'Sind Sie sich sicher, dass Sie diese Übersetzung an Plain Black zur Einbeziehung in die Standardverteilung übermitteln wollen?\r\nWenn Sie den \'Ja\'-Link anklicken, erklären Sie sich damit einverstanden, dass Sie Plain Black eine unbeschränkte Lizenz zur Verwendung der Übersetzung in seiner Softwareverteilung geben.');
INSERT INTO international VALUES (587,'WebGUI',2,'Sind Sie sich sicher, dass Sie diese Sprache und somit auch alle damit verbundene internationale und Hilfe -Nachrichten löschen möchten?');
INSERT INTO international VALUES (586,'WebGUI',2,'Sprachen');
INSERT INTO international VALUES (585,'WebGUI',2,'Übersetzungen bearbeiten');
INSERT INTO international VALUES (584,'WebGUI',2,'Eine neue Sprache hinzufügen.');
INSERT INTO international VALUES (35,'Product',2,'Spezifikation hinzufügen');
INSERT INTO international VALUES (654,'WebGUI',2,'Gestaltung löschen');
INSERT INTO international VALUES (581,'WebGUI',2,'neuen Wert hinzufügen');
INSERT INTO international VALUES (642,'WebGUI',2,'Seite hinzufügen oder bearbeiten');
INSERT INTO international VALUES (62,'Product',2,'Produktvorlage hinzufügen oder bearbeiten');
INSERT INTO international VALUES (62,'MailForm',2,'Emailformularfelder hinzufügen oder bearbeiten');
INSERT INTO international VALUES (605,'WebGUI',2,'Gruppen hinzufügen');
INSERT INTO international VALUES (59,'UserSubmission',2,'nächster Beitrag');
INSERT INTO international VALUES (583,'WebGUI',2,'maximale Größe einer Grafik');
INSERT INTO international VALUES (582,'WebGUI',2,'freilassen');
INSERT INTO international VALUES (580,'WebGUI',2,'Ihre Nachricht wurde abgelehnt.');
INSERT INTO international VALUES (58,'UserSubmission',2,'vorheriger Beitrag');
INSERT INTO international VALUES (58,'Product',2,'Produktvorlage bearbeiten');
INSERT INTO international VALUES (579,'WebGUI',2,'Ihre Nachricht wurde akzeptiert.');
INSERT INTO international VALUES (576,'WebGUI',2,'Löschen');
INSERT INTO international VALUES (575,'WebGUI',2,'Bearbeiten');
INSERT INTO international VALUES (57,'UserSubmission',2,'Antworten');
INSERT INTO international VALUES (57,'Product',2,'Sind Sie sich sicher, dass Sie diese Vorlage löschen nud alle Produkte, die sie benutzen auf die Standardvorlage setzen möchten?');
INSERT INTO international VALUES (569,'WebGUI',2,'Moderationsart');
INSERT INTO international VALUES (56,'UserSubmission',2,'Fotogalerie');
INSERT INTO international VALUES (56,'Product',2,'Eine Produktvorlage hinzufügen.');
INSERT INTO international VALUES (557,'WebGUI',2,'Beschreibung');
INSERT INTO international VALUES (556,'WebGUI',2,'Betrag');
INSERT INTO international VALUES (553,'WebGUI',2,'Status');
INSERT INTO international VALUES (529,'WebGUI',2,'Ergebnisse');










