insert into webguiVersion values ('4.3.0','upgrade',unix_timestamp());

INSERT INTO style VALUES (-6,'WebGUI 4','<META NAME=\"Keywords\" CONTENT=\"WebGUI Content Management System\">\r\n<style>\r\n<!--\r\nbody {font-family: Arial, Helvetica, sans-serif; }\r\na:active {color: #00CCCC; text-decoration: none; background-color: #FFFFCC; }\r\na:visited {color: #003399; text-decoration: none; }\r\na:link {color: #003399; text-decoration: none; }\r\n.myAccountLink {font-weight: bold; }\r\n.verticalMenu, .tableMenu {font-family: \"Times New Roman\", Times, serif; font-style: italic; }\r\n.crumbTrail {color: #990000; font-weight: bold; }\r\nh1 {color: #990000; }\r\nh2 {color: #990000; }\r\nh3 {color: #990000; }\r\nhr {size: 2px; color: #003399;}\r\n\r\n\r\n.highlight {\r\n  background-color: #cccccc;\r\n}\r\n\r\n.tableHeader {\r\n  background-color: #eeeeee;\r\n  font-size: 13px;\r\n}\r\n\r\n.tableData {\r\n  font-size: 13px;\r\n  background-color: #fafafa;\r\n}\r\n\r\n.pollAnswer {\r\n  font-family: Helvetica, Arial;\r\n  font-size: 11px;\r\n}\r\n\r\n.pollColor {\r\n  background-color: #ae2155;\r\n  border: thin solid #000000;\r\n}\r\n\r\n.pollQuestion {\r\n  font-weight: bold;\r\n}\r\n\r\n.faqQuestion {\r\n  font-size: 12pt;\r\n  font-weight: bold;\r\n}\r\n.faqQuestion A {\r\n  text-decoration: none;\r\n  color: black;\r\n}\r\n\r\n-->\r\n</style>','<body bgcolor=\"#FFFFFF\" text=\"#000000\" leftmargin=\"0\" topmargin=\"0\">\r\n<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n<tr><!-- top row -->\r\n<td align=\"left\" valign=\"top\"><a href=\"^H(linkonly);\"><img\r\n\r\n    src=\"^Extras;styles/webgui/webgui4.jpg\"\r\n    width=\"142\"\r\n    height=\"48\"\r\n    alt=\"WebGUI\" border=\"0\"></a></td>\r\n<td valign=\"top\">^AdminBar;</td>\r\n<td align=\"right\">\r\n<a href=\"^r(linkonly);\"><img src=\"^Extras;styles/webgui/print.png\" border=\"0\" alt=\"Print!\"></a>\r\n</td>\r\n</tr><tr>\r\n</tr>\r\n</table>\r\n<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n<tr>\r\n <td colspan=\"2\" height=\"1\"\r\n     background=\"^Extras;styles/webgui/purplepixel.jpg\">\r\n </td>\r\n</tr>\r\n<tr><!-- row for username and crumbtrail -->\r\n <td width=\"120\"\r\n     height=\"20\"\r\n     align=\"left\"\r\n     valign=\"middle\"><table border=\"0\"><tr><td><strong>User:</strong>\r\n     ^a(^@;);</td></tr></table></td>\r\n <td align=\"left\"\r\n     valign=\"middle\"><strong>Location:</strong> ^C;</td>\r\n</tr>\r\n<tr>\r\n <td colspan=\"2\" height=\"1\"\r\n     background=\"^Extras;styles/webgui/purplepixel.jpg\">\r\n </td>\r\n</tr>\r\n</table>\r\n<table width=\"100%\" border=\"0\" cellspacing=\"0\" height=\"50%\" cellpadding=\"0\" align=\"center\">\r\n<tr><!-- row for verticalmenu and content -->\r\n <td width=\"120\"\r\n     align=\"left\"\r\n     valign=\"top\">\r\n   <!-- extra table -->\r\n   <table border=\"0\">\r\n   <tr><td>^FlexMenu;</td></tr>\r\n   <tr><td height=\"30\"></td></tr>\r\n   </table>\r\n   <!-- /extra table -->\r\n </td>\r\n <td align=\"left\"\r\n     valign=\"top\">\r\n\r\n\r\n^-;\r\n\r\n\r\n\r\n<p>\r\n</td>\r\n</tr>\r\n<tr>\r\n <td colspan=\"2\" height=\"1\"\r\n     background=\"^Extras;styles/webgui/purplepixel.jpg\">\r\n </td>\r\n</tr>\r\n<tr><!-- row for date, printable and WebGUI link -->\r\n <td height=\"20\"\r\n     align=\"center\">^D(\"%c %D %y\");</td><td align=\"center\">Powered by <a href=\"http://www.plainblack.com/webgui\">WebGUI</a></td>\r\n</tr>\r\n</table>\r\n</body>\r\n\r\n');

insert into language values (8,'Italiano','ISO-8859-1');
INSERT INTO international VALUES (491,'WebGUI',8,'Aggiungi un campo al profilo.');
INSERT INTO international VALUES (490,'WebGUI',8,'Aggiungi una categoria al profilo.');
INSERT INTO international VALUES (489,'WebGUI',8,'Categoria Profilo');
INSERT INTO international VALUES (488,'WebGUI',8,'Valore(i) di Default');
INSERT INTO international VALUES (487,'WebGUI',8,'Valori Possibili');
INSERT INTO international VALUES (486,'WebGUI',8,'Tipo Data');
INSERT INTO international VALUES (484,'WebGUI',8,'Seleziona Lista');
INSERT INTO international VALUES (485,'WebGUI',8,'Booleano (Checkbox)');
INSERT INTO international VALUES (483,'WebGUI',8,'Si o No');
INSERT INTO international VALUES (482,'WebGUI',8,'Numero (Intero)');
INSERT INTO international VALUES (481,'WebGUI',8,'Telefono');
INSERT INTO international VALUES (479,'WebGUI',8,'Data');
INSERT INTO international VALUES (480,'WebGUI',8,'Indirizzo Email');
INSERT INTO international VALUES (476,'WebGUI',8,'Text Area');
INSERT INTO international VALUES (477,'WebGUI',8,'HTML Area');
INSERT INTO international VALUES (478,'WebGUI',8,'URL');
INSERT INTO international VALUES (475,'WebGUI',8,'Text');
INSERT INTO international VALUES (473,'WebGUI',8,'Visibile?');
INSERT INTO international VALUES (474,'WebGUI',8,'Campo Richisto?');
INSERT INTO international VALUES (470,'WebGUI',8,'Nome');
INSERT INTO international VALUES (472,'WebGUI',8,'Etichetta');
INSERT INTO international VALUES (469,'WebGUI',8,'Id');
INSERT INTO international VALUES (468,'WebGUI',8,'Modifica categoria profilo utenti');
INSERT INTO international VALUES (467,'WebGUI',8,'Sei certo di voler cancellare questo campo e tutti i dati ad esso relativi?');
INSERT INTO international VALUES (466,'WebGUI',8,'Sei certo di voler cancellare questa categoria e spostare il suo contenuto nella categoria Varie?');
INSERT INTO international VALUES (465,'WebGUI',8,'Dimensione Text Box');
INSERT INTO international VALUES (464,'WebGUI',8,'Colonne Text Area');
INSERT INTO international VALUES (463,'WebGUI',8,'Righe Text Area');
INSERT INTO international VALUES (462,'WebGUI',8,'Formato ora');
INSERT INTO international VALUES (461,'WebGUI',8,'Formato data');
INSERT INTO international VALUES (460,'WebGUI',8,'Time Offset');
INSERT INTO international VALUES (459,'WebGUI',8,'Modifica il profilo di questo utente.');
INSERT INTO international VALUES (458,'WebGUI',8,'Modifica il gruppo di questo utente.');
INSERT INTO international VALUES (457,'WebGUI',8,'Modifica l\'account di questo utente.');
INSERT INTO international VALUES (456,'WebGUI',8,'Indietro alla lista degli utenti.');
INSERT INTO international VALUES (455,'WebGUI',8,'Modifica il profilo utente');
INSERT INTO international VALUES (454,'WebGUI',8,'Ultimo aggiornamento');
INSERT INTO international VALUES (452,'WebGUI',8,'Attendi...');
INSERT INTO international VALUES (453,'WebGUI',8,'Data di creazione');
INSERT INTO international VALUES (450,'WebGUI',8,'Professione (Azienda)');
INSERT INTO international VALUES (451,'WebGUI',8,'é richiesto.');
INSERT INTO international VALUES (448,'WebGUI',8,'Albero di Navigazione');
INSERT INTO international VALUES (449,'WebGUI',8,'Informazioni varie');
INSERT INTO international VALUES (447,'WebGUI',8,'Gestisci albero di navigazione.');
INSERT INTO international VALUES (446,'WebGUI',8,'Web Site');
INSERT INTO international VALUES (445,'WebGUI',8,'Preferenze');
INSERT INTO international VALUES (444,'WebGUI',8,'Informazioni Geografiche');
INSERT INTO international VALUES (443,'WebGUI',8,'Informazioni Tempo Libero');
INSERT INTO international VALUES (441,'WebGUI',8,'Email al Pager ');
INSERT INTO international VALUES (442,'WebGUI',8,'Informazioni Professionali');
INSERT INTO international VALUES (440,'WebGUI',8,'Contatti');
INSERT INTO international VALUES (439,'WebGUI',8,'Informazioni Personali');
INSERT INTO international VALUES (438,'WebGUI',8,'Il tuo nome');
INSERT INTO international VALUES (436,'WebGUI',8,'Uccidi Sessione');
INSERT INTO international VALUES (437,'WebGUI',8,'Statistiche');
INSERT INTO international VALUES (435,'WebGUI',8,'Firma di Sessione');
INSERT INTO international VALUES (434,'WebGUI',8,'Stato');
INSERT INTO international VALUES (433,'WebGUI',8,'User Agent');
INSERT INTO international VALUES (432,'WebGUI',8,'Scade');
INSERT INTO international VALUES (431,'WebGUI',8,'Indirizzo IP');
INSERT INTO international VALUES (430,'WebGUI',8,'Ultima pagina vista');
INSERT INTO international VALUES (429,'WebGUI',8,'Ultimo Login');
INSERT INTO international VALUES (427,'WebGUI',8,'Stili');
INSERT INTO international VALUES (428,'WebGUI',8,'Utente (ID)');
INSERT INTO international VALUES (426,'WebGUI',8,'Storico Login');
INSERT INTO international VALUES (425,'WebGUI',8,'Sessioni Attive');
INSERT INTO international VALUES (424,'WebGUI',8,'Visualizza Storico Login.');
INSERT INTO international VALUES (423,'WebGUI',8,'Visualizza Sessioni Attive.');
INSERT INTO international VALUES (422,'WebGUI',8,'<h1>Login Fallito!</h1>\r\nLe informazioni che hai provvisto non corrispondono all\'account.');
INSERT INTO international VALUES (421,'WebGUI',8,'Rimuovi tutto tranne che la formattazione basilare.');
INSERT INTO international VALUES (420,'WebGUI',8,'Lascia com\'è.');
INSERT INTO international VALUES (419,'WebGUI',8,'Rimuovi tutti i tag.');
INSERT INTO international VALUES (418,'WebGUI',8,'Filtra l\'HTML nei contributi degli utenti');
INSERT INTO international VALUES (417,'WebGUI',8,'<h1>Violazione della Sicurezza</h1>\r\nHai cercato di accedere ad un widget non associato a questa pagina. Questo incidente è stato registrato.');
INSERT INTO international VALUES (415,'WebGUI',8,'Visualizza un messaggio amichevole.');
INSERT INTO international VALUES (416,'WebGUI',8,'<h1>Problemi con la richiesta</h1>\r\nci sono stati dei problemi con la tua richiesta. Prego clicca sul bottone \"indietro\" del browser e riprova. Se questo problema persiste, contattaci specificando quello che stai tentando di fare e la data dell\'errore.');
INSERT INTO international VALUES (414,'WebGUI',8,'Visualizza informazioni di  debug.');
INSERT INTO international VALUES (28,'Article',8,'Visualizza Risposte');
INSERT INTO international VALUES (27,'Article',8,'Torna all\'articolo');
INSERT INTO international VALUES (413,'WebGUI',8,'In caso di Errore Critico');
INSERT INTO international VALUES (26,'Article',8,'Cancella Risposta');
INSERT INTO international VALUES (25,'Article',8,'Modifica Risposta');
INSERT INTO international VALUES (24,'Article',8,'Invia Risposta');
INSERT INTO international VALUES (21,'Article',8,'Modifica Timeout');
INSERT INTO international VALUES (22,'Article',8,'Autore');
INSERT INTO international VALUES (23,'Article',8,'Data');
INSERT INTO international VALUES (20,'Article',8,'Chi può moderare?');
INSERT INTO international VALUES (19,'Article',8,'Chi può postare?');
INSERT INTO international VALUES (18,'Article',8,'Consenti discussione?');
INSERT INTO international VALUES (9,'SiteMap',8,'Visualizza Descrizione?');
INSERT INTO international VALUES (411,'WebGUI',8,'Titolo nel Menu');
INSERT INTO international VALUES (412,'WebGUI',8,'Descrizione');
INSERT INTO international VALUES (410,'WebGUI',8,'Gestisci roots.');
INSERT INTO international VALUES (409,'WebGUI',8,'Aggiungi una nuova root.');
INSERT INTO international VALUES (408,'WebGUI',8,'Gestisci Roots');
INSERT INTO international VALUES (18,'SQLReport',8,'Non ci sono risultati per questa query.');
INSERT INTO international VALUES (16,'SQLReport',8,'Debug?');
INSERT INTO international VALUES (17,'SQLReport',8,'<b>Debug:</b> Query:');
INSERT INTO international VALUES (15,'SQLReport',8,'Preprocessa le macro nella query?');
INSERT INTO international VALUES (46,'WebGUI',8,'Il mio account');
INSERT INTO international VALUES (407,'WebGUI',8,'Clicca qui per registrarti.');
INSERT INTO international VALUES (21,'DownloadManager',8,'Visualizza i  thumbnails?');
INSERT INTO international VALUES (406,'WebGUI',8,'Grandezza del Thumbnail');
INSERT INTO international VALUES (405,'WebGUI',8,'Ultima Pagina');
INSERT INTO international VALUES (403,'WebGUI',8,'Preferisco non dirlo.');
INSERT INTO international VALUES (402,'WebGUI',8,'Il messaggio che hai richiesto non esiste.');
INSERT INTO international VALUES (22,'MessageBoard',8,'Cancella Messaggio');
INSERT INTO international VALUES (21,'MessageBoard',8,'Chi può moderare?');
INSERT INTO international VALUES (60,'WebGUI',8,'Sei sicuro di voler disattivare il tuo account? Se continui le informazioni del tuo account saranno perse permanentemente.');
INSERT INTO international VALUES (401,'WebGUI',8,'Sei sicuro di voler cancellare questo messaggio e tutti i messaggi sotto di esso in questo thread?');
INSERT INTO international VALUES (400,'WebGUI',8,'Impedisci la Cache del Proxy');
INSERT INTO international VALUES (399,'WebGUI',8,'Valida questa pagina.');
INSERT INTO international VALUES (398,'WebGUI',8,'Document Type Declaration');
INSERT INTO international VALUES (394,'WebGUI',8,'Gestisci Immagini.');
INSERT INTO international VALUES (395,'WebGUI',8,'Aggiungi una nuova Immagine.');
INSERT INTO international VALUES (396,'WebGUI',8,'Visualizza Immagine');
INSERT INTO international VALUES (397,'WebGUI',8,'Indietro alla lista delle Immagini.');
INSERT INTO international VALUES (393,'WebGUI',8,'Gestisci Immagini');
INSERT INTO international VALUES (391,'WebGUI',8,'Cancella il file Allegato.');
INSERT INTO international VALUES (392,'WebGUI',8,'Sei sicuro di voler cancellare questa Immagine?');
INSERT INTO international VALUES (390,'WebGUI',8,'Visualizza Immagine...');
INSERT INTO international VALUES (389,'WebGUI',8,'Id Immagine');
INSERT INTO international VALUES (387,'WebGUI',8,'Uploadato Da');
INSERT INTO international VALUES (388,'WebGUI',8,'Data di Upload');
INSERT INTO international VALUES (386,'WebGUI',8,'Modifica Immagine');
INSERT INTO international VALUES (385,'WebGUI',8,'Parametri');
INSERT INTO international VALUES (384,'WebGUI',8,'File');
INSERT INTO international VALUES (19,'EventsCalendar',8,'Cambio Pagina dopo');
INSERT INTO international VALUES (383,'WebGUI',8,'Nome');
INSERT INTO international VALUES (18,'EventsCalendar',8,'Calendario');
INSERT INTO international VALUES (16,'EventsCalendar',8,'Layout del Calendario');
INSERT INTO international VALUES (17,'EventsCalendar',8,'Lista');
INSERT INTO international VALUES (20,'DownloadManager',8,'Cambio Pagina dopo');
INSERT INTO international VALUES (14,'SQLReport',8,'Cambio Pagina dopo');
INSERT INTO international VALUES (14,'EventsCalendar',8,'Data di Inizio');
INSERT INTO international VALUES (15,'EventsCalendar',8,'Data di Fine');
INSERT INTO international VALUES (19,'DownloadManager',8,'Non hai files disponibili per il download.');
INSERT INTO international VALUES (18,'DownloadManager',8,'Versione Alternativa #2');
INSERT INTO international VALUES (17,'DownloadManager',8,'Versione Alternativa #1');
INSERT INTO international VALUES (13,'SQLReport',8,'Converti gli a capo?');
INSERT INTO international VALUES (37,'UserSubmission',8,'Cancella');
INSERT INTO international VALUES (17,'Article',8,'Centro');
INSERT INTO international VALUES (15,'Article',8,'Destra');
INSERT INTO international VALUES (16,'Article',8,'Sinistra');
INSERT INTO international VALUES (16,'DownloadManager',8,'Uploadato in Data');
INSERT INTO international VALUES (15,'DownloadManager',8,'Descrizione');
INSERT INTO international VALUES (14,'DownloadManager',8,'File');
INSERT INTO international VALUES (9,'DownloadManager',8,'Modifica Download Manager');
INSERT INTO international VALUES (10,'DownloadManager',8,'Modifica Download');
INSERT INTO international VALUES (11,'DownloadManager',8,'Aggiungi un nuovo download');
INSERT INTO international VALUES (12,'DownloadManager',8,'Sei sicuro di voler cancellare questo download?');
INSERT INTO international VALUES (8,'DownloadManager',8,'Breve Descrizione');
INSERT INTO international VALUES (7,'DownloadManager',8,'Group to Download');
INSERT INTO international VALUES (6,'DownloadManager',8,'Download File');
INSERT INTO international VALUES (3,'DownloadManager',8,'Continua aggiungendo un  file?');
INSERT INTO international VALUES (5,'DownloadManager',8,'Titolo del File');
INSERT INTO international VALUES (1,'DownloadManager',8,'Download Manager');
INSERT INTO international VALUES (380,'WebGUI',8,'ID Stile');
INSERT INTO international VALUES (381,'WebGUI',8,'Il sistema ha ricevuto un richiesta non valida. Utilizza il tasto bagk del browser e prova ancora');
INSERT INTO international VALUES (35,'UserSubmission',8,'Titolo');
INSERT INTO international VALUES (378,'WebGUI',8,'ID utente');
INSERT INTO international VALUES (379,'WebGUI',8,'ID Gruppo');
INSERT INTO international VALUES (34,'UserSubmission',8,'Converti gli a capo');
INSERT INTO international VALUES (33,'UserSubmission',8,'Allegato');
INSERT INTO international VALUES (32,'UserSubmission',8,'Immagine');
INSERT INTO international VALUES (31,'UserSubmission',8,'Contenuto');
INSERT INTO international VALUES (377,'WebGUI',8,'Nessun packages è stato definito dal tuo package manager o amministratore.');
INSERT INTO international VALUES (11,'Poll',8,'Vota!');
INSERT INTO international VALUES (374,'WebGUI',8,'Visualizza packages.');
INSERT INTO international VALUES (375,'WebGUI',8,'Seleziona Package da svolgere');
INSERT INTO international VALUES (376,'WebGUI',8,'Package');
INSERT INTO international VALUES (373,'WebGUI',8,'<b>Attenzione:</b> modificando la lista dei gruppi sottostante, si resetta ogni informazione sulla scadenza di ogni gruppo ai nuovi defaults.');
INSERT INTO international VALUES (371,'WebGUI',8,'Aggiungi Grouping');
INSERT INTO international VALUES (372,'WebGUI',8,'Modifica i gruppi dell\'utente');
INSERT INTO international VALUES (370,'WebGUI',8,'Modifica Grouping');
INSERT INTO international VALUES (369,'WebGUI',8,'Data di scadenza');
INSERT INTO international VALUES (368,'WebGUI',8,'Aggiungi un nuovo gruppo a questo utente.');
INSERT INTO international VALUES (365,'WebGUI',8,'Risultati della ricerca...');
INSERT INTO international VALUES (366,'WebGUI',8,'Non sono state trovate pagine che soddisfano la tua richiesta.');
INSERT INTO international VALUES (364,'WebGUI',8,'Cerca');
INSERT INTO international VALUES (362,'WebGUI',8,'Fianco a fianco');
INSERT INTO international VALUES (363,'WebGUI',8,'Posizione nel Template');
INSERT INTO international VALUES (361,'WebGUI',8,'Tre su Una');
INSERT INTO international VALUES (359,'WebGUI',8,'Colonna Destra');
INSERT INTO international VALUES (360,'WebGUI',8,'Una su Tre');
INSERT INTO international VALUES (358,'WebGUI',8,'Colonna Sinistra');
INSERT INTO international VALUES (357,'WebGUI',8,'News');
INSERT INTO international VALUES (356,'WebGUI',8,'Template');
INSERT INTO international VALUES (355,'WebGUI',8,'Default');
INSERT INTO international VALUES (471,'WebGUI',8,'Modifica campi profilo utenti');
INSERT INTO international VALUES (352,'WebGUI',8,'Data dell\'Elemento');
INSERT INTO international VALUES (159,'WebGUI',8,'Inbox');
INSERT INTO international VALUES (349,'WebGUI',8,'Ultima Versione Disponibile');
INSERT INTO international VALUES (351,'WebGUI',8,'Messaggio');
INSERT INTO international VALUES (350,'WebGUI',8,'Completato');
INSERT INTO international VALUES (348,'WebGUI',8,'Nome');
INSERT INTO international VALUES (347,'WebGUI',8,'Visualizza il Profilo per');
INSERT INTO international VALUES (343,'WebGUI',8,'Visualizza Profilo.');
INSERT INTO international VALUES (345,'WebGUI',8,'Non membro');
INSERT INTO international VALUES (346,'WebGUI',8,'Questo utente non è più membro del nostro sito. Non abbiamo altre informazioni su questo utente.');
INSERT INTO international VALUES (341,'WebGUI',8,'Modifica Profilo.');
INSERT INTO international VALUES (342,'WebGUI',8,'Modifica le informazioni dell\'account.');
INSERT INTO international VALUES (337,'WebGUI',8,'Homepage URL');
INSERT INTO international VALUES (338,'WebGUI',8,'Modifica  Profilo');
INSERT INTO international VALUES (339,'WebGUI',8,'Maschio');
INSERT INTO international VALUES (340,'WebGUI',8,'Femmina');
INSERT INTO international VALUES (336,'WebGUI',8,'Data di nascita');
INSERT INTO international VALUES (335,'WebGUI',8,'Genere');
INSERT INTO international VALUES (331,'WebGUI',8,'Stato lavoro');
INSERT INTO international VALUES (332,'WebGUI',8,'CAP lavoro');
INSERT INTO international VALUES (333,'WebGUI',8,'Provincia lavoro');
INSERT INTO international VALUES (334,'WebGUI',8,'Telefono lavoro');
INSERT INTO international VALUES (330,'WebGUI',8,'Città lavoro');
INSERT INTO international VALUES (329,'WebGUI',8,'Indirizzo lavoro');
INSERT INTO international VALUES (328,'WebGUI',8,'Telefono casa');
INSERT INTO international VALUES (327,'WebGUI',8,'Provincia casa');
INSERT INTO international VALUES (326,'WebGUI',8,'CAP casa');
INSERT INTO international VALUES (324,'WebGUI',8,'Città casa');
INSERT INTO international VALUES (325,'WebGUI',8,'Stato casa');
INSERT INTO international VALUES (323,'WebGUI',8,'Indirizzo casa');
INSERT INTO international VALUES (322,'WebGUI',8,'Pager');
INSERT INTO international VALUES (321,'WebGUI',8,'Telefono Cellulare');
INSERT INTO international VALUES (320,'WebGUI',8,'<a href=\"http://messenger.yahoo.com/\">Yahoo! Messenger</a> Id');
INSERT INTO international VALUES (319,'WebGUI',8,'<a href=\"http://messenger.msn.com/\">MSN Messenger</a> Id');
INSERT INTO international VALUES (318,'WebGUI',8,'<a href=\"http://www.aol.com/aim/homenew.adp\">AIM</a> Id');
INSERT INTO international VALUES (317,'WebGUI',8,'<a href=\"http://www.icq.com\">ICQ</a> UIN');
INSERT INTO international VALUES (316,'WebGUI',8,'Cognome');
INSERT INTO international VALUES (315,'WebGUI',8,'Altro Nome');
INSERT INTO international VALUES (314,'WebGUI',8,'Nome');
INSERT INTO international VALUES (313,'WebGUI',8,'Consenti informazioni varie?');
INSERT INTO international VALUES (312,'WebGUI',8,'Consenti informazioni business?');
INSERT INTO international VALUES (311,'WebGUI',8,'Consenti informazioni home?');
INSERT INTO international VALUES (310,'WebGUI',8,'Consenti informazioni extra sugli account?');
INSERT INTO international VALUES (309,'WebGUI',8,'Consenti il nome reale?');
INSERT INTO international VALUES (307,'WebGUI',8,'Usa i meta tags di default?');
INSERT INTO international VALUES (308,'WebGUI',8,'Modifica i settaggi del profilo');
INSERT INTO international VALUES (306,'WebGUI',8,'Binding del Nome Utente');
INSERT INTO international VALUES (245,'WebGUI',8,'Data');
INSERT INTO international VALUES (304,'WebGUI',8,'Lingua');
INSERT INTO international VALUES (244,'WebGUI',8,'Autore');
INSERT INTO international VALUES (239,'WebGUI',8,'Data:');
INSERT INTO international VALUES (240,'WebGUI',8,'ID Messaggio:');
INSERT INTO international VALUES (238,'WebGUI',8,'Autore:');
INSERT INTO international VALUES (237,'WebGUI',8,'Oggetto:');
INSERT INTO international VALUES (234,'WebGUI',8,'Inviare una Risposta...');
INSERT INTO international VALUES (233,'WebGUI',8,'(eom)');
INSERT INTO international VALUES (232,'WebGUI',8,'Senza Oggetto');
INSERT INTO international VALUES (231,'WebGUI',8,'Inviare un nuovo Messaggio...');
INSERT INTO international VALUES (230,'WebGUI',8,'Messaggio');
INSERT INTO international VALUES (229,'WebGUI',8,'Oggetto');
INSERT INTO international VALUES (228,'WebGUI',8,'Modifica Messaggio...');
INSERT INTO international VALUES (175,'WebGUI',8,'Processa le macro?');
INSERT INTO international VALUES (174,'WebGUI',8,'Visualizza il Titolo?');
INSERT INTO international VALUES (170,'WebGUI',8,'cerca');
INSERT INTO international VALUES (171,'WebGUI',8,'Assistente per la creazione del testo');
INSERT INTO international VALUES (169,'WebGUI',8,'Aggiungi un nuovo Utente.');
INSERT INTO international VALUES (168,'WebGUI',8,'Modifica Utente');
INSERT INTO international VALUES (167,'WebGUI',8,'Sei sicuro di voler cancellare questo utente? Sappi che tutte le informazioni associate all\'utente saranno cancellate se procedi.');
INSERT INTO international VALUES (165,'WebGUI',8,'LDAP URL');
INSERT INTO international VALUES (166,'WebGUI',8,'Connect DN');
INSERT INTO international VALUES (163,'WebGUI',8,'Aggiungi Utente');
INSERT INTO international VALUES (164,'WebGUI',8,'Metodo di autenticazione');
INSERT INTO international VALUES (162,'WebGUI',8,'Sei sicuro di voler cancellare tutte le pagine e i widgets nel cestino?');
INSERT INTO international VALUES (161,'WebGUI',8,'Inviato Da');
INSERT INTO international VALUES (160,'WebGUI',8,'Inviato in Data');
INSERT INTO international VALUES (158,'WebGUI',8,'Aggiungi un nuovo stile.');
INSERT INTO international VALUES (353,'WebGUI',8,'Non hai messaggi in Inbox attualmente.');
INSERT INTO international VALUES (157,'WebGUI',8,'Stili');
INSERT INTO international VALUES (156,'WebGUI',8,'Modifica Stile');
INSERT INTO international VALUES (155,'WebGUI',8,'Sei sicuro di voler cancellare questo stile ed assegnare a tutte le pagine che lo usano lo stile \"Fail Safe\" ?');
INSERT INTO international VALUES (151,'WebGUI',8,'Nome dello stile');
INSERT INTO international VALUES (154,'WebGUI',8,'Style Sheet');
INSERT INTO international VALUES (149,'WebGUI',8,'Utenti');
INSERT INTO international VALUES (148,'WebGUI',8,'Widgets Visualizzabili');
INSERT INTO international VALUES (147,'WebGUI',8,'Pagine Visualizzabili');
INSERT INTO international VALUES (144,'WebGUI',8,'Visualizza statistiche.');
INSERT INTO international VALUES (145,'WebGUI',8,'Versione');
INSERT INTO international VALUES (146,'WebGUI',8,'Sessioni Attive');
INSERT INTO international VALUES (143,'WebGUI',8,'Gestisci i settaggi');
INSERT INTO international VALUES (142,'WebGUI',8,'Timeout della Sessione');
INSERT INTO international VALUES (141,'WebGUI',8,'Pagina non trovata');
INSERT INTO international VALUES (140,'WebGUI',8,'Modifica settaggi vari');
INSERT INTO international VALUES (134,'WebGUI',8,'Messaggio di Recupero Password');
INSERT INTO international VALUES (135,'WebGUI',8,'SMTP Server');
INSERT INTO international VALUES (138,'WebGUI',8,'Sì');
INSERT INTO international VALUES (139,'WebGUI',8,'No');
INSERT INTO international VALUES (133,'WebGUI',8,'Modifica i settaggi della Mail');
INSERT INTO international VALUES (132,'WebGUI',8,'Percorso degli Allegati sul Server');
INSERT INTO international VALUES (130,'WebGUI',8,'Massima Dimensione Allegato');
INSERT INTO international VALUES (131,'WebGUI',8,'Percorso degli Allegati Web');
INSERT INTO international VALUES (129,'WebGUI',8,'Percorso degli Extra di WebGUI');
INSERT INTO international VALUES (128,'WebGUI',8,'Modifica i settaggi dei file');
INSERT INTO international VALUES (127,'WebGUI',8,'URL dell\'Azienda');
INSERT INTO international VALUES (126,'WebGUI',8,'Indirizzo Email dell\'Azienda');
INSERT INTO international VALUES (125,'WebGUI',8,'Nome dell\'Azienda');
INSERT INTO international VALUES (124,'WebGUI',8,'Modifica informazioni sull\'Azienda');
INSERT INTO international VALUES (123,'WebGUI',8,'LDAP Password Name');
INSERT INTO international VALUES (122,'WebGUI',8,'LDAP Identity Name');
INSERT INTO international VALUES (121,'WebGUI',8,'LDAP Identity (default)');
INSERT INTO international VALUES (120,'WebGUI',8,'LDAP URL (default)');
INSERT INTO international VALUES (118,'WebGUI',8,'Registrazione Anonima');
INSERT INTO international VALUES (119,'WebGUI',8,'Authentication Method (default)');
INSERT INTO international VALUES (117,'WebGUI',8,'Modifica settaggi Utente');
INSERT INTO international VALUES (116,'WebGUI',8,'Seleziona \"Si\" per dare a tutte le sottopagine gli stessi privilegi di questa.');
INSERT INTO international VALUES (115,'WebGUI',8,'Chiunque può modificare?');
INSERT INTO international VALUES (113,'WebGUI',8,'Il gruppo può modificare?');
INSERT INTO international VALUES (114,'WebGUI',8,'Chiunque può visualizzare?');
INSERT INTO international VALUES (112,'WebGUI',8,'Il gruppo può visualizzare?');
INSERT INTO international VALUES (111,'WebGUI',8,'Gruppo');
INSERT INTO international VALUES (110,'WebGUI',8,'Il proprietario può modificare?');
INSERT INTO international VALUES (109,'WebGUI',8,'Il proprietario può visualizzare?');
INSERT INTO international VALUES (108,'WebGUI',8,'Proprietario');
INSERT INTO international VALUES (107,'WebGUI',8,'Privilegi');
INSERT INTO international VALUES (106,'WebGUI',8,'Seleziona \"Si\" per dare a tutte le sottopagine lo stesso stile di questa.');
INSERT INTO international VALUES (105,'WebGUI',8,'Stile');
INSERT INTO international VALUES (104,'WebGUI',8,'URL della Pagina');
INSERT INTO international VALUES (102,'WebGUI',8,'Modifica Pagina');
INSERT INTO international VALUES (103,'WebGUI',8,'Specifiche della Pagina');
INSERT INTO international VALUES (101,'WebGUI',8,'Sei sicuro di voler cancellare questa pagina, il suo contenuto, e tutti gli elementi sotto di essa?');
INSERT INTO international VALUES (100,'WebGUI',8,'Meta Tags');
INSERT INTO international VALUES (99,'WebGUI',8,'Titolo');
INSERT INTO international VALUES (97,'WebGUI',8,'Ordinato per Oggetto');
INSERT INTO international VALUES (96,'WebGUI',8,'Ordinato per Azione');
INSERT INTO international VALUES (95,'WebGUI',8,'Indice Aiuto');
INSERT INTO international VALUES (94,'WebGUI',8,'Vedi anche');
INSERT INTO international VALUES (93,'WebGUI',8,'Aiuto');
INSERT INTO international VALUES (92,'WebGUI',8,'Pagina Successiva');
INSERT INTO international VALUES (91,'WebGUI',8,'Pagina Precedente');
INSERT INTO international VALUES (89,'WebGUI',8,'Gruppi');
INSERT INTO international VALUES (90,'WebGUI',8,'Aggiungi nuovo gruppo.');
INSERT INTO international VALUES (88,'WebGUI',8,'Utenti nel Gruppo');
INSERT INTO international VALUES (87,'WebGUI',8,'Modifica Gruppo');
INSERT INTO international VALUES (86,'WebGUI',8,'Sei sicuro di voler cancellare questo gruppo? Sappi che cancellare un gruppo è permanente e rimuoverà tutti i privilrgi associati a questo gruppo.');
INSERT INTO international VALUES (84,'WebGUI',8,'Nome del Gruppo');
INSERT INTO international VALUES (85,'WebGUI',8,'Corpo del testo');
INSERT INTO international VALUES (82,'WebGUI',8,'Funzioni Amministrative...');
INSERT INTO international VALUES (81,'WebGUI',8,'Account aggiornato con successo!');
INSERT INTO international VALUES (80,'WebGUI',8,'Account creato con successo!');
INSERT INTO international VALUES (79,'WebGUI',8,'Cannot connect to LDAP server.');
INSERT INTO international VALUES (78,'WebGUI',8,'Le tue password non corrispondono. Prego prova di nuovo.');
INSERT INTO international VALUES (77,'WebGUI',8,'Questo nome di account è già in uso da un altro membro di questo sito. Prego scegli un nuovo nome utente. Ecco alcuni suggerimenti:');
INSERT INTO international VALUES (76,'WebGUI',8,'Questo indirizzo di email non è nei nostri database.');
INSERT INTO international VALUES (75,'WebGUI',8,'Le Informazioni sul tuo account sono state inviate al tuo indirizzo di email.');
INSERT INTO international VALUES (74,'WebGUI',8,'Informazioni Account');
INSERT INTO international VALUES (73,'WebGUI',8,'Entra.');
INSERT INTO international VALUES (72,'WebGUI',8,'recupera');
INSERT INTO international VALUES (70,'WebGUI',8,'Errore');
INSERT INTO international VALUES (71,'WebGUI',8,'Recupera password');
INSERT INTO international VALUES (69,'WebGUI',8,'Prego contatta il tuo amministratore di sistema per assistenza.');
INSERT INTO international VALUES (68,'WebGUI',8,'Le informazioni sul\' account non sono valide. O l\'account non esiste oppure hai fornito una combinazione errata di Nome Utente/Password.');
INSERT INTO international VALUES (67,'WebGUI',8,'Crea un nuovo account.');
INSERT INTO international VALUES (66,'WebGUI',8,'Entra');
INSERT INTO international VALUES (65,'WebGUI',8,'Prego disattiva il mio account permanentemente.');
INSERT INTO international VALUES (64,'WebGUI',8,'Esci.');
INSERT INTO international VALUES (63,'WebGUI',8,'Attiva l\'Interfaccia Amministrativa.');
INSERT INTO international VALUES (62,'WebGUI',8,'Salva');
INSERT INTO international VALUES (61,'WebGUI',8,'Aggiorna Informazioni dell\'Account');
INSERT INTO international VALUES (492,'WebGUI',8,'Lista dei campi del profilo.');
INSERT INTO international VALUES (59,'WebGUI',8,'Ho dimenticato la password.');
INSERT INTO international VALUES (58,'WebGUI',8,'Ho già un account.');
INSERT INTO international VALUES (57,'WebGUI',8,'E\' necessario solo se vuoi usare funzioni che richiedono l\'email.');
INSERT INTO international VALUES (56,'WebGUI',8,'Indirizzo Email');
INSERT INTO international VALUES (55,'WebGUI',8,'Password (conferma)');
INSERT INTO international VALUES (54,'WebGUI',8,'Crea Account');
INSERT INTO international VALUES (51,'WebGUI',8,'Password');
INSERT INTO international VALUES (52,'WebGUI',8,'login');
INSERT INTO international VALUES (53,'WebGUI',8,'Rendi Pagina Stampabile');
INSERT INTO international VALUES (50,'WebGUI',8,'Nome Utente');
INSERT INTO international VALUES (48,'WebGUI',8,'Ciao');
INSERT INTO international VALUES (49,'WebGUI',8,'<br>Clicca <a href=\"^\\;?op=logout\">qui</a> per uscire.');
INSERT INTO international VALUES (47,'WebGUI',8,'Home');
INSERT INTO international VALUES (45,'WebGUI',8,'No, ho fatto uno sbaglio.');
INSERT INTO international VALUES (44,'WebGUI',8,'Sì, sono sicuro.');
INSERT INTO international VALUES (43,'WebGUI',8,'Sei sicuro di voler cancellare questo contenuto?');
INSERT INTO international VALUES (42,'WebGUI',8,'Prego Conferma');
INSERT INTO international VALUES (41,'WebGUI',8,'Hai cercato di rimuovere un componente vitale del sistema. Se continui può\r\ncessare di funzionare.');
INSERT INTO international VALUES (40,'WebGUI',8,'Componente Vitale');
INSERT INTO international VALUES (39,'WebGUI',8,'Non hai abbastanza privilegi per accedere a questa pagina.');
INSERT INTO international VALUES (38,'WebGUI',8,'Non hai abbastanza privilegi per questa operazione. Prego ^a(entra con un account); che ha sufficenti privilegi prima di eseguire questa operazione.');
INSERT INTO international VALUES (404,'WebGUI',8,'Prima Pagina');
INSERT INTO international VALUES (37,'WebGUI',8,'Permesso negato!');
INSERT INTO international VALUES (36,'WebGUI',8,'Devi essere un amministratore per usare questa funzione. Per favore contatta uno degli amministratori. Questa è una lista degli amministratori di questo sistema:');
INSERT INTO international VALUES (35,'WebGUI',8,'Funzioni Amministrative');
INSERT INTO international VALUES (34,'WebGUI',8,'imposta la data (mm/gg/aaaa)');
INSERT INTO international VALUES (33,'WebGUI',8,'Sabato');
INSERT INTO international VALUES (31,'WebGUI',8,'Giovedì');
INSERT INTO international VALUES (32,'WebGUI',8,'Venerdì');
INSERT INTO international VALUES (30,'WebGUI',8,'Mercoledì');
INSERT INTO international VALUES (29,'WebGUI',8,'Martedì');
INSERT INTO international VALUES (29,'UserSubmission',8,'Sistema di Contributi degli Utenti');
INSERT INTO international VALUES (28,'WebGUI',8,'Lunedì');
INSERT INTO international VALUES (28,'UserSubmission',8,'Ritorna alla lista dei Contributi');
INSERT INTO international VALUES (27,'WebGUI',8,'Domenica');
INSERT INTO international VALUES (27,'UserSubmission',8,'Modifica');
INSERT INTO international VALUES (26,'WebGUI',8,'Dicembre');
INSERT INTO international VALUES (26,'UserSubmission',8,'Rifiuta');
INSERT INTO international VALUES (25,'WebGUI',8,'Novembre');
INSERT INTO international VALUES (25,'UserSubmission',8,'Lascia Pendenti');
INSERT INTO international VALUES (24,'WebGUI',8,'Ottobre');
INSERT INTO international VALUES (24,'UserSubmission',8,'Approva');
INSERT INTO international VALUES (23,'WebGUI',8,'Settembre');
INSERT INTO international VALUES (23,'UserSubmission',8,'Mandato in Data:');
INSERT INTO international VALUES (22,'WebGUI',8,'Agosto');
INSERT INTO international VALUES (22,'UserSubmission',8,'Mandato da:');
INSERT INTO international VALUES (21,'WebGUI',8,'Luglio');
INSERT INTO international VALUES (21,'UserSubmission',8,'Mandato da');
INSERT INTO international VALUES (20,'WebGUI',8,'Giugno');
INSERT INTO international VALUES (20,'UserSubmission',8,'Manda un nuovo Contributo');
INSERT INTO international VALUES (19,'WebGUI',8,'Maggio');
INSERT INTO international VALUES (20,'MessageBoard',8,'Ultima Risposta');
INSERT INTO international VALUES (19,'UserSubmission',8,'Modifica Contributo');
INSERT INTO international VALUES (19,'MessageBoard',8,'Risposte');
INSERT INTO international VALUES (18,'WebGUI',8,'Aprile');
INSERT INTO international VALUES (18,'UserSubmission',8,'Modifica il sistema di contributi degli utenti');
INSERT INTO international VALUES (18,'MessageBoard',8,'Thread Iniziato');
INSERT INTO international VALUES (17,'WebGUI',8,'Marzo');
INSERT INTO international VALUES (17,'UserSubmission',8,'Sei sicuro di voler cancellare questo contributo?');
INSERT INTO international VALUES (17,'MessageBoard',8,'Manda un nuovo Messaggio');
INSERT INTO international VALUES (16,'WebGUI',8,'Febbraio');
INSERT INTO international VALUES (16,'UserSubmission',8,'Senza Titolo');
INSERT INTO international VALUES (16,'MessageBoard',8,'Data');
INSERT INTO international VALUES (15,'WebGUI',8,'Gennaio');
INSERT INTO international VALUES (15,'UserSubmission',8,'Modifica/Cancella');
INSERT INTO international VALUES (15,'MessageBoard',8,'Autore');
INSERT INTO international VALUES (14,'WebGUI',8,'Visualizza i contributi pendenti.');
INSERT INTO international VALUES (14,'UserSubmission',8,'Stato');
INSERT INTO international VALUES (14,'Article',8,'Allinea Immagine');
INSERT INTO international VALUES (13,'WebGUI',8,'Visualizza indice dell\'aiuto.');
INSERT INTO international VALUES (13,'UserSubmission',8,'Data');
INSERT INTO international VALUES (13,'MessageBoard',8,'Rispondi');
INSERT INTO international VALUES (13,'LinkList',8,'Aggiungi un nuovo link.');
INSERT INTO international VALUES (13,'EventsCalendar',8,'Modifica Evento');
INSERT INTO international VALUES (13,'Article',8,'Cancella');
INSERT INTO international VALUES (12,'WebGUI',8,'Spegni interfaccia amministrativa.');
INSERT INTO international VALUES (12,'UserSubmission',8,'(deseleziona se scrivi in HTML)');
INSERT INTO international VALUES (12,'EventsCalendar',8,'Modifica Calendario Eventi');
INSERT INTO international VALUES (12,'LinkList',8,'Modifica Link');
INSERT INTO international VALUES (12,'MessageBoard',8,'Modifica Messaggio');
INSERT INTO international VALUES (12,'SQLReport',8,'Error: Could not connect to the database.');
INSERT INTO international VALUES (11,'WebGUI',8,'Svuota il cestino');
INSERT INTO international VALUES (12,'Article',8,'Modifica Articolo');
INSERT INTO international VALUES (11,'SQLReport',8,'<b>Debug:</b> Errore: c\'è stato un problema con la query.');
INSERT INTO international VALUES (11,'MessageBoard',8,'Torna alla lista dei messaggi');
INSERT INTO international VALUES (11,'EventsCalendar',8,'Metti in grassetto le ricorrenze');
INSERT INTO international VALUES (11,'Article',8,'(Seleziona \"Si\" solo se non hai aggiunto &lt;br&gt; manualmente.)');
INSERT INTO international VALUES (10,'WebGUI',8,'Visualizza il cestino.');
INSERT INTO international VALUES (10,'UserSubmission',8,'Stato predefinito');
INSERT INTO international VALUES (10,'SQLReport',8,'Error: The SQL specified is of an improper format.');
INSERT INTO international VALUES (10,'Poll',8,'Azzera i voti.');
INSERT INTO international VALUES (10,'LinkList',8,'Modifica Lista di Link');
INSERT INTO international VALUES (10,'FAQ',8,'Modifica Domanda');
INSERT INTO international VALUES (10,'EventsCalendar',8,'Sei sicuro di voler cancellare questo evento');
INSERT INTO international VALUES (10,'Article',8,'Converti gli \'a capo\'?');
INSERT INTO international VALUES (9,'WebGUI',8,'Visualizza appunti.');
INSERT INTO international VALUES (9,'UserSubmission',8,'Pendente');
INSERT INTO international VALUES (9,'SQLReport',8,'Error: The DSN specified is of an improper format.');
INSERT INTO international VALUES (9,'Poll',8,'Modifica Sondaggio');
INSERT INTO international VALUES (9,'MessageBoard',8,'ID Messaggio:');
INSERT INTO international VALUES (9,'LinkList',8,'Sei sicuro di voler cancellare questo link?');
INSERT INTO international VALUES (9,'FAQ',8,'Aggiungi una nuova domanda.');
INSERT INTO international VALUES (9,'EventsCalendar',8,'finché');
INSERT INTO international VALUES (9,'Article',8,'Allegato');
INSERT INTO international VALUES (8,'WebGUI',8,'Visualizza pagina non trovata.');
INSERT INTO international VALUES (8,'UserSubmission',8,'Respinto');
INSERT INTO international VALUES (8,'SQLReport',8,'Modifica SQL Report');
INSERT INTO international VALUES (8,'SiteMap',8,'Spaziatura di linea');
INSERT INTO international VALUES (8,'Poll',8,'(Aggiungi una risposta per linea. Non più di 20)');
INSERT INTO international VALUES (8,'MessageBoard',8,'Data:');
INSERT INTO international VALUES (8,'LinkList',8,'URL');
INSERT INTO international VALUES (8,'FAQ',8,'Modifica F.A.Q.');
INSERT INTO international VALUES (8,'EventsCalendar',8,'Ricorre ogni');
INSERT INTO international VALUES (8,'Article',8,'URL del Link');
INSERT INTO international VALUES (7,'WebGUI',8,'Gestisci gli utenti.');
INSERT INTO international VALUES (7,'SQLReport',8,'Password Database');
INSERT INTO international VALUES (7,'UserSubmission',8,'Approvato');
INSERT INTO international VALUES (7,'SiteMap',8,'Bullet');
INSERT INTO international VALUES (7,'Poll',8,'Risposte');
INSERT INTO international VALUES (7,'MessageBoard',8,'Autore:');
INSERT INTO international VALUES (7,'FAQ',8,'Sei sicuro di voler cancellare questa domanda?');
INSERT INTO international VALUES (7,'Article',8,'Titolo del link');
INSERT INTO international VALUES (6,'WebGUI',8,'Gestisci gli stili.');
INSERT INTO international VALUES (6,'UserSubmission',8,'Contributi per pagina');
INSERT INTO international VALUES (6,'SyndicatedContent',8,'Contenuto Attuale');
INSERT INTO international VALUES (6,'SQLReport',8,'Utente Database');
INSERT INTO international VALUES (6,'SiteMap',8,'Rientro');
INSERT INTO international VALUES (6,'Poll',8,'Domanda');
INSERT INTO international VALUES (6,'MessageBoard',8,'Modifica Forum');
INSERT INTO international VALUES (6,'LinkList',8,'Lista di Link');
INSERT INTO international VALUES (6,'FAQ',8,'Risposta');
INSERT INTO international VALUES (6,'ExtraColumn',8,'Modifica Colonna Extra');
INSERT INTO international VALUES (6,'EventsCalendar',8,'Settimana');
INSERT INTO international VALUES (6,'Article',8,'Immagine');
INSERT INTO international VALUES (5,'WebGUI',8,'Gestisci i gruppi.');
INSERT INTO international VALUES (5,'UserSubmission',8,'Il tuo contributo è stato respinto.');
INSERT INTO international VALUES (5,'SyndicatedContent',8,'Ultimo preso');
INSERT INTO international VALUES (5,'SQLReport',8,'DSN');
INSERT INTO international VALUES (5,'SiteMap',8,'Modifica la mappa del sito');
INSERT INTO international VALUES (5,'Poll',8,'Larghezza del grafico');
INSERT INTO international VALUES (5,'MessageBoard',8,'Modifica Timeout');
INSERT INTO international VALUES (5,'LinkList',8,'Continua aggiungendo un link?');
INSERT INTO international VALUES (5,'ExtraColumn',8,'StyleSheet Class');
INSERT INTO international VALUES (5,'FAQ',8,'Domanda');
INSERT INTO international VALUES (5,'Item',8,'Scarica allegato');
INSERT INTO international VALUES (5,'EventsCalendar',8,'Giorno');
INSERT INTO international VALUES (4,'WebGUI',8,'Gestisci i settaggi.');
INSERT INTO international VALUES (4,'UserSubmission',8,'Il tuo contributo è stato approvato.');
INSERT INTO international VALUES (4,'SyndicatedContent',8,'Modifica Contenuto di altri siti');
INSERT INTO international VALUES (4,'SQLReport',8,'Query');
INSERT INTO international VALUES (4,'SiteMap',8,'Profondità');
INSERT INTO international VALUES (4,'Poll',8,'Chi può votare?');
INSERT INTO international VALUES (4,'MessageBoard',8,'Messaggi Per Pagina');
INSERT INTO international VALUES (4,'LinkList',8,'Bullet');
INSERT INTO international VALUES (4,'Item',8,'Item');
INSERT INTO international VALUES (4,'ExtraColumn',8,'Larghezza');
INSERT INTO international VALUES (4,'EventsCalendar',8,'Accade solo una volta.');
INSERT INTO international VALUES (4,'Article',8,'Data di fine');
INSERT INTO international VALUES (3,'WebGUI',8,'Incolla dagli appunti...');
INSERT INTO international VALUES (3,'UserSubmission',8,'Hai nuovi contenuti degli utenti da approvare.');
INSERT INTO international VALUES (3,'SQLReport',8,'Template');
INSERT INTO international VALUES (3,'SiteMap',8,'Partire da questo livello?');
INSERT INTO international VALUES (3,'Poll',8,'Attivo');
INSERT INTO international VALUES (3,'MessageBoard',8,'Chi può postare?');
INSERT INTO international VALUES (3,'LinkList',8,'Apri in nuova finestra?');
INSERT INTO international VALUES (3,'Item',8,'Cancella allegato');
INSERT INTO international VALUES (3,'ExtraColumn',8,'Spaziatore');
INSERT INTO international VALUES (3,'Article',8,'Data di inizio');
INSERT INTO international VALUES (2,'WebGUI',8,'Pagina');
INSERT INTO international VALUES (2,'UserSubmission',8,'Chi può contribuire?');
INSERT INTO international VALUES (2,'SyndicatedContent',8,'Contenuto da altri siti');
INSERT INTO international VALUES (2,'SiteMap',8,'Mappa del sito');
INSERT INTO international VALUES (2,'MessageBoard',8,'Forum');
INSERT INTO international VALUES (2,'LinkList',8,'Spaziatura di linea');
INSERT INTO international VALUES (2,'Item',8,'Allegato');
INSERT INTO international VALUES (2,'FAQ',8,'F.A.Q.');
INSERT INTO international VALUES (2,'EventsCalendar',8,'Calendario Eventi');
INSERT INTO international VALUES (1,'WebGUI',8,'Aggiungi contenuto...');
INSERT INTO international VALUES (1,'UserSubmission',8,'Chi può approvare?');
INSERT INTO international VALUES (1,'SyndicatedContent',8,'URL del file RSS');
INSERT INTO international VALUES (1,'SQLReport',8,'SQL Report');
INSERT INTO international VALUES (1,'Poll',8,'Sondaggio');
INSERT INTO international VALUES (1,'LinkList',8,'Indentazione');
INSERT INTO international VALUES (1,'Item',8,'URL del link');
INSERT INTO international VALUES (1,'FAQ',8,'Continua aggiungendo una domanda?');
INSERT INTO international VALUES (1,'ExtraColumn',8,'Colonna Extra');
INSERT INTO international VALUES (1,'EventsCalendar',8,'Continua aggiungendo un evento?');
INSERT INTO international VALUES (1,'Article',8,'Articolo');
INSERT INTO international VALUES (367,'WebGUI',8,'Scade dopo');
INSERT INTO international VALUES (493,'WebGUI',8,'Torna al sito.');
INSERT INTO international VALUES (495,'WebGUI',8,'Assistente creazione del testo');
INSERT INTO international VALUES (496,'WebGUI',8,'Editor da utilizzare');
INSERT INTO international VALUES (494,'WebGUI',8,'Real Objects Edit-On Pro');
INSERT INTO international VALUES (497,'WebGUI',8,'Data di pubblicazione');
INSERT INTO international VALUES (498,'WebGUI',8,'Data di oscuramento');
INSERT INTO international VALUES (499,'WebGUI',8,'Wobject ID');
INSERT INTO international VALUES (22,'DownloadManager',8,'Continua aggiungendo un download?');
INSERT INTO international VALUES (21,'EventsCalendar',8,'Continua aggiungendo un evento?');
INSERT INTO international VALUES (20,'EventsCalendar',8,'Aggiungi un evento.');
INSERT INTO international VALUES (38,'UserSubmission',8,'(Seleziona \"No\" solo se hai usato l\'assistente per la creazione del testo.)');
INSERT INTO international VALUES (500,'WebGUI',8,'ID pagina');
INSERT INTO international VALUES (501,'WebGUI',8,'Body');
INSERT INTO international VALUES (502,'WebGUI',8,'Sei sicuro di voler cancellare questo template e attribuire a tutte le pagine che lo usano il template di default?');
INSERT INTO international VALUES (503,'WebGUI',8,'Template ID');
INSERT INTO international VALUES (504,'WebGUI',8,'Template');
INSERT INTO international VALUES (505,'WebGUI',8,'Aggiungi un nuovo template.');
INSERT INTO international VALUES (506,'WebGUI',8,'Gestisci i Templates');
INSERT INTO international VALUES (507,'WebGUI',8,'Modifica Template');
INSERT INTO international VALUES (508,'WebGUI',8,'Gestisci templates.');
INSERT INTO international VALUES (39,'UserSubmission',8,'Rispondi');
INSERT INTO international VALUES (40,'UserSubmission',8,'Inviato da');
INSERT INTO international VALUES (41,'UserSubmission',8,'Data');
INSERT INTO international VALUES (42,'UserSubmission',8,'Modifica Risposta');
INSERT INTO international VALUES (43,'UserSubmission',8,'Cancella Risposta');
INSERT INTO international VALUES (45,'UserSubmission',8,'Torna ad invio');
INSERT INTO international VALUES (46,'UserSubmission',8,'Leggi di piu\'...');
INSERT INTO international VALUES (47,'UserSubmission',8,'Rispondi');
INSERT INTO international VALUES (48,'UserSubmission',8,'Consenti Discussioni?');
INSERT INTO international VALUES (49,'UserSubmission',8,'Modifica il Timeout');
INSERT INTO international VALUES (50,'UserSubmission',8,'Chi può postare');
INSERT INTO international VALUES (44,'UserSubmission',8,'Chi può Moderare');
INSERT INTO international VALUES (51,'UserSubmission',8,'Visualizza thumbnails?');
INSERT INTO international VALUES (52,'UserSubmission',8,'Thumbnail');
INSERT INTO international VALUES (53,'UserSubmission',8,'Layout');
INSERT INTO international VALUES (54,'UserSubmission',8,'Web Log');
INSERT INTO international VALUES (55,'UserSubmission',8,'Tradizionale');
INSERT INTO international VALUES (56,'UserSubmission',8,'Photo Gallery');
INSERT INTO international VALUES (57,'UserSubmission',8,'Risposte');
INSERT INTO international VALUES (11,'FAQ',8,'Attiva elenco domande con link?');
INSERT INTO international VALUES (12,'FAQ',8,'Attiva D/R ?');
INSERT INTO international VALUES (13,'FAQ',8,'Attiva [top] link?');
INSERT INTO international VALUES (14,'FAQ',8,'D');
INSERT INTO international VALUES (15,'FAQ',8,'R');
INSERT INTO international VALUES (16,'FAQ',8,'[top]');
INSERT INTO international VALUES (509,'WebGUI',8,'Layout Discussioni');
INSERT INTO international VALUES (510,'WebGUI',8,'Flat');
INSERT INTO international VALUES (511,'WebGUI',8,'Threaded');
INSERT INTO international VALUES (512,'WebGUI',8,'Prossimo Thread');
INSERT INTO international VALUES (513,'WebGUI',8,'Thread Precedente');
INSERT INTO international VALUES (514,'WebGUI',8,'Visto');
INSERT INTO international VALUES (515,'WebGUI',8,'Aggiungi la data di modifica nei posts?');
INSERT INTO international VALUES (517,'WebGUI',8,'Spegni Admin!');
INSERT INTO international VALUES (516,'WebGUI',8,'Attiva Admin!');
INSERT INTO international VALUES (518,'WebGUI',8,'Inbox Notifiche');
INSERT INTO international VALUES (519,'WebGUI',8,'Non voglio ricevere notifiche.');
INSERT INTO international VALUES (520,'WebGUI',8,'Voglio ricevere notifiche via email.');
INSERT INTO international VALUES (521,'WebGUI',8,'Voglio ricevere notifiche via email al pager.');
INSERT INTO international VALUES (522,'WebGUI',8,'Voglio ricevere notifiche via ICQ.');
INSERT INTO international VALUES (523,'WebGUI',8,'Notification');
INSERT INTO international VALUES (524,'WebGUI',8,'Aggiungi la data di modifica nei post?');
INSERT INTO international VALUES (525,'WebGUI',8,'Modifica Settaggi Contenuti');
INSERT INTO international VALUES (526,'WebGUI',8,'Filtra solo JavaScript.');
INSERT INTO international VALUES (527,'WebGUI',8,'Home Page di default');
INSERT INTO international VALUES (354,'WebGUI',8,'Visualizza Inbox.');
INSERT INTO international VALUES (528,'WebGUI',8,'Nome Template');
INSERT INTO international VALUES (529,'WebGUI',8,'Risultati');
INSERT INTO international VALUES (530,'WebGUI',8,'con <b>tutte</b> le parole');
INSERT INTO international VALUES (531,'WebGUI',8,'con la <b>frase esatta</b>');
INSERT INTO international VALUES (532,'WebGUI',8,'con <b>almeno</b> queste parole');
INSERT INTO international VALUES (533,'WebGUI',8,'<b>senza</b> le parole');
INSERT INTO international VALUES (535,'WebGUI',8,'Gruppo a cui notificare un nuovo utente');
INSERT INTO international VALUES (534,'WebGUI',8,'Notifica quando si iscrive un nuovo utente?');
INSERT INTO international VALUES (536,'WebGUI',8,'Il nuovo utente ^@; si è iscritto al sito.');
INSERT INTO international VALUES (537,'WebGUI',8,'Karma');
INSERT INTO international VALUES (538,'WebGUI',8,'Soglia del Karma');
INSERT INTO international VALUES (539,'WebGUI',8,'Abilita Karma?');
INSERT INTO international VALUES (540,'WebGUI',8,'Karma Per Login');
INSERT INTO international VALUES (20,'Poll',8,'Karma Per Voto');
INSERT INTO international VALUES (541,'WebGUI',8,'Karma Per Post');
INSERT INTO international VALUES (30,'UserSubmission',8,'Karma Per Contributo');
INSERT INTO international VALUES (542,'WebGUI',8,'Precedente..');
INSERT INTO international VALUES (543,'WebGUI',8,'Aggiungi un nuovo gruppo');
INSERT INTO international VALUES (544,'WebGUI',8,'Sei sicuro di voler cancellare questo gruppo?');
INSERT INTO international VALUES (545,'WebGUI',8,'Modifica i Gruppi di Immagini');
INSERT INTO international VALUES (546,'WebGUI',8,'Id Gruppo');
INSERT INTO international VALUES (547,'WebGUI',8,'Gruppo Genitore');
INSERT INTO international VALUES (548,'WebGUI',8,'Nome del Gruppo');
INSERT INTO international VALUES (549,'WebGUI',8,'Descrizione del Gruppo');
INSERT INTO international VALUES (550,'WebGUI',8,'Visualizza Gruppo di Immagini');
INSERT INTO international VALUES (382,'WebGUI',8,'Modifica Immagine');
INSERT INTO international VALUES (551,'WebGUI',8,'Avviso');
INSERT INTO international VALUES (552,'WebGUI',8,'Pendente');
INSERT INTO international VALUES (553,'WebGUI',8,'Stato');
INSERT INTO international VALUES (554,'WebGUI',8,'Agisci');
INSERT INTO international VALUES (555,'WebGUI',8,'Modifica il karma di questo utente.');
INSERT INTO international VALUES (556,'WebGUI',8,'Ammontare');
INSERT INTO international VALUES (557,'WebGUI',8,'Descrizione');
INSERT INTO international VALUES (558,'WebGUI',8,'Modifica il karma dell\'utente');
delete from international where namespace='WebGUI' and internationalId=129;
delete from international where namespace='WebGUI' and internationalId=132;
delete from international where namespace='WebGUI' and internationalId=131;
delete from international where namespace='WebGUI' and internationalId=128;
delete from settings where name='attachmentDirectoryLocal';
delete from settings where name='attachmentDirectoryWeb';
delete from settings where name='lib';
update international set message='Attachment' where internationalId=33 and languageId=1 and namespace='UserSubmission';
alter table page add column startDate int not null default 946710000;
alter table page add column endDate int not null default 2082783600;
update page set styleId=-6 where styleId=-3;




