insert into webguiVersion values ('5.2.1','upgrade',unix_timestamp());
delete from international where languageId=10 and namespace='WebGUI' and internationalId=896;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (896,10,'WebGUI','Side cache timeout (gæster)', 1047941737);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=895;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (895,10,'WebGUI','Side cache timeout', 1047941722);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=893;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (893,10,'WebGUI','Wobject egenskaber', 1047941704);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=892;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (892,10,'WebGUI','Diskussion', 1047941691);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=891;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (891,10,'WebGUI','Omvend kun makroer', 1047941682);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=889;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (889,10,'WebGUI','Style Sheets, tab', 1047941643);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=758;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (758,10,'WebGUI','Tilføj en mappe.', 1047941585);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=757;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (757,10,'WebGUI','Administrer brochurer', 1047941567);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=756;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (756,10,'WebGUI','Tilbage till gruppe liste.', 1047941548);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=754;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (754,10,'WebGUI','Administrer brugere i denne gruppe', 1047941534);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=753;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (753,10,'WebGUI','Rediger denne gruppe', 1047941484);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=751;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (751,10,'WebGUI','Funger som denne bruger.', 1047941471);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=750;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (750,10,'WebGUI','Slet denne bruger.', 1047941450);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=749;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (749,10,'WebGUI','Gem data for side statistik?', 1047941439);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=748;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (748,10,'WebGUI','Bruger antal', 1047941411);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=747;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (747,10,'WebGUI','Brugernavn må kun indeholde alfanumeriske tegn.', 1047941398);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=746;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (746,10,'WebGUI','Ikon sæt for toolbar', 1047941373);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=745;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (745,10,'WebGUI','Gå tilbage til siden.', 1047941356);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=742;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (742,10,'WebGUI','Administrer skabeloner.', 1047941342);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=728;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (728,10,'WebGUI','Er du sikker på du vil slette denne fil?', 1047941323);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=659;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (659,10,'WebGUI','Stilarter, Administrer', 1047941289);
delete from international where languageId=10 and namespace='USS' and internationalId=76;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (76,10,'USS','Indlæg skabelon', 1047941144);
delete from international where languageId=10 and namespace='USS' and internationalId=74;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (74,10,'USS','Brugerindlægs System skabelon', 1047941126);
delete from international where languageId=10 and namespace='USS' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,10,'USS','Skabelon for indlæg', 1047941108);
delete from international where languageId=10 and namespace='USS' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,10,'USS','Hoved skabelon', 1047941093);
delete from international where languageId=10 and namespace='USS' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,10,'USS','Brugerindlæg System, Tilføj/Rediger', 1047941076);
delete from international where languageId=10 and namespace='USS' and internationalId=59;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (59,10,'USS','Næste indlæg', 1047941054);
delete from international where languageId=10 and namespace='USS' and internationalId=58;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (58,10,'USS','Forrige indlæg', 1047941045);
delete from international where languageId=10 and namespace='USS' and internationalId=57;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (57,10,'USS','Besvarelser', 1047941029);
delete from international where languageId=10 and namespace='USS' and internationalId=53;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (53,10,'USS','Layout', 1047941018);
delete from international where languageId=10 and namespace='USS' and internationalId=52;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (52,10,'USS','Miniature', 1047941010);
delete from international where languageId=10 and namespace='USS' and internationalId=51;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (51,10,'USS','Vis miniature?', 1047940999);
delete from international where languageId=10 and namespace='USS' and internationalId=48;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (48,10,'USS','Tillad diskussion?', 1047940986);
delete from international where languageId=10 and namespace='USS' and internationalId=47;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (47,10,'USS','Poster et svar', 1047940975);
delete from international where languageId=10 and namespace='USS' and internationalId=46;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (46,10,'USS','Læs mere...', 1047940940);
delete from international where languageId=10 and namespace='USS' and internationalId=45;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (45,10,'USS','Retur til indlæg', 1047940930);
delete from international where languageId=10 and namespace='USS' and internationalId=41;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (41,10,'USS','Dato', 1047940918);
delete from international where languageId=10 and namespace='USS' and internationalId=39;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (39,10,'USS','Skriv et svar', 1047940909);
delete from international where languageId=10 and namespace='USS' and internationalId=38;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (38,10,'USS','Vælg "nej" hvis du skriver et HTML indlæg', 1047940891);
delete from international where languageId=10 and namespace='USS' and internationalId=30;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (30,10,'USS','Karma pr. indlæg', 1047940857);
delete from international where languageId=10 and namespace='MailForm' and internationalId=32;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (32,10,'MailForm','er ikke en gyldig email adresse.', 1047940666);
delete from international where languageId=10 and namespace='MailForm' and internationalId=31;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (31,10,'MailForm','er ikke udfyldt korrekt.', 1047940648);
delete from international where languageId=10 and namespace='MailForm' and internationalId=30;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (30,10,'MailForm','skal være numerisk.', 1047940633);
delete from international where languageId=10 and namespace='MailForm' and internationalId=29;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (29,10,'MailForm','er et påkrævet felt.', 1047940621);
delete from international where languageId=10 and namespace='MailForm' and internationalId=28;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (28,10,'MailForm','Option for tekstområde', 1047940563);
delete from international where languageId=10 and namespace='MailForm' and internationalId=27;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (27,10,'MailForm','Højde', 1047940544);
delete from international where languageId=10 and namespace='HttpProxy' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,10,'HttpProxy','Cookie katalog', 1047940518);
delete from international where languageId=10 and namespace='HttpProxy' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,10,'HttpProxy','Følg videre redirigeringer?', 1047940506);
delete from international where languageId=10 and namespace='HttpProxy' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,10,'HttpProxy','Fjern stil?', 1047940483);
delete from international where languageId=10 and namespace='HttpProxy' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,10,'HttpProxy','Tillad proxy af andre domæner?', 1047940469);
delete from international where languageId=10 and namespace='HttpProxy' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,10,'HttpProxy','Timeout', 1047940449);
delete from international where languageId=10 and namespace='HttpProxy' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,10,'HttpProxy','HTTP Proxy', 1047940439);
delete from international where languageId=10 and namespace='HttpProxy' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,10,'HttpProxy','Rediger HTTP Proxy', 1047940427);
delete from international where languageId=10 and namespace='HttpProxy' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,10,'HttpProxy','HTTP Proxy, Tilføj/Rediger', 1047940410);
delete from international where languageId=10 and namespace='HttpProxy' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,10,'HttpProxy','URL', 1047940393);
delete from international where languageId=10 and namespace='FileManager' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,10,'FileManager','Fil manager, TIlføj/Rediger', 1047940368);
delete from international where languageId=10 and namespace='Discussion' and internationalId=526;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (526,10,'Discussion','af', 1047940324);
delete from international where languageId=10 and namespace='Discussion' and internationalId=525;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (525,10,'Discussion','Redigeret kl.', 1047940318);
delete from international where languageId=10 and namespace='Discussion' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,10,'Discussion','Filtrer post', 1047940296);
delete from international where languageId=10 and namespace='WebGUI' and internationalId=889;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (889,10,'WebGUI','Style Sheets, Faneblad', 1047941643);
delete from international where languageId=6 and namespace='FAQ' and internationalId=76;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (76,6,'FAQ','FAQ-Mall', 1047901230);
delete from international where languageId=6 and namespace='FAQ' and internationalId=75;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (75,6,'FAQ','Lägg till fråga.', 1047901205);
delete from international where languageId=6 and namespace='FAQ' and internationalId=74;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (74,6,'FAQ','Mall', 1047901180);
delete from international where languageId=6 and namespace='MailForm' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,6,'MailForm','Skicka', 1047901148);
delete from international where languageId=6 and namespace='MessageBoard' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,6,'MessageBoard','Mall för Meddelandeforum', 1047901129);
delete from international where languageId=6 and namespace='MessageBoard' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,6,'MessageBoard','Huvudmall', 1047901096);
delete from international where languageId=6 and namespace='Auth/SMB' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,6,'Auth/SMB','SMB Server Error(1)\r\n<br/>\r\nNågot gick fel när domänkontrollanten skulle kontaktas. Kanske tog kontakten för lång tid. Var god försök igen eller kontakta din systemadministratör.', 1047901072);
delete from international where languageId=6 and namespace='Auth/SMB' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,6,'Auth/SMB','SMB Autentiseringsinställningar', 1047900964);
delete from international where languageId=6 and namespace='Auth/LDAP' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,6,'Auth/LDAP','LDAP autentiseringsinställningar', 1047900938);
delete from international where languageId=6 and namespace='SiteMap' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,6,'SiteMap','Mall för Sitekarta', 1047900828);
delete from international where languageId=6 and namespace='Survey' and internationalId=30;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (30,6,'Survey','Lägg till en ny fråga.', 1047900684);
delete from international where languageId=6 and namespace='Survey' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,6,'Survey','Undersökning, Addera/Redigera', 1047900662);
delete from international where languageId=6 and namespace='Survey' and internationalId=29;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (29,6,'Survey','Addera ett textsvar.', 1047900633);
delete from international where languageId=6 and namespace='Survey' and internationalId=28;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (28,6,'Survey','Lägg till en fråga.', 1047900600);
delete from international where languageId=6 and namespace='Survey' and internationalId=27;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (27,6,'Survey','Addera en åsikts(håller med/håller inte med)-svar.', 1047900578);
delete from international where languageId=6 and namespace='Survey' and internationalId=26;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (26,6,'Survey','Addera ett frekvens-(alltid/aldrig)-svar.', 1047900542);
delete from international where languageId=6 and namespace='Survey' and internationalId=25;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (25,6,'Survey','Addera ett sant/falsk-svar.', 1047900487);
delete from international where languageId=6 and namespace='Survey' and internationalId=24;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (24,6,'Survey','Lägg till ett flervalssvar.', 1047900454);
delete from international where languageId=6 and namespace='Survey' and internationalId=23;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (23,6,'Survey','Lägg till nytt svarsalternativ.', 1047900427);
delete from international where languageId=6 and namespace='Survey' and internationalId=22;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (22,6,'Survey','Svarstyp', 1047900403);
delete from international where languageId=6 and namespace='Survey' and internationalId=21;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (21,6,'Survey','Gå Till', 1047900385);
delete from international where languageId=6 and namespace='Survey' and internationalId=20;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (20,6,'Survey','Är detta svar korrekt?', 1047900366);
delete from international where languageId=6 and namespace='Survey' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,6,'Survey','Redigera Undersökning', 1047900345);
delete from international where languageId=6 and namespace='Survey' and internationalId=19;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (19,6,'Survey','Svar', 1047900323);
delete from international where languageId=6 and namespace='Survey' and internationalId=18;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (18,6,'Survey','Redigera Svarsalternativ', 1047900303);
delete from international where languageId=6 and namespace='Survey' and internationalId=17;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (17,6,'Survey','Redigera Fråga', 1047900275);
delete from international where languageId=6 and namespace='Survey' and internationalId=16;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (16,6,'Survey','Slumpmässiga svar?', 1047900253);
delete from international where languageId=6 and namespace='Survey' and internationalId=15;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (15,6,'Survey','Tillåt kommentarer?', 1047900220);
delete from international where languageId=6 and namespace='Survey' and internationalId=14;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (14,6,'Survey','Fråga', 1047900196);
delete from international where languageId=6 and namespace='Survey' and internationalId=13;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (13,6,'Survey','Vem kan visa rapporter?', 1047900179);
delete from international where languageId=6 and namespace='Survey' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,6,'Survey','Vem kan delta i undersökningen?', 1047900154);
delete from international where languageId=6 and namespace='Survey' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,6,'Survey','Undersökningar tillåter dig samla information från dina användare. Vad gäller WebGUI:s undersökningar så kan du också använda dem för att testa dina användares kunskap.\r\n<p/>\r\n<b>Frågeordning</b>\r\n<br>\r\nOrdningen som frågorna ställs. "Sekventiell" visar frågorna i den ordning du skapade dem. "Slumpmässig" visar frågorna slumpmässigt. "Svarsstyrd" visar frågorna i en ordning som baseras på användarens svar.\r\n<p/>\r\n<b>Metod</b>\r\n<br>\r\nStandardläget för en undersökning är "survey". Detta används för att ställa frågor till användaren. I läget "Frågesport" kan du använda undersökningar som självrättande prov av dina användares kunskaper.\r\n<p/>\r\n<b>Vem kan delta i undersökningar?</b>\r\n<br>\r\nVilka användare som kan delta i en undersökning.\r\n<p/>\r\n<b>Vem kan visa rapported?</b>\r\n<br>\r\nVilka som kan se resultated av undersökningen.\r\n<p/>\r\n<b>V!
ad göra här näst?</b>\r\n<br>\r\nOm du lämnar detta med standardinställningar kan du direkt lägga till frågor efter att skapat undersökningen.', 1047900127);
delete from international where languageId=6 and namespace='Survey' and internationalId=11;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (11,6,'Survey','Metod', 1047900081);
delete from international where languageId=6 and namespace='Survey' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,6,'Survey','Frågelek', 1047900015);
delete from international where languageId=6 and namespace='Survey' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,6,'Survey','Undersökning', 1047899992);
delete from international where languageId=6 and namespace='Article' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,6,'Article','Följande variabler är tillgängliga i artikelmallar.\r\n\r\n<p/><b>attachment.box</b><br/>\r\nGet en standard WebGUI bilagetruta med ikon, filnamn och bilageindikator.\r\n\r\n<p/><b>attachment.icon</b><br/>\r\nURL:en till ikonbilden för denna bilagstyp.\r\n\r\n<p/><b>attachment.name</b><br/>\r\nFilnamnet för denna bilaga.\r\n\r\n<p/><b>attachment.url</b><br/>\r\nURL:en för att ladda ner denna bilaga.\r\n\r\n<p/><b>image.thumbnail</b><br/>\r\nURL:en till tumnagelsbilden för den bilagda bilden.\r\n\r\n<p/><b>image.url</b><br/>\r\nURL:en för den bilagda bilden.\r\n\r\n<p/><b>post.label</b><br/>\r\nEn översatt etikett för att addera en kommentar till denna artikel.\r\n\r\n<p/><b>post.URL</b><br/>\r\nURL:en för att addera en kommentar till denna artikel.\r\n\r\n<p/><b>replies.count</b><br/>\r\nAntal svar på denna artikel. \r\n\r\n<p/><b>replies.label</b><br/>\r\nEn översatt!
 etikett som indikerar att man kan titta på svar.\r\n\r\n<p/><b>replies.url</b><br/>\r\nURL:en för att titta på svar till denna artikel. \r\n', 1047899888);
delete from international where languageId=6 and namespace='USS' and internationalId=75;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (75,6,'USS','Detta är en lista av defaultvariabler som är tillgängliga i mallarna till användarnas inläggssystem.\r\n<p/>\r\n<b>readmore.label</b>\r\n<br>\r\nEn översatt etikett som indikerar att användaren skall klicka för att läsa mer.\r\n<p/>\r\n<b>responses.label</b>\r\n<br>\r\nEn översatt etikett som indikerar att användaren skall klicka för att se svaren för detta inlägg.\r\n<p/>\r\n<b>canPost</b>\r\n<br>\r\nEtt vilkor som indikerar huruvida en användare kan lägga till ett nytt inlägg.\r\n<p/>\r\n<b>post.url</b>\r\n<br>\r\nURL för att addera inlägg.\r\n<p/>\r\n<b>post.label</b>\r\n<br>\r\nEn översatt etikett för länken att addera inlägg.\r\n<p/>\r\n<b>search.label</b>\r\n<br>\r\nEn översatt etikett för söklänken.\r\n<p/>\r\n<b>search.url</b>\r\n<br>\r\nURL för att slå på/av WebGUI\'s sökformulär.\r\n<p/>\r\n<b>search.form</b>\r\n<br>\r\nWebGUI\'s sökformulär.\r\n<p/>\r\n<b>title!
.label</b>\r\n<br>\r\nEn översatt etikett för titelkolumnen.\r\n<p/>\r\n<b>thumbnail.label</b>\r\n<br>\r\nEn översatt etikett för tumnagelskolumnen.\r\n<p/>\r\n<b>date.label</b>\r\n<br>\r\nEn översatt etikett för datumkolumnen.\r\n<p/>\r\n<b>by.label</b>\r\n<br>\r\nEn översatt etikett som informerar om vem som skickat inlägget.\r\n<p/>\r\n<b>submissions_loop</b>\r\n<br>\r\nEn loop innehållande varje inlägg.\r\n<p/>\r\n<blockquote>\r\n<b>submission.id</b><br/>\r\nUnik identifierare för detta inlägg. \r\n\r\n<p/><b>submission.url</b><br/>\r\nURL för att visa detta inlägg. \r\n\r\n<p/><b>submission.content</b><br/>\r\nFörkortat innehåll av detta inlägg.\r\n\r\n<p/><b>submission.responses</b><br/>\r\nAntal svar för detta inlägg. \r\n\r\n<p/><b>submission.title</b><br/>\r\nTiteln för detta inlägg. \r\n\r\n<p/><b>submission.userId</b><br/>\r\nUser-id för den användare som postade inlägget. \r\n\r\n<p/><b>submission.username</b><br/>\r\nAnvändarnamnet för den person som postade inl!
ägget. \r\n\r\n<p/><b>submission.status</b><br/>\r\nStatus för detta inlägg (approved, pending, denied). \r\n\r\n<p/><b>submission.thumbnail</b><br/>\r\nTumnagelbild som skickades med detta inlägg (om det finns någon). \r\n\r\n<p/><b>submission.date</b><br/>\r\nDatum när detta inlägg skickades. \r\n\r\n<p/><b>submission.currentUser</b><br/>\r\nTillstånd som indikerar som inloggad användare var den som skickade inlägget. \r\n\r\n<p/><b>submission.userProfile</b><br/>\r\nURL till profilen för den användare som skickade inlägget.\r\n\r\n<p/><b>submission.secondColumn</b><br/>\r\nVilkor som indikerar om detta inlägg hör till den andra kolumnen i en flerkolumns-layout.\r\n\r\n<p/><b>submission.thirdColumn</b><br/>\r\nVilkor som indikerar om detta inlägg hör till den tredje kolumnen i en flerkolumns-layout.\r\n\r\n\r\n<p/><b>submission.fourthColumn</b><br/>\r\nVilkor som indikerar om detta inlägg hör till den fjärde kolumnen i en flerkolumns-layout.\r\n\r\n<p/><b>submission.fifthC!
olumn</b><br/>\r\nVilkor som indikerar om detta inlägg hör till den femte kolumnen i en flerkolumns-layout.\r\n\r\n</blockquote>\r\n<p/><b>firstPage</b><br/>\r\nLänk till första sidan i sidlistan.\r\n\r\n<p/><b>lastPage</b><br/>\r\nLänk till sisda sidan i sidlistan.\r\n\r\n<p/><b>nextPage</b><br/>\r\nLänk till nästa sida i listan.\r\n\r\n<p/><b>previousPage</b><br/>\r\nLänk till föregående sida i listan.\r\n\r\n<p/><b>pageList</b><br/>\r\nEn lista av länkar till alla sidor.\r\n\r\n<p/><b>multiplePages</b><br/>\r\nVilkor som indikerar om det finns fler än en sida i sidlistan.\r\n', 1047899555);
delete from international where languageId=6 and namespace='USS' and internationalId=76;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (76,6,'USS','Inläggsmall', 1047898412);
delete from international where languageId=6 and namespace='USS' and internationalId=74;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (74,6,'USS','Mall för Användarnas Inläggssystem', 1047898337);
delete from international where languageId=6 and namespace='USS' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,6,'USS','Inläggsmall', 1047898252);
delete from international where languageId=6 and namespace='USS' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,6,'USS','Huvudmall', 1047898100);
delete from international where languageId=6 and namespace='Survey' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,6,'Survey','Undersökning', 1047898081);
delete from international where languageId=6 and namespace='Survey' and internationalId=80;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (80,6,'Survey','sekunder', 1047898063);
delete from international where languageId=6 and namespace='Survey' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,6,'Survey','Frågeordning', 1047898046);
delete from international where languageId=6 and namespace='Survey' and internationalId=79;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (79,6,'Survey','minuter', 1047898007);
delete from international where languageId=6 and namespace='Survey' and internationalId=78;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (78,6,'Survey','Totaltid', 1047897990);
delete from international where languageId=6 and namespace='Survey' and internationalId=77;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (77,6,'Survey','Sluttid', 1047897971);
delete from international where languageId=6 and namespace='Survey' and internationalId=76;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (76,6,'Survey','Starttid', 1047897946);
delete from international where languageId=6 and namespace='Survey' and internationalId=75;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (75,6,'Survey','Redigera denna fråga.', 1047897884);
delete from international where languageId=6 and namespace='Survey' and internationalId=74;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (74,6,'Survey','Är du säker på att du vill ta bort alla användarsvar?', 1047897851);
delete from international where languageId=6 and namespace='Survey' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,6,'Survey','Ta bort alla användarsvar.', 1047897821);
delete from international where languageId=6 and namespace='Survey' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,6,'Survey','Är du säker på att du vill ta bort denna användares svar?', 1047897799);
delete from international where languageId=6 and namespace='Survey' and internationalId=71;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (71,6,'Survey','Betyg', 1047897774);
delete from international where languageId=6 and namespace='Survey' and internationalId=70;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (70,6,'Survey','Individuella Svar', 1047897757);
delete from international where languageId=6 and namespace='Survey' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,6,'Survey','Svarsstyrd', 1047897735);
delete from international where languageId=6 and namespace='Survey' and internationalId=69;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (69,6,'Survey','Ta bort denna användares svar.', 1047897689);
delete from international where languageId=6 and namespace='Survey' and internationalId=68;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (68,6,'Survey','Visa rapporter och exporteringar.', 1047897654);
delete from international where languageId=6 and namespace='Survey' and internationalId=67;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (67,6,'Survey','Användare', 1047897588);
delete from international where languageId=6 and namespace='Survey' and internationalId=66;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (66,6,'Survey','Användarsvar', 1047897572);
delete from international where languageId=6 and namespace='Survey' and internationalId=65;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (65,6,'Survey','Exportera sammansatt summering.', 1047897550);
delete from international where languageId=6 and namespace='Survey' and internationalId=62;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (62,6,'Survey','Exportera svarsalternativ.', 1047897503);
delete from international where languageId=6 and namespace='Survey' and internationalId=64;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (64,6,'Survey','Exportera användarsvar.', 1047897455);
delete from international where languageId=6 and namespace='Survey' and internationalId=63;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (63,6,'Survey','Exportera frågor.', 1047897432);
delete from international where languageId=6 and namespace='Survey' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,6,'Survey','Visa betyg.', 1047897391);
delete from international where languageId=6 and namespace='Survey' and internationalId=60;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (60,6,'Survey','Tillbaks till undersökningen.', 1047897270);
delete from international where languageId=6 and namespace='Survey' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,6,'Survey','Slumpmässig', 1047897241);
delete from international where languageId=6 and namespace='Survey' and internationalId=59;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (59,6,'Survey','Visa statistisk överblick', 1047897218);
delete from international where languageId=6 and namespace='Survey' and internationalId=58;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (58,6,'Survey','Statistisk Överblick', 1047897194);
delete from international where languageId=6 and namespace='Survey' and internationalId=57;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (57,6,'Survey','Kommentarer', 1047897169);
delete from international where languageId=6 and namespace='Survey' and internationalId=56;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (56,6,'Survey','Visa kommentarer.', 1047897144);
delete from international where languageId=6 and namespace='Survey' and internationalId=55;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (55,6,'Survey','Visa svar.', 1047897127);
delete from international where languageId=6 and namespace='Survey' and internationalId=54;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (54,6,'Survey','Procent', 1047897104);
delete from international where languageId=6 and namespace='Survey' and internationalId=53;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (53,6,'Survey','Svar', 1047897077);
delete from international where languageId=6 and namespace='Survey' and internationalId=52;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (52,6,'Survey','Poäng', 1047897022);
delete from international where languageId=6 and namespace='Survey' and internationalId=51;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (51,6,'Survey','Kommentarer?', 1047897005);
delete from international where languageId=6 and namespace='Survey' and internationalId=50;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (50,6,'Survey','Nästa', 1047896979);
delete from international where languageId=6 and namespace='Survey' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,6,'Survey','Sekventiell', 1047896962);
delete from international where languageId=6 and namespace='Survey' and internationalId=49;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (49,6,'Survey','Du får för närvarande inte delta i denna frågelek.', 1047896852);
delete from international where languageId=6 and namespace='Survey' and internationalId=48;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (48,6,'Survey','Du är för närvarande inte kvalificerad för att delta i denna undersökning.', 1047896818);
delete from international where languageId=6 and namespace='Survey' and internationalId=47;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (47,6,'Survey','Du har fullföljd denna frågelek.', 1047896737);
delete from international where languageId=6 and namespace='Survey' and internationalId=46;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (46,6,'Survey','Tack för att du tog dig tid att gå igenom vår undersökning.', 1047896633);
delete from international where languageId=6 and namespace='Survey' and internationalId=45;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (45,6,'Survey','Är du säker på att du vill ta bort detta svarsalternativ och dess användarsvar?', 1047896578);
delete from international where languageId=6 and namespace='Survey' and internationalId=44;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (44,6,'Survey','Är du säker på att du vill ta bort denna fråga och dess svar?', 1047896516);
delete from international where languageId=6 and namespace='Survey' and internationalId=43;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (43,6,'Survey','Aldrig', 1047896467);
delete from international where languageId=6 and namespace='Survey' and internationalId=42;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (42,6,'Survey','Ibland', 1047896451);
delete from international where languageId=6 and namespace='Survey' and internationalId=41;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (41,6,'Survey','Ofta', 1047896435);
delete from international where languageId=6 and namespace='Survey' and internationalId=40;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (40,6,'Survey','Alltid', 1047896419);
delete from international where languageId=6 and namespace='Survey' and internationalId=39;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (39,6,'Survey','Ej applicerbart', 1047895854);
delete from international where languageId=6 and namespace='Survey' and internationalId=38;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (38,6,'Survey','Håller verkligen inte med', 1047895822);
delete from international where languageId=6 and namespace='Survey' and internationalId=37;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (37,6,'Survey','Håller inte med', 1047895802);
delete from international where languageId=6 and namespace='Survey' and internationalId=36;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (36,6,'Survey','Håller delvis inte med', 1047895786);
delete from international where languageId=6 and namespace='Survey' and internationalId=35;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (35,6,'Survey','Håller delvis med', 1047895764);
delete from international where languageId=6 and namespace='Survey' and internationalId=34;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (34,6,'Survey','Håller med', 1047895744);
delete from international where languageId=6 and namespace='Survey' and internationalId=33;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (33,6,'Survey','Håller verkligen med', 1047895729);
delete from international where languageId=6 and namespace='Survey' and internationalId=32;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (32,6,'Survey','Falskt', 1047895703);
delete from international where languageId=6 and namespace='Survey' and internationalId=31;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (31,6,'Survey','Sant', 1047895687);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=751;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (751,6,'WebGUI','Bli denna användare.', 1047895671);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=624;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (624,6,'WebGUI','WebGUI macros används för att skapa dynamiskt innehåll bland statiskt innehåll. Till exempel så kan användarnamnet för inloggad användare visas på varje sida.\r\n\r\nMacros börjar alltid med "^", följs alltid med minst ett tecken och avslutas alltid med ";". Vissa macron kan konfigureras genom att man lägger in en parameter. Ett vanlig macro kan skrivas: ^x; men med en paramater ser det ut som: ^x("parameter, vad du vill");\r\n\r\nHär följer en beskrivning av samtliga macron i WebGUI.\r\n\r\n<b>^a; eller ^a(); - Mitt konto-länk</b>\r\nEn länk för att se din kontoinformation. Du kan ändra länktexten genom att skriva macrot som <b>^a("Kontoinformation");</b>.\r\n\r\n<i>Note:</i> Du kan använda specialparametern linkonly (^a(linkonly)) för att bara skapa en URL till kontosidan och inget mer. .myAccountLink stilmallen är knuten till detta macro.\r\n\r\n<b>^AdminBar;</b>\r!
\nPlacerar administrativa menyn på sidan. Detta är ett obligatoriskt macro i "body"-delen av stilhanteraren.\r\n\r\n<b>^AdminText();</b>\r\nVisar ett litet textmeddelande om en användare är i administrationsläge. Exempel: ^AdminText("Du är nu i administrationsläge");.\r\n\r\n<b>^AdminToggle; eller ^AdminToggle();</b>\r\nPlacerar en länk på sidan som bara är synlig för innehållshanterare och administratörer. Länken sätter på/stänger av administrationsläget. Du kan även välja andra namn på länkarna genom att skriva ^AdminToggle("Redigera","Visa");.\r\n\r\n<b>^C; eller ^C(); - Vägspårning</b>\r\nVisar vilken väg man gått genom webbplatsen i en hierarkisk struktur. Du kan själv välja vilken avgrönsare du vill ha mellan de olika sidorna genom att skriva ^C(::). Standard avgränsare är ">". \r\n\r\n<i>Note:</i> .crumbTrail stilklass anger hur den ser ut.\r\n\r\n<b>^c; - Företagsnamn</b>\r\nNamnet på ditt företag, angett av administratören.\r\n\r\n<b>^D; eller ^D(); - Datum</b>\r\nT!
id just nu.\r\n\r\nDu kan själv välja datumformat genom att använda vissa symboler. ^D("%c %D, %y"); skulle generera September 26, 2001. Följande format och symboler finns tillgängliga: \r\n\r\n%% % \r\n%y 4-siffrigt årtal\r\n%Y 2-siffrigt årtal\r\n%m 2-siffrig månad\r\n%M månad\r\n%c månadsnamn\r\n%d 2-siffrig månadsdag\r\n%D månadsdag\r\n%w namn på veckodag\r\n%h 2-siffrig klocka bas 12 timmar\r\n%H klocka bas 12 timmar\r\n%j 2-siffrig klocka bas 24 timmar\r\n%J klocka bas 12 timmar\r\n%p gemen am/pm\r\n%P versal AM/PM\r\n%z användarinställt datumformat\r\n%Z användarinställt tidsformat\r\n\r\n<b>^e; - Företagets e-postadress</b>\r\nE-postadressen som inställd av adminstratören.\r\n\r\n<b>^Env();</b>\r\nAnvänds för att visa serverns variabler. Du kan se alla serverns variabler genom att gå till "www.dinwebplats.tld/env.pl". Macrot ska skrivas som ^Env("REMOTE_ADDR");.\r\n\r\n<b>^Execute();</b>\r\nTillåter innehållshanterare eller administratör att köra ett externt program.!
 Används vanligtvis som ^Execute("/this/file.sh").\r\n\r\n<b>^Extras;</b>\r\nReturnera sökvägen till WebGUI "extras" mapp som innehåller saker som WebGUI ikoner.\r\n\r\n<b>^FlexMenu;</b>\r\nSkapar en expanderbar meny. Fungerar ungerfär som trädstrukturen i Utforskaren på en Windows-dator.\r\n\r\n<b>^FormParam();</b>\r\nAnvänds oftast för att skapa dynamiska frågor genom SQL-rapporter. Genom att använda det här macrot kan du få värdet från valfritt formulärfält bara genom att använda fältets namn. Exempel: ^FormParam("telefonnummer"); \r\n\r\n<b>^GroupText();</b>\r\nVisar en kort text för användare som är medlemmar i en specifik grupp. Exempel: ^GroupText("Visitors","Du behöver ett konto för att använda den här webbplatsen!"); \r\n\r\n<b>^H; or ^H(); - Home Link</b>\r\nEn länk till webbplatsens förstasida. Du kan själv välja länktexten genom att skicka med den som en parameter. Exempel: ^H("Hem");. \r\n\r\n<i>Note:</i> Du kan även skriva ^H(linkonly); för att bara få en URL t!
ill förstasidan. .homeLink stilklassen används för att ändra utseende på länken.\r\n\r\n<b>^I(); - Bild-tagg från bildhanteraren</b>\r\nReturnerar en image-tag (HTML) till en bild definierad i bildhanteraren. Välj vilken bild du vill ha genom att skicka namnet som parameter. Exempel: ^I("bildnamn");. \r\n\r\n<b>^i(); - Image Manager Image Path</b>\r\nReturnera sökvägen till en bild som är uppladdad via bildhanteraren. Välj vilken bild du vill ha sökvägen till genom att skicka namnet som parameter. Exempel: ^i("bildnamn");.\r\n\r\n<b>^Include();</b>\r\nLåter administratör eller innehållshanterare att inkludera filer från lokala filsystemet i HTML-dokumenten. Skicka dokumentets plats som parameter. Exempel: ^Include("/denna/filen.html"); \r\n\r\n<b>^L; or ^L(); - Login</b>\r\nEtt litet inloggningsformulär. Du kan bestämma hur bred rutan ska vara och även ett meddelande som ska visas efter användaren loggat in. För att bestämma storleken så skriver man: ^L(20);. För att skriva !
ett meddelande som visas för användaren så skriver man: ^L(20,Hej ^a(^@;);. Klicka %here% om du vill logga ut!) \r\n\r\n<i>Note:</i> .loginBox stilklassen bestämmer utseendet.\r\n\r\n<b>^LoginToggle; or ^LoginToggle();</b>\r\nVisar ett "Logga in"- eller "Logga ut"-meddelande beroende på om man är ut- eller inloggad. Du kan även välja andra texter genom att skriva såhär: ^LoginToggle("Klicka här för att logga in.","Klicka här för att logga ut."); \r\n\r\n<b>^M; or ^M(); - Nuvarande meny (vertikal)</b>\r\nEn vertikal meny som visar de underalternativ som finns tillgängliga från nuvarande sida och neråt. Som standard så visar den bara de menyalternativ som leder ner en nivå, men du kan själv välja hur många nivåer ner som ska visas. För att gå tre nivåer ner kan du skriva såhär: ^M(3);. Byter du 3\'an mot en 0\'a (noll) så visas hela webbplatsens undersidor.\r\n\r\n<b>^m; - Nuvarande meny (horisontell)</b>\r\nEn horisontell meny som innehåller undersidorna räknat från nuvarande!
 nivå. Du kan själv välja en avgränsare genom att skriva ^m(:--:);. Standard avgränsare är ·. \r\n\r\n<b>^P; or ^P(); - Tidigare meny (vertikal)</b>\r\nEn vertikal meny som innehåller länkar till sidorna innan nuvarande nivå. Som standard så visar den bara de menyalternativ som leder ner en nivå, men du kan själv välja hur många nivåer ner som ska visas. För att gå tre nivåer ner kan du skriva såhär: ^P(3);. Byter du 3\'an mot en 0\'a (noll) så visas hela webbplatsens undersidor.\r\n\r\n<b>^p; - Tidigare meny (horisontell)</b>\r\nEn horisontell meny som innehåller länkar till sidorna innan nuvarande nivå. Du kan själv välja en avgränsare genom att skriva ^m(:--:);. Standard avgränsare är ·. \r\n\r\n<b>^Page();</b>\r\nKan användas för att hämta information om aktuell sida. Till exempel så kan macrot användas för att hämta sidans URL såhär: ^Page("urlizedTitle"); eller sidans title såhär: ^Page("menuTitle");. \r\n\r\n<b>^PageTitle;</b>\r\nVisar titeln på aktuell sida.\r\n\r\n<!
i>Note:</i> Om du använder administratörsfunktioner eller "indepth"-funktioner i wobjects så kommer sidans titel bli en länk som tar dig tillbaka till sidan.\r\n\r\n<b>^r; or ^r(); - Utskriftsbar version</b>\r\nSkapar en länk som visar aktuell sida, men med annan design. Du kan ändra text på länken genom att skriva såhär: ^r("Skriv ut");. \r\n\r\nNär en användare klickar på länken kommer sidans stil att bytas ut mot "Make Page Printable"-stilen i stilhanteraren. Detta kan dock ändras till vilken stil som helst genom att skicka med stilen som paramter. Exempel: ^r("Print!","WebGUI");. Utrskriftssidan kommer då få WebGUI-stilen.\r\n\r\n<i>Note:</i> Du kan även använda specialmacrot ^r(linkonly); för att få en URL till utskriftsbar version. .makePrintableLink stilmallen bestämmer utseende på länken.\r\n\r\n<b>^rootmenu; eller ^rootmenu(); (horisontell)</b>\r\nSkapar en horisontell meny med rötterna i WebGUI (förutom system-menyer). Du kan välja menyavgränsare genom att skriva s!
åhär: ^rootmenu(|); \r\n\r\n<b>^RootTitle;</b>\r\nReturnerar titlen på roten till nuvarande sida. Till exempel är roten till WebGUI "Hem"-sidan\r\nAvancerade sidor kan ha flera rötter och behöver således ett sätt att beskriva för användaren vilken rot denna befinner sig i.\r\n\r\n<b>^S(); - Specifik undermeny (vertikal)</b>\r\nDetta macro ger dig en vertikal undermeny från vilken sida som helst. Undermenyn startar från sidan du anger som parameter till macrot. Till exempel kan du få en undermeny till alla sidor under "Hem" genom att skriva ^S("hem",0);. Det första värdet är URL\'iserade titeln av sidan och den andra paramtern är hur djup du vill att trädstrukturen ska vara. Standardinställningen är att bara visa en nivå. För att gå tre nivåer ner skriver du: ^S("hem",3);. \r\n\r\n<b>^s(); - Specifik undermeny (horisontell)</b>\r\nDetta macro ger dig en horisontell undermeny från vilken sida som helst. Undermenyn startar från sidan du anger som parameter till macrot. Till exe!
mpel kan du få en undermeny till alla sidor under "Hem" genom att skriva ^s("hem");. Parametern är den URL\'iserade titeln av sidan. Du kan även själv välja en avgränsare genom att skriva ^s("hem", ":--:");. Standard avgränsare är ·. \r\n\r\n<b>^SQL();</b>\r\nEn en-rads-SQL-rapport. Ibland vill bara bara ha lite snabba data från databasen och då kan du använda detta macro. Det här macrot kan också användas för att utöka ett. Detta macro använder de numeriska macrona (^0; ^1; ^2; etc) för att positionera data. Macrot ^rownum; för att få fram radnummer kan också användas här. Exempel:\r\n\r\n^SQL("select count(*) from users","Det finns ^0; användare på det här systemet."); \r\n\r\n^SQL("select userId,username from users order by username","<a href=\'^/;?op=viewProfile&uid=^0;\'>^1;</a><br>"); \r\n\r\n<b>^Synopsis; eller ^Synopsis(); Meny</b>\r\nDetta macro ger dig en undermeny till sidor under en viss sida, tillsammans med kort beskrivning av respektive länk. Du kan sätta ett !
heltal som parameter för att välja hur många nivåer djup menyn ska vara.\r\n\r\n<b>Notera:</b> .synopsis_sub, .synopsis_summary, och .synopsis_title stilklasser används av detta macro. \r\n\r\n<b>^T; eller ^T(); - Toppnivåmeny (vertikal)</b>\r\nEn vertikal meny som innehåller alla huvudsidor på webbplatsen, dvs undersidor från hemsidan. Du kan själv välja hur djup du vill ha trädstrukturen genom att skriva ett heltal som parameter. Som standard visar den bara första nivån. För att gå ner tre nivåer skriver du ^T(3). Om du skickar "0" (noll) så kommer hela webbplatsen trädstruktur visas. \r\n\r\n<b>^t; - Toppnivåmeny (horisontell)</b>\r\nEn vertikal meny som innehåller alla huvudsidor på webbplatsen, dvs undersidor från hemsidan. Du kan själv välja en avgränsare mellan sidnamnen genom att skriva ^t(:--:);. Standard avgränsare är ·. \r\n\r\n<b>^Thumbnail();</b>\r\nReturnerar en URL av en minitayrbild av en bild från bildhanteraren. Välj vilken bild du vill ha genom att skicka !
med namnet på bilden som parameter: ^Thumbnail("bildnamn");. \r\n\r\n<b>^ThumbnailLinker();</b>\r\nDu kan använda detta macro för att enkelt göra en sida med skärmdumpar eller ett fotogalleri. Skicka med namnet på en bild i bildhanteraren som parameter till macrot: ^ThumbnailLinker("Min hund"); och på sidan kommer det visas en miniatyrbild men länk under som länkar till bilden i full storlek.\r\n\r\n<b>^u; - Företags-URL</b>\r\nURL till ditt företag, som det är inställt av administratören.\r\n\r\n<b>^URLEncode();</b>\r\nDetta macro är mest användbart i SQL-rapporter, men kan självklart användas på andra ställen också. Macrot tar en sträng som parametera och kodar om den i URL-format så man kan använda den i just en URL. Så här kan du använda den: ^URLEncode("Detta är en sträng med tecken!"); \r\n\r\n<b>^User();</b>\r\nAnvänd detta macro för att visa information om en användare från dennes kontouppgifter eller profil. Om du vill visa användaren dennes e-postadress skriver du:!
 ^User("email");.\r\n\r\n<b>^/; - System-URL</b>\r\nURL till WebGUI-scriptet (exempel: /index.pl/). \r\n\r\n<b>^\\; - Sid-URL</b>\r\nURL till nuvarande sida (exempel: /index.pl/pagename).\r\n\r\n<b>^@; - Användarnamn</b>\r\nAnvändarnamnet på nu inloggad användare.\r\n\r\n<b>^?; - Sök</b>\r\nEn sökbox på sidan. Knuten till WebGUI\'s inbyggda sökmotor.\r\n\r\n<b>Note:</b> .searchBox stilklass används av detta macrot. \r\n\r\n<b>^#; - Användar-ID</b>\r\nAnvändar-ID för nu inloggad användare.\r\n\r\n<b>^*; or ^*(); - Slumpmässigt nummer</b>\r\nSlumpmässigt genererat nummer. Kan användas för att rotera banners eller andra typer av bilder. Du kan även välja högsta nummer för slumptalsfunktionen såhär: ^*(100) för att skapa ett slumptal mellan 0 och 100.\r\n\r\n<b>^-;,^0;,^1;,^2;,^3;, etc.</b>\r\nDessa macros är reserverade för system/wobject-specifika funktioner som i SQL-rapporten och Body i stilhanteraren.', 1047895470);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=412;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (412,6,'WebGUI','Sammanfattning', 1047895380);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=307;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (307,6,'WebGUI','Använd standard meta-taggar?', 1047895267);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=100;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (100,6,'WebGUI','Meta-taggar', 1047895196);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=606;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (606,6,'WebGUI','Tänk på sidor som platshållare för innehåll. Skapa sidan först och fyll den sedan med allt du vill att den ska innehålla.\r\n\r\n<b>Titel</b>\r\nSidans titel. Den används i navigeringen. Titlar ska vara beskrivande, men inte för långa.\r\n\r\n<b>Menytitel</b>\r\nEn förkortad eller ändrad titel som visas i navigeringsmenyer. Om fältet är tomt kommer titeln att visas.\r\n\r\n<b>Sid-URL</b>\r\nNär du skapar en sida kommer en URL att genereras baserad på sidans titel. Om du är missnöjd med URL\'en den skapar automatiskt kan du välja en egen här.\r\n\r\n<b>Omdirigerings-URL</b>\r\nNär den här sidan besöks kommer användaren bli omdirigerad till en URL du fyller i här. För att redigera den här sidan i fortsättningen måste du gå till den via "Hantera träd-vy" under "Administrativa funktioner...".\r\n\r\n<b>Mall</b>\r\nSom standard har WebGUI en stort område där du kan placera!
 wobjects. Du kan välja en annan för att dela upp sidan i mindre områden.\r\n\r\n<b>Beskrivning</b>\r\nKort beskrivning av sidan. Används för att skapa META-taggar och beskrivningar på webbplatskartan.\r\n\r\n<b>Meta-taggar</b>\r\nMeta-taggar används av vissa sökmotorer för att associera nyckelord med innehållet i texten på sidan. Det finns en bra webbplats som heter <a href="http://www.metatagbuilder.com/">Meta Tag Builder</a> som hjälper dig skapa meta-taggar om du aldrig gjort det förrut.\r\n\r\n<i>Avancerade användare:</i> Om du har andra saker som JavaScript kan du lägga in det här.\r\n\r\n<b>Använd standard meta-taggar?</b>\r\nOm du inte vill välja meta-taggar själv så kan WebGUI generera dessa för dig, baserat på sidans titel och ditt företagsnamn. Bocka i denna rutan för att tillåta WebGUI att göra detta.\r\n\r\n<b>Stil</b>\r\nSom standard så ärver en ny sida vissa egenskaper från sidan ovanför. En av dessa egenskaper är stilen. Välj från en lista av stilar om du vil!
l ändra utseendet på just denna sidan. \r\n\r\nVäljer du Ja på frågan under så kommer alla sidor under denna sida att ärva stilen.\r\n\r\n<b>Startdatum</b>\r\nDatum då sidan kommer börja visas för användarna. Innan dess kommer sidan bara visas för personer med rättighet att ändra sidor.\r\n\r\n<b>Slutdatum</b>\r\nDatum då sidan kommer sluta synas. Efter detta kommer sidan bara visas för personer med rättighet att ändra sidor.\r\n\r\n<b>Ägare</b>\r\nVem äger sidan? Vanligtvis personen som skapade den.\r\n\r\n<b>Ägaren kan se sidan?</b>\r\nKan ägaren se sin egen sida?\r\n\r\n<b>Ägaren kan redigera sidan?</b>\r\nKan ägaren redigera sidan? Var försiktig med att stänga av denna funktion eftersom om ägaren inte är i sidgruppen så kommer han inte längre kunna redigera sin egen sida.\r\n\r\n<b>Grupp</b>\r\nVälj vilken grupp som ska äga sidan.\r\n\r\n<b>Grupp kan se sidan?</b>\r\nKan medlemmar i gruppen se sidan?\r\n\r\n<b>Grupp kan redigera sidan?</b>\r\nKan medlemmar i gruppen redg!
iera sidan?\r\n\r\n<b>Vem som helst kan se?</b>\r\nVem som helst kan se sidan, medlemskap eller inte?\r\n\r\n<b>Vem som helst kan redigera sidan?</b>\r\nKan vem som helst redigera sidan?\r\n\r\n<b>Note:</b> Du kan ge samtliga rättigheter rekursivt, så att de även gäller för undersidor.', 1047895156);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,6,'WebGUI','Hantera användare.', 1047894382);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,6,'WebGUI','Hantera stilar.', 1047894359);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,6,'WebGUI','Hantera grupper.', 1047894338);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,6,'WebGUI','Hantera inställningar.', 1047894209);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=143;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (143,6,'WebGUI','Hantera inställningar', 1047894194);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=621;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (621,6,'WebGUI','I stilar kan du använda macros. Se <i>Använd Macros</i> för mer information.\r\n\r\n<b>Stilnamn</b>\r\nEtt unikt namn som beskriver vad stilen ser ut som. Namnet påverkar inte hur stilen ser ut i övrigt.\r\n\r\n<b>Body</b>\r\nBodyn som är precis samma som body-taggen i HTML. Där kan du definiera hur hela sidan ser ut, inklusive navigering, logotyper, coppyright osv. Som minimum bör bodyn innehålla några macron som ^Adminbar; (för att visa administrationsmenyn) och ^-; (avdelare) macrot. ^-; visar var WebGUI kommer lägga webbplatsens innehåll.\r\n\r\nOm du behöver hjälp att skapa en design på din webbplats eller bara hjälp att skapa en stil i WebGUI är du välkommen att kontakta <a href="http://www.plainblack.com/">Plain Black Software</a>.\r\n\r\nMånga lägger in WebGUI macros för att autmatiskt sköta navigeringen på webbplatsen och andra egenskaper.\r\n\r\n<b>Stilmall !
(style sheet)</b>\r\nHär lägger du dina stilmallsdefinitioner. Stilmallar används för att kontrollera färger, storlekar och andra egenskaper för de olika elementen på webbplatsen. Se <i>Använd stilmallar</i> för mer information.\r\n\r\n<i>Avancerade användare:</i> för att öka prestandan kan du skapa en extern stilmall och lägga på servern. För att länka till den skriver du:\r\n&lt;link href="/webgui.css" rel="stylesheet" rev="stylesheet" type="text/css"&gt;', 1047894158);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=422;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (422,6,'WebGUI','<h1>Inloggning misslyckades</h1>\r\nInformationen du gav stämmer inte med kontot.', 1047893561);
delete from international where languageId=6 and namespace='SQLReport' and internationalId=17;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (17,6,'SQLReport','<b>Debug:</b> Förfrågan(query):', 1047893529);
delete from international where languageId=6 and namespace='SQLReport' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,6,'SQLReport','<b>Debug:</b> Error: Could not connect to the database.', 1047893506);
delete from international where languageId=6 and namespace='SQLReport' and internationalId=11;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (11,6,'SQLReport','<b>Debug:</b> Error: There was a problem with the query.', 1047893473);
delete from international where languageId=6 and namespace='SQLReport' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,6,'SQLReport','<b>Debug:</b> Error: The SQL specified is of an improper format.', 1047893431);
delete from international where languageId=6 and namespace='SQLReport' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,6,'SQLReport','<b>Debug:</b> Error: The DSN specified is of an improper format.', 1047893389);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=63;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (63,6,'WebGUI','Slå på administratörsverktyg.', 1047893069);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,6,'WebGUI','Stäng av administratörsverktyg.', 1047893028);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=49;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (49,6,'WebGUI','Klicka <a href="^\\;?op=logout">här</a> för att logga ur.', 1047892752);
delete from international where languageId=6 and namespace='EventsCalendar' and internationalId=79;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (79,6,'EventsCalendar','Huvudmall', 1047892205);
delete from international where languageId=6 and namespace='Article' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,6,'Article','Artikelmall', 1047892178);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=560;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (560,6,'WebGUI','Godkänt', 1047850822);
delete from international where languageId=6 and namespace='WebGUI' and internationalId=514;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (514,6,'WebGUI','Visningar', 1047850784);





