insert into webguiVersion values ('4.2.0','upgrade',unix_timestamp());
insert into international values (6,'Item','English','Edit Item');
insert into settings values ('runOnRegistration','');
insert into international values (559,'WebGUI','English','Run On Registration');
alter table discussion add column locked int not null default 0;
alter table discussion add column status varchar(30) not null default 'Approved';
update international set internationalId=560, namespace='WebGUI' where internationalId=7 and namespace='UserSubmission';
update international set internationalId=561, namespace='WebGUI' where internationalId=8 and namespace='UserSubmission';
update international set internationalId=562, namespace='WebGUI' where internationalId=9 and namespace='UserSubmission';
update international set internationalId=563, namespace='WebGUI' where internationalId=10 and namespace='UserSubmission';
update international set internationalId=564, namespace='WebGUI' where internationalId=3 and namespace='MessageBoard';
update international set internationalId=565, namespace='WebGUI' where internationalId=21 and namespace='MessageBoard';
update international set internationalId=566, namespace='WebGUI' where internationalId=5 and namespace='MessageBoard';
delete from international where internationalId=19 and namespace='Article';
delete from international where internationalId=20 and namespace='Article';
delete from international where internationalId=21 and namespace='Article';
delete from international where namespace='UserSubmission' and internationalId=30;
delete from international where namespace='UserSubmission' and internationalId=49;
delete from international where namespace='UserSubmission' and internationalId=50;
delete from international where namespace='UserSubmission' and internationalId=44;
insert into international values (567,'WebGUI','English','Pre-emptive');
insert into international values (568,'WebGUI','English','After-the-fact');
insert into international values (569,'WebGUI','English','Moderation Type');
alter table wobject add column groupToPost int not null default 2;
alter table wobject add column editTimeout int not null default 1;
alter table wobject add column groupToModerate int not null default 4;
alter table wobject add column karmaPerPost int not null default 0;
alter table wobject add column moderationType varchar(30) not null default 'after';
alter table MessageBoard drop column editTimeout;
alter table MessageBoard drop column groupToModerate;
alter table MessageBoard drop column groupToPost;
alter table MessageBoard drop column karmaPerPost;
alter table UserSubmission drop column groupToPost;
alter table UserSubmission drop column groupToModerate;
alter table UserSubmission drop column editTimeout;
alter table UserSubmission drop column karmaPerPost;
alter table Article drop column karmaPerPost;
alter table Article drop column editTimeout;
alter table Article drop column groupToModerate;
alter table Article drop column groupToPost;
insert into international values (570,'WebGUI','English','Lock Thread');
insert into international values (571,'WebGUI','English','Unlock Thread');
update international set internationalId=572, namespace='WebGUI' where namespace='UserSubmission' and internationalId=24;
update international set internationalId=573, namespace='WebGUI' where namespace='UserSubmission' and internationalId=25;
update international set internationalId=574, namespace='WebGUI' where namespace='UserSubmission' and internationalId=26;
insert into international values (575,'WebGUI','English','Edit');
insert into international values (576,'WebGUI','English','Delete');
update international set internationalId=577, namespace='WebGUI' where namespace='MessageBoard' and internationalId=13;
delete from international where namespace='UserSubmission' and internationalId=42;
delete from international where namespace='UserSubmission' and internationalId=43;
delete from international where namespace='Article' and internationalId=25;
delete from international where namespace='Article' and internationalId=26;
insert into international values (578,'WebGUI','English','You have a pending message to approve.');
insert into international values (579,'WebGUI','English','Your message has been approved.');
insert into international values (580,'WebGUI','English','Your message has been denied.');
insert into international values (58,'UserSubmission','English','Previous Submission');
insert into international values (59,'UserSubmission','English','Next Submission');
insert into international values (1,'Product','English','Product');
create table Product_specification ( wobjectId int not null, productSpecificationId int not null primary key, name varchar(255), value varchar(255), units varchar(255), sequenceNumber int not null);
create table Product_feature ( wobjectId int not null, productFeatureId int not null primary key, feature varchar(255), sequenceNumber int not null);
create table Product (wobjectId int not null primary key, image1 varchar(255), image2 varchar(255), image3 varchar(255), brochure varchar(255), manual varchar(255), warranty varchar(255), price varchar(255), productNumber varchar(255));
insert into incrementer values ('productFeatureId',1000);
insert into incrementer values ('productSpecificationId',1000);
create table Product_accessory ( wobjectId int not null, AccessoryWobjectId int not null, sequenceNumber int not null, primary key (wobjectId, AccessoryWobjectId));
create table Product_related ( wobjectId int not null, RelatedWobjectId int not null, sequenceNumber int not null, primary key (wobjectId, RelatedWobjectId));
insert into international values (7,'Product','English','Product Image 1');
insert into international values (8,'Product','English','Product Image 2');
insert into international values (9,'Product','English','Product Image 3');
insert into international values (5,'Product','English','Are you certain you wish to delete this specification?');
insert into international values (4,'Product','English','Are you certain you wish to delete the relationship to this related product?');
insert into international values (3,'Product','English','Are you certain you wish to delete this feature?');
insert into international values (2,'Product','English','Are you certain you wish to delete the relationship to this accessory?');
insert into international values (6,'Product','English','Edit Product');
insert into international values (10,'Product','English','Price');
insert into international values (11,'Product','English','Product Number');
insert into international values (12,'Product','English','Are you certain you wish to delete this file?');
insert into international values (13,'Product','English','Brochure');
insert into international values (14,'Product','English','Manual');
insert into international values (15,'Product','English','Warranty');
insert into international values (16,'Product','English','Add Accessory');
insert into international values (17,'Product','English','Accessory');
insert into international values (18,'Product','English','Add another accessory?');
insert into international values (21,'Product','English','Add another related product?');
insert into international values (19,'Product','English','Add Related Product');
insert into international values (20,'Product','English','Related Product');
insert into international values (22,'Product','English','Edit Feature');
insert into international values (23,'Product','English','Feature');
insert into international values (24,'Product','English','Add another feature?');
insert into international values (25,'Product','English','Edit Specification');
insert into international values (26,'Product','English','Label');
insert into international values (27,'Product','English','Specification');
insert into international values (28,'Product','English','Add another specification?');
insert into international values (29,'Product','English','Units');
insert into international values (30,'Product','English','Features');
insert into international values (31,'Product','English','Specifications');
insert into international values (32,'Product','English','Accessories');
insert into international values (33,'Product','English','Related Products');
insert into international values (34,'Product','English','Add a feature.');
insert into international values (35,'Product','English','Add a specification.');
insert into international values (36,'Product','English','Add an accessory.');
insert into international values (37,'Product','English','Add a related product.');
insert into international values (581,'WebGUI','English','Add New Value');
insert into international values (582,'WebGUI','English','Leave Blank');









