insert into webguiVersion values ('4.8.0','upgrade',unix_timestamp());
update incrementer set nextValue=100000 where incrementerId='messageId';
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (748,1,'WebGUI','User Count', 1036553016);
INSERT INTO template VALUES (5,'Classifieds','<tmpl_var searchForm>\r\n\r\n<tmpl_if post>\r\n    <tmpl_var post> ·\r\n</tmpl_if>\r\n<tmpl_var search><p/>\r\n\r\n<table width=\"100%\" cellpadding=3 cellspacing=0 border=0>\r\n<tr>\r\n<tmpl_loop submissions_loop>\r\n\r\n<td valign=\"top\" class=\"tableData\" width=\"33%\" style=\"border: 1px dotted black; padding: 10px;\">\r\n  <h2><a href=\"<tmpl_var submission.url>\"><tmpl_var submission.title></a></h2>\r\n  <tmpl_if submission.currentUser>\r\n    (<tmpl_var submission.status>)\r\n  </tmpl_if>\r\n<br/>\r\n  <tmpl_if submission.thumbnail>\r\n       <a href=\"<tmpl_var submission.url>\"><img src=\"<tmpl_var submission.thumbnail>\" border=\"0\"/ align=\"right\"></a><br/>\r\n  </tmpl_if>\r\n<tmpl_var submission.content>\r\n</td>\r\n\r\n<tmpl_if submission.thirdColumn>\r\n  </tr><tr>\r\n</tmpl_if>\r\n\r\n</tmpl_loop>\r\n</tr>\r\n</table>\r\n\r\n<tmpl_if multiplePages>\r\n  <div class=\"pagination\">\r\n    <tmpl_var previousPage>  · <tmpl_var pageList> · <tmpl_var nextPage>\r\n  </div>\r\n</tmpl_if>\r\n','USS');
INSERT INTO template VALUES (6,'Guest Book','<tmpl_if post>\r\n    <tmpl_var post><p>\r\n</tmpl_if>\r\n\r\n<tmpl_loop submissions_loop>\r\n\r\n<tmpl_if __odd__>\r\n<div class=\"highlight\">\r\n</tmpl_if>\r\n\r\n<b>On <tmpl_var submission.date> <a href=\"<tmpl_var submission.userProfile>\"><tmpl_var submission.username></a> from <a href=\"<tmpl_var submission.url>\">the <tmpl_var submission.title> department</a> wrote</b>, <i><tmpl_var submission.content></i>\r\n\r\n<tmpl_if __odd__>\r\n</div >\r\n</tmpl_if>\r\n\r\n<p/>\r\n\r\n</tmpl_loop>\r\n\r\n<tmpl_if multiplePages>\r\n  <div class=\"pagination\">\r\n    <tmpl_var previousPage> · <tmpl_var nextPage>\r\n  </div>\r\n</tmpl_if>\r\n','USS');
delete from international where namespace='Article' and internationalId=14;
delete from international where namespace='Article' and internationalId=15;
delete from international where namespace='Article' and internationalId=16;
delete from international where namespace='Article' and internationalId=17;
alter table Article add column templateId int not null default 1;
update Article set templateId=2 where alignImage='center';
update Article set templateId=3 where alignImage='left';
alter table Article drop column alignImage;
INSERT INTO template VALUES (1,'Default Article','<tmpl_if image>\r\n  <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tr><td class=\"content\">\r\n  <img src=\"<tmpl_var image>\" align=\"right\" border=\"0\">\r\n</tmpl_if>\r\n\r\n<tmpl_if description>\r\n  <tmpl_var description><p/>\r\n</tmpl_if>\r\n\r\n<tmpl_if link.url>\r\n  <tmpl_if link.title>\r\n    <p><a href=\"<tmpl_var linkUrl>\"><tmpl_var linkTitle></a>\r\n  </tmpl_if>\r\n</tmpl_if>\r\n\r\n<tmpl_var attachment.box>\r\n\r\n<tmpl_if image>\r\n  </td></tr></table>\r\n</tmpl_if>\r\n\r\n<tmpl_if allowDiscussion>\r\n  <p><table width=\"100%\" cellspacing=\"2\" cellpadding=\"1\" border=\"0\">\r\n  <tr><td align=\"center\" width=\"50%\" class=\"tableMenu\"><a href=\"<tmpl_var replies.URL>\"><tmpl_var replies.label> (<tmpl_var replies.count>)</a></td>\r\n  <td align=\"center\" width=\"50%\" class=\"tableMenu\"><a href=\"<tmpl_var post.url>\"><tmpl_var post.label></a></td></tr>\r\n  </table>\r\n</tmpl_if>\r\n','Article');
INSERT INTO template VALUES (2,'Center Image','<tmpl_if image>\r\n  <div align=\"center\"><img src=\"<tmpl_var image>\" border=\"0\"></div>\r\n</tmpl_if>\r\n\r\n<tmpl_if description>\r\n  <tmpl_var description><p/>\r\n</tmpl_if>\r\n\r\n<tmpl_if link.url>\r\n  <tmpl_if link.title>\r\n    <p><a href=\"<tmpl_var linkUrl>\"><tmpl_var linkTitle></a>\r\n  </tmpl_if>\r\n</tmpl_if>\r\n\r\n<tmpl_var attachment.box>\r\n\r\n\r\n<tmpl_if allowDiscussion>\r\n  <p><table width=\"100%\" cellspacing=\"2\" cellpadding=\"1\" border=\"0\">\r\n  <tr><td align=\"center\" width=\"50%\" class=\"tableMenu\"><a href=\"<tmpl_var replies.URL>\"><tmpl_var replies.label> (<tmpl_var replies.count>)</a></td>\r\n  <td align=\"center\" width=\"50%\" class=\"tableMenu\"><a href=\"<tmpl_var post.url>\"><tmpl_var post.label></a></td></tr>\r\n  </table>\r\n</tmpl_if>\r\n','Article');
INSERT INTO template VALUES (3,'Left Align Image','<tmpl_if image>\r\n  <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tr><td class=\"content\">\r\n  <img src=\"<tmpl_var image>\" align=\"left\" border=\"0\">\r\n</tmpl_if>\r\n\r\n<tmpl_if description>\r\n  <tmpl_var description><p/>\r\n</tmpl_if>\r\n\r\n<tmpl_if link.url>\r\n  <tmpl_if link.title>\r\n    <p><a href=\"<tmpl_var linkUrl>\"><tmpl_var linkTitle></a>\r\n  </tmpl_if>\r\n</tmpl_if>\r\n\r\n<tmpl_var attachment.box>\r\n\r\n<tmpl_if image>\r\n  </td></tr></table>\r\n</tmpl_if>\r\n\r\n<tmpl_if allowDiscussion>\r\n  <p><table width=\"100%\" cellspacing=\"2\" cellpadding=\"1\" border=\"0\">\r\n  <tr><td align=\"center\" width=\"50%\" class=\"tableMenu\"><a href=\"<tmpl_var replies.URL>\"><tmpl_var replies.label> (<tmpl_var replies.count>)</a></td>\r\n  <td align=\"center\" width=\"50%\" class=\"tableMenu\"><a href=\"<tmpl_var post.url>\"><tmpl_var post.label></a></td></tr>\r\n  </table>\r\n</tmpl_if>\r\n','Article');
create table userSessionScratch (sessionId varchar(60), name varchar(35), value varchar(255));
create table pageStatistics (
dateStamp int,
userId int,
username varchar(35),
ipAddress varchar(15),
userAgent varchar(255),
referer text,
pageId int,
pageTitle varchar(255)
);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (749,1,'WebGUI','Track page statistics?', 1036736182);
insert into settings values ("trackPageStatistics",0);
alter table pageStatistics add column wobjectId int;
alter table pageStatistics add column function varchar(60);
alter table images rename collateral;
alter table imageGroup rename collateralFolder;
alter table collateral change imageId collateralId int not null;
alter table collateral change imageGroupId collateralFolderId int not null;
alter table collateralFolder change imageGroupId collateralFolderId int not null;
alter table collateral add column collateralType varchar(30) not null default 'image';
update incrementer set incrementerId='collateralId' where incrementerId='imageId';
update incrementer set incrementerId='collateralFolderId' where incrementerId='imageGroupId';
insert into help (helpId,namespace,titleId,bodyId,seeAlso) values (49, 'WebGUI', 785, 786, NULL);
delete from international where languageId=1 and namespace='WebGUI' and internationalId=394;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (394,1,'WebGUI','Manage collateral.', 1036954925);
delete from international where namespace='WebGUI' and internationalId=393;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (785,1,'WebGUI','Collateral, Manage', 1036954767);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (786,1,'WebGUI','', 1036954767);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (784,1,'WebGUI','Thumbnail', 1036954393);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (783,1,'WebGUI','Type', 1036954378);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (782,1,'WebGUI','Any', 1036913053);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (781,1,'WebGUI','Snippet', 1036912954);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (780,1,'WebGUI','File', 1036912946);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (779,1,'WebGUI','Image', 1036912938);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (778,1,'WebGUI','Folder Description', 1036906132);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (777,1,'WebGUI','Folder Id', 1036905972);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (776,1,'WebGUI','Edit Folder', 1036905944);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (775,1,'WebGUI','Are you certain you wish to delete this folder and move its contents to it\'s parent folder?', 1036903002);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (774,1,'WebGUI','Are you certain you wish to delete this collateral? It cannot be recovered once deleted.', 1036902945);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (773,1,'WebGUI','File', 1036893165);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (772,1,'WebGUI','Edit File', 1036893140);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (771,1,'WebGUI','Snippet', 1036893079);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (770,1,'WebGUI','Edit Snippet', 1036893050);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (769,1,'WebGUI','Organize in Folder', 1036893015);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (768,1,'WebGUI','Name', 1036892946);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (767,1,'WebGUI','Collateral Id', 1036892929);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (766,1,'WebGUI','Back to collateral list.', 1036892898);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (765,1,'WebGUI','Delete this collateral item.', 1036892866);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (764,1,'WebGUI','Edit this collateral item.', 1036892856);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (763,1,'WebGUI','Add a snippet.', 1036892785);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (762,1,'WebGUI','Add a file.', 1036892774);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (761,1,'WebGUI','Add an image.', 1036892765);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (760,1,'WebGUI','Delete this folder.', 1036892740);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (759,1,'WebGUI','Edit this folder.', 1036892731);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (758,1,'WebGUI','Add a folder.', 1036892705);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (757,1,'WebGUI','Manage Collateral', 1036892669);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (756,1,'WebGUI','Back to group list.', 1036867726);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (754,1,'WebGUI','Manage the users in this group.', 1036866994);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (753,1,'WebGUI','Edit this group.', 1036866979);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (752,1,'WebGUI','View this user\'s profile.', 1036864965);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (751,1,'WebGUI','Become this user.', 1036864905);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (750,1,'WebGUI','Delete this user.', 1036864742);
delete from international where namespace='WebGUI' and internationalId=393;
delete from international where namespace='WebGUI' and internationalId=396;
delete from international where namespace='WebGUI' and internationalId=397;
delete from international where namespace='WebGUI' and internationalId=389;
delete from international where namespace='WebGUI' and internationalId=383;
delete from international where namespace='WebGUI' and internationalId=544;
delete from international where namespace='WebGUI' and internationalId=545;
delete from international where namespace='WebGUI' and internationalId=546;
delete from international where namespace='WebGUI' and internationalId=547;
delete from international where namespace='WebGUI' and internationalId=548;
delete from international where namespace='WebGUI' and internationalId=549;
delete from international where namespace='WebGUI' and internationalId=550;
delete from international where namespace='WebGUI' and internationalId=392;
delete from international where namespace='WebGUI' and internationalId=382;
delete from international where namespace='WebGUI' and internationalId=390;
delete from international where namespace='WebGUI' and internationalId=673;
delete from international where namespace='WebGUI' and internationalId=628;
delete from international where namespace='WebGUI' and internationalId=686;
delete from international where namespace='WebGUI' and internationalId=641;
delete from international where namespace='WebGUI' and internationalId=676;
delete from international where namespace='WebGUI' and internationalId=631;
delete from help where namespace='WebGUI' and helpId=26;
delete from help where namespace='WebGUI' and helpId=23;
delete from help where namespace='WebGUI' and helpId=36;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (790,1,'WebGUI','Delete this profile category.', 1036964807);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (789,1,'WebGUI','Edit this profile category.', 1036964795);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (788,1,'WebGUI','Delete this profile field.', 1036964681);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (787,1,'WebGUI','Edit this profile field.', 1036964659);
delete from settings where name='imageManagersGroup';
delete from international where languageId=1 and namespace='WebGUI' and internationalId=586;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (586,1,'WebGUI','Manage Translations', 1036971445);
delete from international where languageId=1 and namespace='WebGUI' and internationalId=589;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (589,1,'WebGUI','Edit Translation', 1036971172);
delete from international where languageId=1 and namespace='WebGUI' and internationalId=598;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (598,1,'WebGUI','Edit this translation.', 1036971142);
delete from international where languageId=1 and namespace='WebGUI' and internationalId=584;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (584,1,'WebGUI','Add a new translation.', 1036971092);
delete from international where languageId=1 and namespace='WebGUI' and internationalId=718;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (718,1,'WebGUI','Export this translation.', 1036970877);
delete from international where languageId=1 and namespace='WebGUI' and internationalId=593;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (593,1,'WebGUI','Submit this translation.', 1036970850);
delete from international where languageId=1 and namespace='WebGUI' and internationalId=791;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (791,1,'WebGUI','Delete this translation.', 1036970806);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (802,1,'WebGUI','WebGUI is not currently tracking page statistics. You can enable this feature in the settings.', 1036979395);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (801,1,'WebGUI','Wobject Interactions', 1036978843);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (800,1,'WebGUI','Unique Visitors', 1036978829);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (799,1,'WebGUI','Page Views', 1036978804);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (798,1,'WebGUI','Page Title', 1036978688);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (797,1,'WebGUI','View traffic statistics.', 1036978191);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (796,1,'WebGUI','View page statistics.', 1036978043);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (795,1,'WebGUI','Roots', 1036972103);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (794,1,'WebGUI','Packages', 1036971944);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (793,1,'WebGUI','Pieces of Collateral', 1036971785);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (792,1,'WebGUI','Templates', 1036971696);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (805,1,'WebGUI','Delete this style.', 1037075787);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (804,1,'WebGUI','Copy this style.', 1037075775);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (803,1,'WebGUI','Edit this style.', 1037075751);
insert into incrementer values ("Survey_id",1000);
alter table Survey_answer change wobjectId Survey_id int;
alter table Survey_question change wobjectId Survey_id int;
alter table Survey_response change wobjectId Survey_id int;
alter table Survey add column Survey_id int not null;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (74,1,'Survey','Are you certain you wish to delete all the responses?', 1037574455);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,1,'Survey','Delete all the responses.', 1037573893);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,1,'Survey','Are you certain you wish to delete this user\'s responses?', 1037573460);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (71,1,'Survey','Grade Book', 1037573252);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (70,1,'Survey','Individual Responses', 1037573240);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (69,1,'Survey','Delete this user\'s responses.', 1037573082);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (68,1,'Survey','View reports and exports.', 1037560492);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (67,1,'Survey','User', 1037558860);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (66,1,'Survey','Responses', 1037557127);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (65,1,'Survey','Export composite summary.', 1037556821);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (64,1,'Survey','Export responses.', 1037556721);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (63,1,'Survey','Export questions.', 1037556710);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (62,1,'Survey','Export answers.', 1037556697);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,1,'Survey','View grade book.', 1037556642);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (60,1,'Survey','Back to survey.', 1037556626);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (59,1,'Survey','View statistical overview.', 1037556614);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (58,1,'Survey','Statistical Overview', 1037556179);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (57,1,'Survey','Comments', 1037556124);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (56,1,'Survey','View comments.', 1037555787);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (55,1,'Survey','View responses.', 1037555778);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (54,1,'Survey','Percentage', 1037555267);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (53,1,'Survey','Responses', 1037555255);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (52,1,'Survey','Score', 1037506007);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (51,1,'Survey','Comments?', 1037499470);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (50,1,'Survey','Next', 1037499410);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (49,1,'Survey','You may not take this quiz at this time.', 1037499363);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (48,1,'Survey','You are not currently eligible to participate in this survey. ', 1037499301);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (47,1,'Survey','You have completed this quiz.', 1037499131);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (46,1,'Survey','Thank you for taking the time to complete our survey.', 1037499049);
delete from international where languageId=1 and namespace='Survey' and internationalId=35;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (35,1,'Survey','Somewhat Agree', 1037498927);
delete from international where languageId=1 and namespace='Survey' and internationalId=34;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (34,1,'Survey','Agree', 1037498914);
delete from international where languageId=1 and namespace='Survey' and internationalId=38;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (38,1,'Survey','Strongly Disagree', 1037498903);
delete from international where languageId=1 and namespace='Survey' and internationalId=37;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (37,1,'Survey','Disagree', 1037498886);
delete from international where languageId=1 and namespace='Survey' and internationalId=36;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (36,1,'Survey','Somewhat Disagree', 1037498872);
delete from international where languageId=1 and namespace='Survey' and internationalId=33;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (33,1,'Survey','Strongly Agree', 1037498857);
delete from international where languageId=1 and namespace='Survey' and internationalId=31;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (31,1,'Survey','True', 1037498842);
delete from international where languageId=1 and namespace='Survey' and internationalId=32;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (32,1,'Survey','False', 1037498832);
delete from international where languageId=1 and namespace='Survey' and internationalId=42;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (42,1,'Survey','Occasionally', 1037574859);
delete from international where languageId=1 and namespace='Survey' and internationalId=39;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (39,1,'Survey','Not Applicable', 1037574804);
delete from international where languageId=1 and namespace='Survey' and internationalId=41;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (41,1,'Survey','Frequently', 1037574786);
delete from international where languageId=1 and namespace='Survey' and internationalId=43;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (43,1,'Survey','Never', 1037574752);
delete from international where languageId=1 and namespace='Survey' and internationalId=40;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (40,1,'Survey','Always', 1037574725);
delete from help where helpId=1 and namespace='FileManager';
insert into help (helpId,namespace,titleId,bodyId,seeAlso) values (1, 'FileManager', 61, 71, '2,FileManager;21,WebGUI;');
delete from help where helpId=21 and namespace='WebGUI';
insert into help (helpId,namespace,titleId,bodyId,seeAlso) values (21, 'WebGUI', 671, 626, '1,Article;1,FileManager;1,EventsCalendar;1,ExtraColumn;1,FAQ;1,Item;1,LinkList;19,WebGUI;1,MailForm;1,MessageBoard;1,Poll;1,Product;1,SiteMap;1,SQLReport;18,WebGUI;1,SyndicatedContent;1,USS;1,WobjectProxy;27,WebGUI;14,WebGUI;');
delete from help where helpId=47 and namespace='WebGUI';
insert into help (helpId,namespace,titleId,bodyId,seeAlso) values (47, 'WebGUI', 697, 698, '1,Article;17,WebGUI;1,MessageBoard;1,Poll;2,WebGUI;1,USS;');
delete from help where helpId=2 and namespace='FileManager';
insert into help (helpId,namespace,titleId,bodyId,seeAlso) values (2, 'FileManager', 72, 73, '1,FileManager;');
create table groupGroupings (
	groupId int not null,
	inGroup int not null
);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (813,1,'WebGUI','Groups In This Group', 1037583186);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (812,1,'WebGUI','Your message has been sent.', 1037580328);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (811,1,'WebGUI','From', 1037580145);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (810,1,'WebGUI','send', 1037579743);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (809,1,'WebGUI','Email Group', 1037579611);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (808,1,'WebGUI','Email this group.', 1037579487);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (807,1,'WebGUI','Manage the groups in this group.', 1037579473);
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (806,1,'WebGUI','Delete this group.', 1037579396);





