insert into webguiVersion values ('6.0.3','upgrade',unix_timestamp());
delete from international where internationalId=981 and namespace='WebGUI';
INSERT INTO international VALUES (981,'WebGUI',1,'Manage database links.',1056151382,NULL);
delete from replacements where replacementId=0;

delete from international where languageId=13 and namespace='Product' and internationalId=26;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (26,13,'Product','', 1085386749);
delete from international where languageId=13 and namespace='Product' and internationalId=31;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (31,13,'Product','', 1085386742);
delete from international where languageId=13 and namespace='Product' and internationalId=21;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (21,13,'Product','', 1085386734);
delete from international where languageId=13 and namespace='Product' and internationalId=20;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (20,13,'Product','', 1085386728);
delete from international where languageId=13 and namespace='Product' and internationalId=19;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (19,13,'Product','', 1085386720);
delete from international where languageId=13 and namespace='FileManager' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,13,'FileManager','Muokkaa tallennusta', 1085386392);
delete from international where languageId=13 and namespace='FileManager' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,13,'FileManager','RyhmÃ¤ joka saa ladata', 1085386264);
delete from international where languageId=13 and namespace='Navigation' and internationalId=18;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (18,13,'Navigation','Muokkaa tÃ¤tÃ¤ navigointia.', 1083593265);
delete from international where languageId=13 and namespace='Navigation' and internationalId=27;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (27,13,'Navigation','Max syvyys', 1083593246);
delete from international where languageId=13 and namespace='Navigation' and internationalId=24;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (24,13,'Navigation','Tunniste', 1083593222);
delete from international where languageId=13 and namespace='Navigation' and internationalId=23;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (23,13,'Navigation','Navigoinnin ominaisuudet', 1083593203);
delete from international where languageId=13 and namespace='Navigation' and internationalId=22;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (22,13,'Navigation','Muokkaa navigointia', 1083593188);
delete from international where languageId=13 and namespace='Navigation' and internationalId=21;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (21,13,'Navigation','Listaa navigoinnit.', 1083593172);
delete from international where languageId=13 and namespace='Navigation' and internationalId=19;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (19,13,'Navigation','Kopioi tÃ¤mÃ¤ navigointi.', 1083593157);
delete from international where languageId=13 and namespace='Navigation' and internationalId=20;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (20,13,'Navigation','Poista tÃ¤mÃ¤ navigointi.', 1083593134);
delete from international where languageId=13 and namespace='Poll' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,13,'Poll','Gallup mallipohja', 1083593030);
delete from international where languageId=13 and namespace='Survey' and internationalId=86;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (86,13,'Survey','Eteneminen', 1083592968);
delete from international where languageId=13 and namespace='Survey' and internationalId=84;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (84,13,'Survey','Max vastausta / kÃ¤yttÃ¤jÃ¤', 1083592916);
delete from international where languageId=13 and namespace='Survey' and internationalId=83;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (83,13,'Survey','KysymyksiÃ¤ / sivu', 1083592869);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1021;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1021,13,'WebGUI','Arvostele viestiÃ¤', 1083592730);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1018;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1018,13,'WebGUI','Aloita uusi ketju', 1083592663);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1020;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1020,13,'WebGUI','Arvostelu', 1083592616);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1027;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1027,13,'WebGUI','Salli tÃ¤ydennykset?', 1083592553);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1012;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1012,13,'WebGUI','Lukitse tÃ¤mÃ¤ ketju?', 1083592534);
delete from international where languageId=13 and namespace='WSClient' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,13,'WSClient','Virheenselvitys?', 1083592386);
delete from international where languageId=13 and namespace='WSClient' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,13,'WSClient','EsikÃ¤sittele kyselyn makrot?', 1083592364);
delete from international where languageId=13 and namespace='WobjectProxy' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,13,'WobjectProxy','Kumoa kuvaus?', 1083592329);
delete from international where languageId=13 and namespace='WobjectProxy' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,13,'WobjectProxy','Kumoa otsikko?', 1083592301);
delete from international where languageId=13 and namespace='WobjectProxy' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,13,'WobjectProxy','Kumoa mallipohja?', 1083592288);
delete from international where languageId=13 and namespace='WobjectProxy' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,13,'WobjectProxy','Kumoa "NÃ¤ytÃ¤ otsikko"?', 1083592272);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1085;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1085,13,'WebGUI','Sivutus mallipohjan muuttujat', 1083592091);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1084;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1084,13,'WebGUI','Oletus', 1083592066);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1083;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1083,13,'WebGUI','Uusi sisÃ¤ltÃ¶', 1083592055);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1082;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1082,13,'WebGUI','LeikepÃ¶ytÃ¤', 1083592029);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1081;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1081,13,'WebGUI','PÃ¤Ã¤kÃ¤yttÃ¤jÃ¤n tyyli', 1083592018);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1080;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1080,13,'WebGUI','KÃ¤ytÃ¤tkÃ¶ pÃ¤Ã¤kÃ¤yttÃ¤jÃ¤n tyyliÃ¤?', 1083592003);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1079;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1079,13,'WebGUI','Tulostettava muoto', 1083591955);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1072;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1072,13,'WebGUI','SÃ¤hkÃ¶postiosoite on jo kÃ¤ytÃ¶ssÃ¤. KÃ¤ytÃ¤ eri sÃ¤hkÃ¶postiosoitetta.', 1083591904);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1052;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1052,13,'WebGUI','Muokkaa tÃ¤ydennystÃ¤', 1083591766);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1053;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1053,13,'WebGUI','Hallitse tÃ¤ydennyksiÃ¤', 1083591751);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1051;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1051,13,'WebGUI','Korvaa tÃ¤llÃ¤', 1083591681);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1026;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1026,13,'WebGUI','Salli muotoilu?', 1083591551);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=845;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (845,13,'WebGUI','Tyylimakrot', 1083591451);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=841;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (841,13,'WebGUI','Navigointimakrot', 1083591446);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=839;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (839,13,'WebGUI','Ohjelmoijan makrot', 1083591438);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=655;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (655,13,'WebGUI','KÃ¤yttÃ¤jÃ¤, LisÃ¤Ã¤/Muokkaa', 1083591401);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=652;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (652,13,'WebGUI','KÃ¤yttÃ¤jÃ¤asetukset, muokkaa', 1083591393);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=642;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (642,13,'WebGUI','Sivu, LisÃ¤Ã¤/Muokkaa', 1083591383);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,13,'Auth/WebGUI','Salasana ei voi olla "password".', 1083591365);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=4;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (4,13,'Auth/WebGUI','Salasanaa ei voi jÃ¤ttÃ¤Ã¤ tyhjÃ¤ksi.', 1083591357);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,13,'Auth/WebGUI','Salasanasi ei tÃ¤smÃ¤Ã¤. YritÃ¤ uudelleen.', 1083591346);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,13,'Auth/WebGUI','Salasana (vahvista)', 1083591337);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,13,'Auth/WebGUI','WebGUI tunnistautumisen lisÃ¤asetukset', 1083591329);
delete from international where languageId=13 and namespace='EventsCalendar' and internationalId=94;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (94,13,'EventsCalendar','Tapahtumakalenterin mallipohja', 1083591247);
delete from international where languageId=13 and namespace='EventsCalendar' and internationalId=96;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (96,13,'EventsCalendar','Tapahtuman mallipohja', 1083591238);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=8;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (8,13,'Auth/WebGUI','Salasanasi on vanhentunut', 1078874691);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,13,'Auth/WebGUI','Salasanan pituus pitÃ¤Ã¤ olla vÃ¤hintÃ¤Ã¤n', 1078874676);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=6;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (6,13,'Auth/WebGUI','Salli salasanan alustus?', 1078874642);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=22;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (22,13,'Auth/WebGUI','Ei pÃ¤ivitettÃ¤viÃ¤ kenttiÃ¤.', 1078874612);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=21;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (21,13,'Auth/WebGUI','Salli kÃ¤yttÃ¤jÃ¤n muuttaa kÃ¤yttÃ¤jÃ¤tunnus?', 1078874591);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=20;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (20,13,'Auth/WebGUI','Salli kÃ¤yttÃ¤jÃ¤n muuttaa salasana?', 1078874562);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=19;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (19,13,'Auth/WebGUI','Salli kÃ¤yttÃ¤jÃ¤n muuttaa kÃ¤yttÃ¤jÃ¤tunnus?', 1078874534);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=18;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (18,13,'Auth/WebGUI','Salli kÃ¤yttÃ¤jÃ¤n vaihtaa salasana?', 1078874514);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=17;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (17,13,'Auth/WebGUI','Salasana muutettu', 1078874477);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=15;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (15,13,'Auth/WebGUI','Salasanan min. pituus', 1078874419);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=14;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (14,13,'Auth/WebGUI','Salasanan min. pituus.', 1078874394);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=13;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (13,13,'Auth/WebGUI','Salli salasanan alustus?', 1078874370);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,13,'Auth/WebGUI','Et voi kÃ¤yttÃ¤Ã¤ vanhaa salasanaasi uudestaan.', 1078874345);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=11;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (11,13,'Auth/WebGUI','Uusi salasana', 1078874231);
delete from international where languageId=13 and namespace='Auth/WebGUI' and internationalId=10;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (10,13,'Auth/WebGUI','Vanha salasana', 1078874219);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=935;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (935,13,'WebGUI','Tallennetttava tiedosto ei ole kelvollinen teema-tiedosto.', 1069777814);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=941;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (941,13,'WebGUI','Valintaruutulista', 1069777750);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=942;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (942,13,'WebGUI','Valintanappilista', 1069777729);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=943;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (943,13,'WebGUI','Valintaruutu', 1069777679);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=974;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (974,13,'WebGUI','Voiko kÃ¤yttÃ¤jÃ¤t lisÃ¤tÃ¤ itsensÃ¤?', 1069777603);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=983;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (983,13,'WebGUI','Muokkaa tÃ¤tÃ¤ tietokantayhteyttÃ¤.', 1069777531);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=984;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (984,13,'WebGUI','Kopioi tÃ¤mÃ¤ tietokantayhteys.', 1069777515);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=985;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (985,13,'WebGUI','Poista tÃ¤mÃ¤ tietokantayhteys.', 1069777502);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=986;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (986,13,'WebGUI','Takaisin tietokantayhteyksiin.', 1069777487);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=987;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (987,13,'WebGUI','Poista tietokantayhteys', 1069777466);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=988;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (988,13,'WebGUI','Tahdotko varmasti poistaa tietokantayhteyden? Seuraavat osat kÃ¤yttÃ¤vÃ¤t sitÃ¤, eivÃ¤tkÃ¤ toimi oikein poistamisen jÃ¤lkeen:', 1069777440);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=989;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (989,13,'WebGUI','sivulla', 1069777347);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=991;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (991,13,'WebGUI','Tietokantayhteyden tunnus', 1069777326);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=992;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (992,13,'WebGUI','Otsikko', 1069777299);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=891;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (891,13,'WebGUI','KiellÃ¤ ainoastaan makrot.', 1069777281);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=818;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (818,13,'WebGUI','Deaktivoitu', 1069776564);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=801;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (801,13,'WebGUI','Wobjektin vuorovaikutukset', 1069776519);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1069;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1069,13,'WebGUI','KÃ¤ytettÃ¤vÃ¤ hostname', 1069776319);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=993;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (993,13,'WebGUI','DSN', 1069776273);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1011;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1011,13,'WebGUI','Koodi', 1069776171);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1010;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1010,13,'WebGUI','Teksti', 1069776160);
delete from international where languageId=13 and namespace='SiteMap' and internationalId=7;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (7,13,'SiteMap','AakkosjÃ¤rjestys?', 1068724340);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1046;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1046,13,'WebGUI','Arkistoitu', 1068663769);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1041;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1041,13,'WebGUI','Avaa lukitus', 1068663750);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1040;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1040,13,'WebGUI','Lukitse', 1068663738);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1044;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1044,13,'WebGUI','EtsintÃ¤sivun mallipohja', 1068663730);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1039;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1039,13,'WebGUI','Takaisin', 1068663673);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1043;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1043,13,'WebGUI','Koska arkistoidaan', 1068663665);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1042;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1042,13,'WebGUI','Postitusta/sivu', 1068663629);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=898;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (898,13,'WebGUI','Site Icon', 1068663597);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=513;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (513,13,'WebGUI','Edellinen viestiketju', 1068663528);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=512;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (512,13,'WebGUI','Seuraava viestiketju', 1068663522);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=529;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (529,13,'WebGUI','tulosta', 1068663516);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=873;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (873,13,'WebGUI','Liity keskusteluun', 1068663489);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=874;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (874,13,'WebGUI','Eroa viestiketjusta', 1068663482);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=875;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (875,13,'WebGUI','Uusi viesti on saapunut keskusteluun johon olet liittynyt.', 1068663473);
delete from international where languageId=13 and namespace='MessageBoard' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,13,'MessageBoard','Keskustelualueen mallipohja', 1068663449);
delete from international where languageId=13 and namespace='MessageBoard' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,13,'MessageBoard','Keskustelualue, LisÃ¤Ã¤/Muokkaa', 1068663423);
delete from international where languageId=13 and namespace='EventsCalendar' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,13,'EventsCalendar','Tapahtumakalenteri, LisÃ¤Ã¤/Muokkaa', 1068663411);
delete from international where languageId=13 and namespace='Article' and internationalId=61;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (61,13,'Article','Artikkeli, LisÃ¤Ã¤/Muokkaa', 1068663397);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=430;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (430,13,'WebGUI','Viimeksi kÃ¤ytetty', 1065225099);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=435;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (435,13,'WebGUI','Istunnon tunnus', 1065225061);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=448;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (448,13,'WebGUI','Sivuston rakenne', 1065224886);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=528;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (528,13,'WebGUI','Mallin nimi', 1065224772);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=445;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (445,13,'WebGUI','Asetukset', 1065224592);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=133;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (133,13,'WebGUI','Muokkaa viestinvÃ¤litys asetuksia', 1065224474);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=135;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (135,13,'WebGUI','LÃ¤htevÃ¤n postin palvelin (SMTP)', 1065224408);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=467;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (467,13,'WebGUI','Haluatko varmasti poistaa tÃ¤mÃ¤n kentÃ¤n ja kaiken tiedon joka on liitetty siihen?', 1065224234);
delete from international where languageId=13 and namespace='WebGUI/Profile' and internationalId=467;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (467,13,'WebGUI/Profile','Haluatko varmasti poistaa tÃ¤mÃ¤n kentÃ¤n ja kaiken tiedon joka on liitetty siihen?', 1065224204);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=775;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (775,13,'WebGUI','Haluatko varmasti poistaa tÃ¤mÃ¤n kansion? Poistaminen on pysyvÃ¤Ã¤.', 1065224131);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=774;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (774,13,'WebGUI','Haluatko varmasti poistaa tÃ¤mÃ¤n kokoelmasta? Poistamisen jÃ¤lkeen sitÃ¤ ei voi palauttaa.', 1065224125);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=60;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (60,13,'WebGUI','Haluatko varmasti poistaa kÃ¤yttÃ¤jÃ¤tunnuksesi? Jos jatkat, kÃ¤yttÃ¤jÃ¤tunnuksesi poistetaan pysyvÃ¤sti.', 1065224118);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=588;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (588,13,'WebGUI','Haluatko varmasti lÃ¤hettÃ¤Ã¤ kÃ¤Ã¤nnÃ¶ksesi Plain Black:ille heidÃ¤n viralliseen WebGUI jakeluun. Painamalla "KyllÃ¤" annat samalla Plain Black:ille tÃ¤ydet oikeudet kÃ¤yttÃ¤Ã¤ kÃ¤Ã¤nnÃ¶stÃ¤si virallisissa WebGUI versioissa.', 1065224110);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=587;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (587,13,'WebGUI','Haluatko varmasti poistaa tÃ¤mÃ¤n kielen ja kaikki sen opasteet ja kÃ¤Ã¤nnÃ¶kset?', 1065224092);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=43;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (43,13,'WebGUI','Haluatko varmasti poistaa tÃ¤mÃ¤n sisÃ¤llÃ¶n?', 1065224075);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=401;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (401,13,'WebGUI','Haluatko varmasti poistaa tÃ¤mÃ¤n ja kaikki sen alla olevat viestit?', 1065224068);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=167;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (167,13,'WebGUI','Haluatko varmasti poistaa tÃ¤mÃ¤n kÃ¤yttÃ¤jÃ¤n? Kaikki kÃ¤yttÃ¤jÃ¤n tiedot poistetaan jos jatkat.', 1065224062);
delete from international where languageId=13 and namespace='Survey' and internationalId=74;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (74,13,'Survey','Haluatko varmasti poistaa kaikki vastaukset?', 1065224048);
delete from international where languageId=13 and namespace='Survey' and internationalId=72;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (72,13,'Survey','Haluatko varmasti poistaa tÃ¤mÃ¤n kÃ¤yttÃ¤jÃ¤n vastaukset?', 1065224041);
delete from international where languageId=13 and namespace='Survey' and internationalId=45;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (45,13,'Survey','Haluatko varmasti poistaa tÃ¤mÃ¤n kysymyksen ja sen vastaukset?', 1065224034);
delete from international where languageId=13 and namespace='Product' and internationalId=5;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (5,13,'Product','Haluatko varmasti poistaa tÃ¤mÃ¤n mÃ¤Ã¤rittelyn?', 1065224025);
delete from international where languageId=13 and namespace='Product' and internationalId=3;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (3,13,'Product','Haluatko varmasti poistaa tÃ¤mÃ¤n piirteen?', 1065224016);
delete from international where languageId=13 and namespace='Product' and internationalId=2;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (2,13,'Product','Haluatko varmasti poistaa riippuvuudet tÃ¤hÃ¤n tarvikkeeseen?', 1065224010);
delete from international where languageId=13 and namespace='FileManager' and internationalId=12;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (12,13,'FileManager','Haluatko varmasti poistaa tÃ¤mÃ¤n tiedoston?', 1065223999);
delete from international where languageId=13 and namespace='DataForm' and internationalId=19;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (19,13,'DataForm','Haluatko varmasti poistaa tÃ¤mÃ¤n kentÃ¤n?', 1065223976);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=101;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (101,13,'WebGUI','Haluatko varmasti poistaa tÃ¤mÃ¤n sivun ja kaiken siihen liittyvÃ¤n?', 1065223948);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=352;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (352,13,'WebGUI','', 1065223834);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=347;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (347,13,'WebGUI','', 1065223826);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1,13,'WebGUI','LisÃ¤Ã¤ sisÃ¤ltÃ¶Ã¤...', 1065223636);
delete from international where languageId=13 and namespace='USS' and internationalId=31;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (31,13,'USS','SisÃ¤ltÃ¶', 1065223569);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=85;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (85,13,'WebGUI','Kuvaus', 1065223562);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=748;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (748,13,'WebGUI','KÃ¤yttÃ¤jiÃ¤', 1065223525);
delete from international where languageId=13 and namespace='WebGUI' and internationalId=1024;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (1024,13,'WebGUI','Suodata', 1065187099);
delete from international where languageId=13 and namespace='DataForm' and internationalId=87;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (87,13,'DataForm','NÃ¤ytÃ¤ mallipohja', 1065187049);
delete from international where languageId=13 and namespace='DataForm' and internationalId=82;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (82,13,'DataForm','Tietolomakkeen mallipohja', 1065187000);
delete from international where languageId=13 and namespace='DataForm' and internationalId=77;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (77,13,'DataForm','KentÃ¤n otsikko', 1065186948);
delete from international where languageId=13 and namespace='Auth/LDAP' and internationalId=9;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (9,13,'Auth/LDAP','KÃ¤yttÃ¤jÃ¤ RDN', 1065186827);
delete from international where languageId=13 and namespace='DataForm' and internationalId=74;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (74,13,'DataForm','LÃ¤hetÃ¤ tiedot sÃ¤hkÃ¶postilla?', 1063632515);

delete from international where internationalId=72 and namespace='SQLReport';
insert into international values (72,'SQLReport',1,'SQL Report Template',1082371148,'');
delete from help where helpId=4 and namespace='WebGUI';

