insert into webguiVersion values ('4.6.2','upgrade',unix_timestamp());







#Translation export for WebGUI .

#language

delete from language where languageId=3;
insert into language (languageId,language,characterSet) values (3, 'Nederlands', 'ISO-8859-1');

#international

delete from international where languageId=3;
insert into international (internationalId,languageId,namespace,message) values (1,3,'Article','Artikel');
insert into international (internationalId,languageId,namespace,message) values (1,3,'EventsCalendar','Doorgaan naar gebeurtenis toevoegen?');
insert into international (internationalId,languageId,namespace,message) values (1,3,'ExtraColumn','Extra kolom');
insert into international (internationalId,languageId,namespace,message) values (1,3,'FAQ','Doorgaan naar vraag toevoegen?');
insert into international (internationalId,languageId,namespace,message) values (1,3,'LinkList','Inspringen');
insert into international (internationalId,languageId,namespace,message) values (1,3,'Poll','Stemming');
insert into international (internationalId,languageId,namespace,message) values (1,3,'SQLReport','SQL rapport');
insert into international (internationalId,languageId,namespace,message) values (1,3,'SyndicatedContent','URL naar RSS bestand');
insert into international (internationalId,languageId,namespace,message) values (1,3,'UserSubmission','Wie kan goedkeuren?');
insert into international (internationalId,languageId,namespace,message) values (1,3,'WebGUI','Inhoud toevoegen...');
insert into international (internationalId,languageId,namespace,message) values (2,3,'EventsCalendar','Evenementen kalender');
insert into international (internationalId,languageId,namespace,message) values (2,3,'FAQ','FAQ');
insert into international (internationalId,languageId,namespace,message) values (2,3,'LinkList','Regelafstand');
insert into international (internationalId,languageId,namespace,message) values (2,3,'MessageBoard','Berichtenbord');
insert into international (internationalId,languageId,namespace,message) values (2,3,'SiteMap','Sitemap');
insert into international (internationalId,languageId,namespace,message) values (2,3,'SyndicatedContent','Syndicated content');
insert into international (internationalId,languageId,namespace,message) values (2,3,'UserSubmission','Wie kan bijdragen?');
insert into international (internationalId,languageId,namespace,message) values (2,3,'WebGUI','Pagina');
insert into international (internationalId,languageId,namespace,message) values (3,3,'Article','Begindatum');
insert into international (internationalId,languageId,namespace,message) values (3,3,'ExtraColumn','Tussenruimte');
insert into international (internationalId,languageId,namespace,message) values (3,3,'LinkList','Open in nieuw venster?');
insert into international (internationalId,languageId,namespace,message) values (564,3,'WebGUI','Wie kan posten');
insert into international (internationalId,languageId,namespace,message) values (3,3,'Poll','Aktief');
insert into international (internationalId,languageId,namespace,message) values (3,3,'SiteMap','Op dit niveau beginnen?');
insert into international (internationalId,languageId,namespace,message) values (3,3,'SQLReport','Sjabloon');
insert into international (internationalId,languageId,namespace,message) values (3,3,'UserSubmission','U heeft een nieuwe bijdrage om goed te keuren.');
insert into international (internationalId,languageId,namespace,message) values (3,3,'WebGUI','Plakken van het klemboord...');
insert into international (internationalId,languageId,namespace,message) values (4,3,'Article','Eind datum');
insert into international (internationalId,languageId,namespace,message) values (4,3,'EventsCalendar','Gebeurt maar een keer.');
insert into international (internationalId,languageId,namespace,message) values (4,3,'ExtraColumn','Breedte');
insert into international (internationalId,languageId,namespace,message) values (4,3,'LinkList','Opsommingsteken');
insert into international (internationalId,languageId,namespace,message) values (4,3,'MessageBoard','Berichten per pagina');
insert into international (internationalId,languageId,namespace,message) values (4,3,'Poll','Wie kan stemmen?');
insert into international (internationalId,languageId,namespace,message) values (4,3,'SiteMap','Diepteniveau');
insert into international (internationalId,languageId,namespace,message) values (4,3,'SQLReport','Query');
insert into international (internationalId,languageId,namespace,message) values (4,3,'SyndicatedContent','Bewerk syndicated content');
insert into international (internationalId,languageId,namespace,message) values (4,3,'UserSubmission','Uw bijdrage is goedgekeurd.');
insert into international (internationalId,languageId,namespace,message) values (4,3,'WebGUI','Beheer instellingen.');
insert into international (internationalId,languageId,namespace,message) values (700,3,'WebGUI','Dag');
insert into international (internationalId,languageId,namespace,message) values (5,3,'ExtraColumn','Style sheet klasse (class)');
insert into international (internationalId,languageId,namespace,message) values (5,3,'FAQ','Vraag');
insert into international (internationalId,languageId,namespace,message) values (5,3,'LinkList','Doorgaan met link toevoegen?');
insert into international (internationalId,languageId,namespace,message) values (566,3,'WebGUI','Bewerk timeout');
insert into international (internationalId,languageId,namespace,message) values (5,3,'Poll','Grafiek breedte');
insert into international (internationalId,languageId,namespace,message) values (5,3,'SiteMap','Bewerk sitemap');
insert into international (internationalId,languageId,namespace,message) values (5,3,'SQLReport','DSN');
insert into international (internationalId,languageId,namespace,message) values (5,3,'SyndicatedContent','Laatste keer bijgewerkt');
insert into international (internationalId,languageId,namespace,message) values (5,3,'UserSubmission','Uw bijdrage is afgekeurd.');
insert into international (internationalId,languageId,namespace,message) values (5,3,'WebGUI','Beheer groepen.');
insert into international (internationalId,languageId,namespace,message) values (6,3,'Article','Plaatje');
insert into international (internationalId,languageId,namespace,message) values (701,3,'WebGUI','Week');
insert into international (internationalId,languageId,namespace,message) values (6,3,'ExtraColumn','Bewerk extra kolom');
insert into international (internationalId,languageId,namespace,message) values (6,3,'FAQ','Andwoord');
insert into international (internationalId,languageId,namespace,message) values (6,3,'LinkList','Link lijst');
insert into international (internationalId,languageId,namespace,message) values (6,3,'MessageBoard','Bewerk berichten bord');
insert into international (internationalId,languageId,namespace,message) values (6,3,'Poll','Vraag');
insert into international (internationalId,languageId,namespace,message) values (6,3,'SiteMap','Inspringen');
insert into international (internationalId,languageId,namespace,message) values (6,3,'SQLReport','Database gebruiker');
insert into international (internationalId,languageId,namespace,message) values (6,3,'SyndicatedContent','Huidige inhoud');
insert into international (internationalId,languageId,namespace,message) values (6,3,'UserSubmission','Bijdrages per pagina');
insert into international (internationalId,languageId,namespace,message) values (6,3,'WebGUI','Beheer stijlen.');
insert into international (internationalId,languageId,namespace,message) values (7,3,'Article','Link titel');
insert into international (internationalId,languageId,namespace,message) values (7,3,'FAQ','Weet u zeker dat u deze vraag wilt verwijderen?');
insert into international (internationalId,languageId,namespace,message) values (7,3,'MessageBoard','Naam:');
insert into international (internationalId,languageId,namespace,message) values (7,3,'Poll','Antwoorden');
insert into international (internationalId,languageId,namespace,message) values (7,3,'SiteMap','Opsommingsteken');
insert into international (internationalId,languageId,namespace,message) values (7,3,'SQLReport','Database wachtwoord');
insert into international (internationalId,languageId,namespace,message) values (560,3,'WebGUI','Goedgekeurd');
insert into international (internationalId,languageId,namespace,message) values (7,3,'WebGUI','Beheer gebruikers');
insert into international (internationalId,languageId,namespace,message) values (8,3,'Article','Link URL');
insert into international (internationalId,languageId,namespace,message) values (8,3,'EventsCalendar','Herhaalt elke');
insert into international (internationalId,languageId,namespace,message) values (8,3,'FAQ','Bewerk FAQ');
insert into international (internationalId,languageId,namespace,message) values (8,3,'LinkList','URL');
insert into international (internationalId,languageId,namespace,message) values (8,3,'MessageBoard','Datum:');
insert into international (internationalId,languageId,namespace,message) values (8,3,'Poll','(Voer een antwoord per regel in. Niet meer dan 20.)');
insert into international (internationalId,languageId,namespace,message) values (8,3,'SiteMap','Regelafstand');
insert into international (internationalId,languageId,namespace,message) values (8,3,'SQLReport','Bewerk SQL rapport');
insert into international (internationalId,languageId,namespace,message) values (561,3,'WebGUI','Afgekeurd');
insert into international (internationalId,languageId,namespace,message) values (8,3,'WebGUI','Bekijk \'pagina niet gevonden\'.');
insert into international (internationalId,languageId,namespace,message) values (9,3,'Article','Bijlage');
insert into international (internationalId,languageId,namespace,message) values (9,3,'EventsCalendar','Tot');
insert into international (internationalId,languageId,namespace,message) values (9,3,'FAQ','Voeg een nieuwe vraag toe');
insert into international (internationalId,languageId,namespace,message) values (9,3,'LinkList','Weet u zeker dat u deze link wilt verwijderen?');
insert into international (internationalId,languageId,namespace,message) values (9,3,'MessageBoard','Bericht ID:');
insert into international (internationalId,languageId,namespace,message) values (9,3,'Poll','Bewerk stemming');
insert into international (internationalId,languageId,namespace,message) values (9,3,'SQLReport','Fout: De ingevoerde DSN is van een verkeerd formaat.');
insert into international (internationalId,languageId,namespace,message) values (562,3,'WebGUI','Lopend');
insert into international (internationalId,languageId,namespace,message) values (9,3,'WebGUI','Bekijk klembord.');
insert into international (internationalId,languageId,namespace,message) values (10,3,'Article','Enter converteren?');
insert into international (internationalId,languageId,namespace,message) values (10,3,'FAQ','Bewerk vraag');
insert into international (internationalId,languageId,namespace,message) values (10,3,'LinkList','Bewerk link lijst');
insert into international (internationalId,languageId,namespace,message) values (10,3,'Poll','Begin opnieuw met stemmen');
insert into international (internationalId,languageId,namespace,message) values (10,3,'SQLReport','Fout: De ingevoerde SQL instructie is van een verkeerd formaat.');
insert into international (internationalId,languageId,namespace,message) values (563,3,'WebGUI','Standaard status');
insert into international (internationalId,languageId,namespace,message) values (10,3,'WebGUI','Bekijk prullenbak.');
insert into international (internationalId,languageId,namespace,message) values (11,3,'Article','(Vink aan als u geen &lt;br&gt; manueel gebruikt.)');
insert into international (internationalId,languageId,namespace,message) values (11,3,'MessageBoard','Terug naar berichten lijst');
insert into international (internationalId,languageId,namespace,message) values (11,3,'SQLReport','Fout: Er was een probleem met de query');
insert into international (internationalId,languageId,namespace,message) values (11,3,'WebGUI','Leeg prullenbak.');
insert into international (internationalId,languageId,namespace,message) values (12,3,'Article','Bewerk artikel');
insert into international (internationalId,languageId,namespace,message) values (12,3,'EventsCalendar','Bewerk evenementen kalender');
insert into international (internationalId,languageId,namespace,message) values (12,3,'LinkList','Bewerk link');
insert into international (internationalId,languageId,namespace,message) values (12,3,'MessageBoard','Bewerk bericht');
insert into international (internationalId,languageId,namespace,message) values (12,3,'SQLReport','Fout: Kon niet met de database verbinden.');
insert into international (internationalId,languageId,namespace,message) values (12,3,'UserSubmission','(niet aanvinken als u een HTML bijdrage levert.)');
insert into international (internationalId,languageId,namespace,message) values (12,3,'WebGUI','Zet beheermode uit.');
insert into international (internationalId,languageId,namespace,message) values (13,3,'Article','Verwijder');
insert into international (internationalId,languageId,namespace,message) values (13,3,'EventsCalendar','Bewerk evenement');
insert into international (internationalId,languageId,namespace,message) values (13,3,'LinkList','Voeg een nieuwe link toe.');
insert into international (internationalId,languageId,namespace,message) values (577,3,'WebGUI','Post antwoord');
insert into international (internationalId,languageId,namespace,message) values (13,3,'UserSubmission','Invoerdatum');
insert into international (internationalId,languageId,namespace,message) values (13,3,'WebGUI','Laat help index zien.');
insert into international (internationalId,languageId,namespace,message) values (14,3,'UserSubmission','Status');
insert into international (internationalId,languageId,namespace,message) values (14,3,'WebGUI','Laat lopende aanmeldingen zien.');
insert into international (internationalId,languageId,namespace,message) values (15,3,'MessageBoard','Afzender');
insert into international (internationalId,languageId,namespace,message) values (15,3,'UserSubmission','bewerk/Verwijder');
insert into international (internationalId,languageId,namespace,message) values (15,3,'WebGUI','januari');
insert into international (internationalId,languageId,namespace,message) values (16,3,'MessageBoard','Datum');
insert into international (internationalId,languageId,namespace,message) values (16,3,'UserSubmission','Zonder titel');
insert into international (internationalId,languageId,namespace,message) values (16,3,'WebGUI','februari');
insert into international (internationalId,languageId,namespace,message) values (17,3,'MessageBoard','Post nieuw bericht');
insert into international (internationalId,languageId,namespace,message) values (17,3,'UserSubmission','Weet u zeker dat u deze bijdrage wilt verwijderen?');
insert into international (internationalId,languageId,namespace,message) values (17,3,'WebGUI','maart');
insert into international (internationalId,languageId,namespace,message) values (18,3,'MessageBoard','Tread gestart');
insert into international (internationalId,languageId,namespace,message) values (18,3,'UserSubmission','Bewerk gebruikers bijdrage systeem');
insert into international (internationalId,languageId,namespace,message) values (18,3,'WebGUI','april');
insert into international (internationalId,languageId,namespace,message) values (19,3,'MessageBoard','Antwoorden');
insert into international (internationalId,languageId,namespace,message) values (19,3,'UserSubmission','Bewerk bijdrage');
insert into international (internationalId,languageId,namespace,message) values (19,3,'WebGUI','mei');
insert into international (internationalId,languageId,namespace,message) values (20,3,'MessageBoard','Laatste antwoord');
insert into international (internationalId,languageId,namespace,message) values (20,3,'UserSubmission','Post nieuwe bijdrage');
insert into international (internationalId,languageId,namespace,message) values (20,3,'WebGUI','juni');
insert into international (internationalId,languageId,namespace,message) values (21,3,'UserSubmission','Ingevoerd door');
insert into international (internationalId,languageId,namespace,message) values (21,3,'WebGUI','juli');
insert into international (internationalId,languageId,namespace,message) values (22,3,'UserSubmission','ingevoerd door:');
insert into international (internationalId,languageId,namespace,message) values (22,3,'WebGUI','augustus');
insert into international (internationalId,languageId,namespace,message) values (23,3,'UserSubmission','Invoer datum:');
insert into international (internationalId,languageId,namespace,message) values (23,3,'WebGUI','september');
insert into international (internationalId,languageId,namespace,message) values (572,3,'WebGUI','Keur goed');
insert into international (internationalId,languageId,namespace,message) values (24,3,'WebGUI','oktober');
insert into international (internationalId,languageId,namespace,message) values (573,3,'WebGUI','Laat in behandeling');
insert into international (internationalId,languageId,namespace,message) values (25,3,'WebGUI','november');
insert into international (internationalId,languageId,namespace,message) values (574,3,'WebGUI','Keur af');
insert into international (internationalId,languageId,namespace,message) values (26,3,'WebGUI','december');
insert into international (internationalId,languageId,namespace,message) values (27,3,'UserSubmission','Bewerk');
insert into international (internationalId,languageId,namespace,message) values (27,3,'WebGUI','zondag');
insert into international (internationalId,languageId,namespace,message) values (28,3,'UserSubmission','Ga terug naar bijdrage lijst');
insert into international (internationalId,languageId,namespace,message) values (28,3,'WebGUI','maandag');
insert into international (internationalId,languageId,namespace,message) values (29,3,'UserSubmission','Gebruikers bijdrage systeem');
insert into international (internationalId,languageId,namespace,message) values (29,3,'WebGUI','dinsdag');
insert into international (internationalId,languageId,namespace,message) values (30,3,'WebGUI','woensdag');
insert into international (internationalId,languageId,namespace,message) values (31,3,'WebGUI','donderdag');
insert into international (internationalId,languageId,namespace,message) values (32,3,'WebGUI','vrijdag');
insert into international (internationalId,languageId,namespace,message) values (33,3,'WebGUI','zaterdag');
insert into international (internationalId,languageId,namespace,message) values (34,3,'WebGUI','Zet datum');
insert into international (internationalId,languageId,namespace,message) values (35,3,'WebGUI','Administratieve functie');
insert into international (internationalId,languageId,namespace,message) values (36,3,'WebGUI','U moet een beheerder zijn om deze functie uit te voeren. Neem contact op met een van de beheerders:');
insert into international (internationalId,languageId,namespace,message) values (37,3,'WebGUI','Geen toegang!');
insert into international (internationalId,languageId,namespace,message) values (38,3,'WebGUI','U heeft niet voldoende privileges om deze bewerking uit te voeren. ^a(Log in); als een gebruiker met voldoende privileges.');
insert into international (internationalId,languageId,namespace,message) values (39,3,'WebGUI','U heeft niet voldoende privileges om deze pagina op te vragen.');
insert into international (internationalId,languageId,namespace,message) values (40,3,'WebGUI','Vitaal component');
insert into international (internationalId,languageId,namespace,message) values (41,3,'WebGUI','U probeert een vitaal component van het WebGUI systeem te verwijderen. Als u dit zou mogen dan zou WebGUI waarschijnlijk niet meer werken.');
insert into international (internationalId,languageId,namespace,message) values (42,3,'WebGUI','Alstublieft bevestigen');
insert into international (internationalId,languageId,namespace,message) values (43,3,'WebGUI','Weet u zeker dat u deze inhoud wilt verwijderen?');
insert into international (internationalId,languageId,namespace,message) values (44,3,'WebGUI','\"Ja, ik weet het zeker.\"');
insert into international (internationalId,languageId,namespace,message) values (45,3,'WebGUI','\"Nee, ik heb een foutje gemaakt.\"');
insert into international (internationalId,languageId,namespace,message) values (46,3,'WebGUI','Mijn account');
insert into international (internationalId,languageId,namespace,message) values (47,3,'WebGUI','Home');
insert into international (internationalId,languageId,namespace,message) values (48,3,'WebGUI','Hallo');
insert into international (internationalId,languageId,namespace,message) values (49,3,'WebGUI','Klik <a href=\"^\\;?op=logout\">hier</a> om uit te loggen.');
insert into international (internationalId,languageId,namespace,message) values (50,3,'WebGUI','Gebruikersnaam');
insert into international (internationalId,languageId,namespace,message) values (51,3,'WebGUI','Wachtwoord');
insert into international (internationalId,languageId,namespace,message) values (52,3,'WebGUI','Login');
insert into international (internationalId,languageId,namespace,message) values (53,3,'WebGUI','Maak pagina printbaar');
insert into international (internationalId,languageId,namespace,message) values (54,3,'WebGUI','Creëer account');
insert into international (internationalId,languageId,namespace,message) values (55,3,'WebGUI','Wachtwoord (bevestigen)');
insert into international (internationalId,languageId,namespace,message) values (56,3,'WebGUI','Emailadres');
insert into international (internationalId,languageId,namespace,message) values (57,3,'WebGUI','Dit is alleen nodig als er functies gebruikt worden die email nodig hebben.');
insert into international (internationalId,languageId,namespace,message) values (58,3,'WebGUI','Ik heb al een account.');
insert into international (internationalId,languageId,namespace,message) values (59,3,'WebGUI','Ik ben mijn wachtwoord vergeten.');
insert into international (internationalId,languageId,namespace,message) values (60,3,'WebGUI','Weet u zeker dat u uw account wilt deaktiveren? Als u doorgaat gaat alle account informatie voorgoed verloren.');
insert into international (internationalId,languageId,namespace,message) values (61,3,'WebGUI','Account informatie bijwerken');
insert into international (internationalId,languageId,namespace,message) values (62,3,'WebGUI','Bewaar');
insert into international (internationalId,languageId,namespace,message) values (63,3,'WebGUI','Zet beheermode aan');
insert into international (internationalId,languageId,namespace,message) values (64,3,'WebGUI','Log uit.');
insert into international (internationalId,languageId,namespace,message) values (65,3,'WebGUI','Deaktiveer mijn account voorgoed.');
insert into international (internationalId,languageId,namespace,message) values (66,3,'WebGUI','Log in');
insert into international (internationalId,languageId,namespace,message) values (67,3,'WebGUI','Creëer een nieuw account');
insert into international (internationalId,languageId,namespace,message) values (68,3,'WebGUI','De account informatie is niet geldig. Het account bestaat niet of de gebruikersnaam/wachtwoord was fout.');
insert into international (internationalId,languageId,namespace,message) values (69,3,'WebGUI','Vraag uw systeembeheerder om assistentie.');
insert into international (internationalId,languageId,namespace,message) values (70,3,'WebGUI','Fout');
insert into international (internationalId,languageId,namespace,message) values (71,3,'WebGUI','Wachtwoord terugvinden');
insert into international (internationalId,languageId,namespace,message) values (72,3,'WebGUI','Terugvinden');
insert into international (internationalId,languageId,namespace,message) values (73,3,'WebGUI','Log in.');
insert into international (internationalId,languageId,namespace,message) values (74,3,'WebGUI','Account informatie');
insert into international (internationalId,languageId,namespace,message) values (75,3,'WebGUI','Uw account informatie is naar uw email adres verzonden.');
insert into international (internationalId,languageId,namespace,message) values (76,3,'WebGUI','Dat email adresis niet in onze database aanwezig.');
insert into international (internationalId,languageId,namespace,message) values (77,3,'WebGUI','Deze account naam wordt al gebruikt door een andere gebruiker van dit systeem. Probeer een andere naam. We hebben de volgende suggesties:');
insert into international (internationalId,languageId,namespace,message) values (78,3,'WebGUI','De wachtwoorden waren niet gelijk. Probeer opnieuw.');
insert into international (internationalId,languageId,namespace,message) values (79,3,'WebGUI','Kan niet verbinden met LDAP server.');
insert into international (internationalId,languageId,namespace,message) values (80,3,'WebGUI','Account is aangemaakt!');
insert into international (internationalId,languageId,namespace,message) values (81,3,'WebGUI','Account is aangepast!');
insert into international (internationalId,languageId,namespace,message) values (82,3,'WebGUI','Administratieve functies...');
insert into international (internationalId,languageId,namespace,message) values (84,3,'WebGUI','Groep naam');
insert into international (internationalId,languageId,namespace,message) values (85,3,'WebGUI','Beschrijving');
insert into international (internationalId,languageId,namespace,message) values (86,3,'WebGUI','Weet u zeker dat u deze groep wilt verwijderen? Denk er aan dat een groep verwijderen permanent en alle privileges geassocieerd met de groep verwijdert worden.');
insert into international (internationalId,languageId,namespace,message) values (87,3,'WebGUI','Bewerk groep');
insert into international (internationalId,languageId,namespace,message) values (88,3,'WebGUI','Gebruikers in groep');
insert into international (internationalId,languageId,namespace,message) values (89,3,'WebGUI','Groepen');
insert into international (internationalId,languageId,namespace,message) values (90,3,'WebGUI','Voeg nieuwe groep toe.');
insert into international (internationalId,languageId,namespace,message) values (91,3,'WebGUI','Vorige pagina');
insert into international (internationalId,languageId,namespace,message) values (92,3,'WebGUI','Volgende pagina');
insert into international (internationalId,languageId,namespace,message) values (93,3,'WebGUI','Help');
insert into international (internationalId,languageId,namespace,message) values (94,3,'WebGUI','Zie ook');
insert into international (internationalId,languageId,namespace,message) values (95,3,'WebGUI','Help index');
insert into international (internationalId,languageId,namespace,message) values (99,3,'WebGUI','Titel');
insert into international (internationalId,languageId,namespace,message) values (100,3,'WebGUI','Meta tags');
insert into international (internationalId,languageId,namespace,message) values (101,3,'WebGUI','Weet u zeker dat u deze pagina wilt verwijderen en alle inhoud en objecten erachter?');
insert into international (internationalId,languageId,namespace,message) values (102,3,'WebGUI','Bewerk pagina');
insert into international (internationalId,languageId,namespace,message) values (103,3,'WebGUI','Pagina specifiek');
insert into international (internationalId,languageId,namespace,message) values (104,3,'WebGUI','Pagina URL');
insert into international (internationalId,languageId,namespace,message) values (105,3,'WebGUI','Stijl');
insert into international (internationalId,languageId,namespace,message) values (106,3,'WebGUI','Aanvinken om deze stijl in alle pagina\'s te gebruiiken.');
insert into international (internationalId,languageId,namespace,message) values (107,3,'WebGUI','Privileges');
insert into international (internationalId,languageId,namespace,message) values (108,3,'WebGUI','Eigenaar');
insert into international (internationalId,languageId,namespace,message) values (109,3,'WebGUI','Eigenaar kan bekijken?');
insert into international (internationalId,languageId,namespace,message) values (110,3,'WebGUI','Gebruiker kan bewerken?');
insert into international (internationalId,languageId,namespace,message) values (111,3,'WebGUI','Groep');
insert into international (internationalId,languageId,namespace,message) values (112,3,'WebGUI','Groep kan bekijken?');
insert into international (internationalId,languageId,namespace,message) values (113,3,'WebGUI','Groep kan bewerken?');
insert into international (internationalId,languageId,namespace,message) values (114,3,'WebGUI','Iedereen kan bekijken?');
insert into international (internationalId,languageId,namespace,message) values (115,3,'WebGUI','Iedereen kan bewerken?');
insert into international (internationalId,languageId,namespace,message) values (116,3,'WebGUI','Aanvinken om deze privileges aan alle sub pagina\'s te geven.');
insert into international (internationalId,languageId,namespace,message) values (117,3,'WebGUI','Bewerk toegangs controle instellingen');
insert into international (internationalId,languageId,namespace,message) values (118,3,'WebGUI','Anonieme registratie');
insert into international (internationalId,languageId,namespace,message) values (119,3,'WebGUI','Toegangs controle methode (standaard)');
insert into international (internationalId,languageId,namespace,message) values (120,3,'WebGUI','LDAP URL (standaard)');
insert into international (internationalId,languageId,namespace,message) values (121,3,'WebGUI','LDAP identiteit (standaard)');
insert into international (internationalId,languageId,namespace,message) values (122,3,'WebGUI','LDAP identiteit naam');
insert into international (internationalId,languageId,namespace,message) values (123,3,'WebGUI','LDAP wachtwoord naam');
insert into international (internationalId,languageId,namespace,message) values (124,3,'WebGUI','Bewerk bedrijfsinformatie');
insert into international (internationalId,languageId,namespace,message) values (125,3,'WebGUI','Bedrijfsnaam');
insert into international (internationalId,languageId,namespace,message) values (126,3,'WebGUI','Email adres bedrijf');
insert into international (internationalId,languageId,namespace,message) values (127,3,'WebGUI','URL bedrijf');
insert into international (internationalId,languageId,namespace,message) values (130,3,'WebGUI','Maximum grootte bijlagen');
insert into international (internationalId,languageId,namespace,message) values (133,3,'WebGUI','Bewerk email instellingen');
insert into international (internationalId,languageId,namespace,message) values (134,3,'WebGUI','Bericht om wachtwoord terug te vinden');
insert into international (internationalId,languageId,namespace,message) values (135,3,'WebGUI','SMTP server');
insert into international (internationalId,languageId,namespace,message) values (138,3,'WebGUI','Ja');
insert into international (internationalId,languageId,namespace,message) values (139,3,'WebGUI','Nee');
insert into international (internationalId,languageId,namespace,message) values (140,3,'WebGUI','Bewerk allerlei instellingen');
insert into international (internationalId,languageId,namespace,message) values (141,3,'WebGUI','Niet gevonden pagina');
insert into international (internationalId,languageId,namespace,message) values (142,3,'WebGUI','Sessie time out');
insert into international (internationalId,languageId,namespace,message) values (143,3,'WebGUI','Beheer instellingen.');
insert into international (internationalId,languageId,namespace,message) values (144,3,'WebGUI','Bekijk statistieken');
insert into international (internationalId,languageId,namespace,message) values (145,3,'WebGUI','WebGUI versie');
insert into international (internationalId,languageId,namespace,message) values (146,3,'WebGUI','Aktieve sessies');
insert into international (internationalId,languageId,namespace,message) values (147,3,'WebGUI','Pagina\'s');
insert into international (internationalId,languageId,namespace,message) values (148,3,'WebGUI','Wobjects');
insert into international (internationalId,languageId,namespace,message) values (149,3,'WebGUI','Gebruikers');
insert into international (internationalId,languageId,namespace,message) values (151,3,'WebGUI','Stijl naam');
insert into international (internationalId,languageId,namespace,message) values (154,3,'WebGUI','Style sheet');
insert into international (internationalId,languageId,namespace,message) values (155,3,'WebGUI','Weet u zeker dat u deze stijl wilt verwijderen en migreer alle pagina\'s met de “fail safe” stijl?');
insert into international (internationalId,languageId,namespace,message) values (156,3,'WebGUI','Bewerk stijl');
insert into international (internationalId,languageId,namespace,message) values (157,3,'WebGUI','Stijlen');
insert into international (internationalId,languageId,namespace,message) values (158,3,'WebGUI','Een nieuwe stijl toevoegen.');
insert into international (internationalId,languageId,namespace,message) values (159,3,'WebGUI','Berichten log');
insert into international (internationalId,languageId,namespace,message) values (160,3,'WebGUI','Invoer datum');
insert into international (internationalId,languageId,namespace,message) values (161,3,'WebGUI','Ingevoerd door');
insert into international (internationalId,languageId,namespace,message) values (162,3,'WebGUI','Weet u zeker dat u alle pagina\'s en wobjects uit de prullenbak wilt verwijderen?');
insert into international (internationalId,languageId,namespace,message) values (163,3,'WebGUI','Gebruiker toevoegen');
insert into international (internationalId,languageId,namespace,message) values (164,3,'WebGUI','Toegangs controle methode');
insert into international (internationalId,languageId,namespace,message) values (165,3,'WebGUI','LDAP URL');
insert into international (internationalId,languageId,namespace,message) values (166,3,'WebGUI','Verbindt DN');
insert into international (internationalId,languageId,namespace,message) values (167,3,'WebGUI','Weet u zeker dat u deze gebruiker wilt verwijderen? Alle gebruikersinformatie wordt permanent verwijdert als u door gaat.');
insert into international (internationalId,languageId,namespace,message) values (168,3,'WebGUI','Bewerk gebruiker');
insert into international (internationalId,languageId,namespace,message) values (169,3,'WebGUI','Een nieuwe gebruiker toevoegen.');
insert into international (internationalId,languageId,namespace,message) values (170,3,'WebGUI','Zoeken');
insert into international (internationalId,languageId,namespace,message) values (171,3,'WebGUI','Rich edit');
insert into international (internationalId,languageId,namespace,message) values (174,3,'WebGUI','Titel laten zien?');
insert into international (internationalId,languageId,namespace,message) values (175,3,'WebGUI','Macro\'s uitvoeren?');
insert into international (internationalId,languageId,namespace,message) values (228,3,'WebGUI','Bewerk bericht...');
insert into international (internationalId,languageId,namespace,message) values (229,3,'WebGUI','Onderwerp');
insert into international (internationalId,languageId,namespace,message) values (230,3,'WebGUI','Bericht');
insert into international (internationalId,languageId,namespace,message) values (231,3,'WebGUI','Bezig met bericht posten...');
insert into international (internationalId,languageId,namespace,message) values (232,3,'WebGUI','Geen onderwerp');
insert into international (internationalId,languageId,namespace,message) values (233,3,'WebGUI','(einde)');
insert into international (internationalId,languageId,namespace,message) values (234,3,'WebGUI','Bezig met antwoord posten');
insert into international (internationalId,languageId,namespace,message) values (237,3,'WebGUI','Onderwerp:');
insert into international (internationalId,languageId,namespace,message) values (238,3,'WebGUI','Naam:');
insert into international (internationalId,languageId,namespace,message) values (239,3,'WebGUI','Datum:');
insert into international (internationalId,languageId,namespace,message) values (240,3,'WebGUI','Bericht ID:');
insert into international (internationalId,languageId,namespace,message) values (244,3,'WebGUI','Afzender');
insert into international (internationalId,languageId,namespace,message) values (245,3,'WebGUI','Datum');
insert into international (internationalId,languageId,namespace,message) values (304,3,'WebGUI','Taal');
insert into international (internationalId,languageId,namespace,message) values (306,3,'WebGUI','Bind gebruikersnaam');
insert into international (internationalId,languageId,namespace,message) values (307,3,'WebGUI','Gebruik standaard metag tags?');
insert into international (internationalId,languageId,namespace,message) values (308,3,'WebGUI','Bewerk profiel instellingen');
insert into international (internationalId,languageId,namespace,message) values (309,3,'WebGUI','Sta echte naam toe?');
insert into international (internationalId,languageId,namespace,message) values (310,3,'WebGUI','Sta extra contact informatie toe?');
insert into international (internationalId,languageId,namespace,message) values (311,3,'WebGUI','Sta thuis informatie toe?');
insert into international (internationalId,languageId,namespace,message) values (312,3,'WebGUI','Sta bedrijfs informatie toe?');
insert into international (internationalId,languageId,namespace,message) values (313,3,'WebGUI','Sta andere informatie toe?');
insert into international (internationalId,languageId,namespace,message) values (314,3,'WebGUI','Voornaam');
insert into international (internationalId,languageId,namespace,message) values (315,3,'WebGUI','Tussenvoegsel');
insert into international (internationalId,languageId,namespace,message) values (316,3,'WebGUI','Achternaam');
insert into international (internationalId,languageId,namespace,message) values (317,3,'WebGUI','\"<a href=\"\"http://www.icq.com\"\">ICQ</a> UIN\"');
insert into international (internationalId,languageId,namespace,message) values (318,3,'WebGUI','\"<a href=\"\"http://www.aol.com/aim/homenew.adp\"\">AIM</a> Id\"');
insert into international (internationalId,languageId,namespace,message) values (319,3,'WebGUI','\"<a href=\"\"http://messenger.msn.com/\"\">MSN Messenger</a> Id\"');
insert into international (internationalId,languageId,namespace,message) values (320,3,'WebGUI','\"<a href=\"\"http://messenger.yahoo.com/\"\">Yahoo! Messenger</a> Id\"');
insert into international (internationalId,languageId,namespace,message) values (321,3,'WebGUI','Mobiel nummer');
insert into international (internationalId,languageId,namespace,message) values (322,3,'WebGUI','Pager');
insert into international (internationalId,languageId,namespace,message) values (323,3,'WebGUI','Thuis adres');
insert into international (internationalId,languageId,namespace,message) values (324,3,'WebGUI','Thuis plaats');
insert into international (internationalId,languageId,namespace,message) values (325,3,'WebGUI','Thuis staat');
insert into international (internationalId,languageId,namespace,message) values (326,3,'WebGUI','Thuis postcode');
insert into international (internationalId,languageId,namespace,message) values (327,3,'WebGUI','Thuis land');
insert into international (internationalId,languageId,namespace,message) values (328,3,'WebGUI','Thuis telefoon');
insert into international (internationalId,languageId,namespace,message) values (329,3,'WebGUI','Werk adres');
insert into international (internationalId,languageId,namespace,message) values (330,3,'WebGUI','Werk stad');
insert into international (internationalId,languageId,namespace,message) values (331,3,'WebGUI','Werk staat');
insert into international (internationalId,languageId,namespace,message) values (332,3,'WebGUI','Werk postcode');
insert into international (internationalId,languageId,namespace,message) values (333,3,'WebGUI','Werk land');
insert into international (internationalId,languageId,namespace,message) values (334,3,'WebGUI','Werk telefoon');
insert into international (internationalId,languageId,namespace,message) values (335,3,'WebGUI','Sexe');
insert into international (internationalId,languageId,namespace,message) values (336,3,'WebGUI','Geboortedatum');
insert into international (internationalId,languageId,namespace,message) values (337,3,'WebGUI','Home pagina URL');
insert into international (internationalId,languageId,namespace,message) values (338,3,'WebGUI','Bewerk profiel');
insert into international (internationalId,languageId,namespace,message) values (339,3,'WebGUI','Man');
insert into international (internationalId,languageId,namespace,message) values (340,3,'WebGUI','Vrouw');
insert into international (internationalId,languageId,namespace,message) values (341,3,'WebGUI','Bewerk profiel.');
insert into international (internationalId,languageId,namespace,message) values (342,3,'WebGUI','Bewerk account informatie.');
insert into international (internationalId,languageId,namespace,message) values (343,3,'WebGUI','Bekijk profiel.');
insert into international (internationalId,languageId,namespace,message) values (345,3,'WebGUI','Geen lid');
insert into international (internationalId,languageId,namespace,message) values (346,3,'WebGUI','Deze gebruiker in geen lid meer van onze site. We hebben geen informatie meer over deze gebruiker.');
insert into international (internationalId,languageId,namespace,message) values (347,3,'WebGUI','Bekijk profiel van');
insert into international (internationalId,languageId,namespace,message) values (348,3,'WebGUI','Naam');
insert into international (internationalId,languageId,namespace,message) values (349,3,'WebGUI','Laatst beschikbare versie');
insert into international (internationalId,languageId,namespace,message) values (350,3,'WebGUI','Klaar');
insert into international (internationalId,languageId,namespace,message) values (351,3,'WebGUI','Bericht');
insert into international (internationalId,languageId,namespace,message) values (352,3,'WebGUI','Datum van toevoeging');
insert into international (internationalId,languageId,namespace,message) values (353,3,'WebGUI','U heeft nu geen berichten log toevoegingen.');
insert into international (internationalId,languageId,namespace,message) values (354,3,'WebGUI','Bekijk berichten log.');
insert into international (internationalId,languageId,namespace,message) values (355,3,'WebGUI','Standaard');
insert into international (internationalId,languageId,namespace,message) values (14,3,'Article','Plaatje uitlijnen');
insert into international (internationalId,languageId,namespace,message) values (15,3,'Article','Rechts');
insert into international (internationalId,languageId,namespace,message) values (16,3,'Article','links');
insert into international (internationalId,languageId,namespace,message) values (17,3,'Article','Centreren');
insert into international (internationalId,languageId,namespace,message) values (18,3,'Article','Discussie toelaten?');
insert into international (internationalId,languageId,namespace,message) values (22,3,'Article','Auteur');
insert into international (internationalId,languageId,namespace,message) values (23,3,'Article','Datum');
insert into international (internationalId,languageId,namespace,message) values (24,3,'Article','Post reactie');
insert into international (internationalId,languageId,namespace,message) values (27,3,'Article','Terug naar artikel');
insert into international (internationalId,languageId,namespace,message) values (28,3,'Article','Bekijk reacties');
insert into international (internationalId,languageId,namespace,message) values (1,3,'DownloadManager','Download Manager');
insert into international (internationalId,languageId,namespace,message) values (3,3,'DownloadManager','Verder gaan met bestand toevoegen?');
insert into international (internationalId,languageId,namespace,message) values (5,3,'DownloadManager','Bestand Titel');
insert into international (internationalId,languageId,namespace,message) values (6,3,'DownloadManager','Download bestand');
insert into international (internationalId,languageId,namespace,message) values (7,3,'DownloadManager','Groep om te downloaden');
insert into international (internationalId,languageId,namespace,message) values (8,3,'DownloadManager','Korte Omschrijving');
insert into international (internationalId,languageId,namespace,message) values (9,3,'DownloadManager','Bewerk download Manager');
insert into international (internationalId,languageId,namespace,message) values (10,3,'DownloadManager','Bewerk Download');
insert into international (internationalId,languageId,namespace,message) values (11,3,'DownloadManager','Nieuwe download toevoegen');
insert into international (internationalId,languageId,namespace,message) values (12,3,'DownloadManager','Weet u zeker dat u deze download wilt verwijderen?');
insert into international (internationalId,languageId,namespace,message) values (14,3,'DownloadManager','Bestand');
insert into international (internationalId,languageId,namespace,message) values (15,3,'DownloadManager','Beschrijving');
insert into international (internationalId,languageId,namespace,message) values (16,3,'DownloadManager','Upload datum');
insert into international (internationalId,languageId,namespace,message) values (17,3,'DownloadManager','Alternatieve Versie #1');
insert into international (internationalId,languageId,namespace,message) values (18,3,'DownloadManager','Alternatieve Versie #2');
insert into international (internationalId,languageId,namespace,message) values (19,3,'DownloadManager','U heeft geen bestanden te downloaden');
insert into international (internationalId,languageId,namespace,message) values (20,3,'DownloadManager','Kap pagina af na');
insert into international (internationalId,languageId,namespace,message) values (21,3,'DownloadManager','Miniaturen weergeven?');
insert into international (internationalId,languageId,namespace,message) values (22,3,'DownloadManager','Doorgaan met download toevoegen');
insert into international (internationalId,languageId,namespace,message) values (20,3,'EventsCalendar','Evenement toevoegen');
insert into international (internationalId,languageId,namespace,message) values (21,3,'EventsCalendar','Doorgaan met evenement toevoegen?');
insert into international (internationalId,languageId,namespace,message) values (14,3,'EventsCalendar','Start datum');
insert into international (internationalId,languageId,namespace,message) values (15,3,'EventsCalendar','Eind datum');
insert into international (internationalId,languageId,namespace,message) values (16,3,'EventsCalendar','Kalender layout');
insert into international (internationalId,languageId,namespace,message) values (17,3,'EventsCalendar','Lijst');
insert into international (internationalId,languageId,namespace,message) values (18,3,'EventsCalendar','Calendar Month');
insert into international (internationalId,languageId,namespace,message) values (19,3,'EventsCalendar','Breek pagina af na');
insert into international (internationalId,languageId,namespace,message) values (11,3,'FAQ','Zet inhoud aan?');
insert into international (internationalId,languageId,namespace,message) values (12,3,'FAQ','Zet V/A aan?');
insert into international (internationalId,languageId,namespace,message) values (13,3,'FAQ','Zet [top] link aan?');
insert into international (internationalId,languageId,namespace,message) values (14,3,'FAQ','V');
insert into international (internationalId,languageId,namespace,message) values (15,3,'FAQ','A');
insert into international (internationalId,languageId,namespace,message) values (16,3,'FAQ','[top]');
insert into international (internationalId,languageId,namespace,message) values (1,3,'Item','Link URL');
insert into international (internationalId,languageId,namespace,message) values (2,3,'Item','Bijlage');
insert into international (internationalId,languageId,namespace,message) values (3,3,'Item','Verwijder bijlage');
insert into international (internationalId,languageId,namespace,message) values (4,3,'Item','Item');
insert into international (internationalId,languageId,namespace,message) values (5,3,'Item','Download bijlage');
insert into international (internationalId,languageId,namespace,message) values (565,3,'WebGUI','Wie kan bewerken?');
insert into international (internationalId,languageId,namespace,message) values (22,3,'MessageBoard','Verwijder bericht');
insert into international (internationalId,languageId,namespace,message) values (11,3,'Poll','Stem!');
insert into international (internationalId,languageId,namespace,message) values (9,3,'SiteMap','Omschrijving laten zien?');
insert into international (internationalId,languageId,namespace,message) values (13,3,'SQLReport','Converteer Return?');
insert into international (internationalId,languageId,namespace,message) values (14,3,'SQLReport','Breek pagina af na');
insert into international (internationalId,languageId,namespace,message) values (15,3,'SQLReport','Verwerk macros voor query?');
insert into international (internationalId,languageId,namespace,message) values (16,3,'SQLReport','Debug?');
insert into international (internationalId,languageId,namespace,message) values (17,3,'SQLReport','Debug: Query:');
insert into international (internationalId,languageId,namespace,message) values (18,3,'SQLReport','Er waren geen resultaten voor deze query');
insert into international (internationalId,languageId,namespace,message) values (31,3,'UserSubmission','Inhoud');
insert into international (internationalId,languageId,namespace,message) values (32,3,'UserSubmission','Plaatje');
insert into international (internationalId,languageId,namespace,message) values (33,3,'UserSubmission','Bijlage');
insert into international (internationalId,languageId,namespace,message) values (34,3,'UserSubmission','Return converteren');
insert into international (internationalId,languageId,namespace,message) values (35,3,'UserSubmission','Titel');
insert into international (internationalId,languageId,namespace,message) values (37,3,'UserSubmission','Verwijder');
insert into international (internationalId,languageId,namespace,message) values (39,3,'UserSubmission','Post een reactie');
insert into international (internationalId,languageId,namespace,message) values (40,3,'UserSubmission','Gepost door');
insert into international (internationalId,languageId,namespace,message) values (41,3,'UserSubmission','Datum');
insert into international (internationalId,languageId,namespace,message) values (45,3,'UserSubmission','Ga terug naar bijdrages');
insert into international (internationalId,languageId,namespace,message) values (46,3,'UserSubmission','Lees meer...');
insert into international (internationalId,languageId,namespace,message) values (47,3,'UserSubmission','Post een reactie');
insert into international (internationalId,languageId,namespace,message) values (48,3,'UserSubmission','Discussie toestaan?');
insert into international (internationalId,languageId,namespace,message) values (51,3,'UserSubmission','Miniaturen weergeven');
insert into international (internationalId,languageId,namespace,message) values (52,3,'UserSubmission','Miniatuur');
insert into international (internationalId,languageId,namespace,message) values (53,3,'UserSubmission','Layout');
insert into international (internationalId,languageId,namespace,message) values (54,3,'UserSubmission','Web Log');
insert into international (internationalId,languageId,namespace,message) values (55,3,'UserSubmission','Traditioneel');
insert into international (internationalId,languageId,namespace,message) values (56,3,'UserSubmission','Foto gallerij');
insert into international (internationalId,languageId,namespace,message) values (57,3,'UserSubmission','Reacties');
insert into international (internationalId,languageId,namespace,message) values (516,3,'WebGUI','Zet beheermode aan!');
insert into international (internationalId,languageId,namespace,message) values (517,3,'WebGUI','Zet beheermode uit!');
insert into international (internationalId,languageId,namespace,message) values (515,3,'WebGUI','Bewerkings stempel toevoegen?');
insert into international (internationalId,languageId,namespace,message) values (532,3,'WebGUI','Met minstens 1 van de worden');
insert into international (internationalId,languageId,namespace,message) values (531,3,'WebGUI','met de exacte zin');
insert into international (internationalId,languageId,namespace,message) values (505,3,'WebGUI','Een niewe template toevoegen');
insert into international (internationalId,languageId,namespace,message) values (504,3,'WebGUI','Sjabloon');
insert into international (internationalId,languageId,namespace,message) values (503,3,'WebGUI','Sjabloon ID');
insert into international (internationalId,languageId,namespace,message) values (502,3,'WebGUI','Weet u zeker dat u deze sjabloon wilt verwijderen? Elke pagina die de template gebruikt zal de standaard template krijgen!');
insert into international (internationalId,languageId,namespace,message) values (536,3,'WebGUI','Een nieuwe gebruiker genaamd ^@; is bij de site aangemeld');
insert into international (internationalId,languageId,namespace,message) values (356,3,'WebGUI','Sjabloon');
insert into international (internationalId,languageId,namespace,message) values (357,3,'WebGUI','Nieuws');
insert into international (internationalId,languageId,namespace,message) values (358,3,'WebGUI','Linker kolom');
insert into international (internationalId,languageId,namespace,message) values (359,3,'WebGUI','Rechter kolom');
insert into international (internationalId,languageId,namespace,message) values (360,3,'WebGUI','Een boven drie');
insert into international (internationalId,languageId,namespace,message) values (361,3,'WebGUI','Drie boven een');
insert into international (internationalId,languageId,namespace,message) values (362,3,'WebGUI','Zij aan zij');
insert into international (internationalId,languageId,namespace,message) values (363,3,'WebGUI','Sjabloon positie');
insert into international (internationalId,languageId,namespace,message) values (364,3,'WebGUI','Zoeken');
insert into international (internationalId,languageId,namespace,message) values (365,3,'WebGUI','Zoek resultaten');
insert into international (internationalId,languageId,namespace,message) values (366,3,'WebGUI','Er is geen pagina die aan uw vraag voldoet');
insert into international (internationalId,languageId,namespace,message) values (368,3,'WebGUI','Voeg een nieuwe groep aan deze gebruiker toe');
insert into international (internationalId,languageId,namespace,message) values (369,3,'WebGUI','Verloop datum');
insert into international (internationalId,languageId,namespace,message) values (370,3,'WebGUI','Bewerk groeperen');
insert into international (internationalId,languageId,namespace,message) values (371,3,'WebGUI','Groeperen toevoegen');
insert into international (internationalId,languageId,namespace,message) values (372,3,'WebGUI','Bewerk gebruiker groep');
insert into international (internationalId,languageId,namespace,message) values (374,3,'WebGUI','Beheer pakketten');
insert into international (internationalId,languageId,namespace,message) values (375,3,'WebGUI','Selecteer pakket');
insert into international (internationalId,languageId,namespace,message) values (376,3,'WebGUI','Pakket');
insert into international (internationalId,languageId,namespace,message) values (377,3,'WebGUI','Er zijn geen pakketten gedefinieerd door uw pakket manager of beheerder.');
insert into international (internationalId,languageId,namespace,message) values (378,3,'WebGUI','Gebruikers ID');
insert into international (internationalId,languageId,namespace,message) values (379,3,'WebGUI','Groep ID');
insert into international (internationalId,languageId,namespace,message) values (380,3,'WebGUI','Stijl ID');
insert into international (internationalId,languageId,namespace,message) values (381,3,'WebGUI','WebGUI heeft een verkeerde vraag gekregen en kan niet verder gaan. Bepaalde karakters op de pagina kunnen de oorzaak zijn. Probeer terug te gaan naar de vorige pagina en probeer het opnieuw.');
insert into international (internationalId,languageId,namespace,message) values (528,3,'WebGUI','Sjabloon naam');
insert into international (internationalId,languageId,namespace,message) values (383,3,'WebGUI','Naam');
insert into international (internationalId,languageId,namespace,message) values (384,3,'WebGUI','Bestand');
insert into international (internationalId,languageId,namespace,message) values (385,3,'WebGUI','Parameters');
insert into international (internationalId,languageId,namespace,message) values (386,3,'WebGUI','Bewerk plaatje');
insert into international (internationalId,languageId,namespace,message) values (387,3,'WebGUI','Geleverd door');
insert into international (internationalId,languageId,namespace,message) values (388,3,'WebGUI','Upload datum');
insert into international (internationalId,languageId,namespace,message) values (389,3,'WebGUI','Plaatje ID');
insert into international (internationalId,languageId,namespace,message) values (390,3,'WebGUI','Plaatje laten zien......');
insert into international (internationalId,languageId,namespace,message) values (391,3,'WebGUI','Verwijder bijgevoegd bestand');
insert into international (internationalId,languageId,namespace,message) values (392,3,'WebGUI','Weet u zeker dat u dit plaatje wilt verwijderen?');
insert into international (internationalId,languageId,namespace,message) values (393,3,'WebGUI','Beheer plaatjes');
insert into international (internationalId,languageId,namespace,message) values (394,3,'WebGUI','Beheer plaatjes.');
insert into international (internationalId,languageId,namespace,message) values (395,3,'WebGUI','Een nieuw plaatje toevoegen');
insert into international (internationalId,languageId,namespace,message) values (396,3,'WebGUI','Plaatje laten zien');
insert into international (internationalId,languageId,namespace,message) values (397,3,'WebGUI','Terug naar plaatjes lijst');
insert into international (internationalId,languageId,namespace,message) values (398,3,'WebGUI','Document type declaratie');
insert into international (internationalId,languageId,namespace,message) values (399,3,'WebGUI','Valideer deze pagina');
insert into international (internationalId,languageId,namespace,message) values (400,3,'WebGUI','Voorkom Proxy Caching');
insert into international (internationalId,languageId,namespace,message) values (401,3,'WebGUI','Weet u zeker dat u dit bericht wilt verwijderen en alle berichten onder deze thread?');
insert into international (internationalId,languageId,namespace,message) values (402,3,'WebGUI','Het bericht wat u vroeg bestaat niet.');
insert into international (internationalId,languageId,namespace,message) values (403,3,'WebGUI','Geen mening');
insert into international (internationalId,languageId,namespace,message) values (405,3,'WebGUI','Laatste pagina');
insert into international (internationalId,languageId,namespace,message) values (406,3,'WebGUI','Miniatuur grootte');
insert into international (internationalId,languageId,namespace,message) values (407,3,'WebGUI','Klik hier om te registreren');
insert into international (internationalId,languageId,namespace,message) values (506,3,'WebGUI','Beheer Sjablonen');
insert into international (internationalId,languageId,namespace,message) values (408,3,'WebGUI','Beheer roots');
insert into international (internationalId,languageId,namespace,message) values (409,3,'WebGUI','Een nieuwe root toevoegen');
insert into international (internationalId,languageId,namespace,message) values (410,3,'WebGUI','Beheer roots.');
insert into international (internationalId,languageId,namespace,message) values (411,3,'WebGUI','Menu Titel');
insert into international (internationalId,languageId,namespace,message) values (412,3,'WebGUI','Omschrijving');
insert into international (internationalId,languageId,namespace,message) values (416,3,'WebGUI','<h1>Probleem met aanvraag</h1><br> We hebben een probleemm gevonden met de aanvraag van deze pagina. Ga terug naar de vorige pagina en probeer het opnieuw. Mocht het probleem zich blijven voordoen wendt u dan tot de beheerder.');
insert into international (internationalId,languageId,namespace,message) values (417,3,'WebGUI','<h1>Beveiligings probleem</h1><br> U probeerde een widget op te vragen die niet bij deze pagina hoort. Het incident is gerapporteerd.');
insert into international (internationalId,languageId,namespace,message) values (418,3,'WebGUI','Filter Contributed HTML');
insert into international (internationalId,languageId,namespace,message) values (419,3,'WebGUI','Verwijder alle tags');
insert into international (internationalId,languageId,namespace,message) values (420,3,'WebGUI','Laat het zoals het is');
insert into international (internationalId,languageId,namespace,message) values (421,3,'WebGUI','Verwijder alles behalve de basis formaten');
insert into international (internationalId,languageId,namespace,message) values (422,3,'WebGUI','<h1>Login Fout</h1><br>De informatie komt niet overeen met het account');
insert into international (internationalId,languageId,namespace,message) values (423,3,'WebGUI','Laat aktieve sessies zien');
insert into international (internationalId,languageId,namespace,message) values (424,3,'WebGUI','Laat login historie zien');
insert into international (internationalId,languageId,namespace,message) values (425,3,'WebGUI','Aktieve sessies');
insert into international (internationalId,languageId,namespace,message) values (426,3,'WebGUI','Login historie');
insert into international (internationalId,languageId,namespace,message) values (427,3,'WebGUI','Stijlen');
insert into international (internationalId,languageId,namespace,message) values (428,3,'WebGUI','Gebruiker (ID)');
insert into international (internationalId,languageId,namespace,message) values (429,3,'WebGUI','Login tijd');
insert into international (internationalId,languageId,namespace,message) values (430,3,'WebGUI','Laatst bekeken pagina');
insert into international (internationalId,languageId,namespace,message) values (431,3,'WebGUI','IP Adres');
insert into international (internationalId,languageId,namespace,message) values (432,3,'WebGUI','Verloopt');
insert into international (internationalId,languageId,namespace,message) values (433,3,'WebGUI','Gebruikers applicatie');
insert into international (internationalId,languageId,namespace,message) values (434,3,'WebGUI','Status');
insert into international (internationalId,languageId,namespace,message) values (435,3,'WebGUI','Sessie handtekening');
insert into international (internationalId,languageId,namespace,message) values (436,3,'WebGUI','Vermoord sessie');
insert into international (internationalId,languageId,namespace,message) values (437,3,'WebGUI','Statistieken');
insert into international (internationalId,languageId,namespace,message) values (438,3,'WebGUI','Uw naam');
insert into international (internationalId,languageId,namespace,message) values (441,3,'WebGUI','Email naar pager gateway');
insert into international (internationalId,languageId,namespace,message) values (442,3,'WebGUI','Bedrijfs informatie');
insert into international (internationalId,languageId,namespace,message) values (443,3,'WebGUI','Thuis informatie');
insert into international (internationalId,languageId,namespace,message) values (439,3,'WebGUI','Persoonlijke informatie');
insert into international (internationalId,languageId,namespace,message) values (440,3,'WebGUI','Contact informatie');
insert into international (internationalId,languageId,namespace,message) values (444,3,'WebGUI','Demografische informatie');
insert into international (internationalId,languageId,namespace,message) values (445,3,'WebGUI','Voorkeuren');
insert into international (internationalId,languageId,namespace,message) values (446,3,'WebGUI','Bedrijfs website');
insert into international (internationalId,languageId,namespace,message) values (447,3,'WebGUI','Beheer pagina boom');
insert into international (internationalId,languageId,namespace,message) values (448,3,'WebGUI','Pagina boom');
insert into international (internationalId,languageId,namespace,message) values (449,3,'WebGUI','Overige informatie');
insert into international (internationalId,languageId,namespace,message) values (450,3,'WebGUI','Werk naam (Bedrijfsnaam)');
insert into international (internationalId,languageId,namespace,message) values (451,3,'WebGUI','is vereist');
insert into international (internationalId,languageId,namespace,message) values (452,3,'WebGUI','Even wachten alstublieft....');
insert into international (internationalId,languageId,namespace,message) values (453,3,'WebGUI','Creatie datum');
insert into international (internationalId,languageId,namespace,message) values (454,3,'WebGUI','Laatst veranderd');
insert into international (internationalId,languageId,namespace,message) values (455,3,'WebGUI','Bewerk gebruikersprofiel');
insert into international (internationalId,languageId,namespace,message) values (456,3,'WebGUI','Terug naar gebruikers lijst');
insert into international (internationalId,languageId,namespace,message) values (457,3,'WebGUI','Bewerk het account van deze gebruiker');
insert into international (internationalId,languageId,namespace,message) values (458,3,'WebGUI','Bewerk de groepen van deze gebruiker');
insert into international (internationalId,languageId,namespace,message) values (459,3,'WebGUI','Bewerk het profiel van deze gebruiker');
insert into international (internationalId,languageId,namespace,message) values (460,3,'WebGUI','Tijd offset');
insert into international (internationalId,languageId,namespace,message) values (461,3,'WebGUI','Datum formaat');
insert into international (internationalId,languageId,namespace,message) values (462,3,'WebGUI','Tijd formaat');
insert into international (internationalId,languageId,namespace,message) values (463,3,'WebGUI','Tekst vlak rijen');
insert into international (internationalId,languageId,namespace,message) values (464,3,'WebGUI','Tekst vlak kolommen');
insert into international (internationalId,languageId,namespace,message) values (465,3,'WebGUI','Tekst blok grootte');
insert into international (internationalId,languageId,namespace,message) values (466,3,'WebGUI','Weet u zeker dat u deze categorie wilt verwijderen en alle velden naar de overige categorie wilt verplaatsen?');
insert into international (internationalId,languageId,namespace,message) values (467,3,'WebGUI','Weet u zeker dat u dit veld wilt verwijderen en daarmee ook alle data die er aan vast zit?');
insert into international (internationalId,languageId,namespace,message) values (469,3,'WebGUI','Id');
insert into international (internationalId,languageId,namespace,message) values (470,3,'WebGUI','Naam');
insert into international (internationalId,languageId,namespace,message) values (472,3,'WebGUI','Label');
insert into international (internationalId,languageId,namespace,message) values (473,3,'WebGUI','Zichtbaar?');
insert into international (internationalId,languageId,namespace,message) values (474,3,'WebGUI','Verplicht?');
insert into international (internationalId,languageId,namespace,message) values (475,3,'WebGUI','Tekst');
insert into international (internationalId,languageId,namespace,message) values (476,3,'WebGUI','Tekst vlak');
insert into international (internationalId,languageId,namespace,message) values (477,3,'WebGUI','HTML vlak');
insert into international (internationalId,languageId,namespace,message) values (478,3,'WebGUI','URL');
insert into international (internationalId,languageId,namespace,message) values (479,3,'WebGUI','Datum');
insert into international (internationalId,languageId,namespace,message) values (480,3,'WebGUI','Email adres');
insert into international (internationalId,languageId,namespace,message) values (481,3,'WebGUI','Telefoon nummer');
insert into international (internationalId,languageId,namespace,message) values (482,3,'WebGUI','Nummer (Geheel getal)');
insert into international (internationalId,languageId,namespace,message) values (483,3,'WebGUI','Ja of nee');
insert into international (internationalId,languageId,namespace,message) values (484,3,'WebGUI','Selecteer lijst');
insert into international (internationalId,languageId,namespace,message) values (485,3,'WebGUI','Booleaanse waarde (Checkbox)');
insert into international (internationalId,languageId,namespace,message) values (486,3,'WebGUI','Data type');
insert into international (internationalId,languageId,namespace,message) values (487,3,'WebGUI','Mogelijke waardes');
insert into international (internationalId,languageId,namespace,message) values (488,3,'WebGUI','Standaard waarde(s)');
insert into international (internationalId,languageId,namespace,message) values (489,3,'WebGUI','Profiel categorie');
insert into international (internationalId,languageId,namespace,message) values (490,3,'WebGUI','Profiel categorie toevoegen');
insert into international (internationalId,languageId,namespace,message) values (491,3,'WebGUI','Profiel veld toevoegen');
insert into international (internationalId,languageId,namespace,message) values (492,3,'WebGUI','Profiel veld lijst');
insert into international (internationalId,languageId,namespace,message) values (493,3,'WebGUI','terug naar de site');
insert into international (internationalId,languageId,namespace,message) values (496,3,'WebGUI','Ingebouwde editor');
insert into international (internationalId,languageId,namespace,message) values (494,3,'WebGUI','Te gebruiken Editor');
insert into international (internationalId,languageId,namespace,message) values (497,3,'WebGUI','Start datum');
insert into international (internationalId,languageId,namespace,message) values (498,3,'WebGUI','Eind Datum');
insert into international (internationalId,languageId,namespace,message) values (499,3,'WebGUI','Wobject ID');
insert into international (internationalId,languageId,namespace,message) values (500,3,'WebGUI','Pagina ID');
insert into international (internationalId,languageId,namespace,message) values (514,3,'WebGUI','Bekeken');
insert into international (internationalId,languageId,namespace,message) values (527,3,'WebGUI','Standaard home pagina');
insert into international (internationalId,languageId,namespace,message) values (530,3,'WebGUI','Met alle woorden');
insert into international (internationalId,languageId,namespace,message) values (501,3,'WebGUI','Body');
insert into international (internationalId,languageId,namespace,message) values (468,3,'WebGUI','Bewerk gebruikers profiel categorie');
insert into international (internationalId,languageId,namespace,message) values (507,3,'WebGUI','Bewerk sjabloon');
insert into international (internationalId,languageId,namespace,message) values (508,3,'WebGUI','Beheer sjablonen');
insert into international (internationalId,languageId,namespace,message) values (509,3,'WebGUI','Discussie layout');
insert into international (internationalId,languageId,namespace,message) values (510,3,'WebGUI','Plat');
insert into international (internationalId,languageId,namespace,message) values (511,3,'WebGUI','threaded');
insert into international (internationalId,languageId,namespace,message) values (512,3,'WebGUI','Volgende thread');
insert into international (internationalId,languageId,namespace,message) values (513,3,'WebGUI','Vorige thread');
insert into international (internationalId,languageId,namespace,message) values (533,3,'WebGUI','Zonder de woorden');
insert into international (internationalId,languageId,namespace,message) values (529,3,'WebGUI','Resultaten');
insert into international (internationalId,languageId,namespace,message) values (518,3,'WebGUI','Inbox notificaties');
insert into international (internationalId,languageId,namespace,message) values (519,3,'WebGUI','Ik wil geen notificatie krijgen');
insert into international (internationalId,languageId,namespace,message) values (520,3,'WebGUI','Ik wil notificatie via email');
insert into international (internationalId,languageId,namespace,message) values (521,3,'WebGUI','Ik wil notificatie via email naar pager');
insert into international (internationalId,languageId,namespace,message) values (522,3,'WebGUI','Ik wil notificatie via ICQ');
insert into international (internationalId,languageId,namespace,message) values (523,3,'WebGUI','Notificatie');
insert into international (internationalId,languageId,namespace,message) values (524,3,'WebGUI','Voeg bewerk stempel toe aan post');
insert into international (internationalId,languageId,namespace,message) values (525,3,'WebGUI','Bewerk inhoud Settings');
insert into international (internationalId,languageId,namespace,message) values (526,3,'WebGUI','Verwijder alleen javascript');
insert into international (internationalId,languageId,namespace,message) values (72,3,'EventsCalendar','Gebeurtenis, Toevoegen/aanpassen');
insert into international (internationalId,languageId,namespace,message) values (9,3,'Product','Product plaatje 3');
insert into international (internationalId,languageId,namespace,message) values (9,3,'MailForm','Voeg veld toe');
insert into international (internationalId,languageId,namespace,message) values (8,3,'Product','Product plaatje 2');
insert into international (internationalId,languageId,namespace,message) values (8,3,'MailForm','Breedte');
insert into international (internationalId,languageId,namespace,message) values (78,3,'EventsCalendar','Niets weggooien, ik heb een foutje gemaakt.');
insert into international (internationalId,languageId,namespace,message) values (77,3,'EventsCalendar','Gooi deze gebeurtenis weg <b>en</b> alle herhalingen hiervan.');
insert into international (internationalId,languageId,namespace,message) values (76,3,'EventsCalendar','Gooi alleen deze gebeurtenis weg.');
insert into international (internationalId,languageId,namespace,message) values (75,3,'EventsCalendar','Welke van deze keuzes wilt u uitvoeren?');
insert into international (internationalId,languageId,namespace,message) values (74,3,'EventsCalendar','Maandkalender (klein)');
insert into international (internationalId,languageId,namespace,message) values (73,3,'LinkList','<b>Titel</b><br>\r\nText die gelinked zal worden.\r\n<p>\r\n<b>URL</b><br>\r\nDe Website waarnaar gelinked wordt.\r\n<p>\r\n\r\n<b>In een nieuw venster openen?</b><br>\r\nSelecteer ja als u wilt dat deze link in een nieuw opkomend venster geopend wordt.\r\n<p>\r\n\r\n<b>Omschrijving</b><br>\r\nBeschrijf de site waar u naar linkt. Dit kan weggelaten worden als u dat wilt.\r\n<p>\r\n\r\n<b>Nog een link toevoegen?</b><br>\r\nAls u nog een link toe wilt voegen, selecteer dan ja.\r\n<p>\r\n');
insert into international (internationalId,languageId,namespace,message) values (73,3,'FAQ','<b>Vraag</b><br>\r\nVoer de vraag in die u in de FAQ wilt laten verschijnen.\r\n<p>\r\n\r\n\r\n<b>Antwoord</b><br>\r\nVoer het antwoord in voor de vraag die u hierboven heeft ingevuld.\r\n<p>\r\n\r\n\r\n<b>Nog een vraag toevoegen?</b><br>\r\nAls u nog een vraag wilt toevoegen, selecteer dan ja.\r\n<p>\r\n');
insert into international (internationalId,languageId,namespace,message) values (73,3,'EventsCalendar','<b>Titel</b><br>\r\nDe titel voor deze gebeurtenis.\r\n<p>\r\n\r\n<b>Beschrijving</b><br>\r\nOmschrijf de activiteit van deze gebeurtenis of voer informatie in over waar deze gebeurtenis plaatsvind.\r\n<p>\r\n\r\n<b>Begindatum</b><br>\r\nWanneer begint deze gebeurtenis?\r\n<p>\r\n\r\n<b>Einddatum</b><br>\r\nOp welke datum zal deze gebeurtenis plaatsvinden?\r\n<p>\r\n\r\n<b>Gebeurt iedere</b><br>\r\nSelecteer een interval waarin deze gebeurtenis opnieuw plaatsvind.\r\n<p>\r\n\r\n<b>Nog een gebeurtenis toevoegen?</b><br>\r\nAls u nog een gebeurtenis toe wilt voegen, selecteer dan ja.\r\n<p>');
insert into international (internationalId,languageId,namespace,message) values (72,3,'Poll','Antwoorden in willekeurige volgorde weergeven?');
insert into international (internationalId,languageId,namespace,message) values (72,3,'LinkList','Link, Toevoegen/Aanpassen');
insert into international (internationalId,languageId,namespace,message) values (72,3,'FAQ','Vraag, Toevoegen/Aanpasssen');
insert into international (internationalId,languageId,namespace,message) values (72,3,'DownloadManager','Download, Toevoegen/Aanpassen');
insert into international (internationalId,languageId,namespace,message) values (717,3,'WebGUI','Uitloggen');
insert into international (internationalId,languageId,namespace,message) values (716,3,'WebGUI','Inloggen');
insert into international (internationalId,languageId,namespace,message) values (715,3,'WebGUI','Redirect URL');
insert into international (internationalId,languageId,namespace,message) values (714,3,'WebGUI','Sjabloonbeheer groep');
insert into international (internationalId,languageId,namespace,message) values (713,3,'WebGUI','Stijlbeheer groep');
insert into international (internationalId,languageId,namespace,message) values (711,3,'WebGUI','Plaatjesbeheer groep');
insert into international (internationalId,languageId,namespace,message) values (710,3,'WebGUI','Pas privilege instellingen aan');
insert into international (internationalId,languageId,namespace,message) values (654,3,'WebGUI','Stijl, Verwijder');
insert into international (internationalId,languageId,namespace,message) values (471,3,'WebGUI','Pas gebruikers profielveld aan');
insert into international (internationalId,languageId,namespace,message) values (36,3,'Product','Voeg een accesoire toe');
insert into international (internationalId,languageId,namespace,message) values (585,3,'WebGUI','Beheer vertalingen.');
insert into international (internationalId,languageId,namespace,message) values (708,3,'WebGUI','Privilege instellingen, Beheren');
insert into international (internationalId,languageId,namespace,message) values (707,3,'WebGUI','Laat debugging zien?');
insert into international (internationalId,languageId,namespace,message) values (706,3,'WebGUI','Uren');
insert into international (internationalId,languageId,namespace,message) values (705,3,'WebGUI','Minuten');
insert into international (internationalId,languageId,namespace,message) values (704,3,'WebGUI','Seconden');
insert into international (internationalId,languageId,namespace,message) values (703,3,'WebGUI','Jaren');
insert into international (internationalId,languageId,namespace,message) values (702,3,'WebGUI','Maanden');
insert into international (internationalId,languageId,namespace,message) values (7,3,'Product','Product plaatje 1');
insert into international (internationalId,languageId,namespace,message) values (5,3,'WobjectProxy','Wobject proxy, Toevoegen/aanpassen');
insert into international (internationalId,languageId,namespace,message) values (699,3,'WebGUI','Eerste dag van de week');
insert into international (internationalId,languageId,namespace,message) values (696,3,'WebGUI','Prullenbak, Legen');
insert into international (internationalId,languageId,namespace,message) values (697,3,'WebGUI','Karma, Gebruiken');
insert into international (internationalId,languageId,namespace,message) values (686,3,'WebGUI','Plaatjesgroep, Toevoegen');
insert into international (internationalId,languageId,namespace,message) values (685,3,'WebGUI','Sjabloon, verwijderen');
insert into international (internationalId,languageId,namespace,message) values (684,3,'WebGUI','Template, Toevoegen/aanpassen');
insert into international (internationalId,languageId,namespace,message) values (598,3,'WebGUI','Taal aanpassen.');
insert into international (internationalId,languageId,namespace,message) values (596,3,'WebGUI','NIET AANWEZIG');
insert into international (internationalId,languageId,namespace,message) values (605,3,'WebGUI','Voeg groepen toe');
insert into international (internationalId,languageId,namespace,message) values (601,3,'WebGUI','International ID');
insert into international (internationalId,languageId,namespace,message) values (597,3,'WebGUI','Pas internationaal bericht aan');
insert into international (internationalId,languageId,namespace,message) values (594,3,'WebGUI','Vertaal internationale berichten');
insert into international (internationalId,languageId,namespace,message) values (593,3,'WebGUI','Verstuur vertaling naar Plain Black');
insert into international (internationalId,languageId,namespace,message) values (595,3,'WebGUI','Internationale berichten');
insert into international (internationalId,languageId,namespace,message) values (591,3,'WebGUI','Taal');
insert into international (internationalId,languageId,namespace,message) values (590,3,'WebGUI','Taal ID');
insert into international (internationalId,languageId,namespace,message) values (589,3,'WebGUI','Pas taal aan');
insert into international (internationalId,languageId,namespace,message) values (586,3,'WebGUI','Talen');
insert into international (internationalId,languageId,namespace,message) values (584,3,'WebGUI','Voeg een nieuwe taal toe');
insert into international (internationalId,languageId,namespace,message) values (575,3,'WebGUI','Pas aan');
insert into international (internationalId,languageId,namespace,message) values (576,3,'WebGUI','Verwijder');
insert into international (internationalId,languageId,namespace,message) values (582,3,'WebGUI','Laat leeg');
insert into international (internationalId,languageId,namespace,message) values (683,3,'WebGUI','Sjablonen, beheer');
insert into international (internationalId,languageId,namespace,message) values (682,3,'WebGUI','Gebruikersprofiel, Aanpassen');
insert into international (internationalId,languageId,namespace,message) values (681,3,'WebGUI','Pakketten, Maken');
insert into international (internationalId,languageId,namespace,message) values (680,3,'WebGUI','Pakket, Toevoegen');
insert into international (internationalId,languageId,namespace,message) values (679,3,'WebGUI','Inhoudsinstellingen, Aanpassen');
insert into international (internationalId,languageId,namespace,message) values (677,3,'WebGUI','Wobject, Toevoegen/Aanpassen');
insert into international (internationalId,languageId,namespace,message) values (1,3,'MailForm','E-mail formulier');
insert into international (internationalId,languageId,namespace,message) values (10,3,'MailForm','Van');
insert into international (internationalId,languageId,namespace,message) values (11,3,'MailForm','Aan (email, gebruikersnaam of groepsnaam)');
insert into international (internationalId,languageId,namespace,message) values (23,3,'MailForm','Type');
insert into international (internationalId,languageId,namespace,message) values (13,3,'MailForm','Bcc (Onzichtbare kopie naar)');
insert into international (internationalId,languageId,namespace,message) values (12,3,'MailForm','Cc (Kopie naar)');
insert into international (internationalId,languageId,namespace,message) values (22,3,'MailForm','Status');
insert into international (internationalId,languageId,namespace,message) values (21,3,'MailForm','Veldnaam');
insert into international (internationalId,languageId,namespace,message) values (20,3,'MailForm','Pas veld aan');
insert into international (internationalId,languageId,namespace,message) values (2,3,'MailForm','Uw email onderwerp hier');
insert into international (internationalId,languageId,namespace,message) values (14,3,'MailForm','Onderwerp');
insert into international (internationalId,languageId,namespace,message) values (15,3,'MailForm','Doorgaan met meer velden toevoegen?');
insert into international (internationalId,languageId,namespace,message) values (18,3,'MailForm','Ga terug!');
insert into international (internationalId,languageId,namespace,message) values (16,3,'MailForm','Bevestigingsbericht');
insert into international (internationalId,languageId,namespace,message) values (17,3,'MailForm','Mail is verstuurd');
insert into international (internationalId,languageId,namespace,message) values (19,3,'MailForm','Weet u zeker dat u dit veld wilt verwijderen?');
insert into international (internationalId,languageId,namespace,message) values (61,3,'Article','Artikel, Toevoegen/Aanpassen');
insert into international (internationalId,languageId,namespace,message) values (24,3,'MailForm','Mogelijke waarden (alleen voor \'drop-down box\')');
insert into international (internationalId,languageId,namespace,message) values (25,3,'MailForm','Standaard waarde (optioneel)');
insert into international (internationalId,languageId,namespace,message) values (7,3,'MailForm','Pas email formulier aan');
insert into international (internationalId,languageId,namespace,message) values (6,3,'MailForm','Aanpasbaar');
insert into international (internationalId,languageId,namespace,message) values (62,3,'MailForm','Email formulier velden, toevoegen/aanpassen');
insert into international (internationalId,languageId,namespace,message) values (61,3,'MailForm','Email formulier, toevoegen/aanpassen');
insert into international (internationalId,languageId,namespace,message) values (5,3,'MailForm','Zichtbaar(niet aanpasbaar)');
insert into international (internationalId,languageId,namespace,message) values (4,3,'MailForm','Verborgen');
insert into international (internationalId,languageId,namespace,message) values (26,3,'MailForm','Inzendingen opslaan?');
insert into international (internationalId,languageId,namespace,message) values (3,3,'MailForm','Bedankt voor uw bericht!');
insert into international (internationalId,languageId,namespace,message) values (588,3,'WebGUI','Weet u zeker dat u deze vertaling naar Plain Black wilt versturen voor bundeling in de standaarddistributie? Door op de \'ja\' link te klikken snapt u dat u Plain Black een onbeperkte licentie geeft om de vertaling in haar software verspreidingen te gebruiken.');
insert into international (internationalId,languageId,namespace,message) values (581,3,'WebGUI','Voeg een nieuwe waarde toe');
insert into international (internationalId,languageId,namespace,message) values (543,3,'WebGUI','Voeg een nieuwe plaatjesgroep toe.');
insert into international (internationalId,languageId,namespace,message) values (583,3,'WebGUI','Maximale plaatjesgrootte');
insert into international (internationalId,languageId,namespace,message) values (547,3,'WebGUI','Ouder groep');
insert into international (internationalId,languageId,namespace,message) values (546,3,'WebGUI','Groep Id');
insert into international (internationalId,languageId,namespace,message) values (542,3,'WebGUI','Vorige..');
insert into international (internationalId,languageId,namespace,message) values (544,3,'WebGUI','Weet u zeker dat u deze groep wilt verwijderen? ');


