insert into webguiVersion values ('4.9.1','upgrade',unix_timestamp());
delete from template where namespace='MessageBoard' and templateId<2;
delete from template where namespace='LinkList' and templateId<5;
INSERT INTO template VALUES (1,'Default Link List','<tmpl_if displayTitle>\r\n    <h1><tmpl_var title></h1>\r\n</tmpl_if>\r\n\r\n<tmpl_if description>\r\n    <tmpl_var description><p/>\r\n</tmpl_if>\r\n\r\n<tmpl_if session.var.adminOn>\r\n  <a href=\"<tmpl_var addlink.url>\"><tmpl_var addlink.label></a><p />\r\n</tmpl_if>\r\n\r\n<tmpl_loop link_loop>\r\n   <tmpl_if session.var.adminOn>\r\n         <tmpl_var link.controls>\r\n   </tmpl_if>\r\n   &middot;\r\n   <a href=\"<tmpl_var link.url>\"\r\n   <tmpl_if link.newwindow>\r\n          target=\"_blank\"\r\n    </tmpl_if>\r\n    ><span class=\"linkTitle\"><tmpl_var link.name></span></a>\r\n\r\n    <tmpl_if link.description>\r\n              - <tmpl_var link.description>\r\n   </tmpl_if>\r\n   <br/>\r\n</tmpl_loop>\r\n','LinkList');
INSERT INTO template VALUES (2,'Unordered List','<tmpl_if displayTitle>\r\n    <h1><tmpl_var title></h1>\r\n</tmpl_if>\r\n\r\n<tmpl_if description>\r\n    <tmpl_var description><p/>\r\n</tmpl_if>\r\n\r\n<tmpl_if session.var.adminOn>\r\n  <a href=\"<tmpl_var addlink.url>\"><tmpl_var addlink.label></a><p />\r\n</tmpl_if>\r\n\r\n<ul>\r\n<tmpl_loop link_loop>\r\n<li>\r\n   <tmpl_if session.var.adminOn>\r\n         <tmpl_var link.controls>\r\n   </tmpl_if>\r\n   \r\n   <a href=\"<tmpl_var link.url>\"\r\n   <tmpl_if link.newwindow>\r\n          target=\"_blank\"\r\n    </tmpl_if>\r\n    ><span class=\"linkTitle\"><tmpl_var link.name></span></a>\r\n\r\n    <tmpl_if link.description>\r\n              - <tmpl_var link.description>\r\n   </tmpl_if>\r\n </li>\r\n</tmpl_loop>\r\n</u>','LinkList');
INSERT INTO template VALUES (3,'Ordered List','<tmpl_if displayTitle>\r\n    <h1><tmpl_var title></h1>\r\n</tmpl_if>\r\n\r\n<tmpl_if description>\r\n    <tmpl_var description><p/>\r\n</tmpl_if>\r\n\r\n<tmpl_if session.var.adminOn>\r\n  <a href=\"<tmpl_var addlink.url>\"><tmpl_var addlink.label></a><p />\r\n</tmpl_if>\r\n\r\n<ol>\r\n<tmpl_loop link_loop>\r\n  <li>\r\n   <tmpl_if session.var.adminOn>\r\n         <tmpl_var link.controls>\r\n   </tmpl_if>\r\n\r\n   <a href=\"<tmpl_var link.url>\"\r\n   <tmpl_if link.newwindow>\r\n          target=\"_blank\"\r\n    </tmpl_if>\r\n    ><span class=\"linkTitle\"><tmpl_var link.name></span></a>\r\n\r\n    <tmpl_if link.description>\r\n              - <tmpl_var link.description>\r\n   </tmpl_if>\r\n  </li>\r\n</tmpl_loop>\r\n</ol>','LinkList');
INSERT INTO template VALUES (4,'Descriptive','<tmpl_if displayTitle>\r\n    <h1><tmpl_var title></h1>\r\n</tmpl_if>\r\n\r\n<tmpl_if description>\r\n    <tmpl_var description><p/>\r\n</tmpl_if>\r\n\r\n<tmpl_if session.var.adminOn>\r\n  <a href=\"<tmpl_var addlink.url>\"><tmpl_var addlink.label></a><p />\r\n</tmpl_if>\r\n\r\n<tmpl_loop link_loop>\r\n   <tmpl_if session.var.adminOn>\r\n         <tmpl_var link.controls> <br />\r\n   </tmpl_if>\r\n\r\n  <a href=\"<tmpl_var link.url>\"\r\n   <tmpl_if link.newwindow>\r\n          target=\"_blank\"\r\n    </tmpl_if>\r\n    ><span class=\"linkTitle\"><tmpl_var link.name></span></a>\r\n\r\n    <tmpl_if link.description>\r\n              - <tmpl_var link.description>\r\n   </tmpl_if>\r\n   <p />\r\n</tmpl_loop>\r\n','LinkList');
INSERT INTO template VALUES (1,'Default Message Board','<tmpl_if displayTitle>\r\n    <h1><tmpl_var title></h1>\r\n</tmpl_if>\r\n\r\n<tmpl_if description>\r\n    <tmpl_var description><p/>\r\n</tmpl_if>\r\n\r\n<table width=\"100%\" cellpadding=2 cellspacing=1 border=0>\r\n<tr>\r\n <td align=\"right\" valign=\"bottom\" class=\"tableMenu\">\r\n  <tmpl_if canPost>\r\n        <a href=\"<tmpl_var post.url>\"><tmpl_var post.label></a> &middot;\r\n  </tmpl_if>\r\n  <a href=\"<tmpl_var search.url>\"><tmpl_var search.label></a>\r\n  </td></tr></table>\r\n\r\n  <table border=0 cellpadding=2 cellspacing=1 width=\"100%\">\r\n      <tr>\r\n            <td class=\"tableHeader\"><tmpl_var subject.label></td>\r\n            <td class=\"tableHeader\"><tmpl_var user.label></td>\r\n            <td class=\"tableHeader\"><tmpl_var date.label></td>\r\n            <td class=\"tableHeader\"><tmpl_var views.label></td>\r\n            <td class=\"tableHeader\"><tmpl_var replies.label></td>\r\n            <td class=\"tableHeader\"><tmpl_var last.label></td>\r\n     </tr>\r\n\r\n<tmpl_loop message_loop>\r\n   <tr><td class=\"tableData\">\r\n        <a href=\"<tmpl_var message.url>\"><tmpl_var message.subject></a>\r\n         <tmpl_if message.currentUser>\r\n              (<tmpl_var message.status>)\r\n         </tmpl_if>  \r\n     </td>\r\n      <td class=\"tableData\"><a href=\"<tmpl_var message.userProfile>\"><tmpl_var message.username></a></td>\r\n      <td class=\"tableData\"><tmpl_var message.date></td>\r\n      <td class=\"tableData\"><tmpl_var message.views></td>\r\n      <td class=\"tableData\"><tmpl_var message.replies></td>\r\n      <td class=\"tableData\">\r\n         <span style=\"font-size: 8pt;\">\r\n              <a href=\"<tmpl_var last.url>\"><tmpl_var last.subject></a>\r\n              @ <tmpl_var last.date> \r\n              by <a href=\"<tmpl_var last.userProfile>\"><tmpl_var last.username></a>\r\n          </span>\r\n     </td>\r\n   </tr>\r\n</tmpl_loop>\r\n</table>\r\n\r\n\r\n<tmpl_if multiplePages>\r\n  <div class=\"pagination\">\r\n    <tmpl_var previousPage>  &middot; <tmpl_var pageList> &middot; <tmpl_var nextPage>\r\n  </div>\r\n</tmpl_if>\r\n\r\n','MessageBoard');




