insert into webguiVersion values ('5.0.3','upgrade',unix_timestamp());
delete from international where languageId=2 and namespace='WebGUI' and internationalId=625;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (625,2,'WebGUI','Laden Sie einige Bilder hoch, die Sie in mehreren Bereichen der Seite benutzen \r\nmöchten. \r\n<P><b>Name</b><BR>Die Bezeichnung, mit der Sie dieses Bild referenzieren, um \r\nes in anderen Seiten einzufügen. \r\n<P><b>In welches Verzeichnis?</b><BR>In welches Verzeichnis möchten Sie diese \r\nGrafik platzieren?<P><b>Datei</b><BR>Wählen Sie eine Grafik aus Ihrem lokalen \r\nVerzeichnis, die Sie zum Server hochladen möchten. \r\n<P><b>Parameter</b><BR>Geben Sie hier einige  HTML &lt;img Tag Parameter an, \r\ndie Sie standardmässig für diese Grafik benutzen möchten. \r\n<P><I>Beispiel:</I><BR>align=&quot;right&quot;<BR>alt=&quot;Dies ist ein Bild&quot;<BR>\r\n<P><b>Thumbnail Size</b><BR>Wie gross  (in Pixels) soll das Vorschaubild (Thumbnail) \r\nsein?</P>', 1042585804);
delete from international where languageId=2 and namespace='MailForm' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,2,'MailForm','Senden', 1042383682);
delete from international where languageId=2 and namespace='Product' and internationalId=47;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (47,2,'Product','Verwandte Produkte sind Produkte, die vergleichbar zu anderen Produkten sind.<br><br>\r\n<b>Verwandte Produkte</b><br>\r\nWählen Sie aus der Liste ein Produkt aus, das Sie bereits eingegeben haben.<br><br>\r\n<b>Weiteres verwandtes Produkt hinzufügen?</b><br><br>\r\nMöchten Sie ein weiteres Produkt hinzufügen?\r\n', 1042383649);
delete from template where templateId=1 and namespace='USS/Submission';
INSERT INTO template VALUES (1,'Default Submission','<h1><tmpl_var title></h1>\r\n<table width=\"100%\" cellpadding=2 cellspacing=1 border=0>\r\n<tr><td valign=\"top\" class=\"tableHeader\" width=\"100%\">\r\n<b><tmpl_var user.label>:</b> <a href=\"<tmpl_var user.Profile>\"><tmpl_var user.username></a><br />\r\n<b><tmpl_var date.label>:</b> <tmpl_var date.human><br />\r\n<b><tmpl_var status.label>:</b> <tmpl_var status.status><br />\r\n<b><tmpl_var views.label>:</b> <tmpl_var views.count><br />\r\n</td>\r\n<td rowspan=\"2\" class=\"tableMenu\" nowrap=\"1\" valign=\"top\">\r\n\r\n<tmpl_if previous.more>\r\n   <a href=\"<tmpl_var previous.url>\">&laquo;<tmpl_var previous.label></a><br />\r\n</tmpl_if>\r\n<tmpl_if next.more>\r\n   <a href=\"<tmpl_var next.url>\"><tmpl_var next.label>&raquo;</a><br />\r\n</tmpl_if>\r\n<tmpl_if canEdit>\r\n   <a href=\"<tmpl_var edit.url>\"><tmpl_var edit.label></a><br />\r\n   <a href=\"<tmpl_var delete.url>\"><tmpl_var delete.label></a><br />\r\n</tmpl_if>\r\n<tmpl_if canChangeStatus>\r\n   <a href=\"<tmpl_var approve.url>\"><tmpl_var approve.label></a><br />\r\n   <a href=\"<tmpl_var leave.url>\"><tmpl_var leave.label></a><br />\r\n   <a href=\"<tmpl_var deny.url>\"><tmpl_var deny.label></a><br />\r\n</tmpl_if>\r\n<tmpl_if canReply>\r\n   <a href=\"<tmpl_var reply.url>\"><tmpl_var reply.label></a><br />\r\n</tmpl_if>\r\n<tmpl_if canPost>\r\n   <a href=\"<tmpl_var post.url>\"><tmpl_var post.label></a><br />\r\n</tmpl_if>\r\n<a href=\"<tmpl_var search.url>\"><tmpl_var search.label></a><br />\r\n<a href=\"<tmpl_var back.url>\"><tmpl_var back.label></a><br />\r\n\r\n</td</tr><tr><td class=\"tableData\">\r\n<tmpl_if image.url>\r\n  <img src=\"<tmpl_var image.url>\" border=\"0\"><p />\r\n</tmpl_if>\r\n<tmpl_var content><p />\r\n<tmpl_var attachment.box><br />\r\n\r\n</td></tr></table>\r\n\r\n<tmpl_var replies>','USS/Submission');
delete from international where languageId=1 and namespace='WebGUI' and internationalId=624;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (624,1,'WebGUI','WebGUI macros are used to create dynamic content within otherwise static content. For instance, you may wish to show which user is logged in on every page, or you may wish to have a dynamically built menu or crumb trail. \r\n<p>\r\n\r\nMacros always begin with a carat (^) and follow with at least one other character and ended with a semicolon (;). Some macros can be extended/configured by taking the format of ^<i>x</i>("<b>config text</b>");. \r\n<p>\r\n\r\nNOTE: The following macros are reserved for system/wobject-specific functions as in the SQL Report wobject and the Body in the Style Manager: \r\n<b>^-;,^0;,^1;,^2;,^3;, etc.</b><br>\r\n<p>\r\n', 1043289717);
delete from international where languageId=1 and namespace='WebGUI' and internationalId=832;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (832,1,'WebGUI','The collateral management system has several macros for its specific purpose.\r\n<p/>\r\n\r\n<b>^File();</b><br/>\r\nThis macro builds a quick file link. It creates an icon for the file and outputs the files name. Then it links them both to the file for downloading.\r\n<p/>\r\n\r\n<b>^I();</b><br/>\r\nThis macro retrieves an image from the collateral management system along with an HTML image tag so that you can quickly display an image from the repository in your content.\r\n<p/>\r\n<i>Example:</i> ^I("logo");\r\n<p/>\r\n\r\n<b>^i();</b><br/>\r\nThis macro retrieves the URL for any file in the collateral management system.\r\n<p/>\r\n<i>Example:</i> ^i("status report");\r\n<p/>\r\n\r\n<b>^Snippet();</b><br/>\r\nThis macro retrieves the contents of a snippet in the collateral management system and inserts it into the page.\r\n<p />\r\n<i>Example:</i> ^Snippet("flash code");\r\n<p />\r\n\r\n<b>^Thumbnail();</b><br/>\r\nThis macro retrieves the URL for the thumbnail of any image in the collateral management system.\r\n<p/>\r\n<i>Example:</i> ^Thumbnail("logo");\r\n<p/>\r\n\r\n<b>^ThumbnailLinker();</b><br/>\r\nThis macro builds a quick image viewer using nothing more than the collateral management system. It creates a thumbnail image with the name of the image under it and then links them both to the full sized image.\r\n<p/>\r\n<i>Example:</i> ^ThumbnailLinker("logo");\r\n<p/>\r\n\r\n', 1043289595);
delete from language where languageId=4;
insert into language (languageId,language,characterSet,toolbar) values (4, 'Espa�ol (Spanish)', 'ISO-8859-1', 'spanish');
delete from international where languageId=3 and namespace='WebGUI' and internationalId=623;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (623,3,'WebGUI','<a href=\"http://www.w3.org/Style/css/\">Cascading Style Sheets (CSS)</a> zijn \r\neen goede manier om het uiterlijk en gevoel van een webpagina te beheren. \r\nZe worden uitgebreid gebruikt in WebGUI.<br>\r\n <br>\r\n Als er geen ervaring is met het gebruik van CSS, heeft <a\r\n href=\"http://www.plainblack.com\">Plain Black Software</a> cursussen in XHTML \r\nen CSS. Als alternatief kan de CSS editor, genaamd <a\r\n href=\"http://www.bradsoft.com/topstyle/index.asp\">Top Style</a> gebruikt \r\nworden.<br>\r\n <br>\r\n De volgende lijst bevat de verschillende klassen die gebruikt worden het \r\nuiterlijk en gevoel van WebGUI te bepalen:<br>\r\n <br>\r\n <b>A</b><br>\r\n De links in een stijl.<br>\r\n <br>\r\n <b>BODY</b><br>\r\n De tsandaard indeling van alle paginas die de stijl gebruiken.<br>\r\n <br>\r\n <b>H1</b><br>\r\n De headers (koppen) op elke pagina.<br>\r\n <br>\r\n <b>.accountOptions</b><br>\r\n De links sie onder de login en account update formulieren verschijnen.<br>\r\n <br>\r\n <b>.adminBar</b><br>\r\n De balk die bovenaan de pagina verschijnt wanneer de beheer modus gebruikt \r\nwordt.<br>\r\n <br>\r\n <b>.inhoud</b><br>\r\n Het belangrijkste inhouds gebied in elke pagina die de stijl gebruikt<br>\r\n <br>\r\n <b>.formDescription</b><br>\r\n De labels op alle formulieren naast de formulier elementen.<br>\r\n <br>\r\n <b>.formSubtext</b><br>\r\n De labels onder sommige formulier elementen.<br>\r\n  <b><br>\r\n.highlight</b><br>\r\nDuid een highlighted object aan, zoals een bericht dat bekeken wordt binnen\r\neen lijst.<br>\r\n<br>\r\n<b>.horizontalMenu</b><br>\r\nHet horizontale menu (als het horizontale menu macro gebruikt wordt).<br>\r\n<br>\r\n<b>.pagination</b><br>\r\nDe Vorige en Volgende links op paginas die opgebroken worden in meer paginas.<br>\r\n<br>\r\n<b>.selectedMenuItem</b><br>\r\nGebruik deze klasse om de huidige pagina te highlighten in een menu macro.<br>\r\n<br>\r\n<b>.tableData</b><br>\r\nDe data rijen in dingen zoals berichtenborden en gebruikersbijdragen.<br>\r\n<br>\r\n<b>.tableHeader</b><br>\r\nDe headers van kolommen in dingen zoals berichtenborden en gebruikersbijdragen.<br>\r\n <br>\r\n<b>.tableMenu</b><br>\r\nHet menu in dingen zoals berichtenborden en gebruikersbijdragen.<br>\r\n<br>\r\n<b>.verticalMenu</b><br>\r\n Het vertikale menu (als het vertikale menu macro gebruikt wordt).<br>\r\n<br>\r\n<i><b>N.B.:</b></i> Sommige wobjecten en macros hebben hun eigen unieke stylesheet\r\nklasse, die gedocumenteerd worden in hun eigen hulp bestanden.<br>\r\n', 1043314620);
delete from international where languageId=3 and namespace='WebGUI' and internationalId=624;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (624,3,'WebGUI','WebGUI macros worden gebruikt voor het maken van dynamische inhoud binnen een voor de rest statische inhoud. Zo kan bijvoorbeeld voor elke pagina getoond  worden welke gebruikers op deze pagina ingelogd zijn of er kan een  dynamisch  gebouwd menu of een webpad weergegeven worden.<br>\r\n<br>\r\nMacros beginnen altijd met een carat (dakje) (^) en wordt vervolgd met minstens &eacute;&eacute;n ander karakter en eindigen met een puntkomma (;). Sommige  macros kunnen uitgebreid of aangepast worden door de opmaak\r\n<i>^x</i>(\"<b>aangepaste  tekst</b>\"); te gebruiken.\r\n<br>\r\n<b>N.B.</b><br>\r\nOnderstaande macros worden apart gehouden voor systeem of wobject specifieke functies zoals het SQL Verslag wobject en de Body in de Stijl Beheerder.<b>^-;, ^0;, ^1;, ^2;, ^3;, etc</b><br>', 1043314531);
delete from international where languageId=3 and namespace='Product' and internationalId=47;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (47,3,'Product','Gerelateerde produkten zijn produkten die vergelijkbaar zijn met een produkt of die een aanvulling op een produkt.<br>\r\n<br>\r\n<b>Gerelateerde produkten</b><br>\r\nTe kiezen van de lijst met produkten die al ingevoerd zijn.<br>\r\n<br>\r\n<b>Nog een gerelateerd produkt toevoegen?</b><br>\r\nSelecteer \"Ja\" als er nog een gerelateerd produkt toegevoegd gaat worden.<br>', 1043314348);
delete from international where languageId=3 and namespace='WebGUI' and internationalId=832;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (832,3,'WebGUI','<p>Het collaterale inhoudsbeheer systeem heeft de beschikking over enkele specifieke macro\'s.</p>\r\n<b>^File();</b><br/>\r\nDit macro maakt een snelle bestandslink. Het maakt een pictogram voor het bestand en laat de bestandsnaam zien. Daarna linkt het naar dit bestand zodat het gedownload kan worden.<p/>\r\n<p><b>^I();</b><br>\r\nDit macro haalt een plaatje uit het collaterale inhoudsbeheer systeem en voegt daaraan een HTML plaatjes tag toe zodat het mogelijk is snel een plaatje uit het collaterale systeem in uw inhoud te plaatsen.</p>\r\n<p><i>Voorbeeld:</i> ^I(\"logo\");\r\n</p>\r\n<b>^i();</b><br/>\r\nDit macro haalt de URL voor willekeurige inhoud uit het systeem.\r\n<p/>\r\n<i>Voorbeeld:</i> ^i(\"status rapportage\");\r\n<p/>\r\n\r\n<b>^Snippet();</b><br/>\r\nDit makro haalt de inhoud van het knipsel uit het systeem en plakt het in de pagina.\r\n<p/>\r\n<i>Voorbeeld:</i> ^Snippet(\"flash code\");\r\n<p/>\r\n\r\n<b>^Thumbnail();</b><br/>\r\nDit makro geeft de URL voor het pictogram van een plaatje uit het systeem.\r\n<p/>\r\n<i>Voorbeeld:</i> ^Thumbnail(\"trouwfoto\");\r\n<p/>\r\n\r\n<b>^ThumbnailLinker();</b><br/>\r\nDit macro bouwt een plaatje zoals het Thumbnail macro en maakt daar een link van naar het plaatje op volledige groote.\r\n<p/>\r\n<i>Voorbeeld:</i> ^ThumbnailLinker(\"trouwfoto\");\r\n<p/>\r\n\r\n', 1043314308);




