insert into webguiVersion values ('3.9.0','upgrade',unix_timestamp());
alter table style add column body text;
update style set body=concat('^AdminBar;\n\n',header,'\n\n^-;\n\n',footer);
alter table style drop column header;
alter table style drop column footer;
delete from international where internationalId=152 and namespace='WebGUI';
delete from international where internationalId=153 and namespace='WebGUI';
INSERT INTO international VALUES (501,'WebGUI','English','Body');
alter table style change name name varchar(255);
create table template (
  templateId int not null primary key,
  name varchar(255),
  template text
);
INSERT INTO international VALUES (502,'WebGUI','English','Are you certain you wish to delete this template and set all pages using this template to the default template?');
INSERT INTO international VALUES (503,'WebGUI','English','Template ID');
INSERT INTO international VALUES (504,'WebGUI','English','Template');
INSERT INTO international VALUES (505,'WebGUI','English','Add a new template.');
INSERT INTO groups VALUES (8,'Template Managers','Users that have privileges to edit templates for this site.',314496000);
INSERT INTO international VALUES (506,'WebGUI','English','Manage Templates');
INSERT INTO international VALUES (507,'WebGUI','English','Edit Template');
INSERT INTO international VALUES (508,'WebGUI','English','Manage templates.');
INSERT INTO incrementer VALUES ('templateId',1000);
INSERT INTO template VALUES (1,'Default','<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n<tr>\r\n  <td valign=\"top\" class=\"content\">^0;</td>\r\n</tr>\r\n</table>');
INSERT INTO template VALUES (2,'News','<table cellpadding=\"3\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n<tr>\r\n  <td valign=\"top\" class=\"content\" colspan=\"2\" width=\"100%\">^0;</td></tr>\r\n<tr>\r\n  <td valign=\"top\" class=\"content\" width=\"50%\">^1;</td>\r\n  <td valign=\"top\" class=\"content\" width=\"50%\">^2;</td>\r\n</tr>\r\n<tr>\r\n  <td valign=\"top\" class=\"content\" colspan=\"2\" width=\"100%\">^3;</td>\r\n</tr>\r\n</table>\r\n');
INSERT INTO template VALUES (3,'One Over Three','<table cellpadding=\"3\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n<tr>\r\n  <td valign=\"top\" class=\"content\" colspan=\"3\">^0;</td>\r\n</tr>\r\n<tr>\r\n  <td valign=\"top\" class=\"content\" width=\"33%\">^1;</td>\r\n  <td valign=\"top\" class=\"content\" width=\"34%\">^2;</td>\r\n  <td valign=\"top\" class=\"content\" width=\"33%\">^3;</td>\r\n</tr>\r\n</table>');
INSERT INTO template VALUES (4,'Three Over One','<table cellpadding=\"3\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n<tr>\r\n  <td valign=\"top\" class=\"content\" width=\"33%\">^0;</td>\r\n  <td valign=\"top\" class=\"content\" width=\"34%\">^1;</td>\r\n  <td valign=\"top\" class=\"content\" width=\"33%\">^2;</td>\r\n</tr>\r\n<tr>\r\n  <td valign=\"top\" class=\"content\" colspan=\"3\">^3;</td>\r\n</tr>\r\n</table>');
INSERT INTO template VALUES (5,'Left Column','<table cellpadding=\"3\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n<tr>\r\n  <td valign=\"top\" class=\"content\" width=\"34%\">^0;</td>\r\n  <td valign=\"top\" class=\"content\" width=\"66%\">^1;</td>\r\n</tr>\r\n</table>');
INSERT INTO template VALUES (6,'Right Column','<table cellpadding=\"3\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n<tr>\r\n  <td valign=\"top\" class=\"content\" width=\"66%\">^0;</td>\r\n  <td valign=\"top\" class=\"content\" width=\"34%\">^1;</td>\r\n</tr>\r\n</table>\r\n');
INSERT INTO template VALUES (7,'Side By Side','<table cellpadding=\"3\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n<tr>\r\n  <td valign=\"top\" class=\"content\" width=\"50%\">^0;</td>\r\n  <td valign=\"top\" class=\"content\" width=\"50%\">^1;</td>\r\n</tr>\r\n</table>\r\n');
alter table page add column templateId int not null default 1;
update page set templateId=1 where template='Default';
update page set templateId=1 where template='A';
update page set templateId=2 where template='News';
update page set templateId=3 where template='OneOverThree';
update page set templateId=3 where template='One Over Three';
update page set templateId=4 where template='ThreeOverOne';
update page set templateId=4 where template='Three Over One';
update page set templateId=5 where template='LeftColumn';
update page set templateId=5 where template='Left Column';
update page set templateId=6 where template='RightColumn';
update page set templateId=6 where template='Right Column';
update page set templateId=7 where template='SideBySide';
update page set templateId=7 where template='Side By Side';
alter table page drop column template;
update wobject set templatePosition=0 where templatePosition='A';
update wobject set templatePosition=1 where templatePosition='B';
update wobject set templatePosition=2 where templatePosition='C';
update wobject set templatePosition=3 where templatePosition='D';
alter table UserSubmission add column allowDiscussion int not null default 0;
alter table UserSubmission add column editTimeout int not null default 1;
alter table UserSubmission add column groupToPost int not null default 2;
alter table UserSubmission add column groupToApprove int not null default 4;
INSERT INTO international VALUES (39,'UserSubmission','English','Post a Reply');
INSERT INTO international VALUES (40,'UserSubmission','English','Posted by');
INSERT INTO international VALUES (41,'UserSubmission','English','Date');
INSERT INTO international VALUES (42,'UserSubmission','English','Edit Response');
INSERT INTO international VALUES (43,'UserSubmission','English','Delete Response');
INSERT INTO international VALUES (45,'UserSubmission','English','Return to Submission');
INSERT INTO international VALUES (46,'UserSubmission','English','Read more...');
INSERT INTO international VALUES (47,'UserSubmission','English','Post a Response');
INSERT INTO international VALUES (48,'UserSubmission','English','Allow discussion?');
INSERT INTO international VALUES (49,'UserSubmission','English','Edit Timeout');
INSERT INTO international VALUES (50,'UserSubmission','English','Group To Post');
INSERT INTO international VALUES (44,'UserSubmission','English','Group To Moderate');
INSERT INTO international VALUES (51,'UserSubmission','English','Display thumbnails?');
alter table UserSubmission add column displayThumbnails int not null default 0;
INSERT INTO international VALUES (52,'UserSubmission','English','Thumbnail');
alter table UserSubmission add column layout varchar(30) not null default 'traditional';
INSERT INTO international VALUES (53,'UserSubmission','English','Layout');
INSERT INTO international VALUES (54,'UserSubmission','English','Web Log');
INSERT INTO international VALUES (55,'UserSubmission','English','Traditional');
INSERT INTO international VALUES (56,'UserSubmission','English','Photo Gallery');
INSERT INTO international VALUES (57,'UserSubmission','English','Responses');
alter table FAQ add column tocOn int not null default 1;
alter table FAQ add column topOn int not null default 0;
alter table FAQ add column qaOn int not null default 0;
INSERT INTO international VALUES (11,'FAQ','English','Turn TOC on?');
INSERT INTO international VALUES (12,'FAQ','English','Turn Q/A on?');
INSERT INTO international VALUES (13,'FAQ','English','Turn [top] link on?');
INSERT INTO international VALUES (14,'FAQ','English','Q');
INSERT INTO international VALUES (15,'FAQ','English','A');
INSERT INTO international VALUES (16,'FAQ','English','[top]');
INSERT INTO international VALUES (509,'WebGUI','English','Discussion Layout');
INSERT INTO international VALUES (510,'WebGUI','English','Flat');
INSERT INTO international VALUES (511,'WebGUI','English','Threaded');
INSERT INTO userProfileField VALUES ('discussionLayout','WebGUI::International::get(509)',1,0,'select','{\r\n  threaded=>WebGUI::International::get(511),\r\n  flat=>WebGUI::International::get(510)\r\n}','[\'threaded\']',5,4,0);
INSERT INTO international VALUES (512,'WebGUI','English','Next Thread');
INSERT INTO international VALUES (513,'WebGUI','English','Previous Thread');
delete from international where internationalId=10 and namespace='MessageBoard';
delete from international where internationalId=14 and namespace='MessageBoard';
INSERT INTO settings VALUES ('addEditStampToPosts','1');
alter table discussion add column views int not null default 0;
INSERT INTO international VALUES (514,'WebGUI','English','Views');
INSERT INTO international VALUES (515,'WebGUI','English','Add edit stamp to posts?');
alter table UserSubmission_submission add column views int not null default 0
INSERT INTO international VALUES (517,'WebGUI','English','Turn Admin Off!');
INSERT INTO international VALUES (516,'WebGUI','English','Turn Admin On!');
INSERT INTO international VALUES (1,'Article','Dansk','Artikel');
INSERT INTO international VALUES (2,'Article','Dansk','Tilføj artikel');
INSERT INTO international VALUES (3,'Article','Dansk','Fra dato');
INSERT INTO international VALUES (4,'Article','Dansk','Til dato');
INSERT INTO international VALUES (5,'Article','Dansk','Brødtekst');
INSERT INTO international VALUES (6,'Article','Dansk','Billede');
INSERT INTO international VALUES (7,'Article','Dansk','Titel på henvisning');
INSERT INTO international VALUES (8,'Article','Dansk','henvisning URL');
INSERT INTO international VALUES (9,'Article','Dansk','Vis besvarelser');
INSERT INTO international VALUES (10,'Article','Dansk','Konverter linieskift?');
INSERT INTO international VALUES (11,'Article','Dansk','\"(Kontroller at du ikke tilføjer &lt;br&gt; manuelt.)\"');
INSERT INTO international VALUES (12,'Article','Dansk','rediger artikel');
INSERT INTO international VALUES (13,'Article','Dansk','Slet');
INSERT INTO international VALUES (14,'Article','Dansk','Placer billede');
INSERT INTO international VALUES (15,'Article','Dansk','Højre');
INSERT INTO international VALUES (16,'Article','Dansk','Venstre');
INSERT INTO international VALUES (17,'Article','Dansk','Centreret');
INSERT INTO international VALUES (18,'Article','Dansk','Tillad diskussion?');
INSERT INTO international VALUES (19,'Article','Dansk','Hvem kan oprette indlæg?');
INSERT INTO international VALUES (20,'Article','Dansk','Hvem kan moderere?');
INSERT INTO international VALUES (21,'Article','Dansk','Rediger Timeout');
INSERT INTO international VALUES (22,'Article','Dansk','Forfatter');
INSERT INTO international VALUES (23,'Article','Dansk','Dato');
INSERT INTO international VALUES (24,'Article','Dansk','Send respons');
INSERT INTO international VALUES (25,'Article','Dansk','Rediger respons');
INSERT INTO international VALUES (26,'Article','Dansk','Slet respons');
INSERT INTO international VALUES (27,'Article','Dansk','Tilbage til artikel');
INSERT INTO international VALUES (28,'Article','Dansk','Vis respons');
INSERT INTO international VALUES (1,'DownloadManager','Dansk','Download Manager');
INSERT INTO international VALUES (2,'DownloadManager','Dansk','Tilføj Download Manager');
INSERT INTO international VALUES (3,'DownloadManager','Dansk','Fortsæt med at tilføje fil?');
INSERT INTO international VALUES (4,'DownloadManager','Dansk','Tilføj Download');
INSERT INTO international VALUES (5,'DownloadManager','Dansk','Navn på fil');
INSERT INTO international VALUES (6,'DownloadManager','Dansk','Hent fil');
INSERT INTO international VALUES (7,'DownloadManager','Dansk','Gruppe til Download');
INSERT INTO international VALUES (8,'DownloadManager','Dansk','Kort beskrivelse');
INSERT INTO international VALUES (9,'DownloadManager','Dansk','rediger Download Manager');
INSERT INTO international VALUES (10,'DownloadManager','Dansk','rediger Download  ');
INSERT INTO international VALUES (11,'DownloadManager','Dansk','Tilføj ny Download');
INSERT INTO international VALUES (12,'DownloadManager','Dansk','Er du sikker på du vil slette denne Download?');
INSERT INTO international VALUES (13,'DownloadManager','Dansk','Slet tilføjet fil?');
INSERT INTO international VALUES (14,'DownloadManager','Dansk','Fil');
INSERT INTO international VALUES (15,'DownloadManager','Dansk','Beskrivelse');
INSERT INTO international VALUES (16,'DownloadManager','Dansk','Oprettelsesdato');
INSERT INTO international VALUES (17,'DownloadManager','Dansk','Alternativ version nr. 1');
INSERT INTO international VALUES (18,'DownloadManager','Dansk','Alternativ version nr. 2');
INSERT INTO international VALUES (19,'DownloadManager','Dansk','Du har ikke nogen filer til Download');
INSERT INTO international VALUES (20,'DownloadManager','Dansk','Slet efter');
INSERT INTO international VALUES (21,'DownloadManager','Dansk','Hvis miniature?');
INSERT INTO international VALUES (1,'EventsCalendar','Dansk','Fortsæt med at tilføje begivenhed?');
INSERT INTO international VALUES (2,'EventsCalendar','Dansk','Begivenheds kalender');
INSERT INTO international VALUES (3,'EventsCalendar','Dansk','Tilføj begivenheds kalender');
INSERT INTO international VALUES (4,'EventsCalendar','Dansk','Begivenhed sker én gang');
INSERT INTO international VALUES (5,'EventsCalendar','Dansk','dag');
INSERT INTO international VALUES (6,'EventsCalendar','Dansk','uge');
INSERT INTO international VALUES (7,'EventsCalendar','Dansk','Tilføj begivenhed ');
INSERT INTO international VALUES (8,'EventsCalendar','Dansk','Gentages hver');
INSERT INTO international VALUES (9,'EventsCalendar','Dansk','indtil');
INSERT INTO international VALUES (10,'EventsCalendar','Dansk','Er du sikker på du vil slette denne begivenhed');
INSERT INTO international VALUES (11,'EventsCalendar','Dansk','<b>og</b> alle gentagelser af begivenhed');
INSERT INTO international VALUES (12,'EventsCalendar','Dansk','rediger begivenheds kalender');
INSERT INTO international VALUES (13,'EventsCalendar','Dansk','rediger begivenhed ');
INSERT INTO international VALUES (14,'EventsCalendar','Dansk','Fra dato');
INSERT INTO international VALUES (15,'EventsCalendar','Dansk','Til dato');
INSERT INTO international VALUES (16,'EventsCalendar','Dansk','Kalender layout');
INSERT INTO international VALUES (17,'EventsCalendar','Dansk','Liste');
INSERT INTO international VALUES (18,'EventsCalendar','Dansk','Kalender  ');
INSERT INTO international VALUES (19,'EventsCalendar','Dansk','Slet efter ');
INSERT INTO international VALUES (1,'ExtraColumn','Dansk','Ekstra kolonne');
INSERT INTO international VALUES (2,'ExtraColumn','Dansk','Tilføj ekstra kolonne');
INSERT INTO international VALUES (3,'ExtraColumn','Dansk','Mellemrum');
INSERT INTO international VALUES (4,'ExtraColumn','Dansk','Bredde');
INSERT INTO international VALUES (5,'ExtraColumn','Dansk','stilarter klasse');
INSERT INTO international VALUES (6,'ExtraColumn','Dansk','rediger ekstra kolonne');
INSERT INTO international VALUES (1,'FAQ','Dansk','Fortsæt med at tilføje spørgsmål?');
INSERT INTO international VALUES (2,'FAQ','Dansk','Ofte stillede spørgsmål (F.A.Q.)');
INSERT INTO international VALUES (3,'FAQ','Dansk','Tilføj F.A.Q.');
INSERT INTO international VALUES (4,'FAQ','Dansk','Tilføj spørgsmål');
INSERT INTO international VALUES (5,'FAQ','Dansk','Spørgsmål');
INSERT INTO international VALUES (6,'FAQ','Dansk','Svar');
INSERT INTO international VALUES (7,'FAQ','Dansk','Er du sikker på du vil slette dette spørgsmål');
INSERT INTO international VALUES (8,'FAQ','Dansk','Rediger F.A.Q.');
INSERT INTO international VALUES (9,'FAQ','Dansk','Tilføj nyt spørgsmål');
INSERT INTO international VALUES (10,'FAQ','Dansk','rediger spørgsmål');
INSERT INTO international VALUES (1,'Item','Dansk','henvisning URL');
INSERT INTO international VALUES (2,'Item','Dansk','Vedhæft');
INSERT INTO international VALUES (3,'Item','Dansk','Slet vedhæft');
INSERT INTO international VALUES (4,'Item','Dansk','Item');
INSERT INTO international VALUES (5,'Item','Dansk','Hent vedhæftet');
INSERT INTO international VALUES (1,'LinkList','Dansk','Indryk');
INSERT INTO international VALUES (2,'LinkList','Dansk','Linie afstand');
INSERT INTO international VALUES (3,'LinkList','Dansk','Skal der åbnes i nyt vindue?');
INSERT INTO international VALUES (4,'LinkList','Dansk','Punkt');
INSERT INTO international VALUES (5,'LinkList','Dansk','Fortsæt med at tilføje henvisning');
INSERT INTO international VALUES (6,'LinkList','Dansk','Liste over henvisning');
INSERT INTO international VALUES (7,'LinkList','Dansk','Tilføj henvisning');
INSERT INTO international VALUES (8,'LinkList','Dansk','URL');
INSERT INTO international VALUES (9,'LinkList','Dansk','Er du sikker på du vil slette denne henvisning');
INSERT INTO international VALUES (10,'LinkList','Dansk','Rediger henvisnings liste');
INSERT INTO international VALUES (11,'LinkList','Dansk','Tilføj henvisnings liste');
INSERT INTO international VALUES (12,'LinkList','Dansk','Rediger henvisning  ');
INSERT INTO international VALUES (13,'LinkList','Dansk','Tilføj ny henvisning');
INSERT INTO international VALUES (1,'MessageBoard','Dansk','Tilføj opslagstavle');
INSERT INTO international VALUES (2,'MessageBoard','Dansk','Opslagstavle');
INSERT INTO international VALUES (3,'MessageBoard','Dansk','Hvem kan komme med indlæg?');
INSERT INTO international VALUES (4,'MessageBoard','Dansk','Antal beskeder pr. side');
INSERT INTO international VALUES (5,'MessageBoard','Dansk','Rediger Timeout');
INSERT INTO international VALUES (6,'MessageBoard','Dansk','Rediger opslagstavle');
INSERT INTO international VALUES (7,'MessageBoard','Dansk','Forfatter:');
INSERT INTO international VALUES (8,'MessageBoard','Dansk','Dato:');
INSERT INTO international VALUES (9,'MessageBoard','Dansk','Besked nr.:');
INSERT INTO international VALUES (10,'MessageBoard','Dansk','Forrige tråd');
INSERT INTO international VALUES (11,'MessageBoard','Dansk','Tilbage til oversigt');
INSERT INTO international VALUES (12,'MessageBoard','Dansk','Rediger meddelelses');
INSERT INTO international VALUES (13,'MessageBoard','Dansk','Send respons');
INSERT INTO international VALUES (14,'MessageBoard','Dansk','Næste tråd');
INSERT INTO international VALUES (15,'MessageBoard','Dansk','Forfatter');
INSERT INTO international VALUES (16,'MessageBoard','Dansk','Dato');
INSERT INTO international VALUES (17,'MessageBoard','Dansk','Ny meddelelse');
INSERT INTO international VALUES (18,'MessageBoard','Dansk','Tråd startet');
INSERT INTO international VALUES (19,'MessageBoard','Dansk','Antal svar');
INSERT INTO international VALUES (20,'MessageBoard','Dansk','Seneste svar');
INSERT INTO international VALUES (21,'MessageBoard','Dansk','Hvem kan moderere?');
INSERT INTO international VALUES (22,'MessageBoard','Dansk','Slet besked');
INSERT INTO international VALUES (1,'Poll','Dansk','Afstemning');
INSERT INTO international VALUES (2,'Poll','Dansk','Tilføj afstemning');
INSERT INTO international VALUES (3,'Poll','Dansk','Aktiv');
INSERT INTO international VALUES (4,'Poll','Dansk','Hvem kan stemme');
INSERT INTO international VALUES (5,'Poll','Dansk','Bredde på graf');
INSERT INTO international VALUES (6,'Poll','Dansk','Spørgsmål');
INSERT INTO international VALUES (7,'Poll','Dansk','Svar');
INSERT INTO international VALUES (8,'Poll','Dansk','(Indtast ét svar pr. linie. Ikke mere end 20.)');
INSERT INTO international VALUES (9,'Poll','Dansk','Rediger afstemning');
INSERT INTO international VALUES (10,'Poll','Dansk','Nulstil afstemning');
INSERT INTO international VALUES (11,'Poll','Dansk','Stem!');
INSERT INTO international VALUES (1,'SiteMap','Dansk','Tilføj Site oversigt');
INSERT INTO international VALUES (2,'SiteMap','Dansk','Site oversigt');
INSERT INTO international VALUES (3,'SiteMap','Dansk','Startende fra dette niveau');
INSERT INTO international VALUES (4,'SiteMap','Dansk','Dybde?');
INSERT INTO international VALUES (5,'SiteMap','Dansk','Rediger Site oversigt');
INSERT INTO international VALUES (6,'SiteMap','Dansk','Indryk');
INSERT INTO international VALUES (7,'SiteMap','Dansk','Punkt');
INSERT INTO international VALUES (8,'SiteMap','Dansk','Linie afstand');
INSERT INTO international VALUES (9,'SiteMap','Dansk','Vis synopsis?');
INSERT INTO international VALUES (1,'SQLReport','Dansk','SQL rapport');
INSERT INTO international VALUES (2,'SQLReport','Dansk','Tilføj SQL rapport');
INSERT INTO international VALUES (3,'SQLReport','Dansk','Rapport template');
INSERT INTO international VALUES (4,'SQLReport','Dansk','Query');
INSERT INTO international VALUES (5,'SQLReport','Dansk','DSN');
INSERT INTO international VALUES (6,'SQLReport','Dansk','Database bruger');
INSERT INTO international VALUES (7,'SQLReport','Dansk','Database Password');
INSERT INTO international VALUES (8,'SQLReport','Dansk','Rediger SQL rapport');
INSERT INTO international VALUES (9,'SQLReport','Dansk','<b>Debug:</b> Error: The DSN specified is of an improper format.');
INSERT INTO international VALUES (10,'SQLReport','Dansk','<b>Debug:</b> Error: The SQL specified is of an improper format.');
INSERT INTO international VALUES (11,'SQLReport','Dansk','<b>Debug:</b> Error: There was a problem with the query.');
INSERT INTO international VALUES (12,'SQLReport','Dansk','<b>Debug:</b> Error: Could not connect to the database.');
INSERT INTO international VALUES (13,'SQLReport','Dansk','Konverter linieskift?');
INSERT INTO international VALUES (14,'SQLReport','Dansk','Slet efter');
INSERT INTO international VALUES (15,'SQLReport','Dansk','Udfør makroer ved forespørgsel?');
INSERT INTO international VALUES (16,'SQLReport','Dansk','Debut?');
INSERT INTO international VALUES (17,'SQLReport','Dansk','<b>Debug:</b> Query:');
INSERT INTO international VALUES (18,'SQLReport','Dansk','Der var ikke nogen svar til denne forespørgsel!');
INSERT INTO international VALUES (1,'SyndicatedContent','Dansk','URL til RSS fil');
INSERT INTO international VALUES (2,'SyndicatedContent','Dansk','Syndicated Content');
INSERT INTO international VALUES (3,'SyndicatedContent','Dansk','Tilføj Syndicated Content');
INSERT INTO international VALUES (4,'SyndicatedContent','Dansk','Rediger Syndicated Content');
INSERT INTO international VALUES (5,'SyndicatedContent','Dansk','Sidst opdateret');
INSERT INTO international VALUES (6,'SyndicatedContent','Dansk','Gældende indhold');
INSERT INTO international VALUES (1,'UserSubmission','Dansk','Hvem kan godkende indlæg?');
INSERT INTO international VALUES (2,'UserSubmission','Dansk','Hvem kan tilføje indlæg?');
INSERT INTO international VALUES (3,'UserSubmission','Dansk','Du har nye indlæg til godkendelse');
INSERT INTO international VALUES (4,'UserSubmission','Dansk','Dit indlæg er godkendt');
INSERT INTO international VALUES (5,'UserSubmission','Dansk','Dit indlæg er afvist');
INSERT INTO international VALUES (6,'UserSubmission','Dansk','Antal indlæg pr. side');
INSERT INTO international VALUES (7,'UserSubmission','Dansk','Godkendt');
INSERT INTO international VALUES (8,'UserSubmission','Dansk','Afvist');
INSERT INTO international VALUES (9,'UserSubmission','Dansk','Afventer');
INSERT INTO international VALUES (10,'UserSubmission','Dansk','Default Status');
INSERT INTO international VALUES (11,'UserSubmission','Dansk','Tilføj indlæg');
INSERT INTO international VALUES (12,'UserSubmission','Dansk','(Kryds ikke hvis du laver et HTML indlæg.)');
INSERT INTO international VALUES (13,'UserSubmission','Dansk','Tilføjet dato');
INSERT INTO international VALUES (14,'UserSubmission','Dansk','Status');
INSERT INTO international VALUES (15,'UserSubmission','Dansk','Rediger/Slet');
INSERT INTO international VALUES (16,'UserSubmission','Dansk','Ingen titel');
INSERT INTO international VALUES (17,'UserSubmission','Dansk','Er du sikker på du vil slette dette indlæg?');
INSERT INTO international VALUES (18,'UserSubmission','Dansk','Rediger User Submission System');
INSERT INTO international VALUES (19,'UserSubmission','Dansk','Rediger indlæg');
INSERT INTO international VALUES (20,'UserSubmission','Dansk','Lav nyt indlæg');
INSERT INTO international VALUES (21,'UserSubmission','Dansk','Indsendt af');
INSERT INTO international VALUES (22,'UserSubmission','Dansk','Indsendt af:');
INSERT INTO international VALUES (23,'UserSubmission','Dansk','Indsendt dato:');
INSERT INTO international VALUES (24,'UserSubmission','Dansk','Godkendt');
INSERT INTO international VALUES (25,'UserSubmission','Dansk','Afvent ');
INSERT INTO international VALUES (26,'UserSubmission','Dansk','Afvist');
INSERT INTO international VALUES (27,'UserSubmission','Dansk','Rediger');
INSERT INTO international VALUES (28,'UserSubmission','Dansk','Tilbage til Submission oversigt');
INSERT INTO international VALUES (29,'UserSubmission','Dansk','Bruger Indlæg');
INSERT INTO international VALUES (30,'UserSubmission','Dansk','Tilføj bruger indlæg System');
INSERT INTO international VALUES (31,'UserSubmission','Dansk','Indhold');
INSERT INTO international VALUES (32,'UserSubmission','Dansk','Billede');
INSERT INTO international VALUES (33,'UserSubmission','Dansk','Tillæg');
INSERT INTO international VALUES (34,'UserSubmission','Dansk','Konverter linieskift?');
INSERT INTO international VALUES (35,'UserSubmission','Dansk','Titel');
INSERT INTO international VALUES (36,'UserSubmission','Dansk','Slet fil.');
INSERT INTO international VALUES (37,'UserSubmission','Dansk','Slet');
INSERT INTO international VALUES (1,'WebGUI','Dansk','Tilføj indhold');
INSERT INTO international VALUES (2,'WebGUI','Dansk','Side');
INSERT INTO international VALUES (3,'WebGUI','Dansk','Kopier fra udklipsholder');
INSERT INTO international VALUES (4,'WebGUI','Dansk','administrer indstillinger');
INSERT INTO international VALUES (5,'WebGUI','Dansk','administrer grupper');
INSERT INTO international VALUES (6,'WebGUI','Dansk','administrer Stilarter');
INSERT INTO international VALUES (7,'WebGUI','Dansk','administrer brugere');
INSERT INTO international VALUES (8,'WebGUI','Dansk','Vis side_ikke_fundet');
INSERT INTO international VALUES (9,'WebGUI','Dansk','Vis udklipsholder');
INSERT INTO international VALUES (10,'WebGUI','Dansk','administrer skraldespand');
INSERT INTO international VALUES (11,'WebGUI','Dansk','Tøm skraldespand');
INSERT INTO international VALUES (12,'WebGUI','Dansk','Slå administration fra');
INSERT INTO international VALUES (13,'WebGUI','Dansk','Vis hjælpe indeks');
INSERT INTO international VALUES (14,'WebGUI','Dansk','Vis afventende indlæg');
INSERT INTO international VALUES (15,'WebGUI','Dansk','Januar');
INSERT INTO international VALUES (16,'WebGUI','Dansk','Februar');
INSERT INTO international VALUES (17,'WebGUI','Dansk','Marts');
INSERT INTO international VALUES (18,'WebGUI','Dansk','April');
INSERT INTO international VALUES (19,'WebGUI','Dansk','Maj');
INSERT INTO international VALUES (20,'WebGUI','Dansk','Juni');
INSERT INTO international VALUES (21,'WebGUI','Dansk','Juli');
INSERT INTO international VALUES (22,'WebGUI','Dansk','August');
INSERT INTO international VALUES (23,'WebGUI','Dansk','September');
INSERT INTO international VALUES (24,'WebGUI','Dansk','Oktober');
INSERT INTO international VALUES (25,'WebGUI','Dansk','November');
INSERT INTO international VALUES (26,'WebGUI','Dansk','December');
INSERT INTO international VALUES (27,'WebGUI','Dansk','Søndag');
INSERT INTO international VALUES (28,'WebGUI','Dansk','Mandag');
INSERT INTO international VALUES (29,'WebGUI','Dansk','Tirsdag');
INSERT INTO international VALUES (30,'WebGUI','Dansk','Onsdag');
INSERT INTO international VALUES (31,'WebGUI','Dansk','Torsdag');
INSERT INTO international VALUES (32,'WebGUI','Dansk','Fredag');
INSERT INTO international VALUES (33,'WebGUI','Dansk','Lørdag');
INSERT INTO international VALUES (34,'WebGUI','Dansk','Sæt dato');
INSERT INTO international VALUES (35,'WebGUI','Dansk','Administrative funktioner');
INSERT INTO international VALUES (36,'WebGUI','Dansk','Du skal være administrator for at udføre denne funktion. Kontakt en af følgende personer der er administratorer:');
INSERT INTO international VALUES (37,'WebGUI','Dansk','Adgang nægtet!');
INSERT INTO international VALUES (38,'WebGUI','Dansk','\"Du har ikke nødvendige rettigheder til at udføre denne funktion. Venligst log in ^a(log in med en konto); med nødvendige rettigheder før du prøver dette.\"');
INSERT INTO international VALUES (39,'WebGUI','Dansk','Du har ikke rettigheder til at få adgang til denne side.');
INSERT INTO international VALUES (40,'WebGUI','Dansk','Vital komponent');
INSERT INTO international VALUES (41,'WebGUI','Dansk','DU forsøger at fjerne en VITAL system komponent. Hvis du fik lov til dette, ville systemet ikke virke mere …..');
INSERT INTO international VALUES (42,'WebGUI','Dansk','Venligst bekræft');
INSERT INTO international VALUES (43,'WebGUI','Dansk','Er du sikker på du vil slette dette indhold?');
INSERT INTO international VALUES (44,'WebGUI','Dansk','Ja, jeg er sikker!');
INSERT INTO international VALUES (45,'WebGUI','Dansk','Nej, jeg lavede en fejl');
INSERT INTO international VALUES (46,'WebGUI','Dansk','Min konto');
INSERT INTO international VALUES (47,'WebGUI','Dansk','Hjem');
INSERT INTO international VALUES (48,'WebGUI','Dansk','Hej');
INSERT INTO international VALUES (49,'WebGUI','Dansk','\"Klik <a href=\"\"^\\;?op=logout\"\">her</a> for at logge ud.\"');
INSERT INTO international VALUES (50,'WebGUI','Dansk','Brugernavn');
INSERT INTO international VALUES (51,'WebGUI','Dansk','Kodeord');
INSERT INTO international VALUES (52,'WebGUI','Dansk','Login');
INSERT INTO international VALUES (53,'WebGUI','Dansk','Print side');
INSERT INTO international VALUES (54,'WebGUI','Dansk','Opret konto');
INSERT INTO international VALUES (55,'WebGUI','Dansk','Kodeord (bekræft)');
INSERT INTO international VALUES (56,'WebGUI','Dansk','Email Adresse');
INSERT INTO international VALUES (57,'WebGUI','Dansk','Dette er kun nødvendigt hvis du bruger en funktion der kræver Email');
INSERT INTO international VALUES (58,'WebGUI','Dansk','Jeg har allerede en konto');
INSERT INTO international VALUES (59,'WebGUI','Dansk','Jeg har glemt mit kodeord (igen)');
INSERT INTO international VALUES (60,'WebGUI','Dansk','Er du sikker på du vil deaktivere din konto. Kontoen kan IKKE åbnes igen.');
INSERT INTO international VALUES (61,'WebGUI','Dansk','Opdater konto information');
INSERT INTO international VALUES (62,'WebGUI','Dansk','Gem');
INSERT INTO international VALUES (63,'WebGUI','Dansk','Slå administration til.');
INSERT INTO international VALUES (64,'WebGUI','Dansk','Log ud.');
INSERT INTO international VALUES (65,'WebGUI','Dansk','Venligst de-aktiver min konto permanent.');
INSERT INTO international VALUES (66,'WebGUI','Dansk','Log In');
INSERT INTO international VALUES (67,'WebGUI','Dansk','Opret ny konto');
INSERT INTO international VALUES (68,'WebGUI','Dansk','Konto informationen er ikke gyldig. Enten eksisterer kontoen ikke, eller også er brugernavn/kodeord forkert');
INSERT INTO international VALUES (69,'WebGUI','Dansk','Kontakt venligst systemadministratoren for yderligere hjælp!');
INSERT INTO international VALUES (70,'WebGUI','Dansk','Fejl');
INSERT INTO international VALUES (71,'WebGUI','Dansk','Genskab kodeord');
INSERT INTO international VALUES (72,'WebGUI','Dansk','Genskab  ');
INSERT INTO international VALUES (73,'WebGUI','Dansk','Log in.');
INSERT INTO international VALUES (74,'WebGUI','Dansk','Konto information.');
INSERT INTO international VALUES (75,'WebGUI','Dansk','Din konto information er sendt til den oplyste Email adresse');
INSERT INTO international VALUES (76,'WebGUI','Dansk','Email adressen er ikke registreret i systemet');
INSERT INTO international VALUES (77,'WebGUI','Dansk','Det brugernavn er desværre allerede brugt af en anden. Prøv evt. en af disse:');
INSERT INTO international VALUES (78,'WebGUI','Dansk','Du har indtastet to forskellige kodeord - prøv igen!');
INSERT INTO international VALUES (79,'WebGUI','Dansk','Kan ikke forbinde til LDAP server');
INSERT INTO international VALUES (80,'WebGUI','Dansk','Konto er nu oprettet!');
INSERT INTO international VALUES (81,'WebGUI','Dansk','Konto er nu opdateret.');
INSERT INTO international VALUES (82,'WebGUI','Dansk','Administrative funktioner');
INSERT INTO international VALUES (83,'WebGUI','Dansk','Tilføj gruppe');
INSERT INTO international VALUES (84,'WebGUI','Dansk','Gruppe navn');
INSERT INTO international VALUES (85,'WebGUI','Dansk','Beskrivelse');
INSERT INTO international VALUES (86,'WebGUI','Dansk','Er du sikker på du vil slette denne gruppe? - og dermed alle rettigheder der er knyttet hertil');
INSERT INTO international VALUES (87,'WebGUI','Dansk','Rediger gruppe');
INSERT INTO international VALUES (88,'WebGUI','Dansk','brugere i gruppe');
INSERT INTO international VALUES (89,'WebGUI','Dansk','Grupper');
INSERT INTO international VALUES (90,'WebGUI','Dansk','Tilføj gruppe');
INSERT INTO international VALUES (91,'WebGUI','Dansk','Forrige side');
INSERT INTO international VALUES (92,'WebGUI','Dansk','Næste side');
INSERT INTO international VALUES (93,'WebGUI','Dansk','Hjælp');
INSERT INTO international VALUES (94,'WebGUI','Dansk','Se også');
INSERT INTO international VALUES (95,'WebGUI','Dansk','Hjælpe indeks');
INSERT INTO international VALUES (96,'WebGUI','Dansk','Sorteret efter aktion');
INSERT INTO international VALUES (97,'WebGUI','Dansk','Sorteret efter objekt');
INSERT INTO international VALUES (98,'WebGUI','Dansk','Tilføj side');
INSERT INTO international VALUES (99,'WebGUI','Dansk','Titel');
INSERT INTO international VALUES (100,'WebGUI','Dansk','Meta Tags');
INSERT INTO international VALUES (101,'WebGUI','Dansk','Er du sikker på du vil slette denne side, og alt indhold derunder?');
INSERT INTO international VALUES (102,'WebGUI','Dansk','Rediger side');
INSERT INTO international VALUES (103,'WebGUI','Dansk','Side specifikationer');
INSERT INTO international VALUES (104,'WebGUI','Dansk','Side URL');
INSERT INTO international VALUES (105,'WebGUI','Dansk','Stil');
INSERT INTO international VALUES (106,'WebGUI','Dansk','Sæt kryds for at give denne stil til alle undersider');
INSERT INTO international VALUES (107,'WebGUI','Dansk','Rettigheder');
INSERT INTO international VALUES (108,'WebGUI','Dansk','Ejer');
INSERT INTO international VALUES (109,'WebGUI','Dansk','Ejer kan se?');
INSERT INTO international VALUES (110,'WebGUI','Dansk','Ejer kan redigere?');
INSERT INTO international VALUES (111,'WebGUI','Dansk','Gruppe');
INSERT INTO international VALUES (112,'WebGUI','Dansk','Gruppe kan se?');
INSERT INTO international VALUES (113,'WebGUI','Dansk','Gruppe kan redigere?');
INSERT INTO international VALUES (114,'WebGUI','Dansk','Alle kan se?');
INSERT INTO international VALUES (115,'WebGUI','Dansk','Alle kan redigere?');
INSERT INTO international VALUES (116,'WebGUI','Dansk','Sæt kryds for at give disse rettigheder til alle undersider');
INSERT INTO international VALUES (117,'WebGUI','Dansk','Rediger autorisations indstillinger');
INSERT INTO international VALUES (118,'WebGUI','Dansk','Anonym registrering');
INSERT INTO international VALUES (119,'WebGUI','Dansk','autorisations metode (default)');
INSERT INTO international VALUES (120,'WebGUI','Dansk','LDAP URL (default)');
INSERT INTO international VALUES (121,'WebGUI','Dansk','LDAP Identitet (default)');
INSERT INTO international VALUES (122,'WebGUI','Dansk','LDAP Identitets navn');
INSERT INTO international VALUES (123,'WebGUI','Dansk','LDAP kodeord');
INSERT INTO international VALUES (124,'WebGUI','Dansk','Rediger firma information');
INSERT INTO international VALUES (125,'WebGUI','Dansk','Firma/organisations navn');
INSERT INTO international VALUES (126,'WebGUI','Dansk','Firma/organisations Email');
INSERT INTO international VALUES (127,'WebGUI','Dansk','Firma/organisation URL');
INSERT INTO international VALUES (128,'WebGUI','Dansk','Rediger fil indstillinger');
INSERT INTO international VALUES (129,'WebGUI','Dansk','Sti til WebGUI Extras');
INSERT INTO international VALUES (130,'WebGUI','Dansk','Maksimal størrelse på vedhæftede filer');
INSERT INTO international VALUES (131,'WebGUI','Dansk','Web Attachment sti');
INSERT INTO international VALUES (132,'WebGUI','Dansk','Server Attachment sti');
INSERT INTO international VALUES (133,'WebGUI','Dansk','Rediger Mail indstillinger');
INSERT INTO international VALUES (134,'WebGUI','Dansk','Besked for genskab adgangskode');
INSERT INTO international VALUES (135,'WebGUI','Dansk','SMTP Server');
INSERT INTO international VALUES (136,'WebGUI','Dansk','Hjemme side');
INSERT INTO international VALUES (137,'WebGUI','Dansk','Side ikke fundet');
INSERT INTO international VALUES (138,'WebGUI','Dansk','Ja');
INSERT INTO international VALUES (139,'WebGUI','Dansk','Nej ');
INSERT INTO international VALUES (140,'WebGUI','Dansk','Rediger diverse indstillinger');
INSERT INTO international VALUES (141,'WebGUI','Dansk','Ikke fundet side');
INSERT INTO international VALUES (142,'WebGUI','Dansk','Session Timeout');
INSERT INTO international VALUES (143,'WebGUI','Dansk','administrer indstillinger');
INSERT INTO international VALUES (144,'WebGUI','Dansk','Vis statistik');
INSERT INTO international VALUES (145,'WebGUI','Dansk','WebGUI Build Version');
INSERT INTO international VALUES (146,'WebGUI','Dansk','Aktive sessioner');
INSERT INTO international VALUES (147,'WebGUI','Dansk','Sider');
INSERT INTO international VALUES (148,'WebGUI','Dansk','Widgets');
INSERT INTO international VALUES (149,'WebGUI','Dansk','brugere i gruppe');
INSERT INTO international VALUES (150,'WebGUI','Dansk','Tilføj stilart');
INSERT INTO international VALUES (151,'WebGUI','Dansk','Navn på stilart');
INSERT INTO international VALUES (152,'WebGUI','Dansk','Hoved');
INSERT INTO international VALUES (153,'WebGUI','Dansk','Fod');
INSERT INTO international VALUES (154,'WebGUI','Dansk','Stilart Sheet');
INSERT INTO international VALUES (155,'WebGUI','Dansk','\"Er du sikker på du vil slette denne stilart og overføre alle sider der bruger denne til \"\"Fail Safe\"\" stilarten ?\"');
INSERT INTO international VALUES (156,'WebGUI','Dansk','Rediger stilart');
INSERT INTO international VALUES (157,'WebGUI','Dansk','stilarter');
INSERT INTO international VALUES (158,'WebGUI','Dansk','Tilføj ny stilart');
INSERT INTO international VALUES (159,'WebGUI','Dansk','Meddelelses log');
INSERT INTO international VALUES (160,'WebGUI','Dansk','Dato oprettet');
INSERT INTO international VALUES (161,'WebGUI','Dansk','Oprettet af');
INSERT INTO international VALUES (162,'WebGUI','Dansk','Er du sikker på du vil tømme skraldespanden?');
INSERT INTO international VALUES (163,'WebGUI','Dansk','Tilføj bruger  ');
INSERT INTO international VALUES (164,'WebGUI','Dansk','Metode for autorisation');
INSERT INTO international VALUES (165,'WebGUI','Dansk','LDAP URL');
INSERT INTO international VALUES (166,'WebGUI','Dansk','Connect DN');
INSERT INTO international VALUES (167,'WebGUI','Dansk','Er du sikker på du vil slette denne bruger? (Du kan ikke fortryde)');
INSERT INTO international VALUES (168,'WebGUI','Dansk','Rediger bruger');
INSERT INTO international VALUES (169,'WebGUI','Dansk','Tilføj ny bruger');
INSERT INTO international VALUES (170,'WebGUI','Dansk','Søg');
INSERT INTO international VALUES (171,'WebGUI','Dansk','Avanceret redigering');
INSERT INTO international VALUES (174,'WebGUI','Dansk','Vis titel på siden?');
INSERT INTO international VALUES (175,'WebGUI','Dansk','Udfør makroer?');
INSERT INTO international VALUES (228,'WebGUI','Dansk','Rediger besked…');
INSERT INTO international VALUES (229,'WebGUI','Dansk','Emne');
INSERT INTO international VALUES (230,'WebGUI','Dansk','Besked  ');
INSERT INTO international VALUES (231,'WebGUI','Dansk','Oprettet ny besked …');
INSERT INTO international VALUES (232,'WebGUI','Dansk','Intet emne');
INSERT INTO international VALUES (233,'WebGUI','Dansk','(eom)');
INSERT INTO international VALUES (234,'WebGUI','Dansk','Oprettet svar …');
INSERT INTO international VALUES (237,'WebGUI','Dansk','Emne:');
INSERT INTO international VALUES (238,'WebGUI','Dansk','Forfatter:');
INSERT INTO international VALUES (239,'WebGUI','Dansk','Dato:');
INSERT INTO international VALUES (240,'WebGUI','Dansk','Besked ID:');
INSERT INTO international VALUES (244,'WebGUI','Dansk','Forfatter ');
INSERT INTO international VALUES (245,'WebGUI','Dansk','Dato');
INSERT INTO international VALUES (304,'WebGUI','Dansk','Sprog');
INSERT INTO international VALUES (306,'WebGUI','Dansk','Brugernavn binding');
INSERT INTO international VALUES (307,'WebGUI','Dansk','Brug standard meta tags?');
INSERT INTO international VALUES (308,'WebGUI','Dansk','Rediger profil indstillinger');
INSERT INTO international VALUES (309,'WebGUI','Dansk','Tillad rigtige navne?');
INSERT INTO international VALUES (310,'WebGUI','Dansk','Tillad ekstra kontakt information?');
INSERT INTO international VALUES (311,'WebGUI','Dansk','Tillad hjemme information?');
INSERT INTO international VALUES (312,'WebGUI','Dansk','Tillad arbejds information?');
INSERT INTO international VALUES (313,'WebGUI','Dansk','Tillad diverse information?');
INSERT INTO international VALUES (314,'WebGUI','Dansk','Fornavn');
INSERT INTO international VALUES (315,'WebGUI','Dansk','Mellemnavn');
INSERT INTO international VALUES (316,'WebGUI','Dansk','Efternavn');
INSERT INTO international VALUES (317,'WebGUI','Dansk','\"<a href=\"\"http://www.icq.com\"\">ICQ</a> UIN\"');
INSERT INTO international VALUES (318,'WebGUI','Dansk','\"<a href=\"\"http://www.aol.com/aim/homenew.adp\"\">AIM</a> Id\"');
INSERT INTO international VALUES (319,'WebGUI','Dansk','\"<a href=\"\"http://messenger.msn.com/\"\">MSN Messenger</a> Id\"');
INSERT INTO international VALUES (320,'WebGUI','Dansk','\"<a href=\"\"http://messenger.yahoo.com/\"\">Yahoo! Messenger</a> Id\"');
INSERT INTO international VALUES (321,'WebGUI','Dansk','Bil tlf.');
INSERT INTO international VALUES (322,'WebGUI','Dansk','OPS');
INSERT INTO international VALUES (323,'WebGUI','Dansk','Hjemme adresse');
INSERT INTO international VALUES (324,'WebGUI','Dansk','Hjemme by');
INSERT INTO international VALUES (325,'WebGUI','Dansk','Hjemme stat');
INSERT INTO international VALUES (326,'WebGUI','Dansk','Hjemme postnr.');
INSERT INTO international VALUES (327,'WebGUI','Dansk','Hjemme amt');
INSERT INTO international VALUES (328,'WebGUI','Dansk','Hjemme tlf.');
INSERT INTO international VALUES (329,'WebGUI','Dansk','Arbejds adresse');
INSERT INTO international VALUES (330,'WebGUI','Dansk','Arbejds by');
INSERT INTO international VALUES (331,'WebGUI','Dansk','Arbejds stat');
INSERT INTO international VALUES (332,'WebGUI','Dansk','Arbejds postnr.');
INSERT INTO international VALUES (333,'WebGUI','Dansk','Arbejds amt');
INSERT INTO international VALUES (334,'WebGUI','Dansk','Arbejds tlf.');
INSERT INTO international VALUES (335,'WebGUI','Dansk','M/K');
INSERT INTO international VALUES (336,'WebGUI','Dansk','Fødselsdag');
INSERT INTO international VALUES (337,'WebGUI','Dansk','Hjemmeside URL');
INSERT INTO international VALUES (338,'WebGUI','Dansk','Rediger profil  ');
INSERT INTO international VALUES (339,'WebGUI','Dansk','Mand');
INSERT INTO international VALUES (340,'WebGUI','Dansk','Kvinde');
INSERT INTO international VALUES (341,'WebGUI','Dansk','Rediger profil');
INSERT INTO international VALUES (342,'WebGUI','Dansk','Rediger konto information');
INSERT INTO international VALUES (343,'WebGUI','Dansk','Vis profil');
INSERT INTO international VALUES (344,'WebGUI','Dansk','Vis besked log');
INSERT INTO international VALUES (345,'WebGUI','Dansk','Ikke medlem');
INSERT INTO international VALUES (346,'WebGUI','Dansk','Denne bruger findes ikke længere på dette system. Jeg har ikke yderligere oplysninger om denne bruger');
INSERT INTO international VALUES (347,'WebGUI','Dansk','Vis profil for');
INSERT INTO international VALUES (348,'WebGUI','Dansk','Navn  ');
INSERT INTO international VALUES (349,'WebGUI','Dansk','Seneste version');
INSERT INTO international VALUES (350,'WebGUI','Dansk','Gennemført');
INSERT INTO international VALUES (351,'WebGUI','Dansk','Message Log Entry');
INSERT INTO international VALUES (352,'WebGUI','Dansk','Dato');
INSERT INTO international VALUES (353,'WebGUI','Dansk','Du har ingen meddelelser i øjeblikket');
INSERT INTO international VALUES (354,'WebGUI','Dansk','Vis meddelelses log');
INSERT INTO international VALUES (355,'WebGUI','Dansk','Standard');
INSERT INTO international VALUES (356,'WebGUI','Dansk','Template');
INSERT INTO international VALUES (357,'WebGUI','Dansk','Nyheder');
INSERT INTO international VALUES (358,'WebGUI','Dansk','Venstre kolonne');
INSERT INTO international VALUES (359,'WebGUI','Dansk','Højre kolonne');
INSERT INTO international VALUES (360,'WebGUI','Dansk','En over tre');
INSERT INTO international VALUES (361,'WebGUI','Dansk','Tre over en');
INSERT INTO international VALUES (362,'WebGUI','Dansk','Side ved side');
INSERT INTO international VALUES (363,'WebGUI','Dansk','Template position');
INSERT INTO international VALUES (364,'WebGUI','Dansk','Søg');
INSERT INTO international VALUES (365,'WebGUI','Dansk','Søge resultater …');
INSERT INTO international VALUES (366,'WebGUI','Dansk','Jeg fandt desværre ingen sider med de(t) søgeord');
INSERT INTO international VALUES (367,'WebGUI','Dansk','Udløber efter');
INSERT INTO international VALUES (368,'WebGUI','Dansk','Tilføj en ny gruppen til denne bruger.');
INSERT INTO international VALUES (369,'WebGUI','Dansk','Udløbs dato');
INSERT INTO international VALUES (370,'WebGUI','Dansk','Rediger gruppering');
INSERT INTO international VALUES (371,'WebGUI','Dansk','Tilføj gruppering');
INSERT INTO international VALUES (372,'WebGUI','Dansk','Rediger brugers gruppe');
INSERT INTO international VALUES (373,'WebGUI','Dansk','<b>Advarsel</b> Når du retter ovenstående liste, vil du nulstille all udløbsinformation til den nye standard.');
INSERT INTO international VALUES (374,'WebGUI','Dansk','administrer packages');
INSERT INTO international VALUES (375,'WebGUI','Dansk','Vælg package der skal tages i brug');
INSERT INTO international VALUES (376,'WebGUI','Dansk','Package');
INSERT INTO international VALUES (377,'WebGUI','Dansk','\"Der er endnu ikke defineret nogle \"\"Packages\"\".\"');
INSERT INTO international VALUES (378,'WebGUI','Dansk','Bruger ID');
INSERT INTO international VALUES (379,'WebGUI','Dansk','Gruppe ID');
INSERT INTO international VALUES (380,'WebGUI','Dansk','Stilart ID');
INSERT INTO international VALUES (381,'WebGUI','Dansk','WebGUI modtog en fejlformateret besked og kan ikke fortsætte - dette skyldes typisk eb speciel karakter. Prøv evt. at trykke tilbage og prøv igen.');
INSERT INTO international VALUES (382,'WebGUI','Dansk','Tilføj billede');
INSERT INTO international VALUES (383,'WebGUI','Dansk','Navn');
INSERT INTO international VALUES (384,'WebGUI','Dansk','Fil  ');
INSERT INTO international VALUES (385,'WebGUI','Dansk','Parametre');
INSERT INTO international VALUES (386,'WebGUI','Dansk','Rediger billede');
INSERT INTO international VALUES (387,'WebGUI','Dansk','Tilføjet af');
INSERT INTO international VALUES (388,'WebGUI','Dansk','Tilføjet dato');
INSERT INTO international VALUES (389,'WebGUI','Dansk','Billede ID');
INSERT INTO international VALUES (390,'WebGUI','Dansk','Viser billede …');
INSERT INTO international VALUES (391,'WebGUI','Dansk','Sletter vedhæftet fil');
INSERT INTO international VALUES (392,'WebGUI','Dansk','Er du sikker på du vil slette dette billede');
INSERT INTO international VALUES (393,'WebGUI','Dansk','administrer billeder');
INSERT INTO international VALUES (394,'WebGUI','Dansk','administrer billeder.');
INSERT INTO international VALUES (395,'WebGUI','Dansk','Tilføj nyt billede');
INSERT INTO international VALUES (396,'WebGUI','Dansk','Vis billede');
INSERT INTO international VALUES (397,'WebGUI','Dansk','Tilbage til billede oversigt');
INSERT INTO international VALUES (398,'WebGUI','Dansk','Dokument type deklarering');
INSERT INTO international VALUES (399,'WebGUI','Dansk','Valider denne side.');
INSERT INTO international VALUES (400,'WebGUI','Dansk','Forhindre Proxy Caching');
INSERT INTO international VALUES (401,'WebGUI','Dansk','Er du sikker på du vil slette denne besked, og alle under beskeder i tråden?');
INSERT INTO international VALUES (402,'WebGUI','Dansk','Beskeden findes ikke');
INSERT INTO international VALUES (403,'WebGUI','Dansk','Det foretrækker jeg ikke at oplyse');
INSERT INTO international VALUES (404,'WebGUI','Dansk','Første side');
INSERT INTO international VALUES (405,'WebGUI','Dansk','Sidste side');
INSERT INTO international VALUES (406,'WebGUI','Dansk','Miniature størrelse');
INSERT INTO international VALUES (407,'WebGUI','Dansk','Klik her for at registrere');
INSERT INTO international VALUES (408,'WebGUI','Dansk','administrer rod');
INSERT INTO international VALUES (409,'WebGUI','Dansk','Tilføj ny rod');
INSERT INTO international VALUES (410,'WebGUI','Dansk','Administrer rod');
INSERT INTO international VALUES (411,'WebGUI','Dansk','Menu titel');
INSERT INTO international VALUES (412,'WebGUI','Dansk','Synopsis');
INSERT INTO international VALUES (413,'WebGUI','Dansk','Ved kritisk fejl');
INSERT INTO international VALUES (414,'WebGUI','Dansk','Vis debug information');
INSERT INTO international VALUES (415,'WebGUI','Dansk','Vis brugervenlig besked');
INSERT INTO international VALUES (416,'WebGUI','Dansk','<h1>Problem med forespørgsel</h1>Oops, jeg har lidt problemer med din forespørgsel. Tryk tilbage og prøv igen. Hvis problemet fortsætte vil jeg være glad hvis du vil kontakte os og fortælle hvad du prøver, på forhånd tak.');
INSERT INTO international VALUES (417,'WebGUI','Dansk','<h1>Sikkerhedsbrud</h1>Du forsøgte at få adgang med en Widget der ikke hører til her. Jeg har rapporteret dit forsøg.');
INSERT INTO international VALUES (418,'WebGUI','Dansk','Filter Contributed HTML');
INSERT INTO international VALUES (419,'WebGUI','Dansk','Fjern alle tags');
INSERT INTO international VALUES (420,'WebGUI','Dansk','Lad det være');
INSERT INTO international VALUES (421,'WebGUI','Dansk','Fjerne alt bortset fra basal formatering');
INSERT INTO international VALUES (422,'WebGUI','Dansk','<h1>Login mislykkedes</h1>Dine informationer stemmer ikke med mine oplysninger');
INSERT INTO international VALUES (423,'WebGUI','Dansk','Vis aktive sessioner');
INSERT INTO international VALUES (424,'WebGUI','Dansk','Vis login historik');
INSERT INTO international VALUES (425,'WebGUI','Dansk','Aktive sessioner');
INSERT INTO international VALUES (426,'WebGUI','Dansk','Login historik');
INSERT INTO international VALUES (427,'WebGUI','Dansk','stilarter');
INSERT INTO international VALUES (428,'WebGUI','Dansk','Bruger (ID)');
INSERT INTO international VALUES (429,'WebGUI','Dansk','Login tid');
INSERT INTO international VALUES (430,'WebGUI','Dansk','Sidste side vist');
INSERT INTO international VALUES (431,'WebGUI','Dansk','IP Adresse');
INSERT INTO international VALUES (432,'WebGUI','Dansk','Udløber efter');
INSERT INTO international VALUES (433,'WebGUI','Dansk','Bruger agent:');
INSERT INTO international VALUES (434,'WebGUI','Dansk','Status');
INSERT INTO international VALUES (435,'WebGUI','Dansk','Session Signatur');
INSERT INTO international VALUES (436,'WebGUI','Dansk','Afbryd Session');
INSERT INTO international VALUES (437,'WebGUI','Dansk','Statistik');
INSERT INTO international VALUES (438,'WebGUI','Dansk','Dit navn');
INSERT INTO international VALUES (439,'WebGUI','Dansk','Personlig information');
INSERT INTO international VALUES (440,'WebGUI','Dansk','Kontakt information');
INSERT INTO international VALUES (441,'WebGUI','Dansk','Email  til OPS Gateway');
INSERT INTO international VALUES (442,'WebGUI','Dansk','Arbejdsinformation');
INSERT INTO international VALUES (443,'WebGUI','Dansk','Hjemme information');
INSERT INTO international VALUES (444,'WebGUI','Dansk','Demografisk information');
INSERT INTO international VALUES (445,'WebGUI','Dansk','Præferencer');
INSERT INTO international VALUES (446,'WebGUI','Dansk','Arbejds hjemmeside');
INSERT INTO international VALUES (447,'WebGUI','Dansk','Administrer træ struktur');
INSERT INTO international VALUES (448,'WebGUI','Dansk','Træ struktur');
INSERT INTO international VALUES (449,'WebGUI','Dansk','Diverse information');
INSERT INTO international VALUES (450,'WebGUI','Dansk','Arbejdsnavn (Firma navn)');
INSERT INTO international VALUES (451,'WebGUI','Dansk','er påkrævet');
INSERT INTO international VALUES (452,'WebGUI','Dansk','Vent venligst …');
INSERT INTO international VALUES (453,'WebGUI','Dansk','Dato oprettet');
INSERT INTO international VALUES (454,'WebGUI','Dansk','Sidste opdateret');
INSERT INTO international VALUES (455,'WebGUI','Dansk','Rediger bruger profil');
INSERT INTO international VALUES (456,'WebGUI','Dansk','Tilbage til bruger liste');
INSERT INTO international VALUES (457,'WebGUI','Dansk','Rediger denne brugers konto');
INSERT INTO international VALUES (458,'WebGUI','Dansk','Rediger denne bruger gruppe');
INSERT INTO international VALUES (459,'WebGUI','Dansk','Rediger denne brugers profil');
INSERT INTO international VALUES (460,'WebGUI','Dansk','Tidsforskel');
INSERT INTO international VALUES (461,'WebGUI','Dansk','Dato format');
INSERT INTO international VALUES (462,'WebGUI','Dansk','Tids format');
INSERT INTO international VALUES (463,'WebGUI','Dansk','Tekst Area Rows');
INSERT INTO international VALUES (464,'WebGUI','Dansk','Tekst Area Columns');
INSERT INTO international VALUES (465,'WebGUI','Dansk','Tekst Box Size');
INSERT INTO international VALUES (466,'WebGUI','Dansk','Er du sikker på du vil slette denne kategori og flytte indholdet over i diverse kategorien?');
INSERT INTO international VALUES (467,'WebGUI','Dansk','Er du sikker på du vil slette dette felt, og alle relaterede brugerdata?');
INSERT INTO international VALUES (468,'WebGUI','Dansk','Tilføj/rediger bruger profil kategori');
INSERT INTO international VALUES (469,'WebGUI','Dansk','Id');
INSERT INTO international VALUES (470,'WebGUI','Dansk','Navn');
INSERT INTO international VALUES (471,'WebGUI','Dansk','Tilføj/Rediger bruger profil felt');
INSERT INTO international VALUES (472,'WebGUI','Dansk','Label');
INSERT INTO international VALUES (473,'WebGUI','Dansk','Synlig?');
INSERT INTO international VALUES (474,'WebGUI','Dansk','Påkrævet?');
INSERT INTO international VALUES (475,'WebGUI','Dansk','Tekst');
INSERT INTO international VALUES (476,'WebGUI','Dansk','Tekst område');
INSERT INTO international VALUES (477,'WebGUI','Dansk','HTML område');
INSERT INTO international VALUES (478,'WebGUI','Dansk','URL');
INSERT INTO international VALUES (479,'WebGUI','Dansk','Dato');
INSERT INTO international VALUES (480,'WebGUI','Dansk','Email Adresse');
INSERT INTO international VALUES (481,'WebGUI','Dansk','Tlf. nr.');
INSERT INTO international VALUES (482,'WebGUI','Dansk','Heltal');
INSERT INTO international VALUES (483,'WebGUI','Dansk','Ja eller Nej');
INSERT INTO international VALUES (484,'WebGUI','Dansk','Vælg fra list');
INSERT INTO international VALUES (485,'WebGUI','Dansk','Logisk (Checkboks)');
INSERT INTO international VALUES (486,'WebGUI','Dansk','Data type');
INSERT INTO international VALUES (487,'WebGUI','Dansk','Mulige værdier');
INSERT INTO international VALUES (488,'WebGUI','Dansk','Standard værdi');
INSERT INTO international VALUES (489,'WebGUI','Dansk','Profil kategori');
INSERT INTO international VALUES (490,'WebGUI','Dansk','Tilføj en profil kategori');
INSERT INTO international VALUES (491,'WebGUI','Dansk','Tilføj et profil felt');
INSERT INTO international VALUES (492,'WebGUI','Dansk','Liste over profil felter');
INSERT INTO international VALUES (493,'WebGUI','Dansk','Tilbage til Site');
INSERT INTO international VALUES (494,'WebGUI','Dansk','Real Objects Edit-On Pro');
INSERT INTO international VALUES (495,'WebGUI','Dansk','Indbygget editor');
INSERT INTO international VALUES (496,'WebGUI','Dansk','Hvilken editor bruges');
INSERT INTO international VALUES (497,'WebGUI','Dansk','Start dato');
INSERT INTO international VALUES (498,'WebGUI','Dansk','Slut dato');
INSERT INTO international VALUES (499,'WebGUI','Dansk','Wobject ID');
INSERT INTO international VALUES (518,'WebGUI','English','INBOX Notifications');
INSERT INTO international VALUES (519,'WebGUI','English','I would not like to be notified.');
INSERT INTO international VALUES (520,'WebGUI','English','I would like to be notified via email.');
INSERT INTO international VALUES (521,'WebGUI','English','I would like to be notified via email to pager.');
INSERT INTO international VALUES (522,'WebGUI','English','I would like to be notified via ICQ.');
INSERT INTO userProfileField VALUES ('INBOXNotifications','WebGUI::International::get(518)',1,0,'select','{ \r\n  none=>WebGUI::International::get(519),\r\n email=>WebGUI::International::get(520),\r\n  emailToPager=>WebGUI::International::get(521),\r\n  icq=>WebGUI::International::get(522)\r\n}','[\'email\']', 6,4,0);
INSERT INTO international VALUES (523,'WebGUI','English','Notification');
INSERT INTO international VALUES (524,'WebGUI','English','Add edit stamp to posts?');
INSERT INTO international VALUES (525,'WebGUI','English','Edit Content Settings');
INSERT INTO international VALUES (526,'WebGUI','English','Remove only JavaScript.');





















