insert into webguiVersion values ('5.0.3','upgrade',unix_timestamp());
delete from international where languageId=2 and namespace='WebGUI' and internationalId=625;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (625,2,'WebGUI','Laden Sie einige Bilder hoch, die Sie in mehreren Bereichen der Seite benutzen \r\nmöchten. \r\n<P><b>Name</b><BR>Die Bezeichnung, mit der Sie dieses Bild referenzieren, um \r\nes in anderen Seiten einzufügen. \r\n<P><b>In welches Verzeichnis?</b><BR>In welches Verzeichnis möchten Sie diese \r\nGrafik platzieren?<P><b>Datei</b><BR>Wählen Sie eine Grafik aus Ihrem lokalen \r\nVerzeichnis, die Sie zum Server hochladen möchten. \r\n<P><b>Parameter</b><BR>Geben Sie hier einige  HTML &lt;img Tag Parameter an, \r\ndie Sie standardmässig für diese Grafik benutzen möchten. \r\n<P><I>Beispiel:</I><BR>align=&quot;right&quot;<BR>alt=&quot;Dies ist ein Bild&quot;<BR>\r\n<P><b>Thumbnail Size</b><BR>Wie gross  (in Pixels) soll das Vorschaubild (Thumbnail) \r\nsein?</P>', 1042585804);
delete from international where languageId=2 and namespace='MailForm' and internationalId=73;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (73,2,'MailForm','Senden', 1042383682);
delete from international where languageId=2 and namespace='Product' and internationalId=47;
insert into international (internationalId,languageId,namespace,message,lastUpdated) values (47,2,'Product','Verwandte Produkte sind Produkte, die vergleichbar zu anderen Produkten sind.<br><br>\r\n<b>Verwandte Produkte</b><br>\r\nWählen Sie aus der Liste ein Produkt aus, das Sie bereits eingegeben haben.<br><br>\r\n<b>Weiteres verwandtes Produkt hinzufügen?</b><br><br>\r\nMöchten Sie ein weiteres Produkt hinzufügen?\r\n', 1042383649);
delete from template where templateId=1 and namespace='USS/Submission';
INSERT INTO template VALUES (1,'Default Submission','<h1><tmpl_var title></h1>\r\n<table width=\"100%\" cellpadding=2 cellspacing=1 border=0>\r\n<tr><td valign=\"top\" class=\"tableHeader\" width=\"100%\">\r\n<b><tmpl_var user.label>:</b> <a href=\"<tmpl_var user.Profile>\"><tmpl_var user.username></a><br />\r\n<b><tmpl_var date.label>:</b> <tmpl_var date.human><br />\r\n<b><tmpl_var status.label>:</b> <tmpl_var status.status><br />\r\n<b><tmpl_var views.label>:</b> <tmpl_var views.count><br />\r\n</td>\r\n<td rowspan=\"2\" class=\"tableMenu\" nowrap=\"1\" valign=\"top\">\r\n\r\n<tmpl_if previous.more>\r\n   <a href=\"<tmpl_var previous.url>\">&laquo;<tmpl_var previous.label></a><br />\r\n</tmpl_if>\r\n<tmpl_if next.more>\r\n   <a href=\"<tmpl_var next.url>\"><tmpl_var next.label>&raquo;</a><br />\r\n</tmpl_if>\r\n<tmpl_if canEdit>\r\n   <a href=\"<tmpl_var edit.url>\"><tmpl_var edit.label></a><br />\r\n   <a href=\"<tmpl_var delete.url>\"><tmpl_var delete.label></a><br />\r\n</tmpl_if>\r\n<tmpl_if canChangeStatus>\r\n   <a href=\"<tmpl_var approve.url>\"><tmpl_var approve.label></a><br />\r\n   <a href=\"<tmpl_var leave.url>\"><tmpl_var leave.label></a><br />\r\n   <a href=\"<tmpl_var deny.url>\"><tmpl_var deny.label></a><br />\r\n</tmpl_if>\r\n<tmpl_if canReply>\r\n   <a href=\"<tmpl_var reply.url>\"><tmpl_var reply.label></a><br />\r\n</tmpl_if>\r\n<tmpl_if canPost>\r\n   <a href=\"<tmpl_var post.url>\"><tmpl_var post.label></a><br />\r\n</tmpl_if>\r\n<a href=\"<tmpl_var search.url>\"><tmpl_var search.label></a><br />\r\n<a href=\"<tmpl_var back.url>\"><tmpl_var back.label></a><br />\r\n\r\n</td</tr><tr><td class=\"tableData\">\r\n<tmpl_if image.url>\r\n  <img src=\"<tmpl_var image.url>\" border=\"0\"><p />\r\n</tmpl_if>\r\n<tmpl_var content><p />\r\n<tmpl_var attachment.box><br />\r\n\r\n</td></tr></table>\r\n\r\n<tmpl_var replies>','USS/Submission');

