insert into webguiVersion values ('6.3.0','upgrade',unix_timestamp());

delete from template where templateId='tinymce' and namespace='richEditor';
INSERT INTO template VALUES ('tinymce','TinyMCE','^JavaScript(\"<tmpl_var session.config.extrasURL>/tinymce/jscripts/tiny_mce/tiny_mce.js\");\r\n<script language=\"javascript\" type=\"text/javascript\">\r\n	  tinyMCE.init({\r\n    theme : \"advanced\",\r\n    mode : \"textareas\",\r\n    plugins : \"collateral,emotions,insertImage,iespell,insertdatetime,pagetree,preview,zoom\",\r\n    theme_advanced_buttons2_add : \"insertImage,pagetree,collateral\",     \r\n    theme_advanced_buttons3_add : \"emotions,iespell,insertdate,inserttime,preview,zoom\"     \r\n  });\r\n</script>\r\n\r\n<tmpl_var textarea>','richEditor',1,1);
delete from template where templateId='1' and namespace='richEditor/pagetree';
INSERT INTO template VALUES ('1','Rich Editor Page Tree','<html>\r\n\r\n<script language=\"javascript\" src=\"<tmpl_var session.config.extrasURL>/tinymce/jscripts/tiny_mce/tiny_mce_popup.js\"></script>\r\n\r\n<script language=\"javascript\">\r\n\r\nfunction setLink(page) {\r\n    document.getElementById(\"url\").value=\"/index.pl/\" + page;\r\n}\r\n\r\nfunction createLink() {\r\n    if (window.opener) {        \r\n        if (document.getElementById(\"url\").value == \"\") {\r\n           alert(\"You must enter a link url\");\r\n           document.getElementById(\"url\").focus();\r\n        }\r\n\r\ntinyMCE.insertLink(document.getElementById(\"url\").value,document.getElementById(\"target\").value);\r\n //tinyMCE.insertLink(\"hello\",\"_self\");\r\n     window.close();\r\n    }\r\n}\r\n\r\n</script>\r\n\r\n<body>\r\n\r\n<fieldset>\r\n<legend>Insert/Edit Link</legend>\r\n\r\n  <fieldset>\r\n  <legend>Link Settings</legend>\r\n	<form name=\"linkchooser\">\r\n	<table border=\"0\">\r\n    <tr>\r\n    	<td>Link URL:</td>\r\n    	<td><input id=\"url\" name=\"url\" type=\"text value=\"\" style=\"width: 200px\"></td>\r\n    </tr>\r\n    <tr>\r\n        <td>Link Target:</td>\r\n        <td><select id=\"target\" name=\"target\" style=\"width: 200px\">\r\n                <option value=\"_self\">Open link in same window</option>\r\n                <option value=\"_blank\">Open link in new window</option>\r\n             </select>\r\n	    </td>\r\n    </tr>\r\n    <tr><td colspan=\"2\">&nbsp;</td></tr>\r\n	<tr>\r\n	   	<td colspan=\"2\" align=\"right\"><input type=\"button\" value=\"Cancel\" onClick=\"window.close()\"><input type=\"button\" value=\"Create Link\" onClick=\"createLink()\"></td>\r\n	</tr>\r\n	</table>\r\n	</form>\r\n	\r\n\r\n  </fieldset>  \r\n<br>\r\n\r\n\r\n  <fieldset>\r\n  <legend>Available Page Tree</legend>\r\n\r\n<tmpl_loop page_loop>\r\n  <tmpl_var indent><a href=\"#\" onClick=\"setLink(\'<tmpl_var url>\')\"><tmpl_var title></a><br />\r\n</tmpl_loop>\r\n\r\n </fieldset>\r\n  \r\n</fieldset>\r\n</body>\r\n</html>','richEditor/pagetree',1,1);
UPDATE template set template = '<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n           <html>\r\n              <head>\r\n                      <title><tmpl_var session.page.title> - <tmpl_var session.setting.companyName></title>\r\n                       <tmpl_var head.tags>\r\n                <style type=\"text/css\">\r\nTD { font: 8pt \'MS Shell Dlg\', Helvetica, sans-serif; }\r\nTD.delete { font: italic 7pt \'MS Shell Dlg\', Helvetica, sans-serif; }\r\nTD.label { font: 8pt \'MS Shell Dlg\', Helvetica, sans-serif; background-color: #c0c0c0; }\r\nTD.none { font: italic 12pt \'MS Shell Dlg\', Helvetica, sans-serif; }\r\n\r\n</style>\r\n\r\n               </head>\r\n             <script language=\"javascript\">\r\n</script>\r\n<script language=\"javascript\">\r\n\r\nfunction actionComplete(action, path, error, info) {\r\n   var manager=window.parent;\r\n\r\n   if(manager) {\r\n      if(error.length < 1) {\r\n         if(action == \'upload\') {\r\n            manager.document.getElementById(\"image\").value = \'\';\r\n            manager.document.getElementById(\"name\").value = \'\';\r\n            manager.document.getelementById(\"thumbnailSize\") = \'\';\r\n         }\r\n         if(action == \'create\')\r\n            manager.document.getElementById(\"folder\").value = \'\';\r\n         if(action == \'delete\')\r\n            manager.document.getElementById(\"txtFileName\").value = \'\';\r\n      }\r\n\r\nif (manager.document.getElementById(\"DPI\")) {\r\nmanager.document.getElementById(\"DPI\").value = 96;\r\n}\r\nif (manager.document.getElementById(\"path\")) {\r\nmanager.document.getElementById(\"path\").value = path;\r\n}\r\n   }\r\nif (manager.document.getElementById(\"viewer\")) {     \r\nmanager.document.getElementById(\"viewer\").src=\'^/;?op=htmlAreaviewCollateral\';\r\n}   \r\nif(error.length > 0)\r\n      alert(error);\r\n   else if(info.length > 0)\r\n      alert(info);\r\n}\r\n</script>\r\n\r\n<script language=\"javascript\">\r\nfunction deleteCollateral(options) {\r\n   var lister = window.parent.document.getElementById(\"lister\");\r\n\r\n   if(lister && confirm(\"Are you sure you want to delete this item ?\"))\r\n      lister.src=\'^/;?op=htmlAreaDelete&\' + options;\r\n}\r\n</script>\r\n</head>\r\n<body leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\r\n\r\n                   <tmpl_var body.content>\r\n             \r\n</body>\r\n         </html>\r\n             ' where templateId = '10' and namespace='style';

delete from userProfileField where fieldName='richEditor';
INSERT INTO userProfileField VALUES ('richEditor','WebGUI::International::get(496)',1,0,'selectList','{5=>WebGUI::International::get(880),\r\nnone=>WebGUI::International::get(881),\r\n\'tinymce\'=>WebGUI::International::get(\"tinymce\")\n}','[\'tinymce\']',11,'4',0,1);
update userProfileData set fieldData='tinyMCE' where fieldName='richEditor';

