alter table users add column icq_temp varchar(30);
update users set icq_temp=icq;
alter table users drop icq;
alter table users change icq_temp icq varchar(30);
alter table users add column language varchar(30) not null default 'English' after connectDN;
alter table Article change body body mediumtext;
INSERT INTO settings VALUES ('recoverPasswordEmail','Someone (probably you) requested your account information be sent. Your password has been reset. The following represents your new account information:');


CREATE TABLE international (
  internationalId int(11) NOT NULL default '0',
  language varchar(30) NOT NULL default 'English',
  message text,
  PRIMARY KEY  (internationalId,language)
) TYPE=MyISAM;

INSERT INTO international VALUES (1,'English','Add content...');
INSERT INTO international VALUES (2,'English','Page');
INSERT INTO international VALUES (3,'English','Paste from clipboard...');
INSERT INTO international VALUES (4,'English','Manage settings.');
INSERT INTO international VALUES (5,'English','Manage groups.');
INSERT INTO international VALUES (6,'English','Manage styles.');
INSERT INTO international VALUES (7,'English','Manage users.');
INSERT INTO international VALUES (8,'English','View page not found.');
INSERT INTO international VALUES (9,'English','View clipboard.');
INSERT INTO international VALUES (10,'English','View trash.');
INSERT INTO international VALUES (11,'English','Empy trash.');
INSERT INTO international VALUES (12,'English','Turn admin off.');
INSERT INTO international VALUES (13,'English','View help index.');
INSERT INTO international VALUES (14,'English','View pending submissions.');
INSERT INTO international VALUES (15,'English','January');
INSERT INTO international VALUES (16,'English','February');
INSERT INTO international VALUES (17,'English','March');
INSERT INTO international VALUES (18,'English','April');
INSERT INTO international VALUES (19,'English','May');
INSERT INTO international VALUES (20,'English','June');
INSERT INTO international VALUES (21,'English','July');
INSERT INTO international VALUES (22,'English','August');
INSERT INTO international VALUES (23,'English','September');
INSERT INTO international VALUES (24,'English','October');
INSERT INTO international VALUES (25,'English','November');
INSERT INTO international VALUES (26,'English','December');
INSERT INTO international VALUES (27,'English','Sunday');
INSERT INTO international VALUES (28,'English','Monday');
INSERT INTO international VALUES (29,'English','Tuesday');
INSERT INTO international VALUES (30,'English','Wednesday');
INSERT INTO international VALUES (31,'English','Thursday');
INSERT INTO international VALUES (32,'English','Friday');
INSERT INTO international VALUES (33,'English','Saturday');
INSERT INTO international VALUES (34,'English','set date');
INSERT INTO international VALUES (35,'English','Administrative Function');
INSERT INTO international VALUES (36,'English','You must be an administrator to perform this function. Please contact one of your administrators. The following is a list of the administrators for this system:');
INSERT INTO international VALUES (37,'English','Permission Denied!');
INSERT INTO international VALUES (38,'English','You do not have sufficient privileges to perform this operation. Please <a href=\"^\\?op=displayLogin\">log in with an account</a> that has sufficient privileges before attempting this operation.');
INSERT INTO international VALUES (39,'English','You do not have sufficient privileges to access this page.');
INSERT INTO international VALUES (41,'English','You\'re attempting to remove a vital component of the WebGUI system. If you were allowed to continue WebGUI may cease to function.');
INSERT INTO international VALUES (40,'English','Vital Component');
INSERT INTO international VALUES (42,'English','Please Confirm');
INSERT INTO international VALUES (43,'English','Are you certain that you wish to delete this content?');
INSERT INTO international VALUES (44,'English','Yes, I\'m sure.');
INSERT INTO international VALUES (45,'English','No, I made a mistake.');
INSERT INTO international VALUES (46,'English','My Account');
INSERT INTO international VALUES (47,'English','Home');
INSERT INTO international VALUES (48,'English','Hello');
INSERT INTO international VALUES (49,'English','Click <a href=\"^\\?op=logout\">here</a> to log out.');
INSERT INTO international VALUES (50,'English','Username');
INSERT INTO international VALUES (51,'English','Password');
INSERT INTO international VALUES (52,'English','login');
INSERT INTO international VALUES (53,'English','Make Page Printable');
INSERT INTO international VALUES (54,'English','Create Account');
INSERT INTO international VALUES (55,'English','Password (confirm)');
INSERT INTO international VALUES (56,'English','Email Address');
INSERT INTO international VALUES (57,'English','This is only necessary if you wish to use features that require Email.');
INSERT INTO international VALUES (58,'English','I already have an account.');
INSERT INTO international VALUES (59,'English','I forgot my password.');
INSERT INTO international VALUES (60,'English','Are you certain you want to deactivate your account. If you proceed your account information will be lost permanently.');
INSERT INTO international VALUES (61,'English','Update Account Information');
INSERT INTO international VALUES (62,'English','save');
INSERT INTO international VALUES (63,'English','Turn admin on.');
INSERT INTO international VALUES (64,'English','Log out.');
INSERT INTO international VALUES (65,'English','Please deactivate my account permanently.');
INSERT INTO international VALUES (66,'English','Log In');
INSERT INTO international VALUES (67,'English','Create a new account.');
INSERT INTO international VALUES (68,'English','The account information you supplied is invalid. Either the account does not exist or the username/password combination was incorrect.');
INSERT INTO international VALUES (69,'English','Please contact your system administrator for assistance.');
INSERT INTO international VALUES (70,'English','Error');
INSERT INTO international VALUES (71,'English','Recover password');
INSERT INTO international VALUES (72,'English','recover');
INSERT INTO international VALUES (73,'English','Log in.');
INSERT INTO international VALUES (74,'English','Account Information');
INSERT INTO international VALUES (75,'English','Your account information has been sent to your email address.');
INSERT INTO international VALUES (76,'English','That email address is not in our databases.');
INSERT INTO international VALUES (77,'English','That account name is already in use by another member of this site. Please try a different username. The following are some suggestions:');
INSERT INTO international VALUES (78,'English','Your passwords did not match. Please try again.');
INSERT INTO international VALUES (79,'English','Cannot connect to LDAP server.');
INSERT INTO international VALUES (80,'English','Account created successfully!');
INSERT INTO international VALUES (81,'English','Account updated successfully!');
INSERT INTO international VALUES (82,'English','Administrative functions...');
INSERT INTO international VALUES (83,'English','Add Group');
INSERT INTO international VALUES (84,'English','Group Name');
INSERT INTO international VALUES (85,'English','Description');
INSERT INTO international VALUES (86,'English','Are you certain you wish to delete this group? Beware that deleting a group is permanent and will remove all privileges associated with this group.');
INSERT INTO international VALUES (87,'English','Edit Group');
INSERT INTO international VALUES (88,'English','Users In Group');
INSERT INTO international VALUES (89,'English','Groups');
INSERT INTO international VALUES (90,'English','Add new group.');
INSERT INTO international VALUES (91,'English','Previous Page');
INSERT INTO international VALUES (92,'English','Next Page');
INSERT INTO international VALUES (93,'English','Help');
INSERT INTO international VALUES (94,'English','See also');
INSERT INTO international VALUES (95,'English','Help Index');
INSERT INTO international VALUES (96,'English','Sorted By Action');
INSERT INTO international VALUES (97,'English','Sorted by Object');
INSERT INTO international VALUES (98,'English','Add Page');
INSERT INTO international VALUES (99,'English','Title');
INSERT INTO international VALUES (100,'English','Meta Tags');
INSERT INTO international VALUES (101,'English','Are you certain that you wish to delete this page, its content, and all items under it?');
INSERT INTO international VALUES (102,'English','Edit Page');
INSERT INTO international VALUES (103,'English','Page Specifics');
INSERT INTO international VALUES (104,'English','Page URL');
INSERT INTO international VALUES (105,'English','Style');
INSERT INTO international VALUES (106,'English','Check to give this style to all sub-pages.');
INSERT INTO international VALUES (107,'English','Privileges');
INSERT INTO international VALUES (108,'English','Owner');
INSERT INTO international VALUES (109,'English','Owner can view?');
INSERT INTO international VALUES (110,'English','Owner can edit?');
INSERT INTO international VALUES (111,'English','Group');
INSERT INTO international VALUES (112,'English','Group can view?');
INSERT INTO international VALUES (113,'English','Group can edit?');
INSERT INTO international VALUES (114,'English','Anybody can view?');
INSERT INTO international VALUES (115,'English','Anybody can edit?');
INSERT INTO international VALUES (116,'English','Check to give these privileges to all sub-pages.');
INSERT INTO international VALUES (117,'English','Edit Authentication Settings');
INSERT INTO international VALUES (118,'English','Anonymous Registration');
INSERT INTO international VALUES (119,'English','Authentication Method (default)');
INSERT INTO international VALUES (120,'English','LDAP URL (default)');
INSERT INTO international VALUES (121,'English','LDAP Identity (default)');
INSERT INTO international VALUES (122,'English','LDAP Identity Name');
INSERT INTO international VALUES (123,'English','LDAP Password Name');
INSERT INTO international VALUES (124,'English','Edit Company Information');
INSERT INTO international VALUES (125,'English','Company Name');
INSERT INTO international VALUES (126,'English','Company Email Address');
INSERT INTO international VALUES (127,'English','Company URL');
INSERT INTO international VALUES (128,'English','Edit File Settings');
INSERT INTO international VALUES (129,'English','Path to WebGUI Extras');
INSERT INTO international VALUES (130,'English','Maximum Attachment Size');
INSERT INTO international VALUES (131,'English','Web Attachment Path');
INSERT INTO international VALUES (132,'English','Server Attachment Path');
INSERT INTO international VALUES (133,'English','Edit Mail Settings');
INSERT INTO international VALUES (134,'English','Recover Password Message');
INSERT INTO international VALUES (135,'English','SMTP Server');
INSERT INTO international VALUES (136,'English','Home Page');
INSERT INTO international VALUES (137,'English','Page Not Found Page');
INSERT INTO international VALUES (138,'English','Yes');
INSERT INTO international VALUES (139,'English','No');
INSERT INTO international VALUES (140,'English','Edit Miscellaneous Settings');
INSERT INTO international VALUES (141,'English','Not Found Page');
INSERT INTO international VALUES (142,'English','Session Timeout');
INSERT INTO international VALUES (143,'English','Manage Settings');
INSERT INTO international VALUES (144,'English','View Statistics');
INSERT INTO international VALUES (145,'English','WebGUI Build Version');
INSERT INTO international VALUES (146,'English','Active Sessions');
INSERT INTO international VALUES (147,'English','Viewable Pages');
INSERT INTO international VALUES (148,'English','Viewable Widgets');
INSERT INTO international VALUES (149,'English','Users');
INSERT INTO international VALUES (150,'English','Add Style');
INSERT INTO international VALUES (151,'English','Style Name');
INSERT INTO international VALUES (152,'English','Header');
INSERT INTO international VALUES (153,'English','Footer');
INSERT INTO international VALUES (154,'English','Style Sheet');
INSERT INTO international VALUES (155,'English','Are you certain you wish to delete this style and migrate all pages using this style to the \"Fail Safe\" style?');
INSERT INTO international VALUES (156,'English','Edit Style');
INSERT INTO international VALUES (157,'English','Styles');
INSERT INTO international VALUES (158,'English','Add a new style.');
INSERT INTO international VALUES (159,'English','Pending Submissions');
INSERT INTO international VALUES (160,'English','Date Submitted');
INSERT INTO international VALUES (161,'English','Submitted By');
INSERT INTO international VALUES (162,'English','Are you certain that you wish to purge all the pages and widgets in the trash?');
INSERT INTO international VALUES (163,'English','Add User');
INSERT INTO international VALUES (164,'English','Authentication Method');
INSERT INTO international VALUES (165,'English','LDAP URL');
INSERT INTO international VALUES (166,'English','Connect DN');
INSERT INTO international VALUES (167,'English','Are you certain you want to delete this user? Be warned that all this user\'s information will be lost permanently if you choose to proceed.');
INSERT INTO international VALUES (168,'English','Edit User');
INSERT INTO international VALUES (169,'English','Add a new user.');
INSERT INTO international VALUES (170,'English','search');
INSERT INTO international VALUES (171,'English','rich edit');
INSERT INTO international VALUES (172,'English','Article');
INSERT INTO international VALUES (173,'English','Add Article');
INSERT INTO international VALUES (174,'English','Display the title?');
INSERT INTO international VALUES (175,'English','Process macros?');
INSERT INTO international VALUES (176,'English','Start Date');
INSERT INTO international VALUES (177,'English','End Date');
INSERT INTO international VALUES (178,'English','Body');
INSERT INTO international VALUES (179,'English','Image');
INSERT INTO international VALUES (180,'English','Link Title');
INSERT INTO international VALUES (181,'English','Link URL');
INSERT INTO international VALUES (182,'English','Attachment');
INSERT INTO international VALUES (183,'English','Convert carriage returns?');
INSERT INTO international VALUES (184,'English','(Check if you aren\'t adding &lt;br&gt; manually.)');
INSERT INTO international VALUES (185,'English','Edit Article');
INSERT INTO international VALUES (186,'English','Delete');
INSERT INTO international VALUES (187,'English','Events Calendar');
INSERT INTO international VALUES (188,'English','Add Events Calendar');
INSERT INTO international VALUES (189,'English','Happens only once.');
INSERT INTO international VALUES (190,'English','Day');
INSERT INTO international VALUES (191,'English','Week');
INSERT INTO international VALUES (192,'English','Add Event');
INSERT INTO international VALUES (193,'English','Recurs every');
INSERT INTO international VALUES (194,'English','until');
INSERT INTO international VALUES (195,'English','Are you certain that you want to delete this event');
INSERT INTO international VALUES (197,'English','Edit Events Calendar');
INSERT INTO international VALUES (196,'English','<b>and</b> all of its recurring events');
INSERT INTO international VALUES (198,'English','Edit Event');
INSERT INTO international VALUES (199,'English','Extra Column');
INSERT INTO international VALUES (200,'English','Add Extra Column');
INSERT INTO international VALUES (201,'English','Spacer');
INSERT INTO international VALUES (202,'English','Width');
INSERT INTO international VALUES (203,'English','StyleSheet Class');
INSERT INTO international VALUES (204,'English','Edit Extra Column');
INSERT INTO international VALUES (205,'English','F.A.Q.');
INSERT INTO international VALUES (206,'English','Add F.A.Q.');
INSERT INTO international VALUES (207,'English','Add Question');
INSERT INTO international VALUES (208,'English','Question');
INSERT INTO international VALUES (209,'English','Answer');
INSERT INTO international VALUES (211,'English','Edit F.A.Q.');
INSERT INTO international VALUES (210,'English','Are you certain that you want to delete this question?');
INSERT INTO international VALUES (212,'English','Add a new question.');
INSERT INTO international VALUES (213,'English','Edit Question');
INSERT INTO international VALUES (214,'English','Link List');
INSERT INTO international VALUES (215,'English','Add Link');
INSERT INTO international VALUES (216,'English','URL');
INSERT INTO international VALUES (217,'English','Are you certain that you want to delete this link?');
INSERT INTO international VALUES (218,'English','Edit Link List');
INSERT INTO international VALUES (219,'English','Add Link List');
INSERT INTO international VALUES (220,'English','Edit Link');
INSERT INTO international VALUES (221,'English','Add a new link.');
INSERT INTO international VALUES (222,'English','Add Message Board');
INSERT INTO international VALUES (223,'English','Message Board');
INSERT INTO international VALUES (224,'English','Who can post?');
INSERT INTO international VALUES (225,'English','Messages Per Page');
INSERT INTO international VALUES (226,'English','Edit Timeout');
INSERT INTO international VALUES (227,'English','Edit Message Board');
INSERT INTO international VALUES (228,'English','Editing Message...');
INSERT INTO international VALUES (229,'English','Subject');
INSERT INTO international VALUES (230,'English','Message');
INSERT INTO international VALUES (231,'English','Posting New Message...');
INSERT INTO international VALUES (232,'English','no subject');
INSERT INTO international VALUES (233,'English','(eom)');
INSERT INTO international VALUES (234,'English','Posting Reply...');
INSERT INTO international VALUES (235,'English','Edit Message');
INSERT INTO international VALUES (236,'English','Post Reply');
INSERT INTO international VALUES (237,'English','Subject:');
INSERT INTO international VALUES (238,'English','Author:');
INSERT INTO international VALUES (239,'English','Date:');
INSERT INTO international VALUES (240,'English','Message ID:');
INSERT INTO international VALUES (241,'English','Previous Thread');
INSERT INTO international VALUES (242,'English','Back To Message List');
INSERT INTO international VALUES (243,'English','Next Thread');
INSERT INTO international VALUES (244,'English','Author');
INSERT INTO international VALUES (245,'English','Date');
INSERT INTO international VALUES (246,'English','Post New Message');
INSERT INTO international VALUES (247,'English','Thread Started');
INSERT INTO international VALUES (248,'English','Replies');
INSERT INTO international VALUES (249,'English','Last Reply');
INSERT INTO international VALUES (250,'English','Poll');
INSERT INTO international VALUES (251,'English','Add Poll');
INSERT INTO international VALUES (252,'English','Active');
INSERT INTO international VALUES (253,'English','Who can vote?');
INSERT INTO international VALUES (254,'English','Graph Width');
INSERT INTO international VALUES (255,'English','Question');
INSERT INTO international VALUES (256,'English','Answers');
INSERT INTO international VALUES (257,'English','(Enter one answer per line. No more than 20.)');
INSERT INTO international VALUES (258,'English','Edit Poll');
INSERT INTO international VALUES (259,'English','SQL Report');
INSERT INTO international VALUES (260,'English','Add SQL Report');
INSERT INTO international VALUES (261,'English','Template');
INSERT INTO international VALUES (262,'English','Query');
INSERT INTO international VALUES (263,'English','DSN');
INSERT INTO international VALUES (264,'English','Database User');
INSERT INTO international VALUES (265,'English','Database Password');
INSERT INTO international VALUES (266,'English','Edit SQL Report');
INSERT INTO international VALUES (267,'English','Error: The DSN specified is of an improper format.');
INSERT INTO international VALUES (268,'English','Error: The SQL specified is of an improper format.');
INSERT INTO international VALUES (269,'English','Error: There was a problem with the query.');
INSERT INTO international VALUES (270,'English','Error: Could not connect to the database.');
INSERT INTO international VALUES (271,'English','Syndicated Content');
INSERT INTO international VALUES (272,'English','Add Syndicated Content');
INSERT INTO international VALUES (273,'English','URL to RSS File');
INSERT INTO international VALUES (274,'English','Edit Syndicated Content');
INSERT INTO international VALUES (275,'English','Last Fetched');
INSERT INTO international VALUES (276,'English','Current Content');
INSERT INTO international VALUES (277,'English','User Submission System');
INSERT INTO international VALUES (278,'English','Add User Submission System');
INSERT INTO international VALUES (279,'English','Who can contribute?');
INSERT INTO international VALUES (280,'English','Submissions Per Page');
INSERT INTO international VALUES (281,'English','Approved');
INSERT INTO international VALUES (282,'English','Denied');
INSERT INTO international VALUES (283,'English','Pending');
INSERT INTO international VALUES (284,'English','Default Status');
INSERT INTO international VALUES (285,'English','Add Submission');
INSERT INTO international VALUES (286,'English','(Uncheck if you\'re writing an HTML submission.)');
INSERT INTO international VALUES (287,'English','Date Submitted');
INSERT INTO international VALUES (288,'English','Status');
INSERT INTO international VALUES (289,'English','Edit/Delete');
INSERT INTO international VALUES (290,'English','Untitiled');
INSERT INTO international VALUES (291,'English','Are you certain you wish to delete this submission?');
INSERT INTO international VALUES (292,'English','Edit User Submission System');
INSERT INTO international VALUES (293,'English','Edit Submission');
INSERT INTO international VALUES (294,'English','Post New Submission');
INSERT INTO international VALUES (295,'English','Date Submitted');
INSERT INTO international VALUES (296,'English','Submitted By');
INSERT INTO international VALUES (297,'English','Submitted By:');
INSERT INTO international VALUES (298,'English','Date Submitted:');
INSERT INTO international VALUES (299,'English','Approve');
INSERT INTO international VALUES (300,'English','Leave Pending');
INSERT INTO international VALUES (301,'English','Deny');
INSERT INTO international VALUES (302,'English','Edit');
INSERT INTO international VALUES (303,'English','Return To Submissions List');
INSERT INTO international VALUES (304,'English','Language');



